Repository ppy/osu-web, pull requests merged in 2018-06, with the labels that each got.

#3207 Delete scores on qualification
  .env.example
  app/Http/Controllers/API/LegacyController.php
  app/Jobs/RemoveBeatmapsetBestScores.php
  app/Libraries/ReplayFile.php
  app/Models/Beatmapset.php
  app/Models/ReplayViewCount/Fruits.php
  app/Models/ReplayViewCount/Mania.php
  app/Models/ReplayViewCount/Model.php
  app/Models/ReplayViewCount/Osu.php
  app/Models/ReplayViewCount/Taiko.php
  app/Models/Score/Best/Model.php
  app/Traits/Scoreable.php
  config/filesystems.php
  config/osu.php
  database/migrations/2015_01_01_133337_base_tables.php
Labels: resolves issue

#3295 Allow empty changelog entries and fix converter
  app/Http/Controllers/ChangelogController.php
  app/Models/ChangelogEntry.php
Labels: bug, regression

#3289 Style beatmapset discussion search form
  app/Http/Controllers/Users/ModdingHistoryController.php
  app/Models/BeatmapDiscussion.php
  resources/assets/less/bem/simple-form.less
  resources/lang/en/beatmap_discussions.php
  resources/lang/en/common.php
  resources/views/beatmap_discussions/index.blade.php
  resources/views/objects/_checkbox.blade.php
Labels: resolves issue

#3306 Always set params if exist in request
  app/helpers.php
Labels: code quality

#3316 Fix avatar scaling in usercard
  resources/assets/less/bem/usercard.less
Labels: resolves issue

#3331 Fix changelog sort
  app/Http/Controllers/ChangelogController.php
Labels: bug, changelog

#3320 Only link github pr number text
  app/Models/ChangelogEntry.php
  resources/views/changelog/_changelog_change.blade.php
Labels: resolves issue

#3332 Add changelog default scope when showing builds
  app/Http/Controllers/ChangelogController.php
Labels: bug, changelog, high priority

#3327 Update scoreboard colouring when hovering over rows
  resources/assets/less/bem/beatmap-scoreboard-table.less
Labels: resolves issue

#3336 Unjustify changelog change text.
  resources/assets/less/bem/changelog-change.less
Labels: resolves issue

#3337 Unwatch beatmap discussion buttons should have the same icon
  resources/views/beatmapset_watches/index.blade.php
Labels: resolves issue

#3338 Clear previous sign in failure message when signing in again
  resources/assets/coffee/_classes/user-login.coffee
  resources/views/layout/_popup_login.blade.php
Labels: resolves issue

#3342 Add full date tooltip on registration date
  app/helpers.php
Labels: resolves issue

#3339 Update favicon with added mobile support
  config/osu.php
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/mstile-150x150.png
  public/safari-pinned-tab.svg
  public/site.webmanifest
  resources/views/layout/metadata.blade.php
Labels: design

#3319 Add build generator to attach unlinked changelogs
  app/Http/Controllers/ChangelogController.php
  app/Http/Controllers/LegacyInterOpController.php
  app/Libraries/GithubImporter.php
  app/Models/Build.php
  app/Models/ChangelogEntry.php
  app/Models/Repository.php
  app/Models/UpdateStream.php
  database/migrations/2018_06_06_091751_link_streams_to_changelog_entries.php
Labels: changelog

#3351 Update translations
  resources/lang/de/beatmaps.php
  resources/lang/de/users.php
  resources/lang/el/common.php
  resources/lang/it/common.php
  resources/lang/it/errors.php
  resources/lang/it/users.php
  resources/lang/ko/accounts.php
  resources/lang/ko/authorization.php
  resources/lang/ko/beatmap_discussion_posts.php
  resources/lang/ko/beatmap_discussions.php
  resources/lang/ko/beatmappacks.php
  resources/lang/ko/beatmaps.php
  resources/lang/ko/beatmapset_events.php
  resources/lang/ko/beatmapset_watches.php
  resources/lang/ko/beatmapsets.php
  resources/lang/ko/common.php
  resources/lang/ko/community.php
  resources/lang/ko/contest.php
  resources/lang/ko/errors.php
  resources/lang/ko/forum.php
  resources/lang/ko/home.php
  resources/lang/ko/layout.php
  resources/lang/ko/livestreams.php
  resources/lang/ko/model_validation.php
  resources/lang/ko/model_validation/store/product.php
  resources/lang/ko/news.php
  resources/lang/ko/paypal/errors.php
  resources/lang/ko/store.php
  resources/lang/ko/tournament.php
  resources/lang/ko/users.php
  resources/lang/ko/wiki.php
  resources/lang/nl/common.php
  resources/lang/nl/errors.php
  resources/lang/nl/users.php
  resources/lang/pl/users.php
  resources/lang/ru/accounts.php
  resources/lang/ru/artist.php
  resources/lang/ru/authorization.php
  resources/lang/ru/beatmappacks.php
  resources/lang/ru/forum.php
  resources/lang/ru/layout.php
  resources/lang/ru/multiplayer.php
  resources/lang/ru/users.php
  resources/lang/sv/common.php
  resources/lang/sv/errors.php
  resources/lang/sv/users.php
  resources/lang/tr/common.php
  resources/lang/tr/errors.php
  resources/lang/tr/users.php
Labels: localisation

#3317 Boost scores of beatmap search results if they contain all terms
  app/Libraries/Elasticsearch/QueryHelper.php
  app/Libraries/Search/BeatmapsetSearch.php
Labels: resolves issue

#3362 Update placeholder text to show where the user will be posting to.
  resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
  resources/lang/en/beatmaps.php
Labels: resolves issue

#3353 Two columned locale menu
  resources/assets/less/bem/simple-menu.less
  resources/views/layout/_nav2.blade.php
Labels: resolves issue

#3354 Prompt for login when clicking on forum thread reply button
  resources/assets/coffee/_classes/forum-topic-reply.coffee
  resources/assets/less/bem/forum-topic-reply.less
  resources/lang/en/forum.php
  resources/views/forum/topics/show.blade.php
Labels: resolves issue

#3373 Add command to generate build
  app/Console/Commands/BuildsCreate.php
  app/Console/Kernel.php
  app/Models/UpdateStream.php
Labels: changelog, pending review

#3374 Require stream name to view build
  app/Http/Controllers/ChangelogController.php
  app/helpers.php
  resources/views/changelog/_changelog_build.blade.php
  resources/views/changelog/show.blade.php
  routes/web.php
Labels: changelog, code quality

#3366 Fix marking read and poll render of deleted topic
  app/Models/Forum/PollOption.php
  app/Models/Forum/Post.php
  app/Models/Forum/Topic.php
Labels: resolves issue

#3380 Add .editorconfig to project
  .editorconfig
Labels: code quality

#3345 Show pp for recent plays if available
  app/Http/Controllers/UsersController.php
  app/Models/Score/Model.php
  app/Transformers/ScoreTransformer.php
  database/migrations/2015_01_01_133337_base_tables.php
  resources/assets/coffee/react/_components/play-detail.coffee
Labels: resolves issue

#3281 Show supporter filters for non-supporters
  public/images/layout/beatmaps/supporter-required.png
  public/images/layout/beatmaps/supporter-required@2x.png
  resources/assets/coffee/react/beatmaps/main.coffee
  resources/assets/coffee/react/beatmaps/search-panel.coffee
  resources/lang/en/beatmaps.php
Labels: resolves issue

#3352 Pagination template cleanup
  resources/assets/less/bem-index.less
  resources/assets/less/bem/pagination-v0.less
  resources/assets/less/forum/base.less
  resources/views/beatmap_discussion_posts/index.blade.php
  resources/views/beatmap_discussions/index.blade.php
  resources/views/beatmapset_discussion_votes/index.blade.php
  resources/views/beatmapset_events/index.blade.php
  resources/views/beatmapset_watches/index.blade.php
  resources/views/forum/forums/show.blade.php
  resources/views/forum/topic_watches/index.blade.php
  resources/views/news/index.blade.php
  resources/views/objects/_pagination_v0.blade.php
  resources/views/store/index.blade.php
  resources/views/store/invoice.blade.php
  resources/views/store/products/show.blade.php
  resources/views/users/disabled.blade.php
Labels: code quality, pending review

#3391 Add a simple Pull Request template
  .github/pull_request_template.md
Labels: tooling

#3393 Fix legacy changelogs not showing more than one entry
  app/Transformers/BuildTransformer.php
Labels: changelog, regression

#3392 Only import changelogs from specific repository
  app/Models/Build.php
  app/Models/Repository.php
Labels: bug, changelog

#3394 Changelog design tweaks and fixes
  app/Models/ChangelogEntry.php
  resources/assets/coffee/react/_components/build.coffee
  resources/assets/less/bem/changelog-chart.less
  resources/assets/less/sections.less
  resources/assets/less/variables.less
  resources/lang/en/changelog.php
Labels: changelog

#3396 Remove period from placeholder changelog description
  resources/lang/en/changelog.php
Labels: changelog, localisation

#3405 Prevent navigation background from vertically repeating
  resources/assets/less/bem/nav2-header.less
Labels: resolves issue

#3409 Disable add friend button instead of hiding
  resources/assets/coffee/react/_components/friend-button.coffee
  resources/lang/en/friends.php
Labels: resolves issue

#3377 Fix osu! brand naming
  resources/lang/en/authorization.php
  resources/lang/en/beatmaps.php
  resources/lang/en/beatmapsets.php
  resources/lang/en/changelog.php
  resources/lang/en/community.php
  resources/lang/en/contest.php
  resources/lang/en/errors.php
  resources/lang/en/events.php
  resources/lang/en/forum.php
  resources/lang/en/fulfillments.php
  resources/lang/en/layout.php
  resources/lang/en/model_validation/fulfillments.php
  resources/lang/en/store.php
  resources/lang/en/users.php
Labels: localisation

#3422 Filter (legacy) changelog of a build by stream id
  app/Models/Build.php
Labels: bug, changelog

#3416 Update translations
  resources/lang/el/wiki.php
  resources/lang/id/model_validation.php
  resources/lang/it/beatmapsets.php
  resources/lang/ja/beatmaps.php
  resources/lang/ja/home.php
  resources/lang/ru/accounts.php
  resources/lang/tr/beatmapset_events.php
  resources/lang/tr/beatmapsets.php
  resources/lang/tr/changelog.php
  resources/lang/tr/model_validation/store/product.php
Labels: localisation

#3421 Link changelog entry to its url if exists
  app/Transformers/ChangelogEntryTransformer.php
  resources/assets/coffee/react/_components/build.coffee
Labels: changelog, ux

#3423 Allow everyone authorized to post note
  app/Http/Controllers/BeatmapDiscussionPostsController.php
  app/Libraries/OsuAuthorize.php
  app/Models/BeatmapDiscussion.php
  resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
  resources/lang/en/authorization.php
  resources/lang/en/model_validation.php
  tests/Controllers/BeatmapDiscussionPostsControllerTest.php
  tests/Models/BeatmapDiscussionTest.php
Labels: resolves issue

#3424 Fix changelog listing showing no legacy entries
  app/Models/Build.php
  app/Transformers/BuildTransformer.php
Labels: changelog, regression

#3410 Restore focus when loading new search results
  resources/assets/coffee/_classes/search.coffee
  resources/views/home/search.blade.php
  resources/views/objects/search/_forum_options.blade.php
Labels: resolves issue
