Repository ppy/osu-web, pull requests merged in 2018-07, with the labels that each got.

#3438 Find changelog entry orphans by stream id
  app/Models/Build.php
  app/Models/ChangelogEntry.php
  app/Models/Repository.php
  app/Models/UpdateStream.php
  database/migrations/2018_06_22_132317_link_streams_to_repositories.php
Labels: changelog, pending review

#3436 Add confirmation on exiting editor with unsaved changes
  resources/assets/coffee/react/_components/bbcode-editor.coffee
  resources/lang/en/common.php
Labels: resolves issue

#3417 Fix linking pending page in beatmap discussions
  resources/assets/coffee/_classes/beatmap-discussion-helper.coffee
Labels: resolves issue

#3457 Update docker
  SETUP.md
  bin/update_locales_and_routes_js
  build.sh
  docker-compose.yml
  docker/nginx/nginx-osu-next
  docker/php/Dockerfile
  docker/php/overrides.conf
  docker/php/php-fpm.conf
  docker/php/setup.sh
  docker/php/start
  docker/yarn/Dockerfile
  docker/yarn/setup.sh
Labels: resolves issue

#3470 Return class instead of new instance from getClass()
  app/Http/Controllers/API/LegacyController.php
  app/Http/Controllers/RankingController.php
  app/Libraries/Search/BeatmapsetSearch.php
  app/Models/CountryStatistics.php
  app/Models/Score/Model.php
  app/Models/UserStatistics/Model.php
Labels: code quality

#3476 Fix beatmapset disqualification message preview
  resources/assets/coffee/_classes/beatmap-discussion-helper.coffee
  resources/assets/coffee/react/beatmap-discussions/event.coffee
  resources/assets/coffee/react/beatmap-discussions/nominations.coffee
Labels: resolves issue

#3481 Add Bulgarian localisation
  .styleci.yml
  app/Libraries/LocaleMeta.php
  config/app.php
  crowdin.yml
  resources/lang/bg/accounts.php
  resources/lang/bg/admin.php
  resources/lang/bg/api.php
  resources/lang/bg/artist.php
  resources/lang/bg/authorization.php
  resources/lang/bg/bbcode.php
  resources/lang/bg/beatmap_discussion_posts.php
  resources/lang/bg/beatmap_discussions.php
  resources/lang/bg/beatmappacks.php
  resources/lang/bg/beatmaps.php
  resources/lang/bg/beatmapset_discussion_votes.php
  resources/lang/bg/beatmapset_events.php
  resources/lang/bg/beatmapset_watches.php
  resources/lang/bg/beatmapsets.php
  resources/lang/bg/changelog.php
  resources/lang/bg/common.php
  resources/lang/bg/community.php
  resources/lang/bg/contest.php
  resources/lang/bg/errors.php
  resources/lang/bg/events.php
  resources/lang/bg/forum.php
  resources/lang/bg/friends.php
  resources/lang/bg/fulfillments.php
  resources/lang/bg/help.php
  resources/lang/bg/home.php
  resources/lang/bg/layout.php
  resources/lang/bg/livestreams.php
  resources/lang/bg/model_validation.php
  resources/lang/bg/model_validation/fulfillments.php
  resources/lang/bg/model_validation/payments.php
  resources/lang/bg/model_validation/store/product.php
  resources/lang/bg/multiplayer.php
  resources/lang/bg/news.php
  resources/lang/bg/password_reset.php
  resources/lang/bg/paypal/errors.php
  resources/lang/bg/rankings.php
  resources/lang/bg/status_page.php
  resources/lang/bg/store.php
  resources/lang/bg/supporter_tag.php
  resources/lang/bg/tournament.php
  resources/lang/bg/user_verification.php
  resources/lang/bg/users.php
  resources/lang/bg/validation.php
  resources/lang/bg/wiki.php
Labels: localisation

#3480 Update localisations
  resources/lang/cs/beatmaps.php
  resources/lang/cs/layout.php
  resources/lang/cs/model_validation.php
  resources/lang/cs/users.php
  resources/lang/de/beatmap_discussions.php
  resources/lang/de/beatmaps.php
  resources/lang/de/changelog.php
  resources/lang/de/common.php
  resources/lang/de/forum.php
  resources/lang/de/layout.php
  resources/lang/fi/accounts.php
  resources/lang/fi/artist.php
  resources/lang/fi/authorization.php
  resources/lang/fi/beatmap_discussion_posts.php
  resources/lang/fi/beatmap_discussions.php
  resources/lang/fi/beatmappacks.php
  resources/lang/fi/beatmaps.php
  resources/lang/fi/beatmapset_discussion_votes.php
  resources/lang/fi/beatmapset_events.php
  resources/lang/fi/beatmapset_watches.php
  resources/lang/fi/beatmapsets.php
  resources/lang/fi/changelog.php
  resources/lang/fi/common.php
  resources/lang/fi/community.php
  resources/lang/fi/contest.php
  resources/lang/fi/errors.php
  resources/lang/fi/events.php
  resources/lang/fi/forum.php
  resources/lang/fi/fulfillments.php
  resources/lang/fi/home.php
  resources/lang/fi/layout.php
  resources/lang/fi/model_validation.php
  resources/lang/fi/model_validation/store/product.php
  resources/lang/fi/multiplayer.php
  resources/lang/fi/news.php
  resources/lang/fi/rankings.php
  resources/lang/fi/status_page.php
  resources/lang/fi/store.php
  resources/lang/fi/tournament.php
  resources/lang/fi/user_verification.php
  resources/lang/fi/users.php
  resources/lang/fr/users.php
  resources/lang/hu/beatmaps.php
  resources/lang/ko/changelog.php
  resources/lang/ko/home.php
  resources/lang/ko/layout.php
  resources/lang/pl/beatmap_discussions.php
  resources/lang/pl/beatmaps.php
  resources/lang/pl/changelog.php
  resources/lang/sv/beatmap_discussions.php
  resources/lang/tr/beatmaps.php
  resources/lang/tr/changelog.php
  resources/lang/tr/news.php
  resources/lang/vi/authorization.php
  resources/lang/vi/beatmap_discussions.php
  resources/lang/zh-tw/beatmap_discussions.php
  resources/lang/zh-tw/beatmaps.php
  resources/lang/zh-tw/changelog.php
  resources/lang/zh-tw/forum.php
  resources/lang/zh-tw/layout.php
Labels: localisation

#3363 Retrieve user best performance scores from elasticsearch
  .env.example
  app/Http/Controllers/UsersController.php
  app/Jobs/RemoveBeatmapsetBestScores.php
  app/Libraries/Elasticsearch/Es.php
  app/Libraries/Elasticsearch/Indexing.php
  app/Libraries/Elasticsearch/Search.php
  app/Libraries/Elasticsearch/SearchResponse.php
  app/Models/Score/Best/Model.php
  app/Models/User.php
  app/Models/UserScoreable.php
  app/Models/Wiki/Page.php
  app/Providers/ElasticsearchServiceProvider.php
  app/Traits/EsIndexable.php
  app/Transformers/ScoreTransformer.php
  app/helpers.php
  config/app.php
  config/elasticsearch_scores.php
  config/osu.php
Labels: performance, user profile

#3499 Don't log "not found" error of wiki image
  app/Http/Controllers/WikiController.php
  app/Models/Wiki/Image.php
Labels: regression, wiki

#3503 Retrieve first posts for forum search using a separate query
  app/Libraries/Search/ForumSearch.php
  resources/views/home/_search_result_forum_post.blade.php
Labels: performance, search

#3506 Fix layout on Changelog builds page
  resources/assets/coffee/react/changelog-build/main.coffee
Labels: bug

#3508 Fix missing user best performance
  app/Libraries/Elasticsearch/Search.php
Labels: bug

#3447 Support forum-level topics read status
  app/Models/Forum/ForumTrack.php
  app/Models/Forum/TopicTrack.php
  database/migrations/2015_01_01_133337_base_tables.php
Labels: resolves issue

#3513 Don't index topics that were moved to a new topic
  app/Models/Elasticsearch/TopicTrait.php
  resources/views/home/_search_result_forum_post.blade.php
Labels: bug, forum, search

#3509 Add unique token filter to post text analyzer
  config/schemas/posts.json
Labels: performance, search

#3511 Show correct supporter gift duration in mail
  app/Libraries/Fulfillments/SupporterTagFulfillment.php
  app/Mail/SupporterGift.php
  tests/Libraries/Fulfillments/SupporterTagFulfillmentTest.php
Labels: resolves issue

#3501 Make search query cancellable
  .env.example
  app/Libraries/Elasticsearch/Search.php
  config/osu.php
Labels: search

#3215 Allow overriding default font
  resources/assets/less/bbcode.less
  resources/assets/less/bem/osu-md.less
  resources/assets/less/bem/rankinginfo-small.less
  resources/assets/less/bem/userinfo-small.less
  resources/assets/less/bootstrap-variables.less
  resources/assets/less/functions.less
  resources/assets/less/layout.less
  resources/assets/less/variables.less
  resources/views/layout/metadata.blade.php
Labels: resolves issue

#3525 Cosmetic updates to beatmapset search filters
  app/Http/Controllers/BeatmapsetsController.php
  app/Libraries/Search/BeatmapsetSearch.php
  resources/lang/en/beatmaps.php
Labels: resolves issue

#3523 Use paid orders in fulfillment tests
  app/Models/User.php
  database/factories/OrderFactory.php
  tests/Libraries/Fulfillments/BannerFulfillmentTest.php
  tests/Libraries/Fulfillments/SupporterTagFulfillmentTest.php
  tests/Libraries/Fulfillments/UsernameChangeFulfillmentTest.php
Labels: code quality

#3526 Change double post protection message
  resources/lang/en/authorization.php
Labels: resolves issue

#3529 Allows beatmaps to be set as 'loved'
  app/Http/Controllers/BeatmapsetsController.php
  app/Libraries/OsuAuthorize.php
  app/Models/Beatmapset.php
  app/Models/BeatmapsetEvent.php
  app/Models/Event.php
  app/Models/UserGroup.php
  app/Transformers/BeatmapsetTransformer.php
  database/migrations/2018_07_26_110501_add_love_type_to_beatmapset_events.php
  resources/assets/coffee/react/beatmap-discussions/nominations.coffee
  resources/lang/en/beatmaps.php
  resources/lang/en/beatmapset_events.php
  routes/web.php
Labels: resolves issue

#3536 Make sign-in popup less blurry
  resources/assets/coffee/_classes/nav2.coffee
Labels: resolves issue

#3533 Paginate multiplayer match
  app/Http/Controllers/MatchesController.php
  app/Models/Multiplayer/Match.php
  app/Models/Multiplayer/Model.php
  config/osu.php
  package.json
  resources/assets/coffee/main.coffee
  resources/assets/coffee/react/mp-history.coffee
  resources/assets/coffee/react/mp-history/content.coffee
  resources/assets/coffee/react/mp-history/event.coffee
  resources/assets/coffee/react/mp-history/game.coffee
  resources/assets/coffee/react/mp-history/main.coffee
  resources/assets/coffee/react/mp-history/score.coffee
  resources/assets/coffee/turbolinks-overrides.coffee
  resources/assets/less/bem/mp-history-content.less
  resources/lang/en/multiplayer.php
  resources/views/multiplayer/match.blade.php
  yarn.lock
Labels: resolves issue
