Repository ppy/osu-web, pull requests merged in 2018-10, with the labels that each got.

#3591 Add option to delete beatmaps
  .env.example
  app/Http/Controllers/BeatmapsetsController.php
  app/Jobs/BeatmapsetDelete.php
  app/Libraries/OsuAuthorize.php
  app/Models/Beatmapset.php
  app/Models/Elasticsearch/BeatmapsetTrait.php
  app/Models/Event.php
  app/Transformers/BeatmapsetTransformer.php
  config/filesystems.php
  config/osu.php
  resources/assets/coffee/react/beatmap-discussions/nominations.coffee
  resources/lang/en/beatmaps.php
  routes/web.php
Labels: resolves issue

#3703 Search function on beatmapset event listing page
  app/Http/Controllers/BeatmapsetEventsController.php
  app/Http/Controllers/Users/ModdingHistoryController.php
  app/Models/BeatmapsetEvent.php
  resources/assets/less/bem/btn-osu-big.less
  resources/assets/less/bem/simple-form.less
  resources/lang/en/beatmapset_events.php
  resources/views/beatmapset_events/_item.blade.php
  resources/views/beatmapset_events/index.blade.php
Labels: resolves issue

#3736 Prompt for login if not logged in when starting a checkout
  app/Http/Controllers/Store/CheckoutController.php
  app/Http/Controllers/Store/Controller.php
Labels: resolves issue

#3738 Search classes refactoring
  app/Http/Controllers/BeatmapsetsController.php
  app/Http/Controllers/UsersController.php
  app/Libraries/Elasticsearch/HasChildQuery.php
  app/Libraries/Elasticsearch/HasSearch.php
  app/Libraries/Elasticsearch/Search.php
  app/Libraries/Elasticsearch/SearchParams.php
  app/Libraries/Search/BeatmapsetSearch.php
  app/Libraries/Search/BeatmapsetSearchParams.php
  app/Libraries/Search/BeatmapsetSearchRequestParams.php
  app/Libraries/Search/ForumSearch.php
  app/Libraries/Search/ForumSearchParams.php
  app/Libraries/Search/ForumSearchRequestParams.php
  app/Libraries/Search/MultiSearch.php
  app/Libraries/Search/PostSearchRequestParams.php
  app/Libraries/Search/UserSearch.php
  app/Libraries/Search/UserSearchParams.php
  app/Libraries/Search/UserSearchRequestParams.php
  app/Libraries/Search/WikiSearch.php
  app/Libraries/Search/WikiSearchRequestParams.php
Labels: code quality

#3548 Allow users to hide their online status
  app/Http/Controllers/AccountController.php
  app/Models/User.php
  app/Transformers/UserTransformer.php
  resources/assets/coffee/react/profile-page/header-extra.coffee
  resources/lang/en/accounts.php
  resources/views/accounts/_edit_privacy.blade.php
  resources/views/objects/_usercard.blade.php
Labels: resolves issue

#3721 Disallow replying to deleted comment
  app/Http/Controllers/CommentsController.php
  app/Models/Comment.php
  resources/assets/coffee/react/_components/comment.coffee
  resources/lang/en/model_validation.php
  tests/Models/CommentTest.php
Labels: resolves issue

#3747 Fix usercard broken when loaded but user is null
  resources/views/objects/_usercard.blade.php
Labels: bug

#3753 Fix report reasons localization
  resources/assets/lib/report-form.coffee
Labels: resolves issue

#3741 Fix show more not working for admins on restricted user profiles
  app/Http/Controllers/UsersController.php
Labels: bug

#3772 Don't limit beatmaps listing of user profile page
  app/Http/Controllers/UsersController.php
Labels: resolves issue

#3780 Update localisations
  resources/lang/bg/authorization.php
  resources/lang/bg/beatmap_discussions.php
  resources/lang/bg/beatmaps.php
  resources/lang/bg/beatmapset_events.php
  resources/lang/bg/beatmapset_watches.php
  resources/lang/bg/beatmapsets.php
  resources/lang/bg/changelog.php
  resources/lang/bg/common.php
  resources/lang/bg/community.php
  resources/lang/bg/contest.php
  resources/lang/bg/errors.php
  resources/lang/bg/events.php
  resources/lang/bg/forum.php
  resources/lang/bg/friends.php
  resources/lang/bg/fulfillments.php
  resources/lang/bg/home.php
  resources/lang/bg/layout.php
  resources/lang/bg/livestreams.php
  resources/lang/bg/model_validation.php
  resources/lang/bg/multiplayer.php
  resources/lang/bg/news.php
  resources/lang/bg/password_reset.php
  resources/lang/bg/rankings.php
  resources/lang/bg/status_page.php
  resources/lang/bg/store.php
  resources/lang/bg/supporter_tag.php
  resources/lang/bg/tournament.php
  resources/lang/bg/user_verification.php
  resources/lang/bg/users.php
  resources/lang/cs/forum.php
  resources/lang/cs/users.php
  resources/lang/da/beatmap_discussions.php
  resources/lang/da/beatmapset_discussion_votes.php
  resources/lang/da/model_validation.php
  resources/lang/fi/beatmaps.php
  resources/lang/fi/beatmapset_events.php
  resources/lang/fi/changelog.php
  resources/lang/fi/contest.php
  resources/lang/fi/forum.php
  resources/lang/fi/layout.php
  resources/lang/fi/multiplayer.php
  resources/lang/fi/store.php
  resources/lang/fi/users.php
  resources/lang/ja/beatmaps.php
  resources/lang/ja/beatmapset_events.php
  resources/lang/ja/users.php
  resources/lang/nl/users.php
  resources/lang/zh/beatmaps.php
  resources/lang/zh/changelog.php
  resources/lang/zh/forum.php
  resources/lang/zh/users.php
Labels: localisation

#3791 Add command to cancel stale orders
  .env.example
  app/Console/Commands/StoreCleanupStaleOrders.php
  app/Console/Kernel.php
  app/Http/Controllers/Store/Controller.php
  app/Models/Store/Order.php
  config/store.php
  database/migrations/2018_10_12_045503_add_index_to_orders_updated_at.php
Labels: store

#3755 Rename isDeleted/withoutDeleted to trashed/withoutTrashed in model
  app/Libraries/OsuAuthorize.php
  app/Models/BeatmapDiscussion.php
  app/Models/BeatmapDiscussionPost.php
  app/Models/Beatmapset.php
  app/Models/Comment.php
  app/Models/User.php
  resources/views/beatmap_discussions/_item.blade.php
Labels: code quality

#3770 Fix oauth authorization page
  app/framework_helper_overrides.php
Labels: resolves issue

#3821 Fix tournament registration wording error
  resources/lang/en/tournament.php
Labels: localisation

#3802 Show fewer surrounding timestamps on modding new discussion box
  resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
Labels: resolves issue

#3814 Add comment voting
  app/Http/Controllers/CommentsController.php
  app/Libraries/CommentBundle.php
  app/Libraries/OsuAuthorize.php
  app/Models/Comment.php
  app/Models/CommentVote.php
  app/Transformers/CommentTransformer.php
  app/Transformers/CommentableMetaTransformer.php
  database/migrations/2018_10_15_102603_create_comment_votes.php
  database/migrations/2018_10_16_012859_add_votes_count_to_comments.php
  resources/assets/coffee/main.coffee
  resources/assets/coffee/osu_common.coffee
  resources/assets/coffee/react/_components/comment.coffee
  resources/assets/coffee/react/_components/comments-manager.coffee
  resources/assets/coffee/react/_components/comments.coffee
  resources/assets/coffee/react/beatmapset-page/main.coffee
  resources/assets/coffee/react/changelog-build/main.coffee
  resources/assets/coffee/react/comments-index.coffee
  resources/assets/coffee/react/comments-index/main.coffee
  resources/assets/coffee/react/comments-show.coffee
  resources/assets/coffee/react/comments-show/main.coffee
  resources/assets/less/bem-index.less
  resources/assets/less/bem/comment-vote.less
  resources/assets/less/bem/comment.less
  resources/views/news/show.blade.php
  routes/web.php
Labels: comments

#3833 Convert int cursors to string for javascript
  app/Libraries/Elasticsearch/Search.php
Labels: bug, search

#3815 Fix incorrect replies count on new topic
  app/Models/Forum/Topic.php
Labels: resolves issue

#3842 Fix missing react key on profile page
  resources/assets/coffee/react/profile-page/historical.coffee
Labels: bug
