Repository ppy/osu-web, pull requests merged in 2018-12, with the labels that each got.

#3933 Fix anchor offsets on news pages
  resources/assets/less/bem/osu-md.less
Labels: resolves issue

#3934 Add ability to mark forums as read
  app/Http/Controllers/Forum/ForumsController.php
  app/Models/Forum/Forum.php
  app/Models/Forum/TopicTrack.php
  app/Models/User.php
  resources/assets/less/bem/btn-osu-big.less
  resources/assets/less/bem/forum-topics-spacer.less
  resources/assets/less/forum/base.less
  resources/lang/en/forum.php
  resources/views/forum/forums/_mark_as_read.blade.php
  resources/views/forum/forums/_new_topic.blade.php
  resources/views/forum/forums/index.blade.php
  resources/views/forum/forums/show.blade.php
  routes/web.php
Labels: resolves issue

#3921 Apply OAuth permission scoping to API
  app/Exceptions/Handler.php
  app/Http/Controllers/Passport/AuthorizationController.php
  app/Http/Controllers/UsersController.php
  app/Http/Kernel.php
  app/Http/Middleware/RequireScopes.php
  app/Providers/AppServiceProvider.php
  app/Providers/AuthServiceProvider.php
  app/Transformers/UserTransformer.php
  app/helpers.php
  resources/lang/en/api.php
  routes/web.php
  tests/Controllers/Chat/Channels/MessagesControllerTest.php
  tests/Controllers/Chat/ChannelsControllerTest.php
  tests/Controllers/Chat/ChatControllerTest.php
  tests/Controllers/Passport/AuthorizationControllerTest.php
  tests/RequireScopesTest.php
  tests/RouteScopesTest.php
  tests/TestCase.php
Labels: api

#3941 Disable mark as read button if not signed in
  app/Http/Controllers/Forum/ForumsController.php
  resources/views/forum/forums/_mark_as_read.blade.php
Labels: bug

#3949 Fix RequireScopes middleware containsScoped check
  app/Http/Middleware/RequireScopes.php
Labels: bug

#3944 Add post and profile length limit
  app/Http/Controllers/AccountController.php
  app/Models/Forum/Post.php
  app/Models/User.php
  config/osu.php
Labels: resolves issue

#4001 Update url when navigating to anchors
  resources/assets/coffee/turbolinks-overrides.coffee
Labels: resolves issue

#3994 Reduce number of render layers on user profile page
  resources/assets/less/bem/beatmap-playcount.less
  resources/assets/less/bem/page-extra.less
Labels: performance

#4009 Fix some browsers drawing flag icons from wrong offset
  resources/assets/less/bem/flag-country.less
Labels: resolves issue

#3991 Add scope for viewing who a user is following
  app/Http/Controllers/FriendsController.php
  app/Providers/AuthServiceProvider.php
  resources/lang/en/api.php
  tests/RouteScopesTest.php
Labels: api

#4015 Edited node.js requirement
  SETUP.md
Labels: code quality

#4003 Remove user colours from user filter
  resources/assets/coffee/react/beatmap-discussions/user-filter.coffee
Labels: resolves issue

#4020 Add support for reporting comments
  app/Http/Controllers/CommentsController.php
  app/Http/Controllers/ScoresController.php
  app/Http/Controllers/UsersController.php
  app/Libraries/OsuAuthorize.php
  app/Models/Comment.php
  app/Models/Reportable.php
  app/Models/Score/Best/Model.php
  app/Models/User.php
  app/Models/UserReport.php
  app/Providers/AppServiceProvider.php
  database/migrations/2018_12_13_121903_add_reportable_type_to_user_reports.php
  resources/assets/coffee/react/_components/comment.coffee
  resources/assets/lib/coffee-modules.d.ts
  resources/assets/lib/import-shims.coffee
  resources/assets/lib/report-comment.tsx
  resources/assets/ts/globals.d.ts
  resources/lang/en/report.php
  routes/web.php
  tests/Libraries/ReportCommentTest.php
  tests/Libraries/ReportScoreTest.php
  tests/Libraries/ReportUserTest.php
Labels: resolves issue
