Repository ppy/osu-web, pull requests merged in 2018-02, with the labels that each got.

#2355 Docker updates
  README.md
  build.sh
  docker-compose.yml
  docker/php/setup.sh
  docker/yarn/Dockerfile
  docker/yarn/setup.sh
Labels: framework update, pending review

#2373 Don't include results that didn't match the username matchers
  app/Models/Elasticsearch/UserTrait.php
Labels: bug, search

#2345 Scoreboard friend/self highlighting
  resources/assets/coffee/osu_common.coffee
  resources/assets/coffee/react/beatmapset-page/scoreboard-table.coffee
  resources/assets/coffee/react/beatmapset-page/scoreboard.coffee
  resources/assets/less/bem/beatmap-scoreboard-table.less
Labels: resolves issue

#2391 Update Polish translation
  resources/lang/pl/beatmapsets.php
  resources/lang/pl/home.php
  resources/lang/pl/multiplayer.php
  resources/lang/pl/rankings.php
  resources/lang/pl/tournament.php
  resources/lang/pl/users.php
  resources/lang/pl/wiki.php
Labels: localisation

#2386 Show genre and language and fix styles
  app/Http/Controllers/BeatmapsetsController.php
  app/Models/Beatmapset.php
  app/Transformers/BeatmapsetTransformer.php
  resources/assets/coffee/react/beatmapset-page/info.coffee
  resources/assets/less/bem/beatmapset-info.less
  resources/lang/en/beatmapsets.php
Labels: resolves issue

#2390 Add missing beatmaps migration
  database/migrations/2015_01_01_133337_base_tables.php
Labels: database

#2408 Show usercard for mapper name in welcome page
  resources/views/home/_user_beatmapset.blade.php
Labels: resolves issue

#2410 Link to news index
  resources/assets/less/bem/news-post-preview.less
  resources/assets/less/bem/user-home.less
  resources/lang/en/common.php
  resources/views/home/user.blade.php
Labels: resolves issue

#2270 Discussion navigation history
  app/Http/Controllers/BeatmapDiscussionPostsController.php
  app/Http/Controllers/BeatmapsetsController.php
  app/Models/Beatmapset.php
  app/Transformers/BeatmapDiscussionTransformer.php
  app/Transformers/BeatmapsetDiscussionTransformer.php
  app/Transformers/BeatmapsetTransformer.php
  resources/assets/coffee/_classes/beatmap-discussion-helper.coffee
  resources/assets/coffee/_classes/beatmap-discussions-chart.coffee
  resources/assets/coffee/react/beatmap-discussions.coffee
  resources/assets/coffee/react/beatmap-discussions/beatmap-list.coffee
  resources/assets/coffee/react/beatmap-discussions/discussion.coffee
  resources/assets/coffee/react/beatmap-discussions/discussions.coffee
  resources/assets/coffee/react/beatmap-discussions/event.coffee
  resources/assets/coffee/react/beatmap-discussions/events.coffee
  resources/assets/coffee/react/beatmap-discussions/header.coffee
  resources/assets/coffee/react/beatmap-discussions/main.coffee
  resources/assets/coffee/react/beatmap-discussions/mode-switcher.coffee
  resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
  resources/assets/coffee/react/beatmap-discussions/new-reply.coffee
  resources/assets/coffee/react/beatmap-discussions/nominations.coffee
  resources/assets/coffee/react/beatmap-discussions/post.coffee
  resources/assets/coffee/react/beatmap-discussions/subscribe.coffee
  resources/assets/coffee/turbolinks-overrides.coffee
  routes/web.php
Labels: resolves issue

#2406 Differentiate hover and active/focus state buttons
  resources/assets/less/bem/btn-osu-big.less
Labels: resolves issue

#2411 Allow showing all first ranked maps
  app/Http/Controllers/UsersController.php
  resources/assets/coffee/react/profile-page/main.coffee
  resources/assets/coffee/react/profile-page/show-more-link.coffee
Labels: resolves issue

#2423 Link flags to country rankings
  resources/assets/less/bem/usercard.less
  resources/views/forum/topics/_post_info.blade.php
  resources/views/layout/_popup_user.blade.php
  resources/views/objects/_usercard.blade.php
  resources/views/rankings/performance.blade.php
  resources/views/rankings/score.blade.php
Labels: resolves issue

#2468 Spelling corrections in layout.php
  resources/lang/en/layout.php
Labels: resolves issue

#2422 Profile tooltips
  resources/assets/coffee/react/profile-page/header-extra.coffee
  resources/assets/less/bem/profile-header-extra.less
  resources/lang/da/users.php
  resources/lang/en/users.php
  resources/lang/es/users.php
  resources/lang/fr/users.php
  resources/lang/it/users.php
  resources/lang/ko/users.php
  resources/lang/nl/users.php
  resources/lang/pl/users.php
  resources/lang/pt-br/users.php
  resources/lang/ru/users.php
  resources/lang/sv/users.php
  resources/lang/zh/users.php
Labels: resolves issue

#2480 Make "Leave Feedback" button able to be translated
  resources/assets/coffee/react/beatmap-discussions/nominations.coffee
  resources/lang/en/beatmaps.php
Labels: localisation

#2409 Add experience bar to user profiles
  resources/assets/coffee/react/profile-page/stats.coffee
  resources/assets/less/bem/bar.less
  resources/assets/less/bem/profile-badge.less
  resources/assets/less/bem/profile-stats.less
Labels: resolves issue

#2442 Add recommended difficulty and converted beatmap filters to beatmap search panel
  app/Http/Controllers/BeatmapsetsController.php
  app/Models/Beatmapset.php
  app/Models/User.php
  resources/assets/coffee/_classes/beatmapset-filter.coffee
  resources/assets/coffee/react/beatmaps/search-panel.coffee
  resources/lang/en/beatmaps.php
Labels: resolves issue

#2389 Limit voting based on current beatmapset state
  app/Libraries/OsuAuthorize.php
  resources/lang/en/authorization.php
  tests/Controllers/BeatmapDiscussionsControllerTest.php
Labels: resolves issue

#2496 Unbreak safari
  resources/assets/less/bem/account-edit-entry.less
  resources/assets/less/bem/account-edit.less
  resources/assets/less/bem/beatmap-discussion-new-float.less
  resources/assets/less/bem/beatmap-discussion-post.less
  resources/assets/less/bem/beatmap-discussion.less
  resources/assets/less/bem/beatmap-icon.less
  resources/assets/less/bem/beatmapset-beatmap-picker.less
  resources/assets/less/bem/beatmapset-panel.less
  resources/assets/less/bem/beatmapset-row.less
  resources/assets/less/bem/btn-circle.less
  resources/assets/less/bem/btn-osu-big.less
  resources/assets/less/bem/changelog-build.less
  resources/assets/less/bem/detail-row.less
  resources/assets/less/bem/landing-hero.less
  resources/assets/less/bem/loading-overlay.less
  resources/assets/less/bem/notification-banner.less
  resources/assets/less/bem/osu-page-header.less
  resources/assets/less/bem/page-extra-tabs.less
  resources/assets/less/bem/product-box.less
  resources/assets/less/bem/profile-extra-entries.less
  resources/assets/less/bem/search-entry.less
  resources/assets/less/bem/search-result.less
  resources/assets/less/bem/support-osu-popup.less
  resources/assets/less/forum/base.less
  resources/assets/less/functions.less
Labels: browser issue

#2486 Logout links are button.
  resources/assets/less/bem/logo-menu.less
  resources/assets/less/bem/nav-popup.less
  resources/assets/less/bem/navbar-mobile-item.less
  resources/assets/less/bem/user-verification.less
  resources/views/layout/_popup_user.blade.php
  resources/views/layout/header_mobile/user.blade.php
  resources/views/objects/logo-menu.blade.php
  resources/views/users/_verify_box.blade.php
Labels: resolves issue

#2506 Fix wrong target_user_id being saved in UserDonation
  app/Libraries/Fulfillments/ApplySupporterTag.php
Labels: bug

#2514 Tooltip update
  resources/assets/coffee/_classes/tooltip-default.coffee
  resources/assets/coffee/react/profile-page/header-extra.coffee
  resources/assets/less/bem/forum-topic-nav.less
  resources/assets/less/bem/tooltip-default.less
  resources/assets/less/forum/base.less
  resources/views/forum/forums/_forums.blade.php
Labels: resolves issue

#2412 Add a supporter promo to changelogs
  public/images/badges/heart.png
  public/images/badges/heart@2x.png
  public/images/layout/pippi.png
  public/images/layout/pippi@2x.png
  resources/assets/less/bem-index.less
  resources/assets/less/bem/changelog.less
  resources/assets/less/bem/landing-hero.less
  resources/assets/less/bem/supporter-promo.less
  resources/lang/en/changelog.php
  resources/views/changelog/show.blade.php
Labels: resolves issue

#2518 Delete the `NEW` tag from osu!supporter benefits
  resources/lang/da/community.php
  resources/lang/en/community.php
  resources/lang/es/community.php
  resources/lang/fr/community.php
  resources/lang/it/community.php
  resources/lang/ko/community.php
  resources/lang/nl/community.php
  resources/lang/pt-br/community.php
  resources/lang/ru/community.php
  resources/lang/sv/community.php
Labels: localisation

#2515 Unify case for locale menu
  resources/assets/less/bem/nav-popup.less
Labels: resolves issue

#2505 Users controller refactor
  app/Http/Controllers/UsersController.php
  app/Transformers/UserTransformer.php
  resources/assets/coffee/react/profile-page.coffee
  resources/assets/coffee/react/profile-page/main.coffee
  routes/web.php
Labels: resolves issue

#2516 Better input styling
  resources/assets/coffee/_classes/parent-focus.coffee
  resources/assets/coffee/main.coffee
  resources/assets/less/bem/account-edit-entry.less
  resources/assets/less/bem/header-search-box.less
  resources/assets/less/bem/search-header.less
  resources/views/accounts/_edit_email.blade.php
  resources/views/accounts/_edit_entry_simple.blade.php
  resources/views/accounts/_edit_password.blade.php
  resources/views/layout/header.blade.php
Labels: resolves issue

#2521 Spanish language update v3
  resources/lang/es/accounts.php
  resources/lang/es/authorization.php
  resources/lang/es/beatmaps.php
  resources/lang/es/changelog.php
  resources/lang/es/errors.php
  resources/lang/es/home.php
  resources/lang/es/users.php
Labels: localisation

#2522 Replace "Log Out" with "Sign Out"
  resources/lang/da/layout.php
  resources/lang/en/layout.php
  resources/lang/es/layout.php
  resources/lang/fr/layout.php
  resources/lang/it/layout.php
  resources/lang/ko/layout.php
  resources/lang/nl/layout.php
  resources/lang/pl/layout.php
  resources/lang/pt-br/layout.php
  resources/lang/ru/layout.php
  resources/lang/sv/layout.php
  resources/lang/zh/layout.php
Labels: resolves issue

#2530 Add usercard to profile historical listing
  resources/assets/coffee/react/profile-page/historical.coffee
Labels: resolves issue

#2525 Reduce database queries in beatmap discussion fetches
  app/Transformers/BeatmapsetTransformer.php
  resources/assets/coffee/react/beatmap-discussions/main.coffee
  resources/assets/coffee/react/beatmap-discussions/subscribe.coffee
Labels: database, performance

#2524 Fix model_pluck
  app/helpers.php
Labels: resolves issue

#2512 Allow hype/feedback button to wrap text to fit localised strings
  resources/assets/coffee/react/beatmap-discussions/nominations.coffee
  resources/assets/less/bem/beatmap-discussion-nomination.less
  resources/assets/less/bem/btn-osu-big.less
Labels: resolves issue

#2541 Fix softDelete of beatmapset discussion post
  app/Models/BeatmapDiscussion.php
  app/Models/BeatmapDiscussionPost.php
  resources/assets/coffee/react/beatmap-discussions/post.coffee
Labels: modding discussions

#2531 Improved page title
  app/Http/Controllers/BeatmapsetsController.php
  resources/lang/da/layout.php
  resources/lang/en/layout.php
  resources/lang/es/layout.php
  resources/lang/fr/layout.php
  resources/lang/it/layout.php
  resources/lang/ko/layout.php
  resources/lang/pl/layout.php
  resources/lang/pt-br/layout.php
  resources/lang/ru/layout.php
  resources/lang/sv/layout.php
  resources/lang/zh/layout.php
  resources/views/beatmapsets/discussion.blade.php
  resources/views/beatmapsets/show.blade.php
  resources/views/forum/forums/show.blade.php
  resources/views/forum/topics/show.blade.php
  resources/views/master.blade.php
  resources/views/news/index.blade.php
  resources/views/news/show.blade.php
  resources/views/store/products/show.blade.php
  resources/views/wiki/show.blade.php
Labels: resolves issue

#2527 Remove footer links on landing page
  resources/views/home/landing.blade.php
  resources/views/layout/footer.blade.php
Labels: resolves issue

#2528 Full width show more link
  resources/assets/coffee/react/profile-page/beatmaps.coffee
  resources/assets/coffee/react/profile-page/kudosu.coffee
  resources/assets/coffee/react/profile-page/recent-activity.coffee
  resources/assets/coffee/react/profile-page/show-more-link.coffee
  resources/assets/coffee/react/profile-page/top-ranks.coffee
  resources/assets/less/bem-index.less
  resources/assets/less/bem/profile-extra-entries.less
  resources/assets/less/bem/show-more-link.less
Labels: resolves issue

#2578 Show post count on user profile page
  app/Transformers/UserTransformer.php
  resources/assets/coffee/react/profile-page/header-extra.coffee
  resources/lang/en/users.php
Labels: resolves issue

#2570 Avatar positioning
  resources/assets/less/bem/avatar.less
  resources/views/layout/_header_user.blade.php
Labels: resolves issue
