Repository ppy/osu-web, pull requests merged in 2018-08, with the labels that each got.

#3532 Alias index after index group is finished
  app/Console/Commands/EsIndexDocuments.php
  app/Traits/EsIndexable.php
Labels: resolves issue

#3555 Update localisations
  resources/lang/cs/accounts.php
  resources/lang/cs/beatmapsets.php
  resources/lang/cs/layout.php
  resources/lang/cs/user_verification.php
  resources/lang/da/accounts.php
  resources/lang/da/beatmapset_discussion_votes.php
  resources/lang/da/beatmapset_events.php
  resources/lang/da/beatmapsets.php
  resources/lang/da/common.php
  resources/lang/da/paypal/errors.php
  resources/lang/da/users.php
  resources/lang/it/users.php
  resources/lang/ja/model_validation/store/product.php
  resources/lang/ko/beatmaps.php
  resources/lang/ko/beatmapset_events.php
  resources/lang/ko/forum.php
  resources/lang/ko/layout.php
  resources/lang/pl/changelog.php
  resources/lang/pl/layout.php
  resources/lang/ro/beatmapsets.php
  resources/lang/vi/accounts.php
  resources/lang/vi/api.php
  resources/lang/vi/artist.php
  resources/lang/vi/authorization.php
  resources/lang/vi/bbcode.php
  resources/lang/vi/beatmap_discussion_posts.php
  resources/lang/vi/beatmap_discussions.php
  resources/lang/vi/beatmappacks.php
  resources/lang/vi/model_validation/store/product.php
  resources/lang/vi/paypal/errors.php
  resources/lang/zh/model_validation/store/product.php
Labels: localisation

#3168 Centre forum category headers
  resources/assets/less/bem/forum-category-header.less
Labels: design, proposal

#3553 Include recipient of supporter tag in admin notification
  app/Events/Fulfillments/SupporterTagEvent.php
  app/Libraries/Fulfillments/SupporterTagFulfillment.php
  tests/Libraries/Fulfillments/SupporterTagFulfillmentTest.php
Labels: store

#3561 Disable tooltip auto hiding
  resources/assets/coffee/_classes/tooltip-beatmap.coffee
  resources/assets/coffee/_classes/tooltip-default.coffee
Labels: resolves issue

#3524 Apply colours to usernames on the beatmap discussion user filter
  resources/assets/coffee/react/beatmap-discussions/header.coffee
  resources/assets/coffee/react/beatmap-discussions/user-filter.coffee
  resources/assets/less/app.less
  resources/assets/less/bem/beatmap-discussion-post.less
  resources/assets/less/bem/beatmap-discussions-user-filter.less
  resources/assets/less/select-options.less
  resources/assets/less/variables.less
  resources/assets/lib/import-shims.coffee
  resources/assets/lib/select-options.coffee
  webpack.mix.js
Labels: resolves issue

#3569 Update supporter page artwork with new commission
  public/images/headers/community-support.jpg
  public/images/headers/community-support.png
  public/images/headers/community-support@2x.jpg
  public/images/headers/community-support@2x.png
  resources/assets/less/bem/stg-header.less
Labels: design, store

#3584 Show featured artists in alphabetical order
  app/Http/Controllers/ArtistsController.php
Labels: resolves issue

#3600 Record payment country of origin
  app/Libraries/Payments/CentiliPaymentProcessor.php
  app/Libraries/Payments/PaymentProcessor.php
  app/Libraries/Payments/PaypalPaymentProcessor.php
  app/Libraries/Payments/XsollaPaymentProcessor.php
  database/migrations/2018_08_27_053717_add_country_code_to_payments.php
Labels: store

#3610 Don't set background-image url if undefined
  resources/assets/coffee/_classes/current-user-observer.coffee
  resources/assets/coffee/_classes/forum-cover.coffee
  resources/assets/coffee/osu_common.coffee
  resources/assets/coffee/react/_components/beatmapset-mapping.coffee
  resources/assets/coffee/react/_components/track-preview.coffee
  resources/assets/coffee/react/_components/user-avatar.coffee
  resources/assets/coffee/react/beatmap-discussions/header.coffee
  resources/assets/coffee/react/beatmaps/search-panel.coffee
  resources/assets/coffee/react/beatmapset-page/header.coffee
  resources/assets/coffee/react/beatmapset-page/score-top.coffee
  resources/assets/coffee/react/contest/voting/art-entry.coffee
  resources/assets/coffee/react/mp-history/game-header.coffee
  resources/assets/coffee/react/profile-page/badges.coffee
  resources/assets/coffee/react/profile-page/cover-selection.coffee
  resources/assets/coffee/react/profile-page/header-main.coffee
  resources/assets/coffee/react/profile-page/historical.coffee
Labels: bug

#3613 Check more fields for country codes in Centili response
  app/Libraries/Payments/CentiliPaymentProcessor.php
Labels: store

#3572 Hide tooltip on click
  resources/assets/coffee/_classes/tooltip-beatmap.coffee
  resources/assets/coffee/_classes/tooltip-default.coffee
Labels: resolves issue
