Repository ppy/osu-web, pull requests merged in 2018-04, with the labels that each got.

#2883 [lang/es] Fix/update spanish post_count
  resources/lang/es/users.php
Labels: localisation

#2847 Update mods order
  app/Libraries/ModsHelper.php
Labels: resolves issue

#2870 Add missing keys for Polish locale
  resources/lang/pl/common.php
Labels: localisation, resolves issue

#2874 Image Alignment on Modding Discussions Page
  resources/assets/less/bem/beatmap-discussions-header-top.less
Labels: resolves issue

#2865 Don't wrap the tagline text in the downloads page
  resources/assets/less/bem/download-page-header.less
Labels: resolves issue

#2898 Topic events cleanup
  app/Events/Forum/TopicUpdate.php
  app/Events/Forum/TopicWasCreated.php
  app/Events/Forum/TopicWasReplied.php
  app/Events/Forum/TopicWasViewed.php
  app/Http/Controllers/Forum/TopicsController.php
  app/Jobs/NotifyForumUpdateMail.php
  app/Jobs/NotifyForumUpdateSlack.php
  app/Libraries/ForumUpdateNotifier.php
  app/Models/Forum/Post.php
  app/Models/Forum/Topic.php
  app/Models/Forum/TopicTrack.php
  app/Models/Forum/TopicWatch.php
  app/Providers/EventServiceProvider.php
Labels: resolves issue

#2901 Check user is trying to checkout with current cart
  app/Http/Controllers/Store/CheckoutController.php
  resources/assets/lib/store-checkout.coffee
  resources/lang/en/store.php
  resources/views/store/_checkout_centili.blade.php
  resources/views/store/_checkout_free.blade.php
  resources/views/store/_checkout_xsolla.blade.php
Labels: store

#2904 Update badge style
  resources/assets/less/bem/profile-badges.less
Labels: design, user profile

#2903 Misc fixes and user pm link
  app/Http/Controllers/HomeController.php
  resources/assets/coffee/react/_components/friend-button.coffee
  resources/assets/coffee/react/profile-page/header-extra.coffee
  resources/assets/less/bem-index.less
  resources/assets/less/bem/profile-header-extra.less
  resources/assets/less/bem/user-action-button.less
  resources/lang/en/users.php
  resources/views/forum/topics/_posts.blade.php
  resources/views/objects/_usercard.blade.php
  routes/web.php
Labels: user profile

#2911 Touchdevice mod display
  app/Libraries/ModsHelper.php
  public/images/badges/mods/mod_touchdevice.png
  public/images/badges/mods/mod_touchdevice@2x.png
  resources/assets/coffee/react/beatmapset-page/scoreboard.coffee
  resources/assets/less/bem/mod.less
  resources/lang/en/beatmaps.php
Labels: resolves issue

#2924 Navigation header metric tweaks
  resources/assets/less/bem/nav2.less
  resources/assets/less/layout.less
  resources/assets/less/variables.less
Labels: design, ux

#2925 Prevent duplicate voting to same discussion
  database/migrations/2018_04_06_081112_unique_beatmapset_discussion_votes.php
Labels: resolves issue

#2935 use simple_query_string instead of query_string
  app/Libraries/Elasticsearch/QueryHelper.php
Labels: search

#2934 Fix wrong variable
  app/Libraries/Elasticsearch/Search.php
Labels: bug

#2896 Add supporter status to the supporter page
  app/Http/Controllers/Forum/TopicsController.php
  app/Http/Controllers/HomeController.php
  app/Models/User.php
  app/helpers.php
  resources/assets/less/bem-index.less
  resources/assets/less/bem/icon-fancy.less
  resources/assets/less/bem/stg-block.less
  resources/assets/less/bem/stg-status.less
  resources/lang/en/community.php
  resources/views/home/support-the-game.blade.php
Labels: resolves issue

#2965 Wait to acquire row lock before checking if record can be deleted.
  app/Models/Store/Order.php
Labels: bug, store

#2976 Carts that haven't been saved yet can't be locked for update
  app/Models/Store/Order.php
Labels: bug, critical, store

#2973 Spanish language update v5
  resources/lang/es/beatmap_discussions.php
  resources/lang/es/beatmaps.php
  resources/lang/es/beatmapsets.php
  resources/lang/es/common.php
  resources/lang/es/community.php
  resources/lang/es/forum.php
  resources/lang/es/home.php
  resources/lang/es/layout.php
  resources/lang/es/model_validation.php
  resources/lang/es/store.php
  resources/lang/es/users.php
Labels: localisation

#2957 Use Laravel's `File` thingy
  app/Console/Commands/LocaleCheck.php
Labels: code quality

#2977 Add spoiler tag
  app/Libraries/BBCodeForDB.php
Labels: resolves issue

#2980 Configurable sender for donation thanks mail
  app/Mail/DonationThanks.php
  config/store.php
Labels: store

#2956 Send order confirmation mail after store payment received
  app/Listeners/Fulfillments/PaymentSubscribers.php
  app/Mail/StorePaymentCompleted.php
  resources/lang/en/store.php
  resources/views/emails/store/payment_completed-en.blade.php
Labels: resolves issue

#2954 Post to disqualify
  app/Http/Controllers/BeatmapDiscussionPostsController.php
  app/Http/Controllers/BeatmapsetsController.php
  app/Libraries/OsuAuthorize.php
  app/Models/Beatmapset.php
  app/Models/BeatmapsetEvent.php
  resources/assets/coffee/_classes/beatmap-discussion-helper.coffee
  resources/assets/coffee/react/beatmap-discussions/event.coffee
  resources/assets/coffee/react/beatmap-discussions/main.coffee
  resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
  resources/assets/coffee/react/beatmap-discussions/nominations.coffee
  resources/assets/coffee/react/beatmap-discussions/post.coffee
  resources/assets/less/bem-index.less
  resources/assets/less/bem/beatmap-discussion-post.less
  resources/assets/less/bem/beatmapset-discussion-message.less
  resources/lang/da/beatmaps.php
  resources/lang/en/beatmaps.php
  resources/lang/es/beatmaps.php
  resources/lang/it/beatmaps.php
  resources/lang/pl/beatmaps.php
  resources/lang/pt-br/beatmaps.php
  resources/lang/sv/beatmaps.php
  resources/lang/zh-tw/beatmaps.php
  resources/lang/zh/beatmaps.php
  routes/web.php
Labels: resolves issue

#2985 Show correct button labels
  resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
Labels: modding discussions, resolves issue

#2984 Username history
  app/Http/Controllers/UsersController.php
  app/Models/UsernameChangeHistory.php
  app/Transformers/UserTransformer.php
  resources/assets/coffee/react/profile-page/header-info.coffee
  resources/lang/en/users.php
Labels: resolves issue

#2994 Fix messages and featured artists song count pluralization i18n
  resources/lang/da/artist.php
  resources/lang/da/home.php
  resources/lang/en/artist.php
  resources/lang/en/home.php
  resources/lang/es/artist.php
  resources/lang/es/home.php
  resources/lang/it/artist.php
  resources/lang/pl/artist.php
  resources/lang/pl/home.php
  resources/lang/pt-br/artist.php
  resources/lang/pt-br/home.php
  resources/lang/ru/artist.php
  resources/lang/ru/home.php
  resources/lang/sv/artist.php
  resources/lang/sv/home.php
Labels: resolves issue

#2997 Reset size selector on select and load (browser form saving)
  resources/assets/coffee/forum/post-box.coffee
  resources/assets/coffee/react/_components/bbcode-editor.coffee
Labels: resolves issue

#2996 font-awesome icon fixes
  app/Http/Controllers/HomeController.php
  app/Models/Contest.php
  resources/assets/coffee/react/_components/beatmapset-panel.coffee
  resources/assets/coffee/react/_components/tracklist-track.coffee
  resources/assets/coffee/react/beatmap-discussions/new-reply.coffee
  resources/assets/coffee/react/beatmapset-page/header.coffee
  resources/assets/coffee/react/contest/voting/entry.coffee
  resources/views/contests/_voting-entrylist.blade.php
  resources/views/home/download.blade.php
  resources/views/home/landing.blade.php
  resources/views/home/user.blade.php
  resources/views/objects/beatmap-panel.blade.php
Labels: bug, design

#3003 Allow activity text on user profile page to wrap
  resources/assets/less/bem/profile-extra-entries.less
Labels: resolves issue

#2998 Define React and friends as externals in webpack
  webpack.mix.js
Labels: code quality

#3001 Virtualize beatmap listing
  package.json
  resources/assets/coffee/react/beatmaps/main.coffee
  resources/assets/less/bem/beatmapsets.less
  resources/assets/lib/import-shims.coffee
  yarn.lock
Labels: performance, resolves issue

#3021 Wrap table in container
  app/Libraries/OsuMarkdownProcessor.php
  app/Libraries/OsuTableRenderer.php
  resources/assets/less/bem/osu-md.less
Labels: resolves issue

#3020 Allow middle clicking profile icon
  resources/assets/coffee/_classes/click-menu.coffee
  resources/views/layout/_header_user.blade.php
Labels: ux

#3030 Use '100%' instead of 'cover' for .badge-rank
  resources/assets/less/bem/badge-rank.less
Labels: resolves issue

#3033 Add Discord field to user profiles
  app/Http/Controllers/AccountController.php
  app/Models/User.php
  app/Transformers/UserTransformer.php
  resources/assets/coffee/_classes/tooltip-default.coffee
  resources/assets/coffee/react/_components/click-to-copy.coffee
  resources/assets/coffee/react/profile-page/header-extra.coffee
  resources/assets/less/bem-index.less
  resources/assets/less/bem/click-to-copy.less
  resources/lang/en/accounts.php
  resources/lang/en/common.php
  resources/lang/en/model_validation.php
  resources/lang/en/users.php
  resources/views/accounts/edit.blade.php
Labels: resolves issue

#3022 Show total first place rank count on profile; display pp instead of score
  app/Http/Controllers/UsersController.php
  app/Transformers/BeatmapsetCompactTransformer.php
  app/Transformers/UserTransformer.php
  resources/assets/coffee/react/_components/play-detail.coffee
  resources/assets/coffee/react/profile-page.coffee
  resources/assets/coffee/react/profile-page/main.coffee
  resources/assets/coffee/react/profile-page/top-ranks.coffee
  resources/lang/da/users.php
  resources/lang/en/users.php
  resources/lang/es/users.php
  resources/lang/fr/users.php
  resources/lang/it/users.php
  resources/lang/ko/users.php
  resources/lang/nl/users.php
  resources/lang/pl/users.php
  resources/lang/pt-br/users.php
  resources/lang/ru/users.php
  resources/lang/sv/users.php
  resources/lang/zh-tw/users.php
  resources/lang/zh/users.php
Labels: resolves issue

#2891 [WIP] completed japanese localisation for some files
  resources/lang/ja/accounts.php
  resources/lang/ja/admin.php
  resources/lang/ja/api.php
  resources/lang/ja/artist.php
  resources/lang/ja/home.php
  resources/lang/ja/layout.php
  resources/lang/ja/livestreams.php
  resources/lang/ja/user_verification.php
  resources/lang/ja/users.php
  resources/lang/ja/validation.php
  resources/lang/ja/wiki.php
Labels: localisation

#3046 l103: ":names" shouldn't be there!
  resources/lang/fr/users.php
Labels: localisation

#3047 Fix check for showing pp
  resources/assets/coffee/react/_components/play-detail.coffee
Labels: resolves issue

#2857 Search implementation overhaul
  app/Http/Controllers/BeatmapsetsController.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/UsersController.php
  app/Libraries/Elasticsearch/HasChildQuery.php
  app/Libraries/Elasticsearch/HasSearch.php
  app/Libraries/Elasticsearch/Hit.php
  app/Libraries/Elasticsearch/RecordSearch.php
  app/Libraries/Elasticsearch/Search.php
  app/Libraries/Elasticsearch/SearchPaginator.php
  app/Libraries/Elasticsearch/SearchParams.php
  app/Libraries/Elasticsearch/SearchResponse.php
  app/Libraries/Elasticsearch/Sort.php
  app/Libraries/Search.php
  app/Libraries/Search/AllSearch.php
  app/Libraries/Search/BasicSearch.php
  app/Libraries/Search/BeatmapsetSearch.php
  app/Libraries/Search/BeatmapsetSearchParams.php
  app/Libraries/Search/BeatmapsetSearchRequestParams.php
  app/Libraries/Search/EmptySearchParams.php
  app/Libraries/Search/ForumSearch.php
  app/Libraries/Search/ForumSearchParams.php
  app/Libraries/Search/ForumSearchRequestParams.php
  app/Libraries/Search/MultiSearch.php
  app/Libraries/Search/PostSearch.php
  app/Libraries/Search/PostSearchParams.php
  app/Libraries/Search/PostSearchRequestParams.php
  app/Libraries/Search/QuickSearch.php
  app/Libraries/Search/UserSearch.php
  app/Libraries/Search/UserSearchParams.php
  app/Libraries/Search/UserSearchRequestParams.php
  app/Libraries/Search/WikiSearch.php
  app/Libraries/Search/WikiSearchParams.php
  app/Libraries/Search/WikiSearchRequestParams.php
  app/Models/Beatmapset.php
  app/Models/Elasticsearch/UserTrait.php
  app/Models/User.php
  app/Models/Wiki/Page.php
  app/helpers.php
  resources/assets/less/bem-index.less
  resources/assets/less/bem/search-result-entry.less
  resources/assets/less/bem/search-result.less
  resources/views/home/_nav_search_entry.blade.php
  resources/views/home/_search_forum_post.blade.php
  resources/views/home/_search_page_tabs.blade.php
  resources/views/home/_search_result_beatmapset.blade.php
  resources/views/home/_search_result_forum_post.blade.php
  resources/views/home/_search_result_user.blade.php
  resources/views/home/_search_result_wiki_page.blade.php
  resources/views/home/_search_results.blade.php
  resources/views/home/_search_wiki_page.blade.php
  resources/views/home/nav_search_result.blade.php
  resources/views/home/search.blade.php
  resources/views/users/posts.blade.php
  routes/web.php
Labels: resolves issue

#3049 Check if search count workaround queries needs to run before running
  app/Libraries/Search/MultiSearch.php
Labels: bug, search

#3017 Spanish language update v5.2
  resources/lang/es/artist.php
  resources/lang/es/beatmaps.php
  resources/lang/es/beatmapset_events.php
  resources/lang/es/common.php
  resources/lang/es/community.php
  resources/lang/es/store.php
  resources/lang/es/users.php
Labels: localisation

#3068 Less misleading title when pp data doesn't exist for ranked maps
  resources/assets/coffee/react/_components/play-detail.coffee
Labels: user profile

#3053 Update beatmapset ranking queue system
  app/Models/Beatmapset.php
  database/migrations/2018_04_20_100654_add_queue_time_to_beatmapsets.php
Labels: modding discussions

#3069 Eagerload beatmaps.
  app/Http/Controllers/BeatmapsetsController.php
Labels: bug, performance

#3070 Solid color for reply form background
  resources/assets/less/bem/forum-topic-reply.less
Labels: resolves issue

#3067 Allow chart ticks to be fewer than 6 in mobile
  resources/assets/coffee/react/profile-page/historical.coffee
Labels: resolves issue

#3051 Add played filter to beatmap listing
  app/Http/Controllers/BeatmapsetsController.php
  app/Libraries/Search/BeatmapsetSearch.php
  app/Libraries/Search/BeatmapsetSearchParams.php
  app/Libraries/Search/BeatmapsetSearchRequestParams.php
  resources/assets/coffee/_classes/beatmapset-filter.coffee
  resources/assets/coffee/react/beatmaps/search-panel.coffee
  resources/lang/en/beatmaps.php
Labels: resolves issue

#3076 Filter user website value on output as well
  app/Models/User.php
Labels: resolves issue

#3079 Properly show shortened url when editing post
  app/Libraries/BBCodeForDB.php
  app/Libraries/BBCodeFromDB.php
Labels: resolves issue

#3086 Use correct user for rendering post info in editor
  resources/views/forum/topics/_post_edit.blade.php
Labels: bug

#3036 Add check on new player for posting on forum
  .env.example
  app/Exceptions/Handler.php
  app/Libraries/OsuAuthorize.php
  app/Models/UserMonthlyPlaycount.php
  config/osu.php
  resources/lang/da/layout.php
  resources/lang/en/authorization.php
  resources/lang/en/layout.php
  resources/lang/es/layout.php
  resources/lang/fr/layout.php
  resources/lang/it/layout.php
  resources/lang/ja/layout.php
  resources/lang/ko/layout.php
  resources/lang/nl/layout.php
  resources/lang/pl/layout.php
  resources/lang/pt-br/layout.php
  resources/lang/ru/layout.php
  resources/lang/sv/layout.php
  resources/lang/zh-tw/layout.php
  resources/lang/zh/layout.php
  resources/views/layout/error.blade.php
  tests/Controllers/ForumTopicsControllerTest.php
Labels: forum
