Repository ppy/osu-web, pull requests merged in 2018-05, with the labels that each got.

#3113 Keep Docker MySQL container version at 5.7
  docker-compose.yml
Labels: testing

#3129 Change Charts to Spotlights
  resources/lang/da/beatmappacks.php
  resources/lang/da/layout.php
  resources/lang/da/rankings.php
  resources/lang/en/beatmappacks.php
  resources/lang/en/layout.php
  resources/lang/en/rankings.php
  resources/lang/es/beatmappacks.php
  resources/lang/es/layout.php
  resources/lang/es/rankings.php
  resources/lang/fr/beatmappacks.php
  resources/lang/fr/layout.php
  resources/lang/fr/rankings.php
  resources/lang/it/layout.php
  resources/lang/ja/beatmappacks.php
  resources/lang/ja/layout.php
  resources/lang/ja/rankings.php
  resources/lang/ko/beatmappacks.php
  resources/lang/ko/layout.php
  resources/lang/ko/rankings.php
  resources/lang/nl/layout.php
  resources/lang/pt-br/beatmappacks.php
  resources/lang/pt-br/layout.php
  resources/lang/pt-br/rankings.php
  resources/lang/ru/beatmappacks.php
  resources/lang/ru/layout.php
  resources/lang/ru/rankings.php
  resources/lang/sv/beatmappacks.php
  resources/lang/sv/layout.php
  resources/lang/sv/rankings.php
  resources/lang/zh-tw/beatmappacks.php
  resources/lang/zh-tw/layout.php
  resources/lang/zh-tw/rankings.php
  resources/lang/zh/beatmappacks.php
  resources/lang/zh/layout.php
  resources/lang/zh/rankings.php
Labels: resolves issue

#3125 [ES] Changes on User page
  resources/lang/es/users.php
Labels: bug, localisation

#3123 Allow redirecting wiki paths more than one level deep
  routes/web.php
Labels: bug

#3137 Log unknown exceptions for Xsolla to Sentry
  app/Http/Controllers/Payments/XsollaController.php
Labels: store

#3142 Sort discussion by timestamp
  resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
Labels: resolves issue

#3141 Add tooltip to modding history link & hide on bots
  app/Transformers/UserCompactTransformer.php
  resources/assets/coffee/react/beatmap-discussions/post.coffee
  resources/lang/en/beatmap_discussion_posts.php
Labels: resolves issue

#3140 Update flag for SH
  public/images/flags/SH.png
Labels: design

#3139 Various fixes
  app/Exceptions/Handler.php
  app/Http/Controllers/Users/ModdingHistoryController.php
  app/Http/Controllers/UsersController.php
  app/Libraries/BBCodeFromDB.php
  app/Models/Elasticsearch/TopicTrait.php
  resources/assets/coffee/_classes/beatmap-discussion-helper.coffee
  resources/assets/coffee/react/profile-page/main.coffee
Labels: resolves issue

#3146 Fix modding history not applying user filter
  app/Http/Controllers/Users/ModdingHistoryController.php
  app/Models/BeatmapDiscussion.php
  app/Models/BeatmapDiscussionPost.php
  app/Models/BeatmapDiscussionVote.php
Labels: resolves issue

#3090 Add user filter for beatmap discussions
  resources/assets/coffee/_classes/beatmap-discussion-helper.coffee
  resources/assets/coffee/react/beatmap-discussions/beatmap-list.coffee
  resources/assets/coffee/react/beatmap-discussions/discussion.coffee
  resources/assets/coffee/react/beatmap-discussions/discussions.coffee
  resources/assets/coffee/react/beatmap-discussions/header.coffee
  resources/assets/coffee/react/beatmap-discussions/main.coffee
  resources/assets/coffee/react/beatmap-discussions/nominations.coffee
  resources/assets/coffee/react/beatmap-discussions/user-filter.coffee
  resources/assets/less/bem-index.less
  resources/assets/less/bem/beatmap-discussions-header-top.less
  resources/assets/less/bem/beatmap-discussions-user-filter.less
  resources/assets/less/bem/beatmap-list-item.less
  resources/assets/less/bem/beatmap-list.less
  resources/lang/en/beatmap_discussions.php
Labels: resolves issue

#3087 Revise the Polish translation
  resources/lang/pl/accounts.php
  resources/lang/pl/admin.php
  resources/lang/pl/artist.php
  resources/lang/pl/authorization.php
  resources/lang/pl/bbcode.php
  resources/lang/pl/beatmap_discussions.php
  resources/lang/pl/beatmappacks.php
  resources/lang/pl/beatmaps.php
  resources/lang/pl/beatmapset_events.php
  resources/lang/pl/beatmapset_watches.php
  resources/lang/pl/beatmapsets.php
  resources/lang/pl/changelog.php
  resources/lang/pl/common.php
  resources/lang/pl/community.php
  resources/lang/pl/contest.php
  resources/lang/pl/forum.php
  resources/lang/pl/home.php
  resources/lang/pl/layout.php
  resources/lang/pl/livestreams.php
  resources/lang/pl/multiplayer.php
  resources/lang/pl/password_reset.php
  resources/lang/pl/rankings.php
  resources/lang/pl/status_page.php
  resources/lang/pl/store.php
  resources/lang/pl/tournament.php
  resources/lang/pl/user_verification.php
  resources/lang/pl/users.php
  resources/lang/pl/wiki.php
Labels: localisation

#2068 Vietnamese translation
  app/Libraries/LocaleMeta.php
  config/app.php
  resources/lang/vi/accounts.php
  resources/lang/vi/admin.php
  resources/lang/vi/api.php
  resources/lang/vi/artist.php
  resources/lang/vi/authorization.php
  resources/lang/vi/bbcode.php
  resources/lang/vi/beatmap_discussion_posts.php
  resources/lang/vi/beatmap_discussions.php
  resources/lang/vi/beatmappacks.php
  resources/lang/vi/beatmaps.php
  resources/lang/vi/beatmapset_discussion_votes.php
  resources/lang/vi/beatmapset_events.php
  resources/lang/vi/beatmapset_watches.php
  resources/lang/vi/beatmapsets.php
  resources/lang/vi/changelog.php
  resources/lang/vi/common.php
  resources/lang/vi/community.php
  resources/lang/vi/contest.php
  resources/lang/vi/errors.php
  resources/lang/vi/events.php
  resources/lang/vi/forum.php
  resources/lang/vi/friends.php
  resources/lang/vi/fulfillments.php
  resources/lang/vi/help.php
  resources/lang/vi/home.php
  resources/lang/vi/layout.php
  resources/lang/vi/livestreams.php
  resources/lang/vi/model_validation.php
  resources/lang/vi/model_validation/fulfillments.php
  resources/lang/vi/model_validation/payments.php
  resources/lang/vi/multiplayer.php
  resources/lang/vi/news.php
  resources/lang/vi/password_reset.php
  resources/lang/vi/paypal/errors.php
  resources/lang/vi/rankings.php
  resources/lang/vi/status_page.php
  resources/lang/vi/store.php
  resources/lang/vi/supporter_tag.php
  resources/lang/vi/tournament.php
  resources/lang/vi/user_verification.php
  resources/lang/vi/users.php
  resources/lang/vi/validation.php
  resources/lang/vi/wiki.php
Labels: localisation

#3156 Fix discussion counts wrapping under chart on mobile
  resources/assets/less/bem/beatmap-discussions-header-top.less
  resources/assets/less/bem/counter-box.less
Labels: bug, modding discussions

#3155 Skip releasing of reserved stock on cancelled payments
  app/Libraries/Payments/PaymentProcessor.php
Labels: store

#3091 Show tournament supporter banner in profile page
  .env.example
  app/Http/Controllers/UsersController.php
  app/Models/ProfileBanner.php
  app/Transformers/ProfileBannerTransformer.php
  app/Transformers/UserTransformer.php
  config/osu.php
  resources/assets/coffee/osu_common.coffee
  resources/assets/coffee/react/profile-page/header-main.coffee
  resources/assets/less/bem/profile-badges.less
  resources/assets/less/bem/profile-header.less
  resources/assets/less/variables.less
Labels: resolves issue

#3152 Only show discussion starters in user filter
  resources/assets/coffee/react/beatmap-discussions/header.coffee
  resources/assets/coffee/react/beatmap-discussions/main.coffee
Labels: modding discussions, resolves issue

#3158 Set a background colour for the avatar in usercard
  resources/assets/less/bem/usercard.less
Labels: resolves issue

#3171 Replace the old default avatar
  app/Traits/UserAvatar.php
  config/osu.php
Labels: code quality

#3164 Allow larger button in beatmapset header
  resources/assets/less/bem/btn-osu-big.less
Labels: design, user profile

#3151 Update spoilerbox design
  app/Libraries/BBCodeFromDB.php
  resources/assets/less/bem/bbcode-spoilerbox.less
Labels: resolves issue

#3162 Check if cancelled Order already has a cancelled Payment
  app/Libraries/Payments/PaymentProcessor.php
Labels: store

#3170 Filter blank discussions and change to case-insensitive username sort
  resources/assets/coffee/react/beatmap-discussions/main.coffee
Labels: resolves issue

#3166 Retina-ify beatmapset-panel
  resources/assets/coffee/react/_components/beatmapset-panel.coffee
  resources/assets/less/bem/beatmapset-panel.less
Labels: beatmap, design

#3177 Fix discussionLinkify
  resources/assets/coffee/_classes/beatmap-discussion-helper.coffee
Labels: resolves issue

#3181 [zh] Chinese patch-11
  resources/lang/zh/accounts.php
  resources/lang/zh/admin.php
  resources/lang/zh/artist.php
  resources/lang/zh/authorization.php
  resources/lang/zh/beatmap_discussion_posts.php
  resources/lang/zh/beatmap_discussions.php
  resources/lang/zh/beatmaps.php
  resources/lang/zh/beatmapset_events.php
  resources/lang/zh/beatmapsets.php
  resources/lang/zh/changelog.php
  resources/lang/zh/common.php
  resources/lang/zh/community.php
  resources/lang/zh/forum.php
  resources/lang/zh/home.php
  resources/lang/zh/layout.php
  resources/lang/zh/model_validation.php
  resources/lang/zh/store.php
  resources/lang/zh/tournament.php
  resources/lang/zh/users.php
Labels: localisation

#3172 Fix editing user page
  app/Libraries/OsuAuthorize.php
Labels: bug, user profile

#3178 Bahasa Indonesia Localisation Update
  resources/lang/id/accounts.php
  resources/lang/id/artist.php
  resources/lang/id/beatmappacks.php
  resources/lang/id/beatmaps.php
  resources/lang/id/beatmapsets.php
  resources/lang/id/changelog.php
  resources/lang/id/home.php
  resources/lang/id/status_page.php
  resources/lang/id/users.php
Labels: localisation

#3106 Thai translation
  .styleci.yml
  config/app.php
  resources/lang/th/accounts.php
  resources/lang/th/admin.php
  resources/lang/th/api.php
  resources/lang/th/artist.php
  resources/lang/th/authorization.php
  resources/lang/th/bbcode.php
  resources/lang/th/beatmap_discussion_posts.php
  resources/lang/th/beatmap_discussions.php
  resources/lang/th/beatmappacks.php
  resources/lang/th/beatmaps.php
  resources/lang/th/beatmapset_discussion_votes.php
  resources/lang/th/beatmapset_events.php
  resources/lang/th/beatmapset_watches.php
  resources/lang/th/beatmapsets.php
  resources/lang/th/changelog.php
  resources/lang/th/common.php
  resources/lang/th/community.php
  resources/lang/th/contest.php
  resources/lang/th/errors.php
  resources/lang/th/events.php
  resources/lang/th/forum.php
  resources/lang/th/friends.php
  resources/lang/th/fulfillments.php
  resources/lang/th/help.php
  resources/lang/th/home.php
  resources/lang/th/layout.php
  resources/lang/th/livestreams.php
  resources/lang/th/model_validation.php
  resources/lang/th/model_validation/fulfillments.php
  resources/lang/th/model_validation/payments.php
  resources/lang/th/multiplayer.php
  resources/lang/th/news.php
  resources/lang/th/password_reset.php
  resources/lang/th/paypal/errors.php
  resources/lang/th/rankings.php
  resources/lang/th/status_page.php
  resources/lang/th/store.php
  resources/lang/th/supporter_tag.php
  resources/lang/th/tournament.php
  resources/lang/th/user_verification.php
  resources/lang/th/users.php
  resources/lang/th/validation.php
  resources/lang/th/wiki.php
Labels: WIP, localisation

#2240 German Localisation
  .styleci.yml
  config/app.php
  resources/lang/de/accounts.php
  resources/lang/de/admin.php
  resources/lang/de/api.php
  resources/lang/de/artist.php
  resources/lang/de/authorization.php
  resources/lang/de/bbcode.php
  resources/lang/de/beatmap_discussion_posts.php
  resources/lang/de/beatmap_discussions.php
  resources/lang/de/beatmappacks.php
  resources/lang/de/beatmaps.php
  resources/lang/de/beatmapset_discussion_votes.php
  resources/lang/de/beatmapset_events.php
  resources/lang/de/beatmapset_watches.php
  resources/lang/de/beatmapsets.php
  resources/lang/de/changelog.php
  resources/lang/de/common.php
  resources/lang/de/community.php
  resources/lang/de/contest.php
  resources/lang/de/errors.php
  resources/lang/de/events.php
  resources/lang/de/forum.php
  resources/lang/de/friends.php
  resources/lang/de/fulfillments.php
  resources/lang/de/help.php
  resources/lang/de/home.php
  resources/lang/de/layout.php
  resources/lang/de/livestreams.php
  resources/lang/de/model_validation.php
  resources/lang/de/multiplayer.php
  resources/lang/de/news.php
  resources/lang/de/password_reset.php
  resources/lang/de/rankings.php
  resources/lang/de/status_page.php
  resources/lang/de/store.php
  resources/lang/de/supporter_tag.php
  resources/lang/de/todo.md
  resources/lang/de/tournament.php
  resources/lang/de/user_verification.php
  resources/lang/de/users.php
  resources/lang/de/validation.php
  resources/lang/de/wiki.php
  resources/lang/en/community.php
Labels: WIP, localisation

#3194 Override trans to ignore empty strings
  app/Models/Store/OrderItem.php
  app/framework_helper_overrides.php
  resources/assets/coffee/_classes/store-supporter-tag-price.coffee
  resources/assets/coffee/main.coffee
  resources/assets/coffee/osu_common.coffee
  resources/assets/coffee/store-username-change.coffee
  resources/assets/less/bem/simple-form.less
  resources/lang/en/forum.php
  resources/views/accounts/_edit_playstyle_checkbox.blade.php
  resources/views/forum/topics/_create_poll.blade.php
  resources/views/home/_search_results.blade.php
  resources/views/home/search.blade.php
  resources/views/packs/index.blade.php
  resources/views/store/checkout.blade.php
  resources/views/store/products/supporter-tag.blade.php
  resources/views/store/products/username-change.blade.php
  resources/views/users/posts.blade.php
  tests/LocaleTest.php
Labels: code quality, localisation

#3199 Don't escape trans where markup is passed by param
  resources/views/packs/index.blade.php
  resources/views/store/checkout.blade.php
Labels: resolves issue

#3202 Fix mode switching in discussion
  resources/assets/coffee/_classes/beatmap-helper.coffee
Labels: resolves issue

#3204 Fix ranking page titles
  app/Http/Controllers/RankingController.php
  resources/views/rankings/index.blade.php
Labels: resolves issue

#3154 Sort qualified beatmap listing according to qualified queue date
  app/Libraries/Search/BeatmapsetSearch.php
  app/Libraries/Search/BeatmapsetSearchRequestParams.php
  app/Models/Beatmapset.php
Labels: resolves issue, search

#3209 Show past tournaments on the tournament listing
  app/Http/Controllers/TournamentsController.php
  app/Models/Tournament.php
  resources/assets/less/bem/tournament-list-item.less
  resources/assets/less/bem/tournament-list.less
  resources/lang/en/tournament.php
  resources/views/tournaments/index.blade.php
Labels: resolves issue

#3226 Add loved beatmaps to user profile
  app/Http/Controllers/UsersController.php
  app/Models/Beatmapset.php
  app/Models/User.php
  app/Transformers/UserTransformer.php
  resources/assets/coffee/react/profile-page/beatmaps.coffee
  resources/assets/coffee/react/profile-page/main.coffee
  resources/lang/en/users.php
Labels: resolves issue

#3222 Add user events for supporter and username changes
  app/Libraries/Fulfillments/SupporterTagFulfillment.php
  app/Libraries/Fulfillments/UsernameChangeFulfillment.php
  app/Models/Event.php
  app/Models/User.php
Labels: resolves issue

#3227 Order checkout validation does not support null carts
  app/Http/Controllers/Store/CartController.php
Labels: bug, store

#3230 Change new approved beatmaps to new ranked beatmaps
  resources/lang/en/home.php
Labels: resolves issue

#3236 Fix avatar background in beatmap favorite popup
  resources/assets/coffee/react/_components/user-avatar.coffee
  resources/assets/coffee/react/beatmapset-page/header.coffee
  resources/assets/less/bem/beatmapset-favourites.less
Labels: resolves issue

#3234 Never display iframe borders
  resources/assets/less/base.less
Labels: design

#3235 Add social buttons menu bar
  config/osu.php
  resources/assets/coffee/_classes/nav-button.coffee
  resources/assets/coffee/main.coffee
  resources/assets/less/bem/nav2.less
  resources/views/layout/_nav2.blade.php
Labels: design

#3220 Better wording on mapper info
  resources/assets/coffee/react/_components/beatmapset-mapping.coffee
  resources/assets/coffee/react/profile-page/historical.coffee
  resources/lang/en/beatmaps.php
  resources/lang/en/beatmapsets.php
Labels: localisation

#3243 Conditionally activate nav button javascript
  resources/assets/coffee/_classes/nav-button.coffee
Labels: design

#3247 Fix one missed translation key update
  resources/assets/coffee/react/_components/beatmapset-panel.coffee
Labels: localisation, regression

#3250 Preserve discussion timestamps on restore
  app/Models/BeatmapDiscussion.php
Labels: resolves issue

#3246 Remove unused view
  resources/views/objects/beatmap-panel.blade.php
Labels: code quality

#3257 Fix beatmap modding pages not working for guests
  resources/assets/coffee/react/_components/user-avatar.coffee
Labels: regression

#3225 Add toggle to block private messages from non-friends
  app/Http/Controllers/AccountController.php
  app/Models/User.php
  app/Transformers/UserTransformer.php
  resources/assets/coffee/_classes/account-edit.coffee
  resources/assets/less/bem/account-edit-entry.less
  resources/assets/less/bem/account-edit.less
  resources/lang/en/accounts.php
  resources/views/accounts/_edit_privacy.blade.php
  resources/views/accounts/edit.blade.php
Labels: feature, pending review, settings

#3240 Buttons instead of links for language switcher
  resources/assets/less/bem/landing-nav.less
  resources/views/home/landing.blade.php
Labels: resolves issue

#3242 Add github link to legal/status footer
  app/helpers.php
  config/osu.php
  resources/lang/en/layout.php
Labels: resolves issue

#3265 Update footer links in line with new legal links
  app/Http/Controllers/LegalController.php
  app/helpers.php
  resources/lang/en/layout.php
  resources/views/users/_disabled_message-en.blade.php
Labels: layout

#3264 Spinner updates
  app/helpers.php
  resources/assets/coffee/react/_components/big-button.coffee
  resources/assets/coffee/react/_components/friend-button.coffee
  resources/assets/coffee/react/_components/spinner.coffee
  resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
  resources/assets/coffee/react/beatmap-discussions/new-reply.coffee
  resources/assets/coffee/react/beatmaps/paginator.coffee
  resources/assets/coffee/react/profile-page/header-main.coffee
  resources/assets/coffee/react/profile-page/show-more-link.coffee
  resources/assets/less/app.less
  resources/assets/less/bem-index.less
  resources/assets/less/bem/spinner.less
  resources/assets/less/spinner.less
  resources/views/accounts/_edit_entry_status.blade.php
  resources/views/forum/topics/_watch.blade.php
  resources/views/forum/topics/show.blade.php
  resources/views/home/search.blade.php
  resources/views/objects/_usercard.blade.php
  resources/views/users/_verify_box.blade.php
Labels: design

#3260 Update account settings labels
  resources/assets/less/bem/account-edit-entry.less
  resources/views/accounts/_edit_email.blade.php
  resources/views/accounts/_edit_entry_simple.blade.php
  resources/views/accounts/_edit_password.blade.php
  resources/views/accounts/_edit_playstyle_checkbox.blade.php
  resources/views/accounts/_edit_privacy.blade.php
  resources/views/accounts/_edit_signature.blade.php
Labels: settings

#3259 Synchronize account saving behavior
  resources/assets/coffee/_classes/account-edit-playstyle.coffee
  resources/assets/coffee/_classes/account-edit.coffee
Labels: resolves issue

#3252 Add artist name in beatmapset qualification event
  app/Models/Event.php
Labels: resolves issue

#3251 Fix overlay on navigation from beatmap discussion page
  resources/assets/coffee/react/beatmap-discussions/beatmap-list.coffee
Labels: resolves issue

#3249 Less padding on floating page extra tabs
  resources/assets/less/bem/page-extra-tabs.less
  resources/assets/less/bem/page-mode.less
Labels: resolves issue

#3248 Add pagination above of ranking table
  resources/assets/less/bem/ranking-page.less
  resources/views/rankings/index.blade.php
Labels: resolves issue

#3245 Show unranked update date in card
  resources/assets/coffee/react/_components/beatmapset-panel.coffee
  resources/lang/en/beatmapsets.php
Labels: resolves issue

#3238 Link cover in beatmapset watchlist to discussion page
  resources/views/beatmapset_watches/index.blade.php
Labels: resolves issue

#3203 Pre-check topic create auth
  app/Libraries/AuthorizationResult.php
  resources/assets/coffee/_classes/nav2.coffee
  resources/assets/less/bem/forum-topic-entry.less
  resources/lang/en/forum.php
  resources/views/forum/forums/_new_topic.blade.php
  resources/views/forum/forums/_topics.blade.php
  resources/views/forum/forums/show.blade.php
Labels: resolves issue

#3268 Fix incorrect closing tag
  resources/views/layout/header_mobile/user.blade.php
Labels: bug

#3262 Shipping address updates for paypal checkout
  .env.example
  app/Libraries/Payments/PaypalCreatePayment.php
  config/payments.php
  resources/assets/lib/store-checkout.coffee
Labels: store

#3285 Return json on error for a json request
  app/Exceptions/Handler.php
Labels: api, bug

#3263 Move elasticsearch schemas to json
  app/Libraries/Elasticsearch/Indexing.php
  app/Models/Beatmapset.php
  app/Models/Elasticsearch/BeatmapsetTrait.php
  app/Models/Elasticsearch/PostTrait.php
  app/Models/Elasticsearch/TopicTrait.php
  app/Models/Elasticsearch/UserTrait.php
  app/Models/Forum/Post.php
  app/Models/User.php
  app/Traits/EsIndexable.php
  config/schemas/beatmaps.json
  config/schemas/posts.json
  config/schemas/users.json
Labels: code quality, search
