Repository ppy/osu-web, pull requests merged in 2018-09, with the labels that each got.

#3623 Reduce opacity for deleted points on the timeline
  resources/assets/coffee/_classes/beatmap-discussions-chart.coffee
  resources/assets/less/bem/beatmap-discussions-chart.less
Labels: modding discussions

#3589 Add a checker for user best scores
  app/Console/Commands/UserBestScoresCheckCommand.php
  app/Console/Kernel.php
  app/Libraries/UserBestScoresCheck.php
  app/Models/Score/Model.php
  app/Models/UserScoreable.php
Labels: admin

#3595 Link wiki page titles to their pages
  app/Models/Wiki/Page.php
  resources/assets/less/bem/osu-page-header.less
  resources/views/wiki/show.blade.php
Labels: resolves issue

#3664 Add option to download user's top plays
  .gitignore
  app/Http/Controllers/Users/ReplaysController.php
  app/Libraries/ReplayFile.php
  app/Models/Score/Model.php
  app/Transformers/ScoreTransformer.php
  app/helpers.php
  resources/assets/coffee/react/_components/play-detail.coffee
  resources/assets/coffee/react/profile-page/historical.coffee
  resources/assets/coffee/react/profile-page/top-ranks.coffee
  resources/assets/less/bem-index.less
  resources/assets/less/bem/detail-row.less
  resources/assets/less/bem/play-detail-menu.less
  resources/assets/lib/import-shims.coffee
  resources/assets/lib/play-detail-list.coffee
  resources/assets/lib/play-detail-menu.coffee
  resources/assets/lib/play-detail.coffee
  resources/lang/en/users.php
  routes/web.php
  tests/Libraries/ReplayFileTest.php
Labels: resolves issue

#3732 Fix missing replay content length in downloaded replays
  app/Http/Controllers/Users/ReplaysController.php
Labels: bug
