Repository ppy/osu-web, pull requests merged in 2019-09, with the labels that each got.

#4879 Only use inter for pages using torus
  package.json
  resources/assets/less/app.less
  resources/assets/less/variables.less
  resources/views/layout/metadata.blade.php
  yarn.lock
Labels: size/S

#4889 Lower case changelog label mapping exceptions
  app/Models/ChangelogEntry.php
Labels: size/S

#4883 Style code blocks to be dark in comments
  resources/assets/less/bem/comment.less
Labels: size/S

#4880 Display kudosu history entry for deleted beatmap
  app/Transformers/KudosuHistoryTransformer.php
  resources/assets/coffee/react/profile-page/kudosu.coffee
Labels: size/S, user profile

#4871 Remove api v1 routes
  app/Http/Controllers/API/LegacyController.php
  routes/web.php
Labels: size/S

#4813 Fix country ranking not working for api requests
  app/Http/Controllers/RankingController.php
Labels: api, resolves issue, size/XS

#4893 Extract topic poll state and user vote check functions
  app/Libraries/OsuAuthorize.php
  app/Models/Forum/TopicPoll.php
Labels: size/M

#4886 Use inter when using torus
  package.json
  resources/assets/less/app.less
  resources/assets/less/functions.less
  resources/assets/less/layout.less
  resources/assets/less/variables.less
  resources/views/forum/forums/index.blade.php
  resources/views/forum/forums/show.blade.php
  resources/views/master.blade.php
  yarn.lock
Labels: size/S

#4892 Allow updating multiple instances of forum header covers
  resources/assets/coffee/_classes/forum-cover.coffee
Labels: size/XS

#4894 Hide post preview on empty body
  resources/assets/coffee/_classes/post-preview.coffee
Labels: size/S

#4869 Fix undesirable modal closing onclick behaviour
  resources/assets/coffee/react/beatmapset-page/info.coffee
  resources/assets/lib/modal.coffee
Labels: resolves issue, size/M

#4885 New style for checkbox/radio button
  resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
  resources/assets/less/bem-index.less
  resources/assets/less/bem/beatmap-discussion-new.less
  resources/assets/less/bem/osu-switch-v2.less
  resources/views/accounts/_edit_notifications.blade.php
  resources/views/accounts/_edit_playstyle_checkbox.blade.php
  resources/views/accounts/_edit_privacy.blade.php
  resources/views/beatmap_discussions/index.blade.php
  resources/views/beatmapset_events/index.blade.php
  resources/views/forum/topics/_create_poll.blade.php
  resources/views/forum/topics/_poll_row.blade.php
  resources/views/objects/_switch.blade.php
  resources/views/objects/search/_forum_options.blade.php
Labels: size/L

#4877 Update OAuth client registration handling
  .env.example
  app/Http/Controllers/OAuth/ClientsController.php
  app/Models/OAuth/AuthCode.php
  app/Models/OAuth/Client.php
  app/Models/OAuth/RefreshToken.php
  app/Models/OAuth/Token.php
  app/Models/User.php
  app/Providers/AuthServiceProvider.php
  app/Transformers/OAuth/ClientTransformer.php
  config/osu.php
  database/migrations/2019_08_27_094035_add_client_id_index_to_oauth_access_tokens.php
  resources/lang/en/accounts.php
  resources/lang/en/common.php
  resources/lang/en/model_validation.php
  resources/lang/en/oauth.php
  routes/web.php
  tests/Controllers/OAuth/ClientsControllerTest.php
  tests/Models/OAuth/ClientTest.php
  tests/TestCase.php
  tests/Transformers/OAuth/ClientTransformerTest.php
Labels: size/XL

#4870 Force better indices when listing rankings
  app/Http/Controllers/RankingController.php
Labels: performance, size/M

#4891 Add tooltip to the upvote/downvote button of beatmap discussions showing voters
  app/Models/BeatmapDiscussion.php
  app/Transformers/BeatmapsetTransformer.php
  resources/assets/coffee/react/beatmap-discussions/discussion.coffee
  resources/assets/coffee/react/beatmapset-page/header.coffee
  resources/assets/less/bem-index.less
  resources/assets/less/bem/beatmap-discussion-new.less
  resources/assets/less/bem/user-list-popup.less
  resources/lang/en/beatmaps.php
  resources/lang/en/beatmapsets.php
  resources/lang/en/common.php
Labels: modding discussions, resolves issue, size/L

#4895 Fix styling of profile detail bar
  resources/assets/less/bem/profile-detail-bar.less
  resources/assets/less/bem/user-action-button.less
  resources/assets/less/variables.less
Labels: size/S

#4810 Add command to remove expired OAuth tokens
  app/Console/Commands/OAuthDeleteExpiredTokens.php
  app/Console/Kernel.php
  config/osu.php
  database/migrations/2019_08_26_053354_add_expires_at_index_to_oauth_tables.php
  tests/Commands/OAuthDeleteExpiredTokensTest.php
Labels: api, size/L, tooling

#4899 Localise gallery layout
  resources/lang/en/layout.php
  resources/views/layout/gallery_window.blade.php
Labels: size/S

#4913 Set user group badge server side
  app/Http/Controllers/Users/ModdingHistoryController.php
  app/Models/Beatmapset.php
  app/Models/User.php
  app/Models/UserGroup.php
  app/Transformers/UserCompactTransformer.php
  app/Transformers/UserTransformer.php
  resources/assets/coffee/osu_common.coffee
  resources/assets/coffee/react/beatmap-discussions/post.coffee
  resources/assets/coffee/react/beatmap-discussions/user-filter.coffee
  resources/assets/coffee/react/modding-profile/votes.coffee
Labels: code quality

#4785 Add various factories written for testing purposes
  database/factories/ContestEntryFactory.php
  database/factories/Multiplayer/EventFactory.php
  database/factories/Multiplayer/GameFactory.php
Labels: size/M, testing

#4928 Log user security related activities
  app/Http/Controllers/AccountController.php
  app/Http/Controllers/PasswordResetController.php
  app/Models/UserAccountHistory.php
Labels: admin

#4922 Change default username check to use empty string
  app/Http/Controllers/UsersController.php
Labels: code quality

#4915 Clean up new layout gutter variable
  resources/assets/less/bem/forum-list.less
  resources/assets/less/bem/forum-title.less
  resources/assets/less/bem/header-v4.less
  resources/assets/less/functions.less
  resources/assets/less/variables.less
Labels: code quality

#4920 Dark forum topic move dialog
  resources/assets/less/bem-index.less
  resources/assets/less/bem/bootstrap/modal-body.less
  resources/assets/less/bem/form-select.less
  resources/assets/less/bem/search-forum-options.less
  resources/views/forum/topics/_moderate_move.blade.php
  resources/views/objects/search/_forum_options.blade.php
Labels: design, forum

#4939 Add support for mirror mod in score listing
  app/Libraries/ModsHelper.php
  public/images/badges/mods/mod_mirror.png
  public/images/badges/mods/mod_mirror@2x.png
  resources/assets/coffee/react/beatmapset-page/scoreboard.coffee
  resources/assets/less/bem/mod.less
  resources/lang/en/beatmaps.php
Labels: beatmap info

#4953 Fix forum poll percentage being broken on several locales
  resources/views/forum/topics/_poll_row.blade.php
Labels: forum, resolves issue

#4961 Fix user color in discussion filter
  resources/assets/coffee/react/beatmap-discussions/user-filter.coffee
Labels: modding discussions, resolves issue

#4964 Use content font for signature
  resources/assets/less/bem/forum-post.less
  resources/assets/less/functions.less
Labels: forum, resolves issue

#4977 Fix forum post editor preview
  resources/assets/less/bem/forum-post-edit.less
  resources/views/forum/topics/_post_edit_form.blade.php
Labels: forum

#4975 Prevent downloading multiple previews
  resources/assets/coffee/_classes/post-preview.coffee
Labels: code quality, forum

#4971 Add polymorphic mapping name for BeatmapDiscussion
  app/Libraries/MorphMap.php
Labels: code quality, database

#4970 Show inline error message for reset password form
  app/Http/Controllers/PasswordResetController.php
  resources/views/password_reset/_initial.blade.php
Labels: ux

#4974 Fix newline rendering in bbcode code block
  app/Libraries/BBCodeForDB.php
  tests/Libraries/bbcode_examples/basic_code.base.txt
  tests/Libraries/bbcode_examples/basic_code.db.txt
  tests/Libraries/bbcode_examples/basic_code.html
Labels: forum

#4976 Fix bbcode newlines
  app/Libraries/BBCodeFromDB.php
  tests/Libraries/bbcode_examples/box_with_surrounding_newlines.base.txt
  tests/Libraries/bbcode_examples/box_with_surrounding_newlines.db.txt
  tests/Libraries/bbcode_examples/box_with_surrounding_newlines.html
  tests/Libraries/bbcode_examples/notice_with_surrounding_newlines.base.txt
  tests/Libraries/bbcode_examples/notice_with_surrounding_newlines.db.txt
  tests/Libraries/bbcode_examples/spoilerbox_with_surrounding_newlines.base.txt
  tests/Libraries/bbcode_examples/spoilerbox_with_surrounding_newlines.db.txt
  tests/Libraries/bbcode_examples/spoilerbox_with_surrounding_newlines.html
Labels: forum

#4990 Update mod mirror icon
  public/images/badges/mods/mod_mirror.png
  public/images/badges/mods/mod_mirror@2x.png
Labels: design

#4987 Convert TurbolinksReload to TypeScript
  resources/assets/coffee/_classes/turbolinks-reload.coffee
  resources/assets/coffee/main.coffee
  resources/assets/lib/import-shims.coffee
  resources/assets/lib/turbolinks-reload.ts
Labels: code quality

#4983 Update bbcode style
  app/Libraries/BBCodeFromDB.php
  resources/assets/less/bbcode.less
  resources/assets/less/bem/bbcode-spoilerbox.less
  resources/assets/less/bem/forum-post-content.less
  resources/assets/less/bem/forum-topic-entry.less
  tests/Libraries/bbcode_examples/basic_quote.html
  tests/Libraries/bbcode_examples/box_with_surrounding_newlines.html
  tests/Libraries/bbcode_examples/quote_newline.html
  tests/Libraries/bbcode_examples/spoilerbox_with_surrounding_newlines.html
Labels: forum

#5005 Update color for beatmap description editor
  resources/assets/less/bem/beatmapset-description-editor.less
  resources/assets/less/bem/post-editor.less
Labels: beatmap info, resolves issue

#4993 Add fancy scrollbar for osu!wiki TOC
  resources/views/wiki/show.blade.php
Labels: resolves issue, wiki

#4809 Wiki main page
  app/Http/Controllers/WikiController.php
  app/Libraries/Markdown/OsuMarkdownProcessor.php
  app/Libraries/Wiki/MainPageRenderer.php
  app/Libraries/Wiki/MarkdownRenderer.php
  app/Libraries/Wiki/Renderer.php
  app/Models/Wiki/Page.php
  app/helpers.php
  resources/assets/less/bem-index.less
  resources/assets/less/bem/osu-page-header.less
  resources/assets/less/bem/wiki-main-page-panel.less
  resources/assets/less/bem/wiki-main-page.less
  resources/assets/less/bem/wiki-search.less
  resources/assets/less/variables.less
  resources/assets/lib/register-components.coffee
  resources/assets/lib/wiki-search.tsx
  resources/lang/en/common.php
  resources/lang/en/wiki.php
  resources/views/wiki/_actions.blade.php
  resources/views/wiki/_notice.blade.php
  resources/views/wiki/main.blade.php
  resources/views/wiki/show.blade.php
Labels: size/XXL, wiki

#5012 Remove unused old menu
  resources/assets/less/bem-index.less
  resources/assets/less/bem/logo-menu.less
  resources/views/objects/logo_menu.blade.php
Labels: code quality

#5010 Change mods filter to exact match
  app/Libraries/ModsHelper.php
  app/Models/Score/Best/Model.php
Labels: beatmap info, resolves issue

#5029 Remove unused import
  app/Libraries/Elasticsearch/SearchParams.php
Labels: code quality

#5026 Update to use correct polymorphic mapping
  app/Models/BeatmapDiscussion.php
Labels: code quality

#5020 Update to latest CommonMark
  app/Libraries/Markdown/Indexing/NoopRenderer.php
  app/Libraries/Markdown/Indexing/RendererExtension.php
  app/Libraries/Markdown/OsuMarkdown.php
  app/Libraries/Markdown/OsuMarkdownProcessor.php
  app/Libraries/Markdown/OsuTableRenderer.php
  composer.json
  composer.lock
Labels: dependencies
