Repository ppy/osu-web, pull requests merged in 2019-06, with the labels that each got.

#4533 Use correct translation key for unwatch button title
  resources/views/beatmapset_watches/index.blade.php
Labels: resolves issue

#4470 Align join date to top on forum posts
  resources/assets/less/bem/forum-post.less
Labels: forum, proposal

#4541 Change the chat font to a legible one
  resources/assets/less/bem/chat-input.less
  resources/assets/less/bem/chat-message-group.less
Labels: resolves issue

#4551 pin alpine version + reduce layers + image size
  docker/php/Dockerfile
Labels: deploy

#4566 Generate event text for Bancho
  app/Models/Event.php
Labels: resolves issue

#4539 Allow searching by user and beatmapset id
  app/Libraries/Elasticsearch/Hit.php
  app/Libraries/Elasticsearch/SearchParams.php
  app/Libraries/Search/BeatmapsetSearch.php
  app/Libraries/Search/ForumSearchParams.php
  app/Libraries/Search/MultiSearch.php
  app/Libraries/Search/UserSearch.php
  app/Libraries/Search/WikiSearch.php
  resources/lang/be/home.php
  resources/lang/bg/home.php
  resources/lang/cs/home.php
  resources/lang/da/home.php
  resources/lang/de/home.php
  resources/lang/el/home.php
  resources/lang/en/home.php
  resources/lang/es/home.php
  resources/lang/fi/home.php
  resources/lang/fr/home.php
  resources/lang/hu/home.php
  resources/lang/id/home.php
  resources/lang/it/home.php
  resources/lang/ja/home.php
  resources/lang/ko/home.php
  resources/lang/nl/home.php
  resources/lang/no/home.php
  resources/lang/pl/home.php
  resources/lang/pt-br/home.php
  resources/lang/pt/home.php
  resources/lang/ro/home.php
  resources/lang/ru/home.php
  resources/lang/sk/home.php
  resources/lang/sv/home.php
  resources/lang/th/home.php
  resources/lang/tr/home.php
  resources/lang/vi/home.php
  resources/lang/zh-tw/home.php
  resources/lang/zh/home.php
  resources/views/home/search.blade.php
Labels: resolves issue

#4578 Show correct cover on friends page
  resources/assets/lib/friends-index/main.tsx
Labels: resolves issue

#4580 Add some defaults for placeholder changelog entry
  app/Models/ChangelogEntry.php
Labels: api, changelog, resolves issue

#4586 Add xsolla logo to store header
  public/images/headers/store.png
  public/images/headers/store@2x.png
Labels: store

#4585 Search for user via previous username
  app/Http/Controllers/LegacyInterOpController.php
  app/Libraries/ChangeUsername.php
  app/Libraries/Search/UserSearch.php
  app/Models/Elasticsearch/UserTrait.php
  app/Models/User.php
  app/Transformers/UserTransformer.php
  config/schemas/users.json
  routes/web.php
  tests/Libraries/ChangeUsernameTest.php
Labels: resolves issue

#4574 Permissions cleanup
  app/Libraries/OsuAuthorize.php
  app/Models/Chat/Channel.php
  app/Transformers/UserTransformer.php
  resources/assets/coffee/_classes/beatmap-discussion-helper.coffee
  resources/assets/coffee/react/_components/comment.coffee
  resources/assets/coffee/react/beatmap-discussions/discussion.coffee
  resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
  resources/assets/coffee/react/beatmap-discussions/nominations.coffee
  resources/assets/lib/chat/chat-api-responses.ts
Labels: code quality
