Repository ppy/osu-web, pull requests merged in 2019-10, with the labels that each got.

#5027 Fix wiki search results wrapping
  resources/assets/less/bem/search-entry.less
  resources/assets/less/bem/search-wiki-page.less
  resources/views/home/_search_result_wiki_page.blade.php
Labels: resolves issue, search

#4836 Disallow deleting posts after a discussion is resolved
  app/Libraries/OsuAuthorize.php
  app/Models/BeatmapDiscussionPost.php
  resources/assets/coffee/react/beatmap-discussions/discussion.coffee
  resources/lang/en/authorization.php
  tests/Controllers/BeatmapDiscussionPostsControllerTest.php
Labels: modding discussions, resolves issue, size/M

#5030 Remove deprecated has_scores property
  app/Models/Beatmapset.php
  app/Transformers/BeatmapsetTransformer.php
  resources/assets/coffee/react/beatmapset-page/info.coffee
  resources/assets/coffee/react/beatmapset-page/main.coffee
  resources/assets/coffee/react/beatmapset-page/scoreboard.coffee
  resources/assets/coffee/react/beatmapset-page/stats.coffee
Labels: code quality

#4783 Add beatmap information button to discussions
  resources/assets/coffee/react/beatmap-discussions/header.coffee
  resources/assets/less/bem/beatmap-discussions-header-bottom.less
  resources/lang/en/beatmaps.php
Labels: size/S

#4931 Show ordered list for list tag with any parameter
  app/Libraries/BBCodeFromDB.php
Labels: forum

#5004 Rank chart fixes
  app/Models/RankHistory.php
  resources/assets/coffee/react/profile-page/rank-chart.coffee
Labels: resolves issue, user profile

#5050 Improve phpunit wrapper
  bin/phpunit
Labels: testing

#5056 Remove scoreRanks from user statistics response
  app/Http/Controllers/Users/ModdingHistoryController.php
  app/Http/Controllers/UsersController.php
  app/Transformers/UserStatisticsTransformer.php
  resources/assets/coffee/react/profile-page/rank-count.coffee
Labels: api, resolves issue

#5031 Add API endpoint to favourite/unfavourite a beatmapset
  app/Http/Controllers/API/BeatmapsetsController.php
  app/Http/Controllers/Beatmapsets/FavouritesController.php
  app/Http/Controllers/BeatmapsetsController.php
  resources/assets/coffee/react/beatmapset-page/header.coffee
  resources/assets/coffee/react/beatmapset-page/main.coffee
  routes/web.php
Labels: api, resolves issue

#4934 Reporting improvements
  app/Http/Controllers/CommentsController.php
  app/Http/Controllers/ReportsController.php
  app/Http/Controllers/ScoresController.php
  app/Http/Controllers/UsersController.php
  app/Libraries/MorphMap.php
  app/Libraries/ReplayFile.php
  app/Models/BeatmapDiscussionPost.php
  app/Models/Comment.php
  app/Models/Reportable.php
  app/Models/Score/Best/Model.php
  app/Models/User.php
  app/Models/UserReport.php
  app/helpers.php
  database/migrations/2019_09_11_135102_add_beatmap_discussion_post_to_report_types.php
  resources/assets/coffee/react/_components/comment.coffee
  resources/assets/coffee/react/beatmap-discussions/post.coffee
  resources/assets/coffee/react/modding-profile/detail-bar.coffee
  resources/assets/coffee/react/profile-page/detail-bar.coffee
  resources/assets/less/bem/beatmap-discussion-post.less
  resources/assets/lib/coffee-modules.d.ts
  resources/assets/lib/globals.d.ts
  resources/assets/lib/play-detail-menu.tsx
  resources/assets/lib/report-form.coffee
  resources/assets/lib/report-reportable.tsx
  resources/assets/lib/report-score.coffee
  resources/assets/lib/report-user.coffee
  resources/assets/lib/user-card.tsx
  resources/lang/en/model_validation.php
  resources/lang/en/report.php
  routes/web.php
  tests/Controllers/ScoresControllerTest.php
  tests/Libraries/ReportCommentTest.php
  tests/Libraries/ReportScoreTest.php
Labels: admin

#4903 Delete unused strings
  resources/lang/en/changelog.php
  resources/lang/en/friends.php
  resources/lang/en/users.php
  resources/lang/en/wiki.php
Labels: code quality

#4906 Restyle the multiplayer lobby history page for the new colour system
  resources/assets/less/bem/mp-history-event.less
  resources/assets/less/bem/mp-history-events.less
  resources/assets/less/bem/mp-history-game.less
  resources/assets/less/bem/mp-history-player-score.less
  resources/assets/less/bem/osu-layout.less
Labels: design

#5034 Fix selected chat switching when receiving new message or closing channel
  resources/assets/lib/chat/chat-orchestrator.ts
  resources/assets/lib/models/chat/channel.ts
Labels: resolves issue

#4978 Hide deleted comments on the comments listing page
  app/Http/Controllers/CommentsController.php
  app/Libraries/CommentBundle.php
Labels: comments, resolves issue

#4778 Add margin for cover edit button on mobile
  resources/assets/less/bem/profile-header.less
Labels: design, resolves issue, size/XS

#5077 Fix invisible unread indicator blocking close button in chat
  resources/assets/less/bem/chat-conversation-list-item.less
Labels: chat

#5069 Index beatmap difficulties as separate objects
  app/Models/Elasticsearch/BeatmapsetTrait.php
  config/schemas/beatmaps.json
Labels: search

#5084 Include total and cursor in ranking api response
  app/Http/Controllers/RankingController.php
  resources/views/vendor/apidoc/partials/info.blade.php
Labels: resolves issue

#5096 Forum reply box fixes
  resources/assets/coffee/_classes/forum-topic-reply.coffee
  resources/assets/coffee/shared.coffee
  resources/assets/less/bem/forum-post-edit.less
  resources/views/forum/topics/_post_edit_form.blade.php
Labels: forum, resolves issue

#5098 Remove restricted users from friend list
  app/Http/Controllers/BlocksController.php
  app/Models/User.php
  app/Models/UserRelation.php
Labels: settings

#5095 Add date tooltip on multiplayer page
  resources/assets/coffee/react/mp-history/event.coffee
  resources/assets/coffee/react/mp-history/game-header.coffee
  resources/assets/lib/time-with-tooltip.tsx
Labels: multiplayer, resolves issue

#5070 Handle star difficulty per-mode when searching
  app/Libraries/Elasticsearch/Sort.php
  app/Libraries/Search/BeatmapsetSearch.php
  app/Libraries/Search/BeatmapsetSearchRequestParams.php
Labels: resolves issue

#5123 Replace register link with download
  config/osu.php
  resources/assets/less/bem/login-box.less
  resources/lang/en/layout.php
  resources/lang/en/users.php
  resources/views/home/landing.blade.php
  resources/views/layout/_popup_login.blade.php
Labels: ux

#5120 Update rate limit for registration
  app/Http/Controllers/UsersController.php
  app/Libraries/UserRegistration.php
Labels: api

#4973 Update polymorphic name data
  database/migrations/2019_09_18_074659_update_beatmapset_discussion_polymorphic_name.php
Labels: database

#5124 Add command to fix forum listing order
  app/Console/Commands/FixForumDisplayOrder.php
  app/Console/Kernel.php
Labels: forum, tooling

#5085 Add spotlight rankings to API
  app/Http/Controllers/RankingController.php
  app/Models/Spotlight.php
  app/Transformers/SpotlightTransformer.php
Labels: resolves issue

#5073 Centralize the wiki main page styling
  app/Libraries/Wiki/MainPageRenderer.php
  resources/assets/less/bem/wiki-main-page-panel.less
  resources/assets/less/bem/wiki-main-page.less
Labels: wiki

#5147 Add notification icon placeholder
  resources/views/layout/_header_mobile.blade.php
  resources/views/layout/_nav2.blade.php
Labels: resolves issue

#5155 Allow validation-only user registration
  app/Http/Controllers/UsersController.php
  tests/Controllers/UsersControllerTest.php
Labels: api

#4724 Add direct link for beatmap packs
  app/Http/Controllers/BeatmapPacksController.php
  resources/assets/coffee/_classes/beatmap-pack.coffee
  resources/assets/less/bem-index.less
  resources/assets/less/bem/beatmap-pack.less
  resources/assets/less/bem/beatmap-packs-header.less
  resources/assets/less/bem/beatmap-packs.less
  resources/lang/en/beatmappacks.php
  resources/views/packs/_header.blade.php
  resources/views/packs/index.blade.php
  resources/views/packs/raw.blade.php
  resources/views/packs/show.blade.php
  routes/web.php
Labels: beatmap listing, resolves issue

#5143 Include preview in modding discussion notifications
  app/Jobs/BroadcastNotification.php
  resources/assets/lib/globals.d.ts
  resources/assets/lib/notification-maps/category.ts
  resources/assets/lib/notification-maps/icons.ts
  resources/assets/lib/notification-maps/message.ts
  resources/assets/lib/notification-widget/item-compact.tsx
  resources/assets/lib/notification-widget/item-singular.tsx
  resources/lang/en/notifications.php
Labels: modding discussions, notifications, resolves issue

#5165 Add interop endpoint to recalculate ranked_score
  app/Http/Controllers/LegacyInterOpController.php
  app/Models/UserStatistics/Model.php
  routes/web.php
Labels: admin

#5171 Refactor account playstyles setting
  resources/assets/coffee/_classes/account-edit-playstyle.coffee
  resources/assets/coffee/_classes/account-edit.coffee
  resources/assets/coffee/main.coffee
  resources/assets/less/bem/account-edit-entry.less
  resources/views/accounts/_edit_playstyle_checkbox.blade.php
  resources/views/accounts/_edit_playstyles.blade.php
Labels: code quality, settings

#5174 Send notification to NATs and BNs when a qualified beatmap is disqualified
  app/Http/Controllers/BeatmapDiscussionPostsController.php
  app/Jobs/BroadcastNotification.php
  tests/Controllers/BeatmapDiscussionPostsControllerTest.php
Labels: modding discussions

#5158 Show news cards on the logged out landing page
  app/Http/Controllers/HomeController.php
  app/Models/NewsPost.php
  public/images/landing/button-blog.png
  public/images/landing/button-blog@2x.png
  resources/assets/coffee/react/_components/show-more-link.coffee
  resources/assets/less/bem-index.less
  resources/assets/less/bem/landing-news.less
  resources/assets/less/bem/news-card.less
  resources/assets/less/bem/osu-page.less
  resources/assets/lib/landing-news.tsx
  resources/assets/lib/news-index/post-item.tsx
  resources/assets/lib/register-components.coffee
  resources/lang/en/home.php
  resources/views/home/landing.blade.php
Labels: dashboard, news, resolves issue

#5172 Notification option for new problem on qualified beatmapset
  app/Http/Controllers/AccountController.php
  app/Jobs/BroadcastNotification.php
  app/Models/User.php
  app/Models/UserNotificationOption.php
  app/helpers.php
  database/migrations/2019_10_23_100514_create_user_notification_options.php
  resources/assets/less/bem/account-edit-entry.less
  resources/lang/en/accounts.php
  resources/views/accounts/_edit_notifications.blade.php
  routes/web.php
  tests/Controllers/BeatmapDiscussionPostsControllerTest.php
Labels: modding discussions, notifications
