Repository ppy/osu-web, pull requests merged in 2019-04, with the labels that each got.

#4292 Improved accept language detection
  app/Http/Controllers/HomeController.php
  app/Http/Middleware/SetLocale.php
  app/Libraries/AcceptHttpLanguage/Parser.php
  app/helpers.php
  tests/Libraries/AcceptHttpLanguage/ParserTest.php
Labels: resolves issue

#4294 Add support for searching on Beatmapset title prefix
  app/Libraries/Search/BeatmapsetSearch.php
  config/schemas/beatmaps.json
Labels: beatmap listing, search

#4302 Allow restricted users to use the store
  app/Http/Controllers/Store/CartController.php
  app/Http/Controllers/Store/CheckoutController.php
  app/Http/Controllers/Store/Controller.php
  app/Http/Controllers/Store/NotificationRequestsController.php
  app/Http/Controllers/StoreController.php
  app/Libraries/ChangeUsername.php
  app/Models/Store/Order.php
  config/store.php
  resources/lang/en/model_validation.php
  tests/Libraries/ChangeUsernameTest.php
Labels: store

#4299 Remove gap between content and edge of screen on mobile layout
  resources/assets/less/bem/osu-page.less
  resources/views/forum/topics/_post.blade.php
  resources/views/forum/topics/show.blade.php
  resources/views/home/search.blade.php
  resources/views/home/user.blade.php
  resources/views/users/posts.blade.php
Labels: design, mobile

#4296 Add option to keep forum poll results hidden until the poll ends
  app/Http/Controllers/Forum/TopicsController.php
  app/Libraries/OsuAuthorize.php
  app/Models/Forum/Topic.php
  app/Models/Forum/TopicPoll.php
  database/migrations/2019_04_01_202237_add_poll_hide_results_to_topics.php
  resources/lang/en/forum.php
  resources/lang/en/model_validation.php
  resources/views/forum/topics/_create_poll.blade.php
  resources/views/forum/topics/_poll.blade.php
  resources/views/forum/topics/_poll_row.blade.php
Labels: forum

#4293 Add minimum plays for voting
  app/Libraries/OsuAuthorize.php
  app/Models/Model.php
  app/Models/User.php
  database/factories/StatsFactory.php
  resources/assets/coffee/react/profile-page/rank-chart.coffee
  resources/lang/en/authorization.php
  tests/Browser/SanityTest.php
  tests/Controllers/ForumTopicsControllerTest.php
Labels: resolves issue

#4320 Show seconds in time tooltip
  resources/assets/coffee/_classes/tooltip-default.coffee
Labels: resolves issue

#4340 Match forum topic popup notification with email
  app/Models/Forum/TopicWatch.php
Labels: resolves issue

#4339 Style notification popup scrollbar
  resources/assets/less/bem/osu-layout.less
  resources/assets/less/functions.less
  resources/assets/less/utilities.less
  resources/assets/lib/notification-widget/main.tsx
Labels: design, notifications

#4324 Improve visibility of download button in beatmapset panel
  resources/assets/coffee/react/_components/beatmapset-panel.coffee
Labels: design, proposal

#4319 Delete scores and ratings on disqualify
  app/Http/Controllers/BeatmapDiscussionPostsController.php
  app/Libraries/OsuAuthorize.php
  app/Models/Beatmapset.php
Labels: scoring

#4345 Run tslint on CI
  .travis.yml
  package.json
  resources/assets/lib/admin-menu.tsx
  resources/assets/lib/chat/chat-logo.tsx
  resources/assets/lib/chat/conversation-list.tsx
  resources/assets/lib/chat/conversation-view.tsx
  resources/assets/lib/chat/input-box.tsx
  resources/assets/lib/chat/main-view.tsx
  resources/assets/lib/coffee-modules.d.ts
  resources/assets/lib/gallery-contest-vote-button.tsx
  resources/assets/lib/header-v3.tsx
  resources/assets/lib/news-header.tsx
  resources/assets/lib/news-index/main.tsx
  resources/assets/lib/news-index/post-item.tsx
  resources/assets/lib/news-show/main.tsx
  resources/assets/lib/notification-widget/category-group.tsx
  resources/assets/lib/notification-widget/item.tsx
  resources/assets/lib/notification-widget/main.tsx
  resources/assets/lib/notification-widget/type-group.tsx
  resources/assets/lib/play-detail-menu.tsx
  resources/assets/lib/report-comment.tsx
  resources/assets/lib/user-card.tsx
  tslint.json
  yarn.lock
Labels: code quality

#3743 Add explanations to beatmap discussion buttons
  resources/assets/coffee/react/beatmap-discussions/discussion.coffee
  resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
  resources/lang/en/beatmaps.php
Labels: localisation, ux

#4353 Fix missing import in AccountStanding
  resources/assets/coffee/react/profile-page/account-standing.coffee
Labels: bug

#4356 Fix multiplayer match not loading when a user has no country set
  resources/assets/coffee/react/mp-history/score.coffee
Labels: resolves issue

#4301 Add storyboard icon to beatmap card
  resources/assets/coffee/react/_components/beatmapset-panel.coffee
  resources/assets/less/bem/beatmapset-panel.less
Labels: resolves issue

#4370 Simple polyfill for composedPath
  resources/assets/coffee/_classes/polyfills.coffee
Labels: browser issue

#4373 Reduce Sentry error logging noise
  resources/assets/coffee/_classes/user-card.coffee
  resources/assets/lib/notification-widget/worker.ts
  resources/assets/lib/stores/channel-store.ts
  resources/views/layout/metadata.blade.php
Labels: code quality

#4378 Fix audio player catch
  resources/assets/coffee/_classes/osu-audio.coffee
Labels: bug

#4381 Force query to run smaller subquery first when getting rankings
  app/Http/Controllers/RankingController.php
Labels: database, performance

#4380 More new user card tweaks
  resources/assets/less/bem/user-card.less
  resources/assets/lib/user-card.tsx
Labels: design
