Repository ppy/osu-web, pull requests merged in 2019-08, with the labels that each got.

#4749 New pagination style
  resources/assets/less/bem-index.less
  resources/assets/less/bem/pagination-v0.less
  resources/assets/less/bem/pagination-v2.less
  resources/assets/less/bem/paginator.less
  resources/assets/less/colors.less
  resources/views/beatmap_discussion_posts/index.blade.php
  resources/views/beatmap_discussions/index.blade.php
  resources/views/beatmapset_discussion_votes/index.blade.php
  resources/views/beatmapset_events/index.blade.php
  resources/views/beatmapset_watches/index.blade.php
  resources/views/comments/index.blade.php
  resources/views/forum/forums/show.blade.php
  resources/views/forum/topic_watches/index.blade.php
  resources/views/home/_search_results.blade.php
  resources/views/objects/_pagination.blade.php
  resources/views/objects/_pagination_page.blade.php
  resources/views/objects/_pagination_v0.blade.php
  resources/views/objects/_pagination_v2.blade.php
  resources/views/packs/index.blade.php
  resources/views/rankings/index.blade.php
  resources/views/store/orders/index.blade.php
  resources/views/users/posts.blade.php
Labels: design, forum

#4763 Fix changelog redirect handling
  app/Http/Controllers/ChangelogController.php
  resources/views/vendor/apidoc/partials/info.blade.php
  routes/web.php
Labels: changelog

#4764 Fixed multiple of "Check list of open issues"
  README.md
Labels: documentation

#4773 Fix mode tab using incorrect colours when disabled
  resources/assets/less/bem/page-mode-link.less
Labels: design, user profile

#4758 Remove function calls from translations
  resources/assets/coffee/react/profile-page/cover-uploader.coffee
  resources/assets/coffee/react/profile-page/kudosu.coffee
  resources/assets/coffee/react/profile-page/user-page.coffee
  resources/assets/lib/oauth/authorized-client.tsx
  resources/assets/lib/string-with-component.tsx
  resources/lang/be/users.php
  resources/lang/bg/users.php
  resources/lang/cs/users.php
  resources/lang/da/users.php
  resources/lang/de/users.php
  resources/lang/el/users.php
  resources/lang/en/users.php
  resources/lang/es/users.php
  resources/lang/fi/users.php
  resources/lang/fr/users.php
  resources/lang/hu/users.php
  resources/lang/id/users.php
  resources/lang/it/users.php
  resources/lang/ja/users.php
  resources/lang/ko/users.php
  resources/lang/nl/users.php
  resources/lang/no/users.php
  resources/lang/pl/users.php
  resources/lang/pt-br/users.php
  resources/lang/pt/users.php
  resources/lang/ro/users.php
  resources/lang/ru/users.php
  resources/lang/sk/users.php
  resources/lang/sv/users.php
  resources/lang/th/users.php
  resources/lang/tr/users.php
  resources/lang/vi/users.php
  resources/lang/zh-tw/users.php
  resources/lang/zh/users.php
Labels: code quality, localisation

#4762 Add instructions for building docs to SETUP
  SETUP.md
Labels: documentation

#4776 Fix watches table overflowing
  resources/assets/less/bem/beatmapset-watches.less
  resources/views/beatmapset_watches/index.blade.php
Labels: design, resolves issue, size/L

#4782 Add rules for avatars
  resources/assets/less/bem/account-edit-entry.less
  resources/lang/en/accounts.php
  resources/views/accounts/edit.blade.php
Labels: size/S

#4788 Fix wrong user card tooltip on keyed components
  resources/assets/lib/user-card-tooltip.tsx
Labels: bug, size/S

#4772 Remove _source query from high score aggregation
  app/Models/UserScoreable.php
Labels: blocked, search

#4789 Remove unused style files
  resources/assets/less/bem/beatmapset-details.less
  resources/assets/less/bem/beatmapset-scoreboard-first.less
  resources/assets/less/bem/store-orders.less
  resources/assets/less/bem/store-product.less
Labels: size/L

#4803 Include user's high scores for reindexing via LIO
  app/Http/Controllers/LegacyInterOpController.php
  app/Models/Score/Best/Model.php
Labels: size/XS

#4804 Temporary fix for authorization of deleted beatmapset
  app/Libraries/OsuAuthorize.php
Labels: size/XS

#4787 Link avatar in chat message to user page
  resources/assets/lib/chat/message-group.tsx
Labels: chat, size/XS

#4751 Add a link to the user profile in chats
  resources/assets/lib/chat/conversation-view.tsx
  resources/assets/lib/globals.d.ts
Labels: chat, resolves issue, size/XS

#4805 Fix component not unmounted when removing user card tooltip
  resources/assets/lib/user-card-tooltip.tsx
Labels: size/XS

#4771 Incomplete beatmapset submissions should not show
  app/Models/Beatmapset.php
  database/factories/BeatmapsetFactory.php
  tests/Controllers/BeatmapDiscussionPostsControllerTest.php
  tests/Controllers/BeatmapsetControllerTest.php
  tests/Models/BeatmapsetTest.php
Labels: database

#4812 Remove country filtering for score rankings
  app/Http/Controllers/RankingController.php
  resources/views/rankings/index.blade.php
Labels: size/XS

#4814 Modding profile fixes and optimisations
  app/Http/Controllers/Users/ModdingHistoryController.php
  app/Libraries/OsuAuthorize.php
  app/Models/Beatmap.php
  app/Models/BeatmapDiscussion.php
  app/Models/BeatmapDiscussionPost.php
  database/migrations/2019_08_21_104727_add_index_to_beatmapset_events.php
Labels: size/L

#4819 Hide bpm on Beatmaps that have silly BPM values
  resources/assets/coffee/react/_components/beatmap-basic-stats.coffee
Labels: size/XS

#4811 Store toggle status of the user profile rank graph
  app/Http/Controllers/AccountController.php
  app/Models/User.php
  app/Models/UserProfileCustomization.php
  app/Transformers/UserTransformer.php
  resources/assets/coffee/react/profile-page/detail-bar.coffee
  resources/assets/coffee/react/profile-page/detail.coffee
Labels: size/S

#4825 Fix mark forum as read error
  app/Http/Controllers/Forum/ForumsController.php
Labels: size/XS

#4826 Fix some errors not being shown when editing account settings
  resources/views/accounts/_edit_entry_simple.blade.php
Labels: size/XS

#4827 Remove shocking forum header
  resources/assets/less/bem/header-v4.less
Labels: size/XS

#4823 Make sign in text on beatmap packs page white
  resources/assets/less/bem/beatmap-pack.less
Labels: resolves issue, size/XS

#4833 Fix pointer events for anchor target
  resources/assets/coffee/react/_components/comments.coffee
  resources/assets/less/bem/fragment-target.less
  resources/assets/less/utilities.less
  resources/views/forum/forums/index.blade.php
Labels: size/S

#4834 Add some more changelog label mapping exceptions
  app/Models/ChangelogEntry.php
Labels: size/XS, tooling

#4790 Add sockets extensions to php docker image
  docker/php/Dockerfile
Labels: docker, size/XS

#4851 Fix urlPresence to return null on blank/null string
  resources/assets/coffee/osu_common.coffee
Labels: size/XS

#4850 Fix invalid html in translation
  resources/lang/en/events.php
Labels: size/XS

#4853 Fix alignment of topic icon
  resources/assets/less/bem/forum-topic-entry.less
Labels: size/XS

#4855 Revert "force index to make mysql do the smaller query first"
  app/Http/Controllers/RankingController.php
Labels: database, performance, size/S

#4857 Create helper for generating class with modifiers
  app/Libraries/BBCodeFromDB.php
  app/Libraries/Markdown/OsuMarkdown.php
  app/helpers.php
  resources/views/forum/_header.blade.php
  resources/views/layout/_popup_login.blade.php
  resources/views/layout/footer.blade.php
  resources/views/objects/_pagination_v2.blade.php
  resources/views/objects/_show_more_link.blade.php
Labels: size/M

#4858 Allow adding modifiers to spinner
  app/helpers.php
Labels: size/M

#4861 Add more perks
  app/Http/Controllers/HomeController.php
  public/images/layout/supporter/country_ranking.jpg
  public/images/layout/supporter/country_ranking@2x.jpg
  public/images/layout/supporter/friend_ranking.jpg
  public/images/layout/supporter/friend_ranking@2x.jpg
  public/images/layout/supporter/mod_filtering.jpg
  public/images/layout/supporter/mod_filtering@2x.jpg
  resources/assets/less/bem/supporter-perk-list-group.less
  resources/assets/less/bem/supporter-perk-list-hero.less
  resources/assets/less/bem/supporter-perk-list.less
  resources/lang/en/community.php
  resources/views/home/_supporter_perk_image_group.blade.php
Labels: design

#4856 Add pdo_sqlite extension to php container
  docker/php/Dockerfile
Labels: docker, size/XS

#4866 Faster revoking of refresh tokens when revoking client permissions
  app/Models/OAuth/Client.php
Labels: resolves issue, size/XS

#4864 Use "Inter" for content font
  package.json
  resources/assets/less/app.less
  resources/assets/less/variables.less
  resources/views/layout/metadata.blade.php
  yarn.lock
Labels: size/S

#4860 Fix cover uploader bolded text not being bold
  resources/assets/coffee/react/profile-page/cover-uploader.coffee
Labels: bug, size/XS, user profile
