Repository ppy/osu-web, pull requests merged in 2019-01, with the labels that each got.

#4010 Move typescript files into lib
  resources/assets/lib/actions/chat-actions.ts
  resources/assets/lib/actions/dispatcher-action.ts
  resources/assets/lib/actions/user-login-actions.ts
  resources/assets/lib/actions/window-focus-actions.ts
  resources/assets/lib/chat.ts
  resources/assets/lib/chat/chat-api-responses.ts
  resources/assets/lib/chat/chat-api.ts
  resources/assets/lib/chat/chat-logo.tsx
  resources/assets/lib/chat/chat-orchestrator.ts
  resources/assets/lib/chat/chat-state-store.ts
  resources/assets/lib/chat/chat-worker.ts
  resources/assets/lib/chat/conversation-list-item.tsx
  resources/assets/lib/chat/conversation-list.tsx
  resources/assets/lib/chat/conversation-view.tsx
  resources/assets/lib/chat/input-box.tsx
  resources/assets/lib/chat/main-view.tsx
  resources/assets/lib/chat/message-divider.tsx
  resources/assets/lib/chat/message-group.tsx
  resources/assets/lib/dispatch-listener.ts
  resources/assets/lib/dispatcher.ts
  resources/assets/lib/gallery-contest-vote-button.tsx
  resources/assets/lib/gallery-contest.ts
  resources/assets/lib/globals.d.ts
  resources/assets/lib/header-v3.tsx
  resources/assets/lib/models/chat/channel.ts
  resources/assets/lib/models/chat/message.ts
  resources/assets/lib/models/user.ts
  resources/assets/lib/osu-core.ts
  resources/assets/lib/stores/channel-store.ts
  resources/assets/lib/stores/root-data-store.ts
  resources/assets/lib/stores/ui-state-store.ts
  resources/assets/lib/stores/user-store.ts
  resources/assets/lib/user-login-observer.ts
  resources/assets/lib/window-focus-observer.ts
  resources/assets/lib/window-vh-patcher.ts
  tsconfig.json
  webpack.mix.js
Labels: code quality

#4069 Allow burger menu to be scrolled on mobile
  resources/assets/coffee/main.coffee
  resources/assets/less/bem/navbar-mobile.less
  resources/assets/lib/import-shims.coffee
  resources/assets/lib/osu-core.ts
  resources/assets/lib/window-vh-patcher.ts
Labels: resolves issue

#4076 Move contest react source files
  resources/assets/coffee/react/contest-entry/uploader.coffee
  resources/assets/coffee/react/contest-entry/user-entry-list.coffee
  resources/assets/coffee/react/contest-entry/user-entry.coffee
  resources/assets/coffee/react/contest-voting/_base-entry-list.coffee
  resources/assets/coffee/react/contest-voting/art-entry-list.coffee
  resources/assets/coffee/react/contest-voting/art-entry.coffee
  resources/assets/coffee/react/contest-voting/entry-list.coffee
  resources/assets/coffee/react/contest-voting/entry.coffee
  resources/assets/coffee/react/contest-voting/vote-summary.coffee
  resources/assets/coffee/react/contest-voting/voter.coffee
  webpack.mix.js
Labels: code quality

#3993 Enable feature vote
  .env.example
  app/Http/Controllers/Forum/ForumsController.php
  app/Http/Controllers/Forum/TopicsController.php
  app/Models/Forum/FeatureVote.php
  app/Models/Forum/Forum.php
  app/Models/Forum/Topic.php
  config/osu.php
  resources/assets/coffee/react/_components/comments-sort.coffee
  resources/assets/coffee/react/beatmap-discussions/discussions.coffee
  resources/assets/coffee/react/beatmaps/main.coffee
  resources/assets/coffee/react/beatmaps/search-sort.coffee
  resources/assets/less/bem-index.less
  resources/assets/less/bem/beatmap-discussions.less
  resources/assets/less/bem/beatmapsets-show-more.less
  resources/assets/less/bem/beatmapsets.less
  resources/assets/less/bem/btn-osu-big.less
  resources/assets/less/bem/forum-topic-feature-vote.less
  resources/assets/less/bem/osu-page.less
  resources/assets/less/bem/simple-menu.less
  resources/assets/less/bem/sort.less
  resources/assets/less/forum/colours.less
  resources/lang/en/beatmaps.php
  resources/lang/en/comments.php
  resources/lang/en/forum.php
  resources/lang/en/sort.php
  resources/views/forum/forums/_topic.blade.php
  resources/views/forum/forums/_topics_sort.blade.php
  resources/views/forum/forums/show.blade.php
  resources/views/forum/topics/_feature_vote.blade.php
  resources/views/forum/topics/show.blade.php
Labels: resolves issue

#4085 Return null instead of object with null fields if country is null.
  app/Transformers/CountryStatisticsTransformer.php
  app/Transformers/UserCompactTransformer.php
  app/Transformers/UserTransformer.php
  resources/assets/coffee/react/_components/flag-country.coffee
Labels: resolves issue

#4083 Trim auto submitted text fields when editing profile
  resources/assets/coffee/_classes/account-edit.coffee
Labels: resolves issue

#4088 Add button prompting for login on beatmap page
  resources/assets/coffee/react/beatmapset-page/header.coffee
  resources/lang/en/beatmapsets.php
Labels: resolves issue

#4086 Allow beatmap pack list item to be toggled close
  resources/assets/coffee/_classes/beatmap-pack.coffee
  resources/assets/less/bem/beatmap-pack.less
Labels: resolves issue

#3758 Add more tooltips to beatmapset panels
  resources/assets/coffee/react/_components/beatmapset-panel.coffee
  resources/lang/en/beatmaps.php
Labels: resolves issue

#4100 Remove calls to non-existent properties
  app/Models/Store/Product.php
  app/Transformers/BeatmapDiscussionTransformer.php
Labels: code quality

#4119 Fix wording on osu!supporter gift email
  resources/lang/en/fulfillments.php
  resources/views/emails/store/supporter_gift-en.blade.php
Labels: localisation

#4122 Remove supporter requirement for using api download endpoint
  app/Http/Controllers/BeatmapsetsController.php
Labels: api

#4079 Remove ability to purchase tournament banners from store after tournament ends
  app/Console/Commands/StoreExpireProducts.php
  app/Console/Kernel.php
  app/Http/Controllers/Store/ProductsController.php
  app/Http/Controllers/StoreController.php
  app/Libraries/OrderCheckout.php
  app/Models/Store/Product.php
  app/Models/Tournament.php
  database/migrations/2019_01_17_051612_add_available_until_to_products.php
  routes/web.php
  tests/Libraries/OrderCheckoutTest.php
Labels: resolves issue

#4128 Fix username lookups with ints instead of strings
  app/Models/User.php
Labels: high priority, performance, user profile
