Repository ppy/osu-web, pull requests merged in 2020-04, with the labels that each got.

#5861 Add user to index user after new user registration
  app/Libraries/UserRegistration.php
Labels: area:search

#5863 Revert transformer ordering of rankHistory temporarily to allow lazer to coexist
  app/Transformers/UserCompactTransformer.php
Labels: type:api

#5862 Add _lio endpoint for indexing beatmapsets
  app/Http/Controllers/LegacyInterOpController.php
  routes/web.php
Labels: type:api

#5853 Add title to multiplayer match page
  app/Http/Controllers/MatchesController.php
  resources/assets/coffee/react/mp-history/content.coffee
  resources/assets/coffee/react/mp-history/main.coffee
  resources/assets/less/bem/osu-layout.less
  resources/assets/less/bem/osu-page.less
  resources/views/multiplayer/match.blade.php
Labels: area:multiplayer

#5844 Fix beatmap selector hiding incorrect overlay
  resources/assets/coffee/react/beatmap-discussions/beatmap-list.coffee
Labels: area:beatmap-discussions

#5854 Prevent language/genre Any from being set
  app/Models/Beatmapset.php
  resources/assets/lib/beatmapsets-show/metadata-editor.tsx
  resources/lang/en/model_validation.php
Labels: area:beatmap-info

#5880 Generate https urls in api authentication docs
  app/Providers/AppServiceProvider.php
Labels: type:documentation

#5857 Rearrange and clean up beatmap nomination box
  resources/assets/coffee/react/beatmap-discussions/nominations.coffee
  resources/assets/less/bem/beatmap-discussion-nomination.less
Labels: area:beatmap-discussions

#5878 Fix beatmap listing repeating songs
  resources/assets/lib/beatmaps/beatmapset-search-controller.ts
  resources/assets/lib/beatmaps/beatmapset-search.ts
  resources/assets/lib/beatmaps/result-set.ts
  resources/assets/lib/beatmaps/search-results.ts
Labels: area:beatmap-listing

#5877 Add ability to reset OAuth client secret
  app/Http/Controllers/OAuth/ClientsController.php
  app/Http/Middleware/RequireScopes.php
  app/Models/OAuth/Client.php
  resources/assets/less/bem/oauth-client-details.less
  resources/assets/lib/models/oauth/own-client.ts
  resources/assets/lib/oauth/client-details.tsx
  resources/lang/en/oauth.php
  routes/web.php
  tests/Models/OAuth/ClientTest.php
  tests/TestCase.php
Labels: area:settings

#5875 Update time display
  resources/assets/coffee/main.coffee
  resources/views/layout/metadata.blade.php
  webpack.mix.js
Labels: type:ux

#5843 Add beatmap default download option
  app/Http/Controllers/AccountController.php
  app/Models/UserProfileCustomization.php
  app/Transformers/UserCompactTransformer.php
  resources/assets/coffee/_classes/account-edit.coffee
  resources/assets/coffee/react/_components/beatmapset-panel.coffee
  resources/assets/lib/osu-url-helper.ts
  resources/lang/en/accounts.php
  resources/lang/en/beatmapsets.php
  resources/views/accounts/_edit_options.blade.php
  resources/views/accounts/edit.blade.php
Labels: area:settings

#5896 CSS import cleanup
  resources/assets/less/app.less
Labels: type:code-quality

#5897 Include beatmap favourite count in search scoring
  app/Libraries/Elasticsearch/FunctionScore.php
  app/Libraries/Search/BeatmapsetSearch.php
Labels: area:search

#5901 Style loved modding event correctly
  resources/assets/coffee/react/beatmap-discussions/event.coffee
  resources/assets/less/bem/beatmapset-event.less
  resources/lang/en/beatmapset_events.php
Labels: area:beatmap-discussions

#5895 Link medal notification to game mode
  app/Jobs/BroadcastNotification.php
  resources/assets/lib/notification-maps/url.ts
Labels: area:notifications

#5920 Remove unused variable
  resources/assets/coffee/react/beatmap-discussions/nominations.coffee
Labels: type:code-quality

#5929 Hide "show more" button on empty chat channel
  resources/assets/lib/models/chat/channel.ts
Labels: area:chat

#5830 Refactor BeatmapsetTransformer
  app/Libraries/OsuAuthorize.php
  app/Transformers/BeatmapCompactTransformer.php
  app/Transformers/BeatmapTransformer.php
  app/Transformers/BeatmapsetCompactTransformer.php
  app/Transformers/BeatmapsetTransformer.php
  resources/assets/coffee/react/modding-profile/main.coffee
  resources/assets/lib/beatmap-discussions/beatmaps-context.ts
  resources/assets/lib/beatmap-icon.tsx
  resources/assets/lib/beatmaps/beatmapset-search.ts
  resources/assets/lib/beatmapsets-show/metadata-editor.tsx
  resources/assets/lib/beatmapsets/beatmapset-json.ts
  resources/assets/lib/globals.d.ts
  resources/assets/lib/interfaces/beatmap-json-extended.ts
  resources/assets/lib/interfaces/beatmap-json.ts
  resources/assets/lib/quick-search/beatmapset.tsx
  resources/assets/lib/quick-search/worker.ts
  resources/assets/lib/stores/beatmapset-store.ts
  tests/Transformers/BeatmapsetCompactTransformerTest.php
  tests/Transformers/BeatmapsetTransformerTest.php
Labels: type:api

#5919 Beatmap page style adjustments
  resources/assets/coffee/react/beatmapset-page/hype.coffee
  resources/assets/less/bem/beatmapset-hype.less
  resources/lang/en/beatmapsets.php
Labels: area:beatmap-info

#5935 Add osu!lazer mania 10K mod
  app/Libraries/Multiplayer/Mod.php
Labels: area:multiplayer

#5910 Add cutoff for showing relative time in beatmap info
  app/helpers.php
  resources/assets/coffee/_classes/timeago.coffee
  resources/assets/coffee/_classes/tooltip-default.coffee
  resources/assets/coffee/osu_common.coffee
  resources/assets/coffee/react/_components/beatmapset-mapping.coffee
  resources/assets/less/bem/beatmapset-mapping.less
  resources/assets/lib/time-with-tooltip.tsx
Labels: type:ux

#5934 Simplify difficulty color styling
  resources/assets/coffee/_classes/tooltip-beatmap.coffee
  resources/assets/coffee/osu_common.coffee
  resources/assets/less/bem/beatmap-icon.less
  resources/assets/less/bem/tooltip-beatmap.less
  resources/assets/less/layout.less
  resources/assets/less/variables.less
  resources/assets/lib/beatmap-icon.tsx
  resources/assets/lib/globals.d.ts
Labels: type:code-quality

#5937 Fix react key on wrong element
  resources/assets/coffee/react/_components/beatmapset-mapping.coffee
Labels: type:code-quality

#5922 Update beatmap link in profile page to include the mode
  app/Http/Controllers/BeatmapsController.php
  resources/assets/coffee/react/profile-page/beatmap-playcount.coffee
  resources/assets/coffee/react/profile-page/historical.coffee
  resources/assets/lib/play-detail.coffee
Labels: area:user-profile

#5936 Switch to multiple user channel notification
  app/Events/NewNotificationEvent.php
  app/Events/NewPrivateNotificationEvent.php
  app/Events/UserSubscriptionChangeEvent.php
  app/Http/Controllers/BeatmapsetWatchesController.php
  app/Http/Controllers/FollowsController.php
  app/Jobs/BroadcastNotification.php
  app/Libraries/RedisBroadcaster.php
  app/Models/Chat/Channel.php
  app/Models/Forum/TopicWatch.php
  app/Providers/BroadcastServiceProvider.php
  tests/Controllers/BeatmapDiscussionPostsControllerTest.php
Labels: area:notifications
