Repository ppy/osu-web, pull requests merged in 2020-05, with the labels that each got.

#5980 Remove temporarily restored events
  app/Events/NewNotificationEvent.php
  app/Events/UserSubscriptionChangeEvent.php
Labels: type:code-quality

#5997 Clean up PopupMenuPersistent
  resources/assets/lib/popup-menu-persistent.tsx
Labels: type:code-quality

#5992 Fix lack of spaces in nomination bar x/y display
  resources/assets/coffee/react/beatmap-discussions/nominations.coffee
Labels: area:beatmap-discussions, type:design

#5963 Refactor beatmap modding event component
  app/Http/Controllers/BeatmapsetEventsController.php
  app/Http/Controllers/Users/ModdingHistoryController.php
  app/Http/Controllers/UsersController.php
  app/Libraries/ModdingHistoryEventsBundle.php
  app/Libraries/Transformers/Scope.php
  resources/assets/coffee/react/beatmap-discussions-history/main.coffee
  resources/assets/coffee/react/beatmap-discussions/event.coffee
  resources/assets/coffee/react/beatmap-discussions/events.coffee
  resources/assets/coffee/react/beatmap-discussions/main.coffee
  resources/assets/coffee/react/modding-profile/discussions.coffee
  resources/assets/coffee/react/modding-profile/events.coffee
  resources/assets/coffee/react/modding-profile/main.coffee
  resources/assets/coffee/react/modding-profile/posts.coffee
  resources/assets/less/bem-index.less
  resources/assets/less/bem/beatmapset-activities.less
  resources/assets/less/bem/beatmapset-cover.less
  resources/assets/less/bem/beatmapset-event.less
  resources/assets/lib/beatmap-discussions/event.tsx
  resources/assets/lib/beatmap-discussions/events.tsx
  resources/assets/lib/beatmapset-events.ts
  resources/assets/lib/globals.d.ts
  resources/assets/lib/interfaces/beatmapset-event-json.ts
  resources/assets/lib/register-components.coffee
  resources/assets/lib/time-with-tooltip.tsx
  resources/views/beatmap_discussion_posts/_item.blade.php
  resources/views/beatmap_discussions/_item.blade.php
  resources/views/beatmapset_events/_item.blade.php
  resources/views/beatmapset_events/index.blade.php
Labels: area:beatmap-discussions

#5900 Log beatmap genre and language changes
  app/Http/Controllers/BeatmapsetsController.php
  app/Models/BeatmapsetEvent.php
  database/migrations/2020_04_12_101236_add_genre_and_language_edit_to_beatmapset_events.php
  resources/assets/less/bem/beatmapset-event.less
  resources/lang/en/beatmapset_events.php
Labels: area:beatmap-info

#5958 Record volume settings
  app/Http/Controllers/AccountController.php
  app/Models/UserProfileCustomization.php
  app/Transformers/UserCompactTransformer.php
  resources/assets/lib/osu-audio/main.ts
  resources/assets/lib/osu-audio/settings.ts
Labels: type:ux

#5982 Show chat muted notice on existing channels
  app/Models/Chat/UserChannel.php
  resources/assets/less/bem/chat-conversation.less
  resources/assets/less/bem/chat-message-group.less
  resources/assets/lib/chat/chat-api-responses.ts
  resources/assets/lib/models/chat/channel.ts
  resources/docs/source/includes/_structures.md
Labels: area:chat, type:ux

#6010 Fix slow beatmap events listing
  app/Libraries/ModdingHistoryEventsBundle.php
  app/Models/BeatmapsetEvent.php
  resources/assets/coffee/react/modding-profile/events.coffee
  resources/assets/lib/beatmap-discussions/event.tsx
  resources/assets/lib/beatmap-discussions/events.tsx
Labels: type:performance

#5981 Add more endpoints to public api
  app/Console/Commands/RouteConvert.php
  app/Console/Kernel.php
  app/Http/Controllers/API/BeatmapsController.php
  app/Http/Controllers/API/BeatmapsetsController.php
  app/Http/Controllers/BeatmapsController.php
  app/Http/Controllers/BeatmapsetsController.php
  app/Http/Controllers/FriendsController.php
  app/Http/Controllers/NewsController.php
  app/Http/Controllers/RankingController.php
  app/Http/Controllers/SpotlightsController.php
  app/Http/Controllers/UsersController.php
  app/Http/Middleware/AuthApi.php
  app/Http/Middleware/RequireScopes.php
  app/Libraries/RouteScopesHelper.php
  app/Providers/AuthServiceProvider.php
  app/Transformers/EventTransformer.php
  database/factories/BuildFactory.php
  database/factories/ChangelogFactory.php
  database/factories/CommentFactory.php
  resources/assets/coffee/react/profile-page/recent-activity.coffee
  resources/lang/en/api.php
  resources/views/vendor/apidoc/partials/info.blade.php
  routes/web.php
  tests/RequireScopesTest.php
  tests/RouteScopesTest.php
  tests/api_routes.json
Labels: type:api

#5941 Add score detail page
  app/Http/Controllers/ScoresController.php
  app/Libraries/RouteSection.php
  app/Models/Beatmap.php
  app/Transformers/BeatmapsetCompactTransformer.php
  app/Transformers/ScoreTransformer.php
  package.json
  public/fonts/venera/Venera-500.otf
  resources/assets/coffee/react/_components/mod.coffee
  resources/assets/coffee/react/_components/mods.coffee
  resources/assets/coffee/react/beatmapset-page/scoreboard-mod.coffee
  resources/assets/coffee/react/beatmapset-page/scoreboard.coffee
  resources/assets/less/app.less
  resources/assets/less/bem-index.less
  resources/assets/less/bem/mod.less
  resources/assets/less/bem/score-beatmap.less
  resources/assets/less/bem/score-dial.less
  resources/assets/less/bem/score-info.less
  resources/assets/less/bem/score-player.less
  resources/assets/less/bem/score-stats.less
  resources/assets/less/bem/score-tower.less
  resources/assets/less/colors.less
  resources/assets/less/variables.less
  resources/assets/less/venera.less
  resources/assets/lib/beatmap-icon.tsx
  resources/assets/lib/interfaces/game-mode.ts
  resources/assets/lib/interfaces/rank.ts
  resources/assets/lib/interfaces/score-json.ts
  resources/assets/lib/mod.tsx
  resources/assets/lib/play-detail-menu.tsx
  resources/assets/lib/score-helper.ts
  resources/assets/lib/scores-show.ts
  resources/assets/lib/scores-show/beatmap-info.tsx
  resources/assets/lib/scores-show/dial.tsx
  resources/assets/lib/scores-show/info.tsx
  resources/assets/lib/scores-show/main.tsx
  resources/assets/lib/scores-show/player.tsx
  resources/assets/lib/scores-show/stats.tsx
  resources/assets/lib/scores-show/tower.tsx
  resources/assets/lib/user-link.tsx
  resources/assets/lib/utils/score.ts
  resources/lang/en/page_title.php
  resources/lang/en/scores.php
  resources/lang/en/users.php
  resources/views/scores/show.blade.php
  routes/web.php
  tests/Controllers/ScoresControllerTest.php
  webpack.mix.js
  yarn.lock
Labels: type:design

#6037 Ignore new_case IPN messages
  app/Libraries/Payments/NotificationType.php
  app/Libraries/Payments/PaymentProcessor.php
  app/Libraries/Payments/PaypalPaymentProcessor.php
Labels: area:store

#6008 Collapse long comments
  resources/assets/coffee/react/_components/comment.coffee
  resources/assets/less/bem-index.less
  resources/assets/less/bem/comment.less
  resources/assets/less/bem/comments.less
  resources/assets/less/bem/estimate-min-lines.less
  resources/assets/less/bem/osu-page.less
  resources/assets/lib/utils/estimate-min-lines.ts
  resources/lang/en/common.php
  resources/views/master.blade.php
Labels: area:comments, type:ux

#5907 Add options for notification delivery
  app/Http/Controllers/AccountController.php
  app/Http/Controllers/BeatmapDiscussionPostsController.php
  app/Jobs/BroadcastNotification.php
  app/Models/UserNotificationOption.php
  database/factories/BeatmapsetFactory.php
  resources/assets/coffee/_classes/account-edit.coffee
  resources/assets/less/bem/account-edit-entry.less
  resources/assets/less/bem/osu-switch-v2.less
  resources/lang/en/accounts.php
  resources/views/accounts/_edit_notifications.blade.php
  resources/views/objects/_switch.blade.php
  tests/BeatmapsetDisqualifyTest.php
  tests/BroadcastNotificationTest.php
  tests/Controllers/BeatmapDiscussionPostsControllerTest.php
  tests/TestCase.php
Labels: area:settings
