Repository ppy/osu-web, pull requests merged in 2020-02, with the labels that each got.

#5572 Add arabic localisation
  .styleci.yml
  app/Libraries/LocaleMeta.php
  config/app.php
  crowdin.yml
  resources/lang/ar/accounts.php
  resources/lang/ar/admin.php
  resources/lang/ar/api.php
  resources/lang/ar/artist.php
  resources/lang/ar/authorization.php
  resources/lang/ar/bbcode.php
  resources/lang/ar/beatmap_discussion_posts.php
  resources/lang/ar/beatmap_discussions.php
  resources/lang/ar/beatmappacks.php
  resources/lang/ar/beatmaps.php
  resources/lang/ar/beatmapset_discussion_votes.php
  resources/lang/ar/beatmapset_events.php
  resources/lang/ar/beatmapset_watches.php
  resources/lang/ar/beatmapsets.php
  resources/lang/ar/changelog.php
  resources/lang/ar/chat.php
  resources/lang/ar/client_verifications.php
  resources/lang/ar/comments.php
  resources/lang/ar/common.php
  resources/lang/ar/community.php
  resources/lang/ar/contest.php
  resources/lang/ar/errors.php
  resources/lang/ar/events.php
  resources/lang/ar/forum.php
  resources/lang/ar/friends.php
  resources/lang/ar/help.php
  resources/lang/ar/home.php
  resources/lang/ar/layout.php
  resources/lang/ar/livestreams.php
  resources/lang/ar/mail.php
  resources/lang/ar/model_validation.php
  resources/lang/ar/model_validation/fulfillments.php
  resources/lang/ar/model_validation/payments.php
  resources/lang/ar/model_validation/store/product.php
  resources/lang/ar/multiplayer.php
  resources/lang/ar/news.php
  resources/lang/ar/notifications.php
  resources/lang/ar/oauth.php
  resources/lang/ar/password_reset.php
  resources/lang/ar/paypal/errors.php
  resources/lang/ar/quick_search.php
  resources/lang/ar/rankings.php
  resources/lang/ar/report.php
  resources/lang/ar/sessions.php
  resources/lang/ar/sort.php
  resources/lang/ar/status_page.php
  resources/lang/ar/store.php
  resources/lang/ar/supporter_tag.php
  resources/lang/ar/tournament.php
  resources/lang/ar/user_verification.php
  resources/lang/ar/users.php
  resources/lang/ar/validation.php
  resources/lang/ar/wiki.php
Labels: localisation

#5583 Use readonly connection when fetching beatmap score ranking
  app/Http/Controllers/BeatmapsController.php
Labels: performance

#5582 Fix missing game mode when linking from modding profile
  resources/assets/coffee/react/modding-profile/header.coffee
Labels: resolves issue

#5589 Fix wiki redirecting to empty page
  app/Models/Wiki/Page.php
Labels: wiki

#5535 Add autocomplete to wiki main page search bar
  app/Http/Controllers/WikiController.php
  app/Libraries/Search/WikiSuggestions.php
  app/Libraries/Search/WikiSuggestionsParams.php
  app/Libraries/Search/WikiSuggestionsRequestParams.php
  config/schemas/wiki_page.json
  resources/assets/less/bem/wiki-search.less
  resources/assets/less/variables.less
  resources/assets/lib/wiki-search-controller.ts
  resources/assets/lib/wiki-search.tsx
  routes/web.php
Labels: wiki

#5588 Fix markdown renderer for indexing output
  app/Libraries/Markdown/Indexing/RendererExtension.php
  app/Libraries/Markdown/Indexing/TableRenderer.php
  app/Libraries/Markdown/OsuTableRenderer.php
  tests/Libraries/Markdown/markdown_examples/table.md
  tests/Libraries/Markdown/markdown_examples/table.txt
Labels: search

#5591 Merge errors from discussion to post if discussion validation fails
  app/Models/BeatmapDiscussionPost.php
Labels: beatmap discussions

#5602 Remove blade string renderer helper
  app/Http/Controllers/SessionsController.php
  app/Libraries/UserVerification.php
  app/helpers.php
  resources/views/forum/topics/replace_button.blade.php
  resources/views/forum/topics/replace_delete_button.blade.php
  resources/views/forum/topics/replace_watch_button.blade.php
  resources/views/users/show.blade.php
Labels: code quality

#5615 Fix travis settings
  .travis.yml
Labels: tooling

#5605 Fix UserSeeder
  database/seeds/ModelSeeders/UserSeeder.php
Labels: testing

#5562 Endpoint for creating beatmap discussion 'reviews'
  .env.example
  app/Http/Controllers/BeatmapDiscussionsController.php
  app/Libraries/BeatmapsetDiscussionReview.php
  app/Libraries/OsuAuthorize.php
  config/osu.php
  resources/lang/en/beatmap_discussions.php
  routes/web.php
  tests/Controllers/BeatmapDiscussionsControllerTest.php
  tests/Libraries/BeatmapsetDiscussionReviewTest.php
Labels: api, beatmap discussions

#5599 Add Ukraine localisation
  .styleci.yml
  app/Libraries/LocaleMeta.php
  config/app.php
  crowdin.yml
  resources/lang/uk/accounts.php
  resources/lang/uk/admin.php
  resources/lang/uk/api.php
  resources/lang/uk/artist.php
  resources/lang/uk/authorization.php
  resources/lang/uk/bbcode.php
  resources/lang/uk/beatmap_discussion_posts.php
  resources/lang/uk/beatmap_discussions.php
  resources/lang/uk/beatmappacks.php
  resources/lang/uk/beatmaps.php
  resources/lang/uk/beatmapset_discussion_votes.php
  resources/lang/uk/beatmapset_events.php
  resources/lang/uk/beatmapset_watches.php
  resources/lang/uk/beatmapsets.php
  resources/lang/uk/changelog.php
  resources/lang/uk/chat.php
  resources/lang/uk/client_verifications.php
  resources/lang/uk/comments.php
  resources/lang/uk/common.php
  resources/lang/uk/community.php
  resources/lang/uk/contest.php
  resources/lang/uk/errors.php
  resources/lang/uk/events.php
  resources/lang/uk/forum.php
  resources/lang/uk/friends.php
  resources/lang/uk/help.php
  resources/lang/uk/home.php
  resources/lang/uk/layout.php
  resources/lang/uk/livestreams.php
  resources/lang/uk/mail.php
  resources/lang/uk/model_validation.php
  resources/lang/uk/model_validation/fulfillments.php
  resources/lang/uk/model_validation/payments.php
  resources/lang/uk/model_validation/store/product.php
  resources/lang/uk/multiplayer.php
  resources/lang/uk/news.php
  resources/lang/uk/notifications.php
  resources/lang/uk/oauth.php
  resources/lang/uk/password_reset.php
  resources/lang/uk/paypal/errors.php
  resources/lang/uk/quick_search.php
  resources/lang/uk/rankings.php
  resources/lang/uk/report.php
  resources/lang/uk/sessions.php
  resources/lang/uk/sort.php
  resources/lang/uk/status_page.php
  resources/lang/uk/store.php
  resources/lang/uk/supporter_tag.php
  resources/lang/uk/tournament.php
  resources/lang/uk/user_verification.php
  resources/lang/uk/users.php
  resources/lang/uk/validation.php
  resources/lang/uk/wiki.php
Labels: localisation

#5617 Fix error on missing group
  .env.dusk.local.example
  .env.example
  .travis.yml
  app/Libraries/Groups.php
  config/group.php
  phpunit.xml
Labels: tooling

#5622 Remove unused function
  app/Models/UserGroup.php
Labels: code quality

#5625 Use existing country column for scores filter
  app/Models/Score/Best/Model.php
  database/migrations/2020_02_13_080406_add_country_acronym_to_scores_high.php
Labels: database

#5639 Use count query for first place scores
  app/Transformers/UserTransformer.php
Labels: code quality, performance

#5642 Add breaking change note for beatmap and build stream json response update
  resources/views/vendor/apidoc/partials/info.blade.php
Labels: api, documentation

#5643 Update mail wording
  resources/lang/en/mail.php
Labels: localisation

#5592 Add stripe for unread notifications in notification history view
  resources/assets/less/bem/notification-popup-item.less
  resources/assets/lib/notification-widget/item.tsx
Labels: notifications

#5594 Change ScoreTransformer to always return pp inline.
  app/Http/Controllers/UsersController.php
  app/Transformers/ScoreTransformer.php
  resources/assets/lib/play-detail.coffee
Labels: code quality

#5541 Allow guests to search the wiki
  app/Http/Controllers/HomeController.php
  app/Libraries/Elasticsearch/Search.php
  app/Libraries/Elasticsearch/SearchParams.php
  app/Libraries/Search/ForumSearchParams.php
  app/Libraries/Search/WikiSearchParams.php
  app/Libraries/Search/WikiSuggestionsParams.php
  resources/lang/en/home.php
  resources/views/home/_search_page_tabs.blade.php
  resources/views/home/_search_results.blade.php
  resources/views/wiki/main.blade.php
Labels: search, wiki

#5555 Mobile page header links
  resources/assets/less/bem-index.less
  resources/assets/less/bem/header-nav-mobile.less
  resources/assets/less/bem/header-nav-v4.less
  resources/assets/less/variables.less
  resources/assets/lib/header-v4.tsx
  resources/views/layout/_page_header_v4.blade.php
  resources/views/store/header.blade.php
Labels: mobile

#5621 Show friend button on bots' profile page
  resources/assets/coffee/react/profile-page/header.coffee
  resources/assets/lib/globals.d.ts
  resources/assets/lib/profile-page/detail-bot.tsx
Labels: user profile

#5627 Add user title on forum post info
  resources/assets/less/bem/forum-post-info.less
  resources/views/forum/topics/_post_info.blade.php
Labels: forum

#5322 React-ify beatmap discussion history page
  app/Http/Controllers/BeatmapDiscussionsController.php
  app/Http/Controllers/Users/ModdingHistoryController.php
  resources/assets/coffee/react/beatmap-discussions-history.coffee
  resources/assets/coffee/react/beatmap-discussions-history/main.coffee
  resources/assets/coffee/react/modding-profile/discussions.coffee
  resources/assets/coffee/react/modding-profile/main.coffee
  resources/assets/less/bem/beatmapset-activities.less
  resources/assets/less/bem/modding-profile-list.less
  resources/lang/en/beatmap_discussions.php
  resources/views/beatmap_discussions/index.blade.php
  routes/web.php
  webpack.mix.js
Labels: beatmap discussions, user profile

#5603 Exclude group permission grants from OAuth grant
  app/Jobs/NotifyForumUpdateSlack.php
  app/Libraries/OsuAuthorize.php
  app/Models/User.php
  app/Transformers/UserTransformer.php
  resources/assets/coffee/_classes/beatmap-discussion-helper.coffee
  resources/assets/coffee/react/beatmap-discussions/discussion.coffee
  resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
  resources/assets/coffee/react/beatmap-discussions/nominations.coffee
  resources/assets/coffee/react/beatmapset-page/hype.coffee
  resources/assets/coffee/react/profile-page/user-page.coffee
  resources/assets/lib/chat/chat-api-responses.ts
  resources/assets/lib/models/comment.ts
  tests/karma/osu-core.spec.ts
Labels: api

#5648 Update pinned comments system
  app/Exceptions/ModelNotSavedException.php
  app/Http/Controllers/CommentsController.php
  app/Models/Comment.php
  app/Transformers/CommentTransformer.php
  resources/assets/coffee/react/_components/comment.coffee
  resources/assets/coffee/react/_components/comments.coffee
  resources/assets/less/bem/comment.less
  resources/assets/less/bem/comments.less
  resources/assets/lib/models/comment.ts
  resources/lang/en/model_validation.php
Labels: comments

#5677 Fix Nightcore/Daycore mods not working in multiplayer
  app/Libraries/Multiplayer/Mod.php
Labels: multiplayer

#5673 Remove Ubuntu quick setup script
  README.md
  SETUP.md
  bootstrap.sh
Labels: documentation

#5663 Show time ago for statuses in beatmap page
  resources/assets/coffee/react/_components/beatmapset-mapping.coffee
  resources/lang/ar/beatmapsets.php
  resources/lang/be/beatmapsets.php
  resources/lang/bg/beatmapsets.php
  resources/lang/cs/beatmapsets.php
  resources/lang/da/beatmapsets.php
  resources/lang/de/beatmapsets.php
  resources/lang/el/beatmapsets.php
  resources/lang/en/beatmapsets.php
  resources/lang/es/beatmapsets.php
  resources/lang/fi/beatmapsets.php
  resources/lang/fr/beatmapsets.php
  resources/lang/hu/beatmapsets.php
  resources/lang/id/beatmapsets.php
  resources/lang/it/beatmapsets.php
  resources/lang/ja/beatmapsets.php
  resources/lang/ko/beatmapsets.php
  resources/lang/nl/beatmapsets.php
  resources/lang/no/beatmapsets.php
  resources/lang/pl/beatmapsets.php
  resources/lang/pt-br/beatmapsets.php
  resources/lang/pt/beatmapsets.php
  resources/lang/ro/beatmapsets.php
  resources/lang/ru/beatmapsets.php
  resources/lang/sk/beatmapsets.php
  resources/lang/sv/beatmapsets.php
  resources/lang/th/beatmapsets.php
  resources/lang/tr/beatmapsets.php
  resources/lang/uk/beatmapsets.php
  resources/lang/vi/beatmapsets.php
  resources/lang/zh-tw/beatmapsets.php
  resources/lang/zh/beatmapsets.php
Labels: beatmap info

#5680 Adjust font and styles of news and wiki pages
  app/Libraries/Markdown/OsuMarkdown.php
  app/Transformers/CommentTransformer.php
  resources/assets/less/bem-index.less
  resources/assets/less/bem/changelog-entry.less
  resources/assets/less/bem/changelog-md.less
  resources/assets/less/bem/comment.less
  resources/assets/less/bem/comments.less
  resources/assets/less/bem/news-card.less
  resources/assets/less/bem/osu-md.less
  resources/assets/less/bem/osu-page.less
  resources/assets/less/bem/wiki-main-page.less
  resources/assets/less/bem/wiki-notice.less
  resources/assets/less/bem/wiki-page.less
  resources/assets/less/bem/wiki-toc-list.less
  resources/views/comments/index.blade.php
  resources/views/comments/show.blade.php
  resources/views/news/index.blade.php
  resources/views/news/show.blade.php
  resources/views/wiki/_notice.blade.php
  resources/views/wiki/main.blade.php
  resources/views/wiki/show.blade.php
Labels: design
