Repository ppy/osu-web, pull requests merged in 2020-10, with the labels that each got.

#6711 Change nomination requirement for 'hybrid' beatmapsets
  .env.example
  app/Models/Beatmapset.php
  config/osu.php
Labels: area:beatmap-discussions

#6714 Update translations from crowdin
  resources/lang/da/accounts.php
  resources/lang/de/authorization.php
  resources/lang/de/model_validation.php
  resources/lang/es/authorization.php
  resources/lang/es/model_validation.php
  resources/lang/fr/authorization.php
  resources/lang/fr/model_validation.php
  resources/lang/id/authorization.php
  resources/lang/id/model_validation.php
  resources/lang/it/model_validation.php
  resources/lang/ja/authorization.php
  resources/lang/ja/model_validation.php
  resources/lang/pt-br/authorization.php
  resources/lang/pt-br/mail.php
  resources/lang/pt-br/model_validation.php
  resources/lang/pt/authorization.php
  resources/lang/pt/events.php
  resources/lang/pt/forum.php
  resources/lang/pt/home.php
  resources/lang/pt/layout.php
  resources/lang/pt/model_validation.php
  resources/lang/pt/notifications.php
  resources/lang/pt/rankings.php
  resources/lang/pt/users.php
  resources/lang/ru/mail.php
  resources/lang/ru/model_validation.php
  resources/lang/sv/authorization.php
  resources/lang/sv/model_validation.php
  resources/lang/zh-tw/community.php
  resources/lang/zh-tw/mail.php
  resources/lang/zh-tw/model_validation.php
  resources/lang/zh-tw/users.php
  resources/lang/zh-tw/wiki.php
Labels: type:localisation

#6715 Limit max timestamp of beatmap discussion timeline chart
  resources/assets/lib/beatmap-discussions/chart.tsx
Labels: area:beatmap-discussions, type:design

#6708 Wrap or show less group badges on mobile
  resources/assets/coffee/react/profile-page/header-info.coffee
  resources/assets/less/bem/profile-info.less
  resources/assets/less/bem/quick-search-items.less
  resources/assets/less/bem/search-result-more.less
  resources/assets/less/bem/user-search-card.less
  resources/assets/less/utilities.less
  resources/assets/lib/quick-search/user.tsx
  resources/assets/lib/user-group-badges.tsx
Labels: type:design

#6716 Show reviews with open issues in pending filter on beatmap discussion
  resources/assets/coffee/react/beatmap-discussions/main.coffee
Labels: area:beatmap-discussions, type:ux

#6713 Lang.js cleanup
  resources/assets/coffee/osu_common.coffee
  resources/assets/coffee/react/profile-page/links.coffee
  resources/assets/lib/lang-overrides.ts
Labels: type:code-quality

#6728 Fix broken gallery
  resources/assets/coffee/main.coffee
  resources/assets/lib/app-deps.ts
  resources/assets/lib/gallery.coffee
  resources/assets/lib/import-shims.coffee
Labels: type:code-quality

#6707 Add user id to profile bbcode tag
  .travis.yml
  app/Libraries/BBCodeForDB.php
  app/Libraries/BBCodeFromDB.php
  phpunit.xml
  tests/Libraries/BBCodeForDBTest.php
  tests/Libraries/BBCodeFromDBTest.php
  tests/Libraries/bbcode_examples/basic_profile.db.txt
  tests/Libraries/bbcode_examples/basic_profile.html
  tests/Libraries/bbcode_examples/basic_profile_with_id.db.txt
  tests/Libraries/bbcode_examples/basic_profile_with_id.html
  tests/Libraries/bbcode_examples/tag_inside_profile.base.txt
  tests/Libraries/bbcode_examples/tag_inside_profile.db.txt
  tests/Libraries/bbcode_examples/tag_inside_profile.html
Labels: area:forum

#6672 Add more info to ranking ETA message
  app/Models/Beatmapset.php
  app/Transformers/BeatmapsetCompactTransformer.php
  resources/assets/coffee/react/beatmap-discussions/nominations.coffee
  resources/lang/en/beatmaps.php
Labels: type:ux

#6720 Fix beatmap favourites listing sometimes not showing correctly
  resources/assets/coffee/react/beatmapset-page/header.coffee
Labels: area:beatmap-info

#6717 Add support of bulk indexing of documents through LIO
  app/Console/Commands/EsIndexDocuments.php
  app/Http/Controllers/InterOp/Indexing/BulkController.php
  app/Jobs/EsIndexDocumentBulk.php
  app/Libraries/Elasticsearch/Es.php
  app/Libraries/Elasticsearch/Indexable.php
  app/Libraries/UserBestScoresCheck.php
  app/Models/Beatmapset.php
  app/Models/Forum/Post.php
  app/Models/Forum/Topic.php
  app/Models/User.php
  app/Traits/EsIndexableModel.php
  routes/web.php
Labels: type:database

#6703 Fix title and icon of grouped medal notifications
  resources/assets/less/bem/notification-popup-item.less
  resources/assets/lib/models/notification.ts
  resources/assets/lib/notification-maps/icons.ts
  resources/assets/lib/notification-maps/message.ts
  resources/assets/lib/notification-widget/item-group.tsx
  resources/lang/en/notifications.php
Labels: area:notifications, type:ux

#6740 Remove promise wrapping for chat api calls
  resources/assets/lib/chat/chat-api.ts
  resources/assets/lib/chat/chat-orchestrator.ts
  resources/assets/lib/chat/chat-worker.ts
Labels: area:chat, type:code-quality

#6739 Exclude no_profile user group from user lookup
  app/Libraries/BBCodeForDB.php
  app/Libraries/OsuAuthorize.php
  app/Models/User.php
  resources/views/forum/topics/_post_info.blade.php
Labels: area:user-profile

#6733 Add links to user titles
  app/Models/Rank.php
  app/Models/User.php
  app/Transformers/UserTransformer.php
  database/migrations/2020_10_06_010117_add_url_to_ranks.php
  resources/assets/coffee/react/profile-page/header-info.coffee
  resources/assets/less/bem/forum-post-info.less
  resources/assets/less/bem/profile-info.less
  resources/views/forum/topics/_post_info.blade.php
Labels: area:user-profile, type:ux

#6744 Fix alignment of audio player bar under [centre] BBCode
  resources/assets/less/bem/audio-player.less
Labels: type:design

#6718 Fix incorrectly nesting array for elasticsearch query
  app/Libraries/Elasticsearch/QueryHelper.php
  app/Libraries/Elasticsearch/SearchResponse.php
  app/Libraries/Search/BeatmapsetSearch.php
  app/Models/Wiki/Page.php
Labels: type:code-quality

#6746 Clearer score rank indicator
  resources/assets/less/bem/score-tower.less
  resources/assets/lib/scores-show/tower.tsx
Labels: type:ux

#6749 Mark notifications (the model) as read direct from its store
  resources/assets/lib/models/notification-stack.ts
  resources/assets/lib/stores/notification-stack-store.ts
  resources/assets/lib/stores/notification-store.ts
  resources/assets/lib/stores/widget-notification-stack-store.ts
Labels: area:notifications, type:code-quality

#6729 Simplify beatmap pack url render
  app/Models/BeatmapPack.php
  resources/views/packs/raw.blade.php
Labels: type:code-quality

#6741 Show verification dialog when sending chat message if required
  resources/assets/lib/chat/chat-worker.ts
Labels: area:chat

#6753 Make store/state constructor dependencies explicit
  resources/assets/lib/chat/chat-orchestrator.ts
  resources/assets/lib/chat/chat-state-store.ts
  resources/assets/lib/chat/conversation-list-item.tsx
  resources/assets/lib/chat/conversation-view.tsx
  resources/assets/lib/chat/input-box.tsx
  resources/assets/lib/stores/beatmapset-store.ts
  resources/assets/lib/stores/channel-store.ts
  resources/assets/lib/stores/client-store.ts
  resources/assets/lib/stores/comment-store.ts
  resources/assets/lib/stores/commentable-meta-store.ts
  resources/assets/lib/stores/own-client-store.ts
  resources/assets/lib/stores/root-data-store.ts
  resources/assets/lib/stores/store.ts
  resources/assets/lib/stores/ui-state-store.ts
  resources/assets/lib/stores/user-store.ts
Labels: type:code-quality

#6758 Simplify notifications history header links
  resources/assets/lib/notifications-index/main.tsx
Labels: type:code-quality

#6748 Use _doc as _type for Elasticsearch
  .travis.yml
  app/Console/Commands/EsIndexDocuments.php
  app/Console/Commands/EsIndexWiki.php
  app/Jobs/EsIndexDocumentBulk.php
  app/Libraries/Elasticsearch/Indexing.php
  app/Models/Elasticsearch/BeatmapsetTrait.php
  app/Models/Elasticsearch/PostTrait.php
  app/Models/Elasticsearch/TopicTrait.php
  app/Models/Elasticsearch/UserTrait.php
  app/Models/Elasticsearch/WikiPageTrait.php
  app/Models/Wiki/Page.php
  app/Traits/EsIndexable.php
  app/Traits/EsIndexableModel.php
  composer.json
  composer.lock
  config/schemas/beatmaps.json
  config/schemas/posts.json
  config/schemas/users.json
  config/schemas/wiki_page.json
Labels: area:search, type:code-quality

#6682 Add username prefix search
  config/schemas/users.json
Labels: area:search

#6751 Save Paypal API transaction id when processing orders
  app/Http/Controllers/Payments/PaypalController.php
  app/Libraries/Payments/PaymentProcessor.php
  app/Models/Store/Order.php
  database/migrations/2020_10_13_064901_add_provider_reference_to_orders.php
Labels: area:store

#6754 Show verification dialog if required when marking notifications as read
  resources/assets/lib/notifications/notification-resolver.ts
Labels: area:notifications

#6755 Require verification to send chat message
  app/Libraries/OsuAuthorize.php
  tests/Libraries/ChatTest.php
Labels: area:chat

#6761 Move setting of chat initial channel out of view
  resources/assets/lib/chat.ts
  resources/assets/lib/chat/main-view.tsx
Labels: area:chat, type:code-quality

#6768 Remove display of user lastfm
  resources/assets/coffee/react/profile-page/links.coffee
  resources/docs/source/includes/_structures/user.md
  resources/lang/en/users.php
Labels: area:user-profile

#6771 Hide user lastfm from API
  app/Models/DeletedUser.php
  app/Models/User.php
  app/Models/UserNotFound.php
  app/Transformers/UserTransformer.php
Labels: area:user-profile

#6756 Show game and score mods on multiplayer scores
  app/Models/Match/Score.php
Labels: area:multiplayer

#6730 Include more user profile related counts
  app/Http/Controllers/UsersController.php
  app/Libraries/ModdingHistoryEventsBundle.php
  app/Models/UserScoreable.php
  app/Transformers/UserCompactTransformer.php
  resources/assets/coffee/react/profile-page/historical.coffee
  resources/assets/coffee/react/profile-page/top-ranks.coffee
  resources/docs/source/includes/_structures/user_compact.md
Labels: area:user-profile

#6760 Add "Remove from Loved" button, event, and notification
  app/Http/Controllers/BeatmapsetsController.php
  app/Jobs/Notifications/BeatmapsetRemoveFromLoved.php
  app/Models/Beatmapset.php
  app/Models/BeatmapsetEvent.php
  app/Models/Notification.php
  app/Transformers/BeatmapsetCompactTransformer.php
  database/migrations/2020_10_14_030317_add_remove_from_loved_type_to_beatmapset_events.php
  resources/assets/coffee/react/beatmap-discussions/nominations.coffee
  resources/assets/less/bem/beatmapset-event.less
  resources/assets/lib/beatmap-discussions/event.tsx
  resources/assets/lib/notification-maps/category.ts
  resources/assets/lib/notification-maps/icons.ts
  resources/assets/lib/notification-maps/url.ts
  resources/docs/source/includes/_structures/notification.md
  resources/lang/en/beatmaps.php
  resources/lang/en/beatmapset_events.php
  resources/lang/en/notifications.php
  routes/web.php
Labels: area:beatmap-info

#6798 Remove unused class and modifier
  resources/assets/less/bem-index.less
  resources/assets/less/bem/flag-country.less
  resources/assets/less/bem/userinfo-small.less
Labels: type:code-quality

#6802 Fix missing tooltip on some cut off text
  resources/assets/coffee/_classes/tooltip-default.coffee
Labels: type:ux

#6789 Standardize Json naming
  resources/assets/coffee/react/_components/comment.coffee
  resources/assets/coffee/react/_components/comments-manager.coffee
  resources/assets/coffee/react/comments-index.coffee
  resources/assets/coffee/react/comments-show.coffee
  resources/assets/lib/actions/chat-actions.ts
  resources/assets/lib/beatmap-discussions/event.tsx
  resources/assets/lib/beatmap-discussions/events.tsx
  resources/assets/lib/beatmap-discussions/mapper-group.ts
  resources/assets/lib/beatmap-discussions/new-review.tsx
  resources/assets/lib/chat.ts
  resources/assets/lib/chat/chat-api-responses.ts
  resources/assets/lib/chat/chat-api.ts
  resources/assets/lib/chat/chat-orchestrator.ts
  resources/assets/lib/chat/chat-worker.ts
  resources/assets/lib/friends-index/main.tsx
  resources/assets/lib/globals.d.ts
  resources/assets/lib/groups-show/main.tsx
  resources/assets/lib/interfaces/client-json.ts
  resources/assets/lib/interfaces/comment-json.ts
  resources/assets/lib/interfaces/current-user.ts
  resources/assets/lib/interfaces/group-json.ts
  resources/assets/lib/interfaces/own-client-json.ts
  resources/assets/lib/interfaces/score-json.ts
  resources/assets/lib/interfaces/user-json-extended.ts
  resources/assets/lib/interfaces/user-json.ts
  resources/assets/lib/models/chat/channel.ts
  resources/assets/lib/models/chat/message.ts
  resources/assets/lib/models/comment.ts
  resources/assets/lib/models/oauth/client.ts
  resources/assets/lib/models/oauth/own-client.ts
  resources/assets/lib/models/user.ts
  resources/assets/lib/oauth/new-client.tsx
  resources/assets/lib/osu-core.ts
  resources/assets/lib/profile-page/detail-bot.tsx
  resources/assets/lib/quick-search/user.tsx
  resources/assets/lib/quick-search/worker.ts
  resources/assets/lib/report-reportable.tsx
  resources/assets/lib/stores/channel-store.ts
  resources/assets/lib/stores/client-store.ts
  resources/assets/lib/stores/comment-store.ts
  resources/assets/lib/stores/commentable-meta-store.ts
  resources/assets/lib/stores/own-client-store.ts
  resources/assets/lib/stores/root-data-store.ts
  resources/assets/lib/stores/ui-state-store.ts
  resources/assets/lib/stores/user-store.ts
  resources/assets/lib/user-card-brick.tsx
  resources/assets/lib/user-card-store.tsx
  resources/assets/lib/user-card-tooltip.tsx
  resources/assets/lib/user-card.tsx
  resources/assets/lib/user-cards.tsx
  resources/assets/lib/user-group-badge.tsx
  resources/assets/lib/user-group-badges.tsx
  resources/assets/lib/user-list.tsx
  resources/assets/lib/wiki-search-controller.ts
  tests/karma/osu-core.spec.ts
Labels: type:code-quality

#6772 Global typing fixes
  resources/assets/lib/beatmapsets-show/metadata-editor.tsx
  resources/assets/lib/chat.ts
  resources/assets/lib/globals.d.ts
  resources/assets/lib/notifications-index.ts
Labels: type:code-quality

#6799 Locale flag cleanup
  app/helpers.php
  resources/assets/coffee/react/_components/flag-country.coffee
  resources/assets/coffee/react/beatmapset-page/score-top.coffee
  resources/assets/coffee/react/beatmapset-page/scoreboard-table-row.coffee
  resources/assets/coffee/react/mp-history/score.coffee
  resources/assets/coffee/react/profile-page/header-info.coffee
  resources/assets/less/bem/flag-country.less
  resources/assets/less/bem/forum-post-info.less
  resources/assets/less/bem/landing-nav.less
  resources/assets/less/bem/nav-button.less
  resources/assets/less/bem/nav2-locale-item.less
  resources/assets/less/bem/navbar-mobile-item.less
  resources/assets/less/bem/profile-info.less
  resources/assets/less/bem/user-card.less
  resources/assets/less/bem/user-search-card.less
  resources/assets/lib/coffee-modules.d.ts
  resources/assets/lib/flag-country.tsx
  resources/assets/lib/quick-search/user.tsx
  resources/assets/lib/user-card.tsx
  resources/views/accounts/_edit_sessions.blade.php
  resources/views/forum/topics/_post_info.blade.php
  resources/views/home/landing.blade.php
  resources/views/layout/_nav2.blade.php
  resources/views/layout/header_mobile/nav.blade.php
  resources/views/multiplayer/rooms/_rankings_table.blade.php
  resources/views/objects/_country_flag.blade.php
  resources/views/objects/_flag_country.blade.php
  resources/views/rankings/_spotlight_rankings_table.blade.php
  resources/views/rankings/country.blade.php
  resources/views/rankings/performance.blade.php
  resources/views/rankings/score.blade.php
Labels: type:code-quality

#6763 Move chat channel and message handling to store
  resources/assets/lib/actions/chat-actions.ts
  resources/assets/lib/actions/user-silence-action.ts
  resources/assets/lib/chat.ts
  resources/assets/lib/chat/chat-api-responses.ts
  resources/assets/lib/chat/chat-orchestrator.ts
  resources/assets/lib/chat/chat-worker.ts
  resources/assets/lib/chat/input-box.tsx
  resources/assets/lib/models/chat/channel.ts
  resources/assets/lib/models/chat/message.ts
  resources/assets/lib/osu-core.ts
  resources/assets/lib/stores/channel-store.ts
Labels: area:chat, type:code-quality

#6800 Add language menu for wiki page
  app/Models/Wiki/Page.php
  resources/assets/less/bem/btn-osu-big.less
  resources/assets/less/bem/header-buttons.less
  resources/assets/less/bem/nav2-locale-item.less
  resources/assets/less/bem/simple-menu.less
  resources/views/wiki/_actions.blade.php
Labels: area:wiki

#6831 Use composer v1 for running phpcs workflow
  .github/workflows/phpcs.yml
Labels: area:tooling
