Repository ppy/osu-web, pull requests merged in 2020-08, with the labels that each got.

#6368 Add minimum width in table cell wiki
  resources/assets/less/bem/osu-md.less
Labels: area:wiki, platform:mobile

#6403 Change notification mail interval to 1 hour
  app/Console/Kernel.php
Labels: area:notifications

#6413 Shorten duration of guest sessions
  app/Libraries/Session/CacheBasedSessionHandler.php
  app/Libraries/Session/SessionManager.php
  app/Libraries/Session/Store.php
Labels: type:performance

#6353 Remove messages of silenced users
  app/Http/Controllers/Chat/ChatController.php
  app/Transformers/Chat/UserSilenceTransformer.php
  database/migrations/2020_07_22_045416_add_timestamp_index_to_user_account_history.php
  resources/assets/lib/actions/user-silence-action.ts
  resources/assets/lib/chat/chat-api-responses.ts
  resources/assets/lib/chat/chat-api.ts
  resources/assets/lib/chat/chat-worker.ts
  resources/assets/lib/stores/channel-store.ts
Labels: area:chat

#6259 Add block count display to the review editor
  app/Http/Controllers/BeatmapsetsController.php
  resources/assets/coffee/react/beatmap-discussions/main.coffee
  resources/assets/less/bem-index.less
  resources/assets/less/bem/beatmap-discussion-editor.less
  resources/assets/less/bem/circular-progress.less
  resources/assets/lib/beatmap-discussions/editor-helpers.ts
  resources/assets/lib/beatmap-discussions/editor.tsx
  resources/assets/lib/beatmap-discussions/review-editor-config-context.ts
  resources/assets/lib/circular-progress.tsx
  resources/assets/lib/interfaces/review-editor-config-json.ts
  resources/lang/en/beatmap_discussions.php
Labels: area:beatmap-discussions

#6417 Fix mail notification digest links
  app/Jobs/Notifications/BeatmapsetDiscussionPostNotification.php
  app/Jobs/Notifications/BeatmapsetDiscussionReviewNew.php
  app/Mail/UserNotificationDigest.php
  resources/views/emails/user_notification_digest.blade.php
Labels: area:notifications

#6449 Add temporary exception for timeshift submission from unsupported clients
  app/Http/Controllers/Multiplayer/Rooms/Playlist/ScoresController.php
Labels: area:multiplayer

#6398 Add play count for unranked beatmapset card
  resources/assets/coffee/react/_components/beatmapset-panel.coffee
  resources/assets/less/bem/beatmapset-panel.less
Labels: area:beatmap-listing

#6444 Fix review block counter in some pages
  app/Http/Controllers/BeatmapDiscussionsController.php
  app/Http/Controllers/BeatmapsetsController.php
  app/Libraries/BeatmapsetDiscussionReview.php
  app/Libraries/ModdingHistoryEventsBundle.php
  resources/assets/coffee/react/beatmap-discussions-history.coffee
  resources/assets/coffee/react/beatmap-discussions-history/main.coffee
  resources/assets/coffee/react/modding-profile.coffee
  resources/assets/coffee/react/modding-profile/main.coffee
Labels: area:beatmap-discussions

#6437 Add documentation for user API endpoint
  app/Http/Controllers/UsersController.php
Labels: type:api, type:documentation

#6438 Fix add new embed show discussion deleted in beatmap discussion history page
  resources/assets/coffee/react/beatmap-discussions-history/main.coffee
Labels: area:beatmap-discussions

#6476 Make User profile navigation bar always be present in viewport
  resources/assets/less/bem/page-extra-tabs.less
Labels: area:user-profile, type:ux

#6477 Remove unused placeholder
  resources/assets/less/bem/beatmap-discussion-editor.less
Labels: type:code-quality

#6471 Remove old buttons and clean up fileupload
  resources/assets/coffee/react/contest-entry/uploader.coffee
  resources/assets/coffee/react/contest-entry/user-entry.coffee
  resources/assets/coffee/react/profile-page/cover-selector.coffee
  resources/assets/coffee/react/profile-page/cover-uploader.coffee
  resources/assets/coffee/react/profile-page/user-page.coffee
  resources/assets/less/base.less
  resources/assets/less/bem-index.less
  resources/assets/less/bem/account-edit-entry.less
  resources/assets/less/bem/btn-osu-big.less
  resources/assets/less/bem/btn-osu-lite.less
  resources/assets/less/bem/contest-userentry.less
  resources/assets/less/bem/fileupload.less
  resources/assets/less/bem/profile-cover-change-popup.less
  resources/assets/less/bem/profile-cover-uploader.less
  resources/views/accounts/edit.blade.php
  resources/views/admin/store/orders/show.blade.php
  resources/views/forum/topics/_cover_editor.blade.php
Labels: type:code-quality

#6494 Add missing positioning of play detail on mobile
  resources/assets/less/bem/play-detail.less
Labels: type:design

#6495 Add missing relative position for changelog graph
  resources/assets/less/bem/changelog-chart.less
Labels: type:design

#6482 Add missing preload for forum topic page
  app/Http/Controllers/Forum/TopicsController.php
  app/Models/Forum/Post.php
Labels: type:performance

#6496 Fix positioning of score page elements
  resources/assets/less/bem/score-info.less
  resources/assets/less/bem/score-stats.less
Labels: type:design

#6497 Fix forum topic bookmark menu and search form
  resources/assets/less/bem/search-forum-options.less
  resources/views/forum/topics/_watch.blade.php
Labels: type:design

#6499 More fixes on positioning
  resources/assets/less/bem/forum-item.less
  resources/assets/less/bem/forum-list.less
  resources/assets/less/bem/forum-post.less
  resources/assets/less/bem/mods.less
  resources/assets/less/bem/mp-history-game.less
Labels: type:design

#6503 Fix landing page links not being clickable
  resources/assets/less/bem/landing-hero.less
  resources/assets/less/bem/landing-nav.less
  resources/assets/less/variables.less
Labels: type:design

#6452 Truncate long artist name in beatmapset card
  resources/assets/coffee/react/_components/beatmapset-panel.coffee
Labels: area:beatmap-listing

#6508 Log login attempts to datadog
  app/Http/Controllers/SessionsController.php
  app/Http/Middleware/VerifyCsrfToken.php
  app/Libraries/User/DatadogLoginAttempt.php
  app/Models/User.php
Labels: area:tooling

#6472 Ranking pagination fix
  app/Http/Controllers/RankingController.php
Labels: area:rankings

#6374 Add notifications for replies to comments
  app/Jobs/Notifications/CommentNew.php
  app/Models/UserNotificationOption.php
  resources/assets/lib/models/notification.ts
  resources/assets/lib/notification-maps/category.ts
  resources/assets/lib/notification-maps/icons.ts
  resources/assets/lib/notification-maps/url.ts
  resources/lang/en/accounts.php
  resources/lang/en/notifications.php
  resources/views/accounts/_edit_notifications.blade.php
  tests/Models/CommentTest.php
Labels: area:comments, area:notifications

#6439 Omit some notifications from notification mail digest
  app/Http/Controllers/Forum/TopicsController.php
  app/Jobs/Notifications/BeatmapsetDiscussionLock.php
  app/Jobs/Notifications/BeatmapsetDiscussionReviewNew.php
  app/Jobs/Notifications/BeatmapsetDiscussionUnlock.php
  app/Jobs/Notifications/BroadcastNotificationBase.php
  app/Jobs/Notifications/ForumTopicReply.php
  app/Jobs/Notifications/UserAchievementUnlock.php
  app/Jobs/UserNotificationDigest.php
  app/Libraries/NotificationsBundle.php
  app/Models/Notification.php
  app/Models/User.php
  database/factories/ForumFactory.php
  database/seeds/ModelSeeders/ForumSeeder.php
  resources/lang/en/notifications.php
  tests/BroadcastNotificationTest.php
  tests/Commands/NotificationsSendMailTest.php
  tests/Jobs/UserNotificationDigestTest.php
  tests/TestCase.php
Labels: area:notifications

#6501 Fix show more previous posts incorrectly showing on forum thread
  app/Http/Controllers/Forum/TopicsController.php
Labels: area:forum

#6506 Add multiplayer support for mania invert mod
  app/Libraries/Multiplayer/Mod.php
Labels: area:multiplayer

#6519 Wrap long username instead of truncating
  resources/assets/less/bem/forum-post-info.less
  resources/views/forum/topics/_post_info.blade.php
Labels: area:forum

#6511 Account edit page fixes
  resources/assets/less/bem/account-edit-entry.less
  resources/assets/less/bem/fragment-target.less
  resources/assets/less/bem/osu-switch-v2.less
Labels: type:design

#6525 Fix position of delete button in contest entry submissions
  resources/assets/less/bem/contest-userentry.less
Labels: type:design

#6527 Add missing dot in datadog login attempts name
  app/Libraries/User/DatadogLoginAttempt.php
Labels: area:tooling

#6545 Remove old navbar icon script
  resources/assets/app.js
  resources/assets/coffee/navbar-mobile.coffee
  resources/views/layout/_header_mobile.blade.php
Labels: type:code-quality

#6542 Remove manual event throttling on scroll and resize
  resources/assets/coffee/_classes/changelog-chart-loader.coffee
  resources/assets/coffee/_classes/fancy-graph.coffee
  resources/assets/coffee/_classes/forum-auto-click.coffee
  resources/assets/coffee/_classes/forum.coffee
  resources/assets/coffee/_classes/landing-graph.coffee
  resources/assets/coffee/_classes/nav-button.coffee
  resources/assets/coffee/_classes/nav2.coffee
  resources/assets/coffee/_classes/scale.coffee
  resources/assets/coffee/_classes/sticky-footer.coffee
  resources/assets/coffee/_classes/sticky-header.coffee
  resources/assets/coffee/_classes/sync-height.coffee
  resources/assets/coffee/_classes/throttled-window-events.coffee
  resources/assets/coffee/_classes/user-verification.coffee
  resources/assets/coffee/main.coffee
  resources/assets/coffee/react/beatmap-discussions/header.coffee
  resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
  resources/assets/coffee/react/beatmapset-page/info.coffee
  resources/assets/coffee/react/beatmapset-page/stats.coffee
  resources/assets/coffee/react/modding-profile/main.coffee
  resources/assets/coffee/react/profile-page/historical.coffee
  resources/assets/coffee/react/profile-page/main.coffee
  resources/assets/coffee/react/profile-page/rank-chart.coffee
  resources/assets/lib/beatmap-discussions/new-review.tsx
  resources/assets/lib/chat/conversation-view.tsx
  resources/assets/lib/popup-menu.coffee
  resources/assets/lib/window-vh-patcher.ts
Labels: type:code-quality

#6546 Ignore hidden filter for user best scores listing
  app/Models/UserScoreable.php
Labels: area:user-profile

#6473 Make chat channel with moderator visible even if blocked
  app/Models/Chat/Channel.php
  app/Models/Chat/UserChannel.php
Labels: area:chat

#6478 Fix forum post reply read notification not being sent properly
  app/Jobs/MarkNotificationsRead.php
  app/Models/Notification.php
Labels: area:notifications

#6537 Always show beatmap play success chart
  resources/assets/coffee/react/beatmapset-page/info.coffee
  resources/lang/en/beatmapsets.php
Labels: area:beatmap-info

#6553 Group beatmap discussion moderation buttons separately and add colour
  resources/assets/coffee/react/beatmap-discussions/nominations.coffee
  resources/assets/less/bem/beatmap-discussion-nomination.less
  resources/assets/less/bem/btn-osu-big.less
Labels: area:beatmap-discussions, type:ux

#6541 Limit execution of page change event callbacks
  resources/assets/coffee/_classes/current-user-observer.coffee
  resources/assets/coffee/_classes/forum-auto-click.coffee
  resources/assets/coffee/_classes/forum.coffee
  resources/assets/coffee/_classes/sticky-footer.coffee
  resources/assets/coffee/_classes/sticky-header.coffee
  resources/assets/coffee/_classes/sync-height.coffee
  resources/assets/coffee/osu_common.coffee
Labels: type:performance

#6544 Event cleanup in Popup Menu component
  resources/assets/lib/popup-menu.coffee
Labels: type:code-quality

#6539 Show label on user/signin button in mobile menu
  resources/assets/less/bem/mobile-menu-tab.less
  resources/lang/en/layout.php
  resources/views/layout/_header_mobile.blade.php
Labels: type:design

#6556 Fix documentation formatting for multiplayer
  app/Http/Controllers/Multiplayer/Rooms/Playlist/ScoresController.php
Labels: type:design

#6549 Add troubleshooting help on download page
  resources/assets/less/bem/download-page.less
  resources/lang/en/home.php
  resources/views/home/download.blade.php
Labels: type:ux

#6526 Captcha cleanup and improvements
  app/Http/Controllers/SessionsController.php
  app/helpers.php
  package.json
  resources/assets/coffee/_classes/user-login.coffee
  resources/assets/coffee/main.coffee
  resources/assets/coffee/osu_common.coffee
  resources/assets/lib/captcha.ts
  resources/assets/lib/import-shims.coffee
  resources/views/layout/_popup_login.blade.php
  resources/views/layout/metadata.blade.php
  yarn.lock
Labels: type:code-quality, type:ux

#6547 Disable voting and kudosu on posts by bots
  app/Libraries/OsuAuthorize.php
  app/Models/BeatmapDiscussion.php
  resources/assets/coffee/react/beatmap-discussions/discussion.coffee
  resources/lang/en/authorization.php
Labels: area:beatmap-discussions

#6554 Locally cache groups data
  .env.dusk.local.example
  .env.example
  .travis.yml
  app/Libraries/Groups.php
  config/cache.php
  phpunit.xml
Labels: type:performance

#6559 Check match end time to determine whether or not it's still ongoing
  app/Http/Controllers/MatchesController.php
  resources/assets/coffee/react/mp-history.coffee
  resources/assets/coffee/react/mp-history/main.coffee
  resources/views/matches/index.blade.php
Labels: area:multiplayer

#6560 Show rank count in mobile profile page
  resources/assets/coffee/react/profile-page/header.coffee
  resources/assets/less/bem/profile-header.less
  resources/assets/less/bem/profile-rank-count.less
Labels: area:user-profile

#6563 Allow restricted users to update some preferences
  app/Http/Controllers/AccountController.php
  resources/assets/coffee/react/profile-page/game-mode-switcher.coffee
  resources/views/accounts/_edit_notifications.blade.php
  resources/views/accounts/_edit_options.blade.php
  resources/views/accounts/_edit_playstyles.blade.php
  resources/views/accounts/_edit_privacy.blade.php
Labels: area:settings

#6569 Fix position of close button in modding reply box
  resources/assets/coffee/react/beatmap-discussions/new-reply.coffee
  resources/assets/less/bem/beatmap-discussion-post.less
Labels: area:beatmap-discussions, type:design

#6566 Fix verification dialog error message position
  resources/assets/less/bem/user-verification.less
Labels: type:design

#6481 Add warning indicator to review issues that are near existing posts
  resources/assets/coffee/_classes/beatmap-discussion-helper.coffee
  resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
  resources/assets/less/bem/beatmap-discussion-review-post-embed-preview.less
  resources/assets/less/bem/tooltip-default.less
  resources/assets/lib/beatmap-discussions/drafts-context.ts
  resources/assets/lib/beatmap-discussions/editor-discussion-component.tsx
  resources/assets/lib/beatmap-discussions/editor.tsx
  resources/assets/lib/globals.d.ts
  resources/lang/en/beatmap_discussions.php
Labels: area:beatmap-discussions

#6561 More thorough user best score check and cleanup
  app/Console/Commands/UserBestScoresCheckCommand.php
  app/Libraries/Elasticsearch/Search.php
  app/Libraries/UserBestScoresCheck.php
Labels: area:user-profile, type:reliability

#6577 Return user recent events in consistent order
  app/Models/Event.php
Labels: area:user-profile
