Repository ppy/osu-web, pull requests merged in 2021-11, with the labels that each got.

#8281 Remove unused forum title view
  resources/views/forum/topics/_header_title.blade.php
Labels: type:code-quality

#8280 Test for session reset on password change
  resources/views/accounts/_edit_password.blade.php
  tests/Browser/AccountTest.php
Labels: type:testing

#7822 Add topic logs
  app/Http/Controllers/Forum/TopicLogsController.php
  app/Models/Log.php
  database/migrations/2021_11_01_194418_add_post_id_to_phpbb_log.php
  resources/assets/less/bem-index.less
  resources/assets/less/bem/forum-topic-logs-table.less
  resources/lang/en/forum.php
  resources/lang/en/page_title.php
  resources/views/forum/_header.blade.php
  resources/views/forum/topics/_moderate_logs.blade.php
  resources/views/forum/topics/_nav.blade.php
  resources/views/forum/topics/logs/index.blade.php
  routes/web.php
  tests/Browser/SanityTest.php
Labels: area:forum, area:admin

#8286 Handle replay download with missing beatmap or user
  app/Http/Controllers/ScoresController.php
  app/Libraries/ReplayFile.php
  database/factories/BeatmapFactory.php
  tests/Controllers/ScoresControllerTest.php
  tests/Libraries/ReplayFileTest.php
Labels: type:reliability

#8285 Allow importing from existing coffee classes
  package.json
  resources/assets/app.ts
  resources/assets/coffee/_classes/account-edit-avatar.coffee
  resources/assets/coffee/_classes/account-edit-blocklist.coffee
  resources/assets/coffee/_classes/account-edit.coffee
  resources/assets/coffee/_classes/bbcode-preview.coffee
  resources/assets/coffee/_classes/beatmap-discussion-helper.coffee
  resources/assets/coffee/_classes/beatmap-pack.coffee
  resources/assets/coffee/_classes/beatmapset-filter.coffee
  resources/assets/coffee/_classes/changelog-chart-loader.coffee
  resources/assets/coffee/_classes/changelog-chart.coffee
  resources/assets/coffee/_classes/checkbox-validation.coffee
  resources/assets/coffee/_classes/current-user-observer.coffee
  resources/assets/coffee/_classes/dumb-storage.coffee
  resources/assets/coffee/_classes/fancy-chart.coffee
  resources/assets/coffee/_classes/fancy-graph.coffee
  resources/assets/coffee/_classes/form-clear.coffee
  resources/assets/coffee/_classes/form-confirmation.coffee
  resources/assets/coffee/_classes/form-error.coffee
  resources/assets/coffee/_classes/form-placeholder-hide.coffee
  resources/assets/coffee/_classes/form-toggle.coffee
  resources/assets/coffee/_classes/forum-auto-click.coffee
  resources/assets/coffee/_classes/forum-cover.coffee
  resources/assets/coffee/_classes/forum-posts-seek.coffee
  resources/assets/coffee/_classes/forum-topic-post-jump.coffee
  resources/assets/coffee/_classes/forum-topic-reply.coffee
  resources/assets/coffee/_classes/forum-topic-title.coffee
  resources/assets/coffee/_classes/forum-topic-watch-ajax.coffee
  resources/assets/coffee/_classes/forum.coffee
  resources/assets/coffee/_classes/global-drag.coffee
  resources/assets/coffee/_classes/hits.coffee
  resources/assets/coffee/_classes/input-handler.coffee
  resources/assets/coffee/_classes/landing-graph.coffee
  resources/assets/coffee/_classes/landing-user-stats.coffee
  resources/assets/coffee/_classes/line-chart.coffee
  resources/assets/coffee/_classes/loading-overlay.coffee
  resources/assets/coffee/_classes/menu.coffee
  resources/assets/coffee/_classes/nav-button.coffee
  resources/assets/coffee/_classes/nav2.coffee
  resources/assets/coffee/_classes/polyfills.coffee
  resources/assets/coffee/_classes/post-preview.coffee
  resources/assets/coffee/_classes/scale.coffee
  resources/assets/coffee/_classes/search.coffee
  resources/assets/coffee/_classes/stacked-bar-chart.coffee
  resources/assets/coffee/_classes/sticky-footer.coffee
  resources/assets/coffee/_classes/sticky-header.coffee
  resources/assets/coffee/_classes/store-cart.coffee
  resources/assets/coffee/_classes/store-supporter-tag-price.coffee
  resources/assets/coffee/_classes/store-supporter-tag.coffee
  resources/assets/coffee/_classes/sync-height.coffee
  resources/assets/coffee/_classes/timeout.coffee
  resources/assets/coffee/_classes/tooltip-beatmap.coffee
  resources/assets/coffee/_classes/tooltip-default.coffee
  resources/assets/coffee/_classes/turbolinks-ujs.coffee
  resources/assets/coffee/_classes/twitch-player.coffee
  resources/assets/coffee/main.coffee
  resources/assets/coffee/osu_common.coffee
  webpack.unmix.js
  yarn.lock
Labels: type:code-quality

#8289 Fix artist track search's enter to submit on Safari
  resources/assets/less/utilities.less
  resources/assets/lib/artist-tracks-index/search-form.tsx
Labels: area:featured-artist

#8290 Fix store request notification button style
  resources/views/store/products/show.blade.php
Labels: area:store

#8291 Throw validation error when failing to save factory user
  database/factories/UserFactory.php
Labels: type:testing

#8293 Fix popup menu clipping offscreen
  resources/assets/coffee/react/modding-profile/detail-bar.coffee
  resources/assets/coffee/react/profile-page/detail-bar.coffee
  resources/assets/lib/popup-menu.coffee
  resources/assets/lib/profile-page/extra-menu.tsx
Labels: area:user-profile, type:ux, area:beatmap-info

#8282 Convert `Comment` factory to class
  app/Models/Comment.php
  database/factories/CommentFactory.php
  database/factories/NewsPostFactory.php
  tests/Browser/SanityTest.php
  tests/Controllers/CommentsControllerTest.php
  tests/RouteScopesTest.php
  tests/Transformers/CommentTransformerTest.php
Labels: type:testing, type:code-quality

#8303 Update allowed beatmap types for score submission
  app/Http/Controllers/Solo/ScoreTokensController.php
  app/Models/Beatmap.php
  database/factories/BeatmapFactory.php
  tests/Controllers/Solo/ScoreTokensControllerTest.php
Labels: area:scoring

#8292 Update Lang.js initialisation
  resources/assets/app.ts
  resources/assets/coffee/main.coffee
  resources/assets/lib/app-deps.ts
  resources/assets/lib/globals.d.ts
  resources/assets/lib/lang-overrides.ts
  tests/karma/osu_common.spec.ts
Labels: type:reliability

#8294 Typescript MedalsCount component
  resources/assets/coffee/react/profile-page/detail-mobile.coffee
  resources/assets/coffee/react/profile-page/detail.coffee
  resources/assets/coffee/react/profile-page/medals-count.coffee
  resources/assets/lib/profile-page/medals-count.tsx
Labels: area:user-profile, type:code-quality

#8297 Simplify video player on landing page
  resources/assets/app.ts
  resources/assets/coffee/_classes/scale.coffee
  resources/assets/coffee/main.coffee
  resources/assets/less/bem/landing-hero.less
  resources/views/home/landing.blade.php
Labels: type:code-quality

#8304 More consistent user profile details bar buttons
  app/Http/Controllers/UsersController.php
  app/Transformers/UserCompactTransformer.php
  resources/assets/coffee/react/modding-profile/detail-bar.coffee
  resources/assets/coffee/react/modding-profile/detail.coffee
  resources/assets/coffee/react/modding-profile/header.coffee
  resources/assets/coffee/react/profile-page/detail-bar.coffee
  resources/assets/coffee/react/profile-page/detail.coffee
  resources/assets/lib/coffee-modules.d.ts
  resources/assets/lib/interfaces/user-extended-json.ts
  resources/assets/lib/profile-page/detail-bar-buttons.tsx
  resources/assets/lib/profile-page/detail-bot.tsx
  resources/assets/lib/user-multiplayer-index/header.tsx
  resources/assets/lib/user-profile-container.tsx
  resources/assets/lib/utils/user-helper.ts
Labels: area:user-profile

#8315 Fix styling for discussion review selector menu
  resources/assets/lib/beatmap-discussions/icon-dropdown-menu.tsx
Labels: area:beatmap-discussions

#8316 Fix discussion review selector menu popup direction
  resources/assets/lib/beatmap-discussions/icon-dropdown-menu.tsx
  resources/assets/lib/coffee-modules.d.ts
  resources/assets/lib/popup-menu.coffee
Labels: area:beatmap-discussions

#8305 Typescript profile page section of user profile
  resources/assets/coffee/react/profile-page/main.coffee
  resources/assets/coffee/react/profile-page/user-page.coffee
  resources/assets/lib/profile-page/beatmapsets.tsx
  resources/assets/lib/profile-page/extra-page-props.ts
  resources/assets/lib/profile-page/kudosu.tsx
  resources/assets/lib/profile-page/user-page-editor.tsx
  resources/assets/lib/profile-page/user-page.tsx
Labels: area:user-profile, type:code-quality

#8319 Convert user profile rank component to typescript
  resources/assets/coffee/react/modding-profile/detail-bar.coffee
  resources/assets/coffee/react/profile-page/detail-bar.coffee
  resources/assets/coffee/react/profile-page/detail-mobile.coffee
  resources/assets/coffee/react/profile-page/detail.coffee
  resources/assets/coffee/react/profile-page/rank.coffee
  resources/assets/lib/interfaces/user-statistics-json.ts
  resources/assets/lib/profile-page/rank.tsx
Labels: area:user-profile, type:code-quality

#8321 Enable no scope mod for osu!catch
  app/Libraries/Multiplayer/Mod.php
Labels: area:multiplayer, area:scoring

#8322 Ensure unique username and email in tests
  database/factories/UserFactory.php
Labels: type:testing

#8324 Add notice for profile page top ranks (scores) section
  .env.example
  config/osu.php
  resources/assets/coffee/react/profile-page.coffee
  resources/assets/coffee/react/profile-page/main.coffee
  resources/assets/coffee/react/profile-page/top-ranks.coffee
  resources/assets/less/bem/wiki-notice.less
  resources/views/users/show.blade.php
Labels: area:user-profile

#8323 Convert PlayTime component to typescript
  resources/assets/coffee/react/profile-page/detail-mobile.coffee
  resources/assets/coffee/react/profile-page/detail.coffee
  resources/assets/coffee/react/profile-page/play-time.coffee
  resources/assets/lib/interfaces/user-statistics-json.ts
  resources/assets/lib/profile-page/play-time.tsx
Labels: area:user-profile

#8296 Typescript Loading Overlay utility
  resources/assets/app.ts
  resources/assets/coffee/_classes/forum-topic-watch-ajax.coffee
  resources/assets/coffee/_classes/forum.coffee
  resources/assets/coffee/_classes/loading-overlay.coffee
  resources/assets/coffee/main.coffee
  resources/assets/coffee/react/beatmap-discussions/discussion.coffee
  resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
  resources/assets/coffee/react/beatmap-discussions/new-reply.coffee
  resources/assets/coffee/react/beatmap-discussions/nominations.coffee
  resources/assets/coffee/react/profile-page/main.coffee
  resources/assets/coffee/ujs-common.coffee
  resources/assets/lib/beatmap-discussions/love-beatmap-modal.tsx
  resources/assets/lib/globals.d.ts
  resources/assets/lib/profile-page/user-page-editor.tsx
  resources/assets/lib/store-checkout.coffee
  resources/assets/lib/store-xsolla.coffee
  resources/assets/lib/store.ts
  resources/assets/lib/utils/loading-overlay.ts
Labels: type:code-quality

#8325 Handle per-mode rank history offset
  app/Models/Count.php
  app/Models/RankHistory.php
  database/seeders/ModelSeeders/MiscSeeder.php
Labels: area:user-profile

#8310 Refactor Friend Button
  resources/assets/coffee/react/_components/friend-button.coffee
  resources/assets/coffee/react/modding-profile/detail-bar.coffee
  resources/assets/coffee/react/profile-page/detail-bar.coffee
  resources/assets/lib/coffee-modules.d.ts
  resources/assets/lib/components/friend-button.tsx
  resources/assets/lib/interfaces/user-extended-json.ts
  resources/assets/lib/profile-page/detail-bar-buttons.tsx
  resources/assets/lib/quick-search/user.tsx
  resources/assets/lib/register-components.coffee
  resources/assets/lib/user-card.tsx
Labels: type:code-quality

#8311 Typescript profile page statistics
  resources/assets/coffee/react/profile-page/header.coffee
  resources/assets/coffee/react/profile-page/stats.coffee
  resources/assets/lib/interfaces/user-statistics-json.ts
  resources/assets/lib/profile-page/stats.tsx
Labels: type:code-quality

#8330 Refactor Block Button
  resources/assets/coffee/react/_components/block-button.coffee
  resources/assets/coffee/react/modding-profile/main.coffee
  resources/assets/coffee/react/profile-page/main.coffee
  resources/assets/lib/coffee-modules.d.ts
  resources/assets/lib/components/block-button.tsx
  resources/assets/lib/components/friend-button.tsx
  resources/assets/lib/profile-page/extra-menu.tsx
  resources/assets/lib/register-components.coffee
  resources/assets/lib/user-card-brick.tsx
  resources/assets/lib/user-card.tsx
  resources/assets/lib/user-profile-container.tsx
Labels: type:code-quality

#8326 Update d3 library
  package.json
  resources/assets/coffee/_classes/changelog-chart.coffee
  resources/assets/coffee/_classes/fancy-chart.coffee
  resources/assets/coffee/_classes/line-chart.coffee
  yarn.lock
Labels: type:code-quality

#8307 Typescript top scores section of profile page
  resources/assets/coffee/react/profile-page/main.coffee
  resources/assets/coffee/react/profile-page/top-ranks.coffee
  resources/assets/lib/interfaces/user-json.ts
  resources/assets/lib/profile-page/extra-page-props.ts
  resources/assets/lib/profile-page/top-scores.tsx
Labels: type:code-quality

#8306 Migrate url helpers to typescript
  resources/assets/coffee/_classes/beatmap-discussion-helper.coffee
  resources/assets/coffee/osu_common.coffee
  resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
  resources/assets/coffee/react/beatmap-discussions/nominations.coffee
  resources/assets/coffee/react/beatmap-discussions/system-post.coffee
  resources/assets/coffee/react/beatmaps/search-filter.coffee
  resources/assets/coffee/react/modding-profile/main.coffee
  resources/assets/coffee/react/mp-history/event.coffee
  resources/assets/coffee/react/profile-page/main.coffee
  resources/assets/coffee/turbolinks-overrides.coffee
  resources/assets/lib/beatmap-discussions/autolink-plugin.ts
  resources/assets/lib/beatmap-discussions/editor-discussion-component.tsx
  resources/assets/lib/beatmap-discussions/event.tsx
  resources/assets/lib/globals.d.ts
  resources/assets/lib/import-shims.coffee
  resources/assets/lib/models/chat/message.ts
  resources/assets/lib/notifications/notification-controller.ts
  resources/assets/lib/ranking-filter.tsx
  resources/assets/lib/spotlight-select-options.coffee
  resources/assets/lib/user-list.tsx
  resources/assets/lib/utils/beatmapset-discussion-helper.ts
  resources/assets/lib/utils/url.ts
  tests/karma/osu_common.spec.ts
  tests/karma/utils/url.spec.ts
Labels: type:code-quality

#8308 Typescript page tab in profile page
  resources/assets/coffee/react/modding-profile/main.coffee
  resources/assets/coffee/react/profile-page/extra-tab.coffee
  resources/assets/coffee/react/profile-page/main.coffee
  resources/assets/lib/interfaces/user-extended-json.ts
  resources/assets/lib/profile-page/extra-tab.tsx
Labels: type:code-quality

#8327 Always expand profile page score detail on mobile
  resources/assets/less/bem/play-detail.less
  resources/assets/lib/play-detail.tsx
Labels: area:user-profile

#8333 Convert RankCount to typescript
  resources/assets/coffee/react/profile-page/detail.coffee
  resources/assets/coffee/react/profile-page/header.coffee
  resources/assets/coffee/react/profile-page/rank-count.coffee
  resources/assets/lib/interfaces/user-statistics-json.ts
  resources/assets/lib/profile-page/rank-count.tsx
Labels: area:user-profile

#8334 Convert RankChart to typescript
  resources/assets/coffee/react/profile-page/detail-mobile.coffee
  resources/assets/coffee/react/profile-page/detail.coffee
  resources/assets/coffee/react/profile-page/rank-chart.coffee
  resources/assets/lib/globals.d.ts
  resources/assets/lib/interfaces/rank-history-json.ts
  resources/assets/lib/interfaces/user-statistics-json.ts
  resources/assets/lib/profile-page/rank-chart.tsx
Labels: area:user-profile, type:code-quality

#8341 Typescript Beatmap Playcount
  resources/assets/coffee/react/profile-page/beatmap-playcount.coffee
  resources/assets/coffee/react/profile-page/historical.coffee
  resources/assets/lib/interfaces/beatmap-playcount-json.ts
  resources/assets/lib/profile-page/beatmap-playcount.tsx
Labels: area:user-profile, type:code-quality

#8331 Reorganise traits for model
  app/Models/ArtistTrack.php
  app/Models/BeatmapDiscussionPost.php
  app/Models/Beatmapset.php
  app/Models/Build.php
  app/Models/Comment.php
  app/Models/Forum/Post.php
  app/Models/LegacyMatch/LegacyMatch.php
  app/Models/LegacyMatch/Score.php
  app/Models/Model.php
  app/Models/Multiplayer/PlaylistItemUserHighScore.php
  app/Models/Multiplayer/Room.php
  app/Models/Multiplayer/UserScoreAggregate.php
  app/Models/NewsPost.php
  app/Models/Score/Best/Model.php
  app/Models/Score/Model.php
  app/Models/Traits/CommentableDefaults.php
  app/Models/Traits/Es/ArtistTrackSearch.php
  app/Models/Traits/Es/BaseDbIndexable.php
  app/Models/Traits/Es/BaseIndexable.php
  app/Models/Traits/Es/BeatmapsetSearch.php
  app/Models/Traits/Es/ForumPostSearch.php
  app/Models/Traits/Es/UserSearch.php
  app/Models/Traits/Es/WikiPageSearch.php
  app/Models/Traits/Reportable.php
  app/Models/Traits/Scoreable.php
  app/Models/Traits/UserAvatar.php
  app/Models/Traits/UserScoreable.php
  app/Models/Traits/UserStore.php
  app/Models/Traits/WithDbCursorHelper.php
  app/Models/User.php
  app/Models/Wiki/Page.php
  app/Traits/MacroableModel.php
Labels: type:code-quality

#8336 Add web support for multiplayer queue modes
  app/Models/Multiplayer/PlaylistItem.php
  app/Models/Multiplayer/Room.php
  app/Transformers/Multiplayer/PlaylistItemTransformer.php
  app/Transformers/Multiplayer/RoomTransformer.php
  database/factories/Multiplayer/PlaylistItemFactory.php
  database/migrations/2021_11_17_073841_add_queue_mode_to_multiplayer_rooms.php
  database/migrations/2021_11_17_074221_add_owner_id_to_multiplayer_playlist_items.php
  tests/Controllers/Multiplayer/RoomsControllerTest.php
Labels: area:multiplayer

#8348 Update queue mode names
  app/Models/Multiplayer/Room.php
  database/migrations/2021_11_17_073841_add_queue_mode_to_multiplayer_rooms.php
Labels: area:multiplayer

#8355 Move EventJson to its own file
  resources/assets/lib/interfaces/event-json.ts
  resources/assets/lib/profile-page/parse-event.tsx
  resources/assets/lib/profile-page/recent-activity.tsx
  resources/assets/lib/utils/switch-never.ts
Labels: type:code-quality

#8362 Cast BeatmapsetEvent search type param to string
  app/Models/BeatmapsetEvent.php
Labels: area:beatmap-discussions

#8357 Convert profile page detail bar to typescript
  resources/assets/coffee/react/modding-profile/detail-bar.coffee
  resources/assets/coffee/react/modding-profile/detail.coffee
  resources/assets/coffee/react/modding-profile/header.coffee
  resources/assets/coffee/react/profile-page/detail-bar.coffee
  resources/assets/coffee/react/profile-page/detail.coffee
  resources/assets/coffee/react/profile-page/header.coffee
  resources/assets/lib/interfaces/user-extended-json.ts
  resources/assets/lib/profile-page/detail-bot.tsx
  resources/assets/lib/profile-page/detail.tsx
  resources/assets/lib/user-multiplayer-index/header.tsx
Labels: area:user-profile, type:code-quality

#8369 Remove unused Beatmapset function
  app/Models/Beatmapset.php
Labels: type:code-quality

#8371 Fix profile page detail class name
  resources/assets/lib/profile-page/detail.tsx
Labels: area:user-profile

#8377 Fix params target_id cast
  app/Http/Controllers/Chat/ChannelsController.php
Labels: type:code-quality, area:chat

#8373 Move gameModes to GameMode interface file
  resources/assets/coffee/react/profile-page/game-mode-switcher.coffee
  resources/assets/coffee/react/profile-page/main.coffee
  resources/assets/lib/interfaces/game-mode.ts
  resources/assets/lib/utils/beatmap-helper.ts
Labels: type:code-quality

#8383 Remove User lastPlayed function
  app/Models/User.php
Labels: type:code-quality

#8365 Remove global current user from typescript
  resources/assets/coffee/_classes/current-user-observer.coffee
  resources/assets/lib/admin-menu.tsx
  resources/assets/lib/app-deps.ts
  resources/assets/lib/beatmap-discussions/editor.tsx
  resources/assets/lib/beatmaps/beatmapset-search-controller.ts
  resources/assets/lib/beatmapsets-show/nsfw-warning.tsx
  resources/assets/lib/chat/conversation-view.tsx
  resources/assets/lib/chat/input-box.tsx
  resources/assets/lib/chat/message-group.tsx
  resources/assets/lib/core/user/user-login.ts
  resources/assets/lib/follow-toggle.tsx
  resources/assets/lib/follow-user-mapping-button.tsx
  resources/assets/lib/follows-comment.tsx
  resources/assets/lib/follows-comment/main.tsx
  resources/assets/lib/follows-mapping.tsx
  resources/assets/lib/follows-mapping/main.tsx
  resources/assets/lib/friends-index.tsx
  resources/assets/lib/friends-index/main.tsx
  resources/assets/lib/globals.d.ts
  resources/assets/lib/header-v4.tsx
  resources/assets/lib/models/chat/channel.ts
  resources/assets/lib/models/comment.ts
  resources/assets/lib/models/notification.ts
  resources/assets/lib/osu-core.ts
  resources/assets/lib/profile-page/header-info.tsx
  resources/assets/lib/profile-page/links.tsx
  resources/assets/lib/quick-search-button.tsx
  resources/assets/lib/ranking-filter.tsx
  resources/assets/lib/sort.tsx
  resources/assets/lib/stores/channel-store.ts
  resources/assets/lib/user-card-tooltip.tsx
  resources/assets/lib/user-card.tsx
  resources/assets/lib/utils/beatmap-helper.ts
  resources/assets/lib/utils/score-helper.ts
Labels: type:code-quality

#8367 Documentation fixes
  resources/views/docs/_structures/beatmap.md
  resources/views/docs/_structures/beatmapset_compact.md
  resources/views/docs/_structures/beatmapset_discussion.md
  resources/views/docs/_structures/beatmapset_discussion_post.md
  resources/views/docs/_structures/forum_post.md
  resources/views/docs/_structures/forum_topic.md
  resources/views/docs/_structures/kudosu_history.md
  resources/views/docs/_structures/user_compact.md
Labels: type:api

#8386 Fix displayed channel messages being reset when opening new PM
  app/Http/Controllers/ChatController.php
  app/Models/Chat/Channel.php
  resources/assets/lib/chat/channel-join-event.ts
  resources/assets/lib/chat/chat-state-store.ts
  resources/assets/lib/chat/chat-worker.ts
Labels: area:chat, priority:1
