Repository ppy/osu-web, pull requests merged in 2021-09, with the labels that each got.

#8074 Show v2 mod badge
  public/images/badges/mods/mod_v2.png
  public/images/badges/mods/mod_v2@2x.png
  resources/assets/less/bem/mod.less
Labels: type:design

#8070 Fix cursor handling for news listing page
  app/Http/Controllers/NewsController.php
  app/Models/NewsPost.php
  resources/assets/coffee/osu_common.coffee
  resources/assets/lib/globals.d.ts
  resources/assets/lib/news-index.tsx
  resources/assets/lib/news-index/main.tsx
  resources/views/news/index.blade.php
  tests/karma/osu_common.spec.ts
Labels: type:api, area:news

#8014 Refactor chat presence response
  app/Http/Controllers/Chat/ChannelsController.php
  app/Http/Controllers/Chat/ChatController.php
  app/Http/Controllers/ChatController.php
  app/Libraries/Chat.php
  app/Libraries/OsuAuthorize.php
  app/Libraries/UserChannelList.php
  app/Models/Chat/Channel.php
  app/Models/Chat/UserChannel.php
  app/Transformers/Chat/ChannelTransformer.php
  database/factories/Chat/ChannelFactory.php
  resources/assets/lib/chat.tsx
  resources/assets/lib/chat/chat-api-responses.ts
  resources/assets/lib/chat/conversation-view.tsx
  resources/assets/lib/chat/input-box.tsx
  resources/assets/lib/models/chat/channel.ts
  resources/assets/lib/stores/channel-store.ts
  resources/views/docs/_structures/chat_channel.md
  resources/views/docs/_structures/current_user_attributes.md
  resources/views/docs/info.blade.php
  tests/Controllers/Chat/ChannelsControllerTest.php
  tests/Models/Chat/ChannelTest.php
Labels: area:chat

#8075 Reduce query for chat page
  app/Http/Controllers/Chat/ChatController.php
  app/Libraries/UserChannelList.php
  app/Models/Chat/Message.php
Labels: type:performance, area:chat

#8053 Convert user profile account standing page to TypeScript
  app/Transformers/UserAccountHistoryTransformer.php
  resources/assets/coffee/react/profile-page/account-standing.coffee
  resources/assets/coffee/react/profile-page/main.coffee
  resources/assets/lib/interfaces/user-account-history-json.ts
  resources/assets/lib/interfaces/user-json.ts
  resources/assets/lib/profile-page/account-standing.tsx
  resources/assets/lib/profile-page/extra-page-props.ts
  resources/lang/en/users.php
  resources/views/docs/_structures/user_compact.md
Labels: area:user-profile, type:code-quality, javascript

#8078 Refresh timeago on datetime attribute update
  resources/assets/lib/core/timeago.ts
Labels: type:ux, type:reliability

#8061 Convert user profile achievement badge component to TypeScript
  resources/assets/coffee/react/profile-page/achievement-badge.coffee
  resources/assets/coffee/react/profile-page/medals.coffee
  resources/assets/coffee/react/profile-page/recent-activity.coffee
  resources/assets/less/bem/qtip.less
  resources/assets/less/bem/tooltip-achievement.less
  resources/assets/lib/interfaces/achievement-json.ts
  resources/assets/lib/interfaces/user-achievement-json.ts
  resources/assets/lib/profile-page/achievement-badge-icon.tsx
  resources/assets/lib/profile-page/achievement-badge-popup.tsx
  resources/assets/lib/profile-page/achievement-badge.tsx
  resources/assets/lib/utils/css.ts
Labels: area:user-profile, type:performance, javascript

#7609 Improve featured artist beatmaps visibility
  app/Http/Controllers/ArtistTracksController.php
  app/Http/Controllers/ArtistsController.php
  app/Libraries/Search/BeatmapsetQueryParser.php
  app/Libraries/Search/BeatmapsetSearch.php
  app/Libraries/Search/BeatmapsetSearchParams.php
  app/Libraries/Search/BeatmapsetSearchRequestParams.php
  app/Models/Artist.php
  app/Models/ArtistTrack.php
  app/Models/Beatmapset.php
  app/Transformers/BeatmapsetCompactTransformer.php
  config/schemas/beatmaps.json
  database/factories/ArtistTrackFactory.php
  database/migrations/2021_08_30_153214_add_track_id_to_beatmapsets.php
  resources/assets/coffee/react/beatmap-discussions/header.coffee
  resources/assets/coffee/react/beatmaps/search-filter.coffee
  resources/assets/coffee/react/beatmapset-page/header.coffee
  resources/assets/less/bem-index.less
  resources/assets/less/bem/beatmapset-badge.less
  resources/assets/less/bem/beatmapsets-search-filter.less
  resources/assets/lib/beatmapset-panel.tsx
  resources/assets/lib/interfaces/beatmapset-json.ts
  resources/lang/en/artist.php
  resources/lang/en/beatmaps.php
  resources/lang/en/beatmapsets.php
  routes/web.php
  tests/Browser/SanityTest.php
Labels: area:beatmap-listing

#8081 Rename featured artist track osu! exclusive to osu! original
  resources/assets/coffee/react/_components/tracklist-track.coffee
  resources/lang/en/artist.php
Labels: type:design, area:featured-artist

#8082 Existence check for featured artist maps instead of full count
  app/Http/Controllers/ArtistsController.php
Labels: type:performance, area:featured-artist

#8095 Fix wiki infobox padding
  resources/assets/less/bem/osu-md.less
Labels: type:design, area:wiki

#8096 Limit reportable beatmap states
  app/Models/UserReport.php
  resources/assets/coffee/react/beatmapset-page/header.coffee
  resources/lang/en/model_validation.php
Labels: area:beatmap-info

#8079 Combine styling for audio player's play button
  resources/assets/coffee/react/_components/track-preview.coffee
  resources/assets/coffee/react/beatmapset-page/stats.coffee
  resources/assets/less/bem-index.less
  resources/assets/less/bem/audio-player.less
  resources/assets/less/bem/beatmapset-panel.less
  resources/assets/less/bem/beatmapset-stats.less
  resources/assets/less/bem/play-button.less
  resources/assets/less/bem/tracklist.less
  resources/assets/lib/beatmapset-panel.tsx
  resources/assets/lib/core/osu-audio/main.ts
Labels: type:code-quality

#8099 Split chat-related json exports into separate modules
  resources/assets/lib/chat.tsx
  resources/assets/lib/chat/chat-api-responses.ts
  resources/assets/lib/chat/chat-api.ts
  resources/assets/lib/interfaces/chat/channel-json.ts
  resources/assets/lib/interfaces/chat/chat-updates-json.ts
  resources/assets/lib/interfaces/chat/message-json.ts
  resources/assets/lib/models/chat/channel.ts
  resources/assets/lib/models/chat/message.ts
  resources/assets/lib/stores/channel-store.ts
Labels: type:code-quality, area:chat

#8080 Refactor TrackPreview component
  resources/assets/coffee/react/_components/track-preview.coffee
  resources/assets/coffee/react/_components/tracklist-track.coffee
  resources/assets/coffee/react/contest-voting/entry.coffee
  resources/assets/less/bem-index.less
  resources/assets/less/bem/play-button.less
  resources/assets/less/bem/track-cover-preview.less
  resources/assets/less/bem/tracklist.less
  resources/assets/lib/track-preview.tsx
Labels: type:code-quality, area:contests, javascript

#8100 Fix MobX `@computed` usage
  resources/assets/lib/app-deps.ts
  resources/assets/lib/chat.tsx
  resources/assets/lib/chat/conversation-view.tsx
  resources/assets/lib/chat/message-group.tsx
  resources/assets/lib/core/react-turbolinks.ts
  resources/assets/lib/stores/channel-store.ts
Labels: type:reliability

#8104 Update php side of class modifiers helper
  app/helpers.php
  tests/HelpersTest.php
Labels: type:code-quality, php

#8106 Remove green button css
  resources/assets/less/bem/btn-osu-big.less
Labels: type:code-quality

#8105 Home button cleanup
  resources/assets/less/bem/btn-home.less
  resources/assets/less/colors.less
  resources/views/home/_user_giant_button.blade.php
  resources/views/home/user.blade.php
Labels: type:design, type:code-quality, area:dashboard

#8103 Tidy up some chat-related classes
  app/Http/Controllers/Chat/Channels/MessagesController.php
  app/Http/Controllers/Chat/ChatController.php
  app/Http/Controllers/LegacyInterOpController.php
  app/Libraries/Chat.php
  app/Models/Chat/Channel.php
Labels: type:code-quality, area:chat

#8108 Convert BigButton component to TypeScript
  resources/assets/coffee/react/_components/big-button.coffee
  resources/assets/coffee/react/_components/comment-editor.coffee
  resources/assets/coffee/react/beatmap-discussions/header.coffee
  resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
  resources/assets/coffee/react/beatmap-discussions/new-reply.coffee
  resources/assets/coffee/react/beatmap-discussions/nominations.coffee
  resources/assets/coffee/react/beatmap-discussions/post.coffee
  resources/assets/coffee/react/beatmap-discussions/subscribe.coffee
  resources/assets/coffee/react/beatmapset-page/header.coffee
  resources/assets/coffee/react/beatmapset-page/hype.coffee
  resources/assets/lib/beatmap-discussions/nominator.tsx
  resources/assets/lib/big-button.tsx
  resources/assets/lib/chat/input-box.tsx
  resources/assets/lib/coffee-modules.d.ts
  resources/assets/lib/oauth/authorized-client.tsx
  resources/assets/lib/oauth/own-client.tsx
  resources/assets/lib/oauth/own-clients.tsx
Labels: type:code-quality

#8097 Globally add HasFactory
  app/Models/ArtistTrack.php
  app/Models/BeatmapsetNomination.php
  app/Models/Model.php
Labels: type:code-quality

#8124 Fix ChannelTest namespace
  phpcs.xml
  tests/Models/Chat/ChannelTest.php
Labels: type:code-quality

#8127 Remove unrelated file in translation directory
  resources/lang/de/todo.md
Labels: type:code-quality

#8128 Fix oauth error message
  app/Exceptions/Handler.php
Labels: type:api

#8117 Show custom notice on stub pages of the wiki
  app/Models/Wiki/Page.php
  resources/lang/en/wiki.php
  resources/views/wiki/_notice.blade.php
Labels: area:wiki

#8141 Remove unused views
  resources/views/objects/bat-tools.blade.php
  resources/views/users/logout.blade.php
Labels: type:code-quality

#8110 Support selectively excluding data from chat updates
  app/Http/Controllers/Chat/ChatController.php
  resources/views/docs/_structures/user_silence.md
Labels: area:chat

#8120 Update Solo Score table structure
  app/Http/Controllers/Solo/ScoresController.php
  app/Libraries/ScoreCheck.php
  app/Models/Solo/Score.php
  app/Transformers/Solo/ScoreTransformer.php
  database/migrations/2021_09_15_065842_create_new_score_tables.php
  tests/Controllers/Solo/ScoresControllerTest.php
  tests/Models/Solo/ScoreTest.php
Labels: area:scoring

#8149 Increase max blocked users to double the previous amount
  app/Models/User.php
Labels: area:user-profile

#8151 Label routes requiring a user in API docs
  app/Libraries/ApidocRouteHelper.php
  resources/views/docs/info.blade.php
  resources/views/vendor/scribe/index.blade.php
  resources/views/vendor/scribe/partials/endpoint.blade.php
Labels: type:documentation

#8145 Remove unused analyzer from schemas
  config/schemas/beatmaps.json
  config/schemas/wiki_page.json
Labels: area:search, type:code-quality

#8098 Index Featured Artist tracks to ElasticSearch
  app/Console/Commands/EsIndexDocuments.php
  app/Libraries/Elasticsearch/Utils/ComparatorParam.php
  app/Libraries/Elasticsearch/Utils/SearchAfterParam.php
  app/Libraries/Search/ArtistTrackSearch.php
  app/Libraries/Search/ArtistTrackSearchParams.php
  app/Libraries/Search/ArtistTrackSearchParamsFromRequest.php
  app/Libraries/Search/BeatmapsetQueryParser.php
  app/Libraries/Search/BeatmapsetSearchRequestParams.php
  app/Models/Artist.php
  app/Models/ArtistTrack.php
  app/Models/Elasticsearch/ArtistTrackTrait.php
  app/Traits/EsIndexableModel.php
  app/helpers.php
  config/schemas/artist_tracks.json
Labels: area:search, area:featured-artist

#8143 Use correct transaction id for logging paypal discrepencies
  app/Libraries/Payments/PaypalPaymentProcessor.php
Labels: area:store

#8150 Allow chat bots to send messages to users regardless of block or friend settings
  app/Libraries/OsuAuthorize.php
  app/Models/Chat/Channel.php
  tests/Libraries/ChatTest.php
  tests/Models/Chat/ChannelTest.php
Labels: area:chat

#8155 Fix multiplayer score validation
  app/Models/Multiplayer/Score.php
Labels: type:api, area:multiplayer

#8156 Update placeholder image for test
  tests/Libraries/bbcode_examples/basic_img.base.txt
  tests/Libraries/bbcode_examples/basic_img.db.txt
  tests/Libraries/bbcode_examples/basic_img.html
Labels: type:testing

#8158 Fix disappearing chat
  app/Http/Controllers/Chat/ChatController.php
Labels: area:chat

#8144 Fix narrow user card list layout
  resources/assets/less/bem/user-card.less
  resources/assets/lib/user-card.tsx
Labels: area:user-profile

#8164 Update Laravel
  composer.lock
Labels: type:code-quality

#8165 Remove redundant Eloquent model guard setting
  app/Models/Chat/Message.php
  app/Models/Chat/UserChannel.php
  app/Models/Score/Model.php
  app/Models/Spotlight.php
Labels: type:code-quality
