Repository ppy/osu-web, pull requests merged in 2021-05, with the labels that each got.

#7553 Update translations from crowdin
  resources/lang/de/errors.php
  resources/lang/es/errors.php
  resources/lang/fr/comments.php
  resources/lang/fr/errors.php
  resources/lang/id/errors.php
  resources/lang/it/beatmap_discussions.php
  resources/lang/it/beatmapsets.php
  resources/lang/it/chat.php
  resources/lang/it/errors.php
  resources/lang/it/forum.php
  resources/lang/it/model_validation.php
  resources/lang/ko/errors.php
  resources/lang/pt/errors.php
  resources/lang/ru/errors.php
  resources/lang/tr/beatmappacks.php
  resources/lang/tr/beatmapsets.php
  resources/lang/tr/errors.php
  resources/lang/tr/page_title.php
  resources/lang/uk/accounts.php
  resources/lang/uk/artist.php
  resources/lang/uk/authorization.php
  resources/lang/uk/beatmapset_watches.php
  resources/lang/uk/errors.php
  resources/lang/uk/layout.php
  resources/lang/zh-tw/api.php
  resources/lang/zh-tw/authorization.php
  resources/lang/zh-tw/beatmappacks.php
  resources/lang/zh-tw/beatmapset_events.php
  resources/lang/zh-tw/beatmapsets.php
  resources/lang/zh-tw/errors.php
  resources/lang/zh-tw/mail.php
  resources/lang/zh-tw/page_title.php
  resources/lang/zh-tw/store.php
  resources/lang/zh/errors.php
Labels: type:localisation

#7542 Use wiki branch config everywhere
  app/Libraries/GithubImporter.php
  app/Libraries/OsuWiki.php
  app/Models/NewsPost.php
  app/Models/Wiki/Page.php
Labels: area:wiki, type:code-quality

#7573 Fix getting last item for cursor
  app/Libraries/DbCursorHelper.php
Labels: type:api

#7535 Convert Timeago to TypeScript
  package.json
  resources/assets/coffee/_classes/timeago.coffee
  resources/assets/coffee/main.coffee
  resources/assets/lib/osu-core.ts
  resources/assets/lib/timeago.ts
  yarn.lock
Labels: type:code-quality

#7536 Reduce image lazy-loading related works
  resources/assets/lib/osu-layzr.ts
Labels: type:performance

#7537 Don't reobserve on page load
  resources/assets/lib/localtime.ts
  resources/assets/lib/osu-audio/main.ts
Labels: type:code-quality

#7574 Remove duplicate commentable meta objects
  app/Libraries/CommentBundle.php
  app/Models/Beatmapset.php
  app/Models/Build.php
  app/Models/NewsPost.php
  app/Traits/CommentableDefaults.php
Labels: type:api

#7544 Fix markdown TOC and header ID generation
  app/Libraries/Markdown/OsuMarkdownProcessor.php
Labels: area:wiki

#7539 Fix display of news articles with first img tag at top level
  resources/assets/lib/news-show/main.tsx
Labels: area:wiki

#7546 Add infobox support for wiki
  app/Libraries/Markdown/Indexing/RendererExtension.php
  app/Libraries/Markdown/OsuMarkdown.php
  app/Libraries/Markdown/OsuMarkdownProcessor.php
  app/Libraries/Markdown/StyleBlock/Element.php
  app/Libraries/Markdown/StyleBlock/Extension.php
  app/Libraries/Markdown/StyleBlock/Parser.php
  app/Libraries/Markdown/StyleBlock/Renderer.php
  resources/assets/less/bem/osu-md.less
  tests/Libraries/Markdown/IndexingProcessorTest.php
  tests/Libraries/Markdown/ProcessorTest.php
  tests/Libraries/Markdown/html_markdown_examples/style_block.html
  tests/Libraries/Markdown/html_markdown_examples/style_block.md
  tests/Libraries/Markdown/html_markdown_examples/style_block_invalid_class.html
  tests/Libraries/Markdown/html_markdown_examples/style_block_invalid_class.md
  tests/Libraries/Markdown/html_markdown_examples/style_block_invalid_space.html
  tests/Libraries/Markdown/html_markdown_examples/style_block_invalid_space.md
  tests/Libraries/Markdown/html_markdown_examples/style_block_nested.html
  tests/Libraries/Markdown/html_markdown_examples/style_block_nested.md
  tests/Libraries/Markdown/html_markdown_examples/style_block_unclosed.html
  tests/Libraries/Markdown/html_markdown_examples/style_block_unclosed.md
  tests/Libraries/Markdown/indexable_markdown_examples/header.md
  tests/Libraries/Markdown/indexable_markdown_examples/header.txt
  tests/Libraries/Markdown/indexable_markdown_examples/html.md
  tests/Libraries/Markdown/indexable_markdown_examples/html.txt
  tests/Libraries/Markdown/indexable_markdown_examples/link.md
  tests/Libraries/Markdown/indexable_markdown_examples/link.txt
  tests/Libraries/Markdown/indexable_markdown_examples/list.md
  tests/Libraries/Markdown/indexable_markdown_examples/list.txt
  tests/Libraries/Markdown/indexable_markdown_examples/newline.md
  tests/Libraries/Markdown/indexable_markdown_examples/newline.txt
  tests/Libraries/Markdown/indexable_markdown_examples/style_block.md
  tests/Libraries/Markdown/indexable_markdown_examples/style_block.txt
  tests/Libraries/Markdown/indexable_markdown_examples/table.md
  tests/Libraries/Markdown/indexable_markdown_examples/table.txt
Labels: area:wiki

#7580 Display entry name on result for external contest
  resources/assets/coffee/react/contest-voting/art-entry.coffee
  resources/assets/less/bem/contest-art-entry.less
  resources/assets/less/bem/contest.less
Labels: type:ux

#7587 Fix contest art display in "show voted" filter mode
  resources/assets/coffee/react/contest-voting/art-entry-list.coffee
  resources/assets/coffee/react/contest-voting/art-entry.coffee
Labels: area:contests, type:ux

#7588 Fix art contest page style
  resources/assets/coffee/react/contest-voting/art-entry.coffee
  resources/assets/less/bem/contest-art-entry.less
  resources/assets/less/bem/contest.less
Labels: area:contests, type:reliability

#7590 Workaround getting size of contest entry missing image
  app/Transformers/ContestEntryTransformer.php
Labels: area:contests

#7517 Allow changing beatmap difficulty owner
  app/Http/Controllers/BeatmapsController.php
  app/Jobs/Notifications/BeatmapOwnerChange.php
  app/Libraries/OsuAuthorize.php
  app/Models/Beatmap.php
  app/Models/BeatmapDiscussion.php
  app/Models/BeatmapsetEvent.php
  app/Models/Notification.php
  app/Models/UserNotificationOption.php
  app/Transformers/BeatmapCompactTransformer.php
  app/Transformers/BeatmapsetCompactTransformer.php
  database/migrations/2021_04_26_075454_add_beatmap_owner_change_to_beatmapset_events.php
  resources/assets/coffee/react/beatmap-discussions-history/main.coffee
  resources/assets/coffee/react/beatmap-discussions/discussion.coffee
  resources/assets/coffee/react/beatmap-discussions/header.coffee
  resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
  resources/assets/coffee/react/beatmap-discussions/nominations.coffee
  resources/assets/coffee/react/modding-profile/discussions.coffee
  resources/assets/less/bem-index.less
  resources/assets/less/bem/beatmap-discussions-header-top.less
  resources/assets/less/bem/beatmap-owner-editor.less
  resources/assets/less/bem/beatmaps-owner-editor.less
  resources/assets/less/bem/beatmapset-event.less
  resources/assets/lib/beatmap-discussions/beatmap-owner-editor.tsx
  resources/assets/lib/beatmap-discussions/beatmaps-owner-editor.tsx
  resources/assets/lib/beatmap-discussions/event.tsx
  resources/assets/lib/beatmap-discussions/guest-group.ts
  resources/assets/lib/interfaces/beatmap-json.ts
  resources/assets/lib/models/notification/beatmap-owner-change-notification.ts
  resources/assets/lib/notification-maps/category.ts
  resources/assets/lib/notification-maps/icons.ts
  resources/assets/lib/notification-maps/message.ts
  resources/assets/lib/notification-maps/url.ts
  resources/assets/lib/utils/html.ts
  resources/lang/en/accounts.php
  resources/lang/en/beatmap_discussions.php
  resources/lang/en/beatmaps.php
  resources/lang/en/beatmapset_events.php
  resources/lang/en/notifications.php
  routes/web.php
  tests/Browser/BeatmapDiscussionPostsTest.php
  tests/Controllers/BeatmapDiscussionPostsControllerTest.php
  tests/Controllers/BeatmapsControllerTest.php
Labels: area:beatmap-discussions

#7610 Check user status when changing beatmap owner
  app/Libraries/OsuAuthorize.php
Labels: area:beatmap-discussions

#7612 Fix event colour in profile and listing page
  resources/assets/lib/beatmap-discussions/event.tsx
Labels: area:beatmap-discussions

#7613 Disallow nomination of beatmapset containing own beatmap
  app/Libraries/OsuAuthorize.php
  resources/assets/lib/beatmap-discussions/nominator.tsx
  tests/Controllers/BeatmapsetsControllerTest.php
Labels: area:beatmap-discussions

#7615 Add taiko swap mod
  app/Libraries/Multiplayer/Mod.php
Labels: area:multiplayer

#7614 Show correct guest badge in per-beatmap discussion replies
  resources/assets/coffee/react/beatmap-discussions/discussion.coffee
  resources/assets/coffee/react/beatmap-discussions/post.coffee
  resources/assets/lib/utils/beatmapset-discussion-helper.ts
Labels: area:beatmap-discussions

#7618 Fix guest badge check for discussions on modding profile page
  resources/assets/lib/utils/beatmapset-discussion-helper.ts
Labels: area:beatmap-discussions, area:user-profile

#7575 Mask negative notification count
  resources/assets/lib/chat-icon.tsx
  resources/assets/lib/main-notification-icon.tsx
  resources/assets/lib/notification-icon.tsx
  resources/assets/lib/register-components.coffee
  resources/views/layout/_header_mobile.blade.php
  resources/views/layout/_nav2.blade.php
Labels: area:notifications

#7581 Add beatmap playcount apidoc
  app/Http/Controllers/UsersController.php
  resources/docs/source/includes/_structures/beatmap_playcount.md
Labels: type:documentation

#7619 Fix hiding mark as read button nearby "show more" button
  resources/assets/lib/notification-widget/item-group.tsx
Labels: area:notifications, type:ux

#7592 Centralised user preferences handling
  app/Models/UserProfileCustomization.php
  resources/assets/coffee/_classes/beatmapset-filter.coffee
  resources/assets/coffee/_classes/forum.coffee
  resources/assets/coffee/react/_components/comment.coffee
  resources/assets/coffee/react/_components/comments-manager.coffee
  resources/assets/coffee/react/_components/comments.coffee
  resources/assets/coffee/react/beatmapset-page/main.coffee
  resources/assets/coffee/react/profile-page/detail-bar.coffee
  resources/assets/coffee/react/profile-page/detail.coffee
  resources/assets/lib/beatmapset-panel.tsx
  resources/assets/lib/beatmapsets-show/nsfw-warning.tsx
  resources/assets/lib/interfaces/current-user.ts
  resources/assets/lib/models/notification.ts
  resources/assets/lib/osu-audio/main.ts
  resources/assets/lib/osu-audio/settings.ts
  resources/assets/lib/osu-core.ts
  resources/assets/lib/stores/ui-state-store.ts
  resources/assets/lib/user-list.tsx
  resources/assets/lib/user-preferences.ts
  resources/assets/lib/utils/beatmap-helper.ts
  resources/assets/lib/utils/beatmapset-helper.ts
Labels: area:user-profile, type:code-quality

#7598 Typescript React Turbolinks
  resources/assets/coffee/react/admin/contest.coffee
  resources/assets/coffee/react/artist-page.coffee
  resources/assets/coffee/react/beatmap-discussions-history.coffee
  resources/assets/coffee/react/beatmap-discussions.coffee
  resources/assets/coffee/react/beatmapset-page.coffee
  resources/assets/coffee/react/changelog-build.coffee
  resources/assets/coffee/react/changelog-index.coffee
  resources/assets/coffee/react/comments-index.coffee
  resources/assets/coffee/react/comments-show.coffee
  resources/assets/coffee/react/contest-entry.coffee
  resources/assets/coffee/react/contest-voting.coffee
  resources/assets/coffee/react/modding-profile.coffee
  resources/assets/coffee/react/mp-history.coffee
  resources/assets/coffee/react/profile-page.coffee
  resources/assets/lib/account-edit.tsx
  resources/assets/lib/beatmaps.tsx
  resources/assets/lib/beatmapset-events.ts
  resources/assets/lib/beatmapset-events.tsx
  resources/assets/lib/chat.tsx
  resources/assets/lib/follows-comment.tsx
  resources/assets/lib/follows-mapping.tsx
  resources/assets/lib/friends-index.tsx
  resources/assets/lib/globals.d.ts
  resources/assets/lib/groups-show.tsx
  resources/assets/lib/news-index.ts
  resources/assets/lib/news-index.tsx
  resources/assets/lib/news-show.ts
  resources/assets/lib/news-show.tsx
  resources/assets/lib/notifications-index.tsx
  resources/assets/lib/osu-core.ts
  resources/assets/lib/react-turbolinks.coffee
  resources/assets/lib/react-turbolinks.ts
  resources/assets/lib/register-components.coffee
  resources/assets/lib/scores-show.tsx
  resources/assets/lib/user-card-tooltip.tsx
  webpack.unmix.js
Labels: type:code-quality

#7611 Ensure landing page footer sticks at the bottom
  resources/assets/less/bem/osu-layout.less
Labels: type:design

#7577 Potentially faster user group lookup
  app/Models/User.php
Labels: type:code-quality

#7622 Remove stray debug line
  resources/assets/lib/chat/input-box.tsx
Labels: type:code-quality

#7522 Include channel in response when joining channel
  app/Http/Controllers/Chat/ChannelsController.php
  app/Libraries/OsuAuthorize.php
  app/Models/Chat/Channel.php
  app/Models/Chat/UserChannel.php
  app/Models/Multiplayer/Room.php
  database/factories/Multiplayer/RoomFactory.php
  resources/assets/lib/chat.tsx
  resources/assets/lib/chat/chat-api.ts
  resources/assets/lib/chat/conversation-list.tsx
  resources/assets/lib/stores/channel-store.ts
  tests/Controllers/Chat/ChannelsControllerTest.php
  tests/Controllers/Chat/ChatControllerTest.php
Labels: area:chat

#7624 Fix user page not rendering for guest
  resources/assets/coffee/react/profile-page/detail-bar.coffee
Labels: area:user-profile, type:reliability

#7597 Clean up ShowMoreLink component
  resources/assets/coffee/react/_components/comment-show-more.coffee
  resources/assets/coffee/react/_components/comment.coffee
  resources/assets/coffee/react/beatmaps/paginator.coffee
  resources/assets/coffee/react/changelog-index/main.coffee
  resources/assets/coffee/react/mp-history/content.coffee
  resources/assets/coffee/react/profile-page/beatmaps.coffee
  resources/assets/coffee/react/profile-page/historical.coffee
  resources/assets/coffee/react/profile-page/kudosu.coffee
  resources/assets/coffee/react/profile-page/recent-activity.coffee
  resources/assets/coffee/react/profile-page/top-ranks.coffee
  resources/assets/lib/chat/conversation-view.tsx
  resources/assets/lib/landing-news.tsx
  resources/assets/lib/news-index/main.tsx
  resources/assets/lib/notification-widget/item-group.tsx
  resources/assets/lib/notification-widget/main.tsx
  resources/assets/lib/notifications-index/main.tsx
  resources/assets/lib/show-more-link.tsx
Labels: type:code-quality

#7630 Don't restrict year when no year is specified for news listing
  app/Http/Controllers/NewsController.php
Labels: area:news

#7629 Update short name for Relax mod
  app/Libraries/ModsHelper.php
  resources/assets/less/bem/mod.less
  resources/lang/en/beatmaps.php
Labels: type:ux

#7625 Add browser tests for guest
  tests/Browser/SanityTest.php
Labels: type:testing

#7545 Use brighter beatmap status colors
  resources/assets/less/layout.less
Labels: type:design

#7620 Don't show multiplayer channels in web chat
  resources/assets/lib/stores/channel-store.ts
Labels: area:chat

#7635 Rollback existing tooltip during page load instead
  resources/assets/coffee/_classes/tooltip-default.coffee
Labels: type:ux

#7616 Option for larger beatmap card size
  app/Http/Controllers/AccountController.php
  app/Models/UserProfileCustomization.php
  app/Transformers/BeatmapsetTransformer.php
  app/Transformers/UserCompactTransformer.php
  resources/assets/coffee/react/beatmaps/search-content.coffee
  resources/assets/less/bem/beatmaps-popup.less
  resources/assets/less/bem/beatmapset-panel.less
  resources/assets/less/bem/beatmapset-status.less
  resources/assets/less/bem/beatmapsets.less
  resources/assets/less/variables.less
  resources/assets/lib/beatmaps/beatmapset-card-size-selector.tsx
  resources/assets/lib/beatmaps/virtual-list-meta.ts
  resources/assets/lib/beatmapset-panel.tsx
  resources/assets/lib/beatmapset-panel/beatmaps-popup.tsx
  resources/assets/lib/beatmapsets/beatmapset-json.ts
  resources/assets/lib/interfaces/current-user.ts
Labels: area:beatmap-listing, type:design

#7644 Update to latest upstream xsolla sdk
  composer.json
  composer.lock
Labels: type:code-quality

#7633 Fix permission check for modding page and related
  app/Http/Controllers/Users/ModdingHistoryController.php
  app/Libraries/ModdingHistoryEventsBundle.php
  app/Models/BeatmapDiscussion.php
  app/Models/BeatmapDiscussionPost.php
  app/Models/BeatmapDiscussionVote.php
  app/Models/BeatmapsetEvent.php
Labels: area:beatmap-discussions

#7505 Slight profile page header refactoring
  app/Transformers/ProfileBannerTransformer.php
  app/Transformers/UserCompactTransformer.php
  app/Transformers/UserTransformer.php
  resources/assets/coffee/_classes/current-user-observer.coffee
  resources/assets/coffee/react/modding-profile/header.coffee
  resources/assets/coffee/react/profile-page/badges.coffee
  resources/assets/coffee/react/profile-page/header-info.coffee
  resources/assets/coffee/react/profile-page/header.coffee
  resources/assets/coffee/react/profile-page/links.coffee
  resources/assets/coffee/react/profile-page/main.coffee
  resources/assets/lib/globals.d.ts
  resources/assets/lib/header-v4.tsx
  resources/assets/lib/interfaces/profile-banner.ts
  resources/assets/lib/interfaces/user-badge-json.ts
  resources/assets/lib/interfaces/user-json-extended.ts
  resources/assets/lib/interfaces/user-json.ts
  resources/assets/lib/profile-page/badges.tsx
  resources/assets/lib/profile-page/header-info.tsx
  resources/assets/lib/profile-page/header-links.ts
  resources/assets/lib/profile-page/links.tsx
  resources/assets/lib/profile-tournament-banner.tsx
  resources/assets/lib/string-with-component.tsx
  resources/assets/lib/user-card.tsx
  resources/docs/source/includes/_structures/user.md
  resources/docs/source/includes/_structures/user_compact.md
  resources/views/vendor/apidoc/partials/info.blade.php
  tests/karma/osu-core.spec.ts
Labels: area:user-profile

#7634 Simplify additional script loading
  resources/assets/coffee/_classes/twitch-player.coffee
  resources/assets/lib/store-xsolla.coffee
  resources/assets/lib/turbolinks-reload.ts
Labels: type:code-quality

#7645 Observable window size state
  resources/assets/coffee/_classes/forum-topic-reply.coffee
  resources/assets/coffee/_classes/input-handler.coffee
  resources/assets/coffee/_classes/line-chart.coffee
  resources/assets/coffee/_classes/sticky-header.coffee
  resources/assets/coffee/osu_common.coffee
  resources/assets/coffee/react/_components/comment.coffee
  resources/assets/coffee/react/beatmaps/search-content.coffee
  resources/assets/coffee/react/profile-page/historical.coffee
  resources/assets/less/bootstrap-variables.less
  resources/assets/lib/beatmaps/virtual-list-meta.ts
  resources/assets/lib/chat/input-box.tsx
  resources/assets/lib/globals.d.ts
  resources/assets/lib/news-sidebar/month-listing.tsx
  resources/assets/lib/osu-core.ts
  resources/assets/lib/user-card-tooltip.tsx
  resources/assets/lib/user-verification.ts
  resources/assets/lib/window-size.ts
  resources/assets/lib/window-vh-patcher.ts
Labels: type:code-quality, type:performance

#7628 Filter out restricted users on country statistics aggregate
  app/Console/Kernel.php
  app/Models/CountryStatistics.php
Labels: area:rankings, type:reliability

#7646 Avoid loading invisible beatmap card background on mobile
  resources/assets/lib/beatmapset-panel.tsx
Labels: area:beatmap-listing, type:performance

#7653 Remove animated height on beatmap card resize
  resources/assets/less/bem/beatmapset-panel.less
Labels: area:beatmap-listing, type:ux

#7631 Misc. markdown library improvements
  app/Libraries/Markdown/Attributes/AttributesOnlyIdListener.php
  app/Libraries/Markdown/Indexing/Extension.php
  app/Libraries/Markdown/Indexing/RendererExtension.php
  app/Libraries/Markdown/Indexing/Renderers/BlockRenderer.php
  app/Libraries/Markdown/Indexing/Renderers/InlineRenderer.php
  app/Libraries/Markdown/Indexing/Renderers/ListBlockRenderer.php
  app/Libraries/Markdown/Indexing/Renderers/ListItemRenderer.php
  app/Libraries/Markdown/Indexing/Renderers/NewlineRenderer.php
  app/Libraries/Markdown/Indexing/Renderers/NoopRenderer.php
  app/Libraries/Markdown/Indexing/Renderers/TableRenderer.php
  app/Libraries/Markdown/Osu/DocumentProcessor.php
  app/Libraries/Markdown/Osu/Extension.php
  app/Libraries/Markdown/Osu/Renderers/ListItemRenderer.php
  app/Libraries/Markdown/Osu/Renderers/TableRenderer.php
  app/Libraries/Markdown/OsuMarkdown.php
  composer.json
  composer.lock
  tests/Libraries/Markdown/ProcessorTest.php
  tests/Libraries/Markdown/html_markdown_examples/attribute.html
  tests/Libraries/Markdown/html_markdown_examples/attribute.md
  tests/Libraries/Markdown/html_markdown_examples/list.html
  tests/Libraries/Markdown/html_markdown_examples/list.md
  tests/Libraries/Markdown/html_markdown_examples/table.html
  tests/Libraries/Markdown/html_markdown_examples/table.md
  tests/Libraries/Markdown/indexable_markdown_examples/attribute.md
  tests/Libraries/Markdown/indexable_markdown_examples/attribute.txt
Labels: type:code-quality

#7632 Save post editor content
  app/Http/Controllers/Forum/PostsController.php
  resources/assets/app.ts
  resources/assets/coffee/_classes/bbcode-preview.coffee
  resources/assets/coffee/_classes/forum-topic-reply.coffee
  resources/assets/coffee/_classes/forum.coffee
  resources/assets/coffee/_classes/nav2.coffee
  resources/assets/coffee/_classes/post-preview.coffee
  resources/assets/coffee/forum/topic-ajax.coffee
  resources/assets/coffee/osu_common.coffee
  resources/assets/coffee/react/beatmap-discussions/nominations.coffee
  resources/assets/coffee/react/modding-profile/main.coffee
  resources/assets/coffee/react/profile-page/main.coffee
  resources/assets/coffee/spoilerbox.coffee
  resources/assets/lib/forum-post-edit.ts
  resources/assets/lib/forum-post-input.ts
  resources/assets/lib/import-shims.coffee
  resources/assets/lib/osu-core.ts
  resources/assets/lib/utils/page-change.ts
  resources/views/forum/posts/edit.blade.php
  resources/views/forum/topics/_post_edit_form.blade.php
  resources/views/forum/topics/_reply.blade.php
  resources/views/forum/topics/create.blade.php
  resources/views/forum/topics/delete.blade.php
  resources/views/forum/topics/replace_delete_button.blade.php
Labels: area:forum, type:ux

#7657 Disable mail notification by default
  app/Jobs/Notifications/BroadcastNotificationBase.php
  app/Models/UserNotificationOption.php
  resources/views/accounts/_edit_notifications.blade.php
  tests/BroadcastNotificationTest.php
Labels: area:notifications

#7659 Show user last visit as relative time
  resources/assets/lib/profile-page/links.tsx
Labels: area:user-profile

#7663 Fix missing mobile header background in profile page
  resources/assets/lib/profile-page/header-info.tsx
Labels: area:user-profile

#7654 Use correct cover size
  resources/assets/lib/beatmapset-panel.tsx
Labels: area:beatmap-listing

#7665 Fix missing highlight on last seen date in user profile
  resources/assets/lib/profile-page/links.tsx
Labels: area:user-profile

#7666 convert Img2x to typescript
  resources/assets/coffee/osu_common.coffee
  resources/assets/coffee/react/_components/img2x.coffee
  resources/assets/coffee/react/beatmaps/search-content.coffee
  resources/assets/coffee/react/modding-profile/header.coffee
  resources/assets/coffee/react/profile-page/achievement-badge.coffee
  resources/assets/coffee/react/profile-page/header.coffee
  resources/assets/lib/beatmapset-panel.tsx
  resources/assets/lib/chat/main-view.tsx
  resources/assets/lib/coffee-modules.d.ts
  resources/assets/lib/img2x.tsx
  resources/assets/lib/profile-tournament-banner.tsx
  resources/assets/lib/quick-search/beatmapset.tsx
Labels: type:code-quality

#7668 Update beatmap cover size
  resources/assets/less/bem/beatmap-playcount.less
  resources/assets/less/bem/beatmapset-search-card.less
  resources/assets/less/bem/beatmapset-watches.less
Labels: type:design

#7667 Return int for usort callback function
  app/Libraries/AcceptHttpLanguage/Parser.php
Labels: type:reliability

#7647 Rename Match to LegacyMatch
  app/Http/Controllers/MatchesController.php
  app/Libraries/OsuAuthorize.php
  app/Models/Chat/Channel.php
  app/Models/LegacyMatch/Event.php
  app/Models/LegacyMatch/Game.php
  app/Models/LegacyMatch/LegacyMatch.php
  app/Models/LegacyMatch/Model.php
  app/Models/LegacyMatch/Score.php
  app/Transformers/LegacyMatch/EventTransformer.php
  app/Transformers/LegacyMatch/GameTransformer.php
  app/Transformers/LegacyMatch/LegacyMatchTransformer.php
  database/factories/Chat/ChannelFactory.php
  database/factories/LegacyMatch/EventFactory.php
  database/factories/LegacyMatch/GameFactory.php
  database/factories/LegacyMatch/LegacyMatchFactory.php
  tests/Browser/SanityTest.php
  tests/Controllers/MatchesControllerTest.php
Labels: type:code-quality
