Repository ppy/osu-web, pull requests merged in 2021-07, with the labels that each got.

#7780 Add php typings to CommentBundle
  app/Libraries/CommentBundle.php
  app/Libraries/CommentBundleParams.php
Labels: type:code-quality

#7818 Adjust approach rate mod exclusivities
  app/Libraries/Multiplayer/Mod.php
Labels: area:multiplayer

#7819 Add active user indicator in multiplayer rooms high table
  app/Models/Multiplayer/Room.php
  app/Models/Multiplayer/UserScoreAggregate.php
  app/Transformers/Multiplayer/RoomTransformer.php
  database/migrations/2021_07_01_091316_add_in_room_to_multiplayer_rooms_high.php
Labels: area:multiplayer

#7817 Accept legacy "m" parameter for beatmap redirect mode
  app/Http/Controllers/BeatmapsController.php
Labels: area:beatmap-info

#7823 Minor typescript lint fixes
  resources/assets/lib/beatmap-discussions/nominator.tsx
  resources/assets/lib/beatmap-discussions/review-document.ts
  resources/assets/lib/click-menu.ts
  resources/assets/lib/stores/notification-store.ts
Labels: type:code-quality

#7820 Perform full page load on logout
  app/Http/Controllers/SessionsController.php
  resources/assets/app.ts
  resources/assets/coffee/logout.coffee
  resources/assets/lib/actions/user-login-actions.ts
  resources/assets/lib/beatmaps/beatmapset-search.ts
  resources/assets/lib/chat/chat-state-store.ts
  resources/assets/lib/notifications/worker.ts
  resources/assets/lib/socket-worker.ts
  resources/assets/lib/stores/beatmapset-store.ts
  resources/assets/lib/stores/channel-store.ts
  resources/assets/lib/stores/client-store.ts
  resources/assets/lib/stores/comment-store.ts
  resources/assets/lib/stores/commentable-meta-store.ts
  resources/assets/lib/stores/notification-stack-store.ts
  resources/assets/lib/stores/notification-store.ts
  resources/assets/lib/stores/own-client-store.ts
  resources/assets/lib/stores/user-store.ts
  resources/assets/lib/user-login-observer.ts
  resources/views/client_verifications/completed.blade.php
Labels: type:code-quality

#7807 Remove comments count from current user json
  app/Http/Controllers/FriendsController.php
  app/Http/Controllers/GroupsController.php
  app/Http/Controllers/Users/MultiplayerController.php
  app/Http/Controllers/UsersController.php
  app/Libraries/ModdingHistoryEventsBundle.php
  app/Transformers/UserCompactTransformer.php
  app/Transformers/UserTransformer.php
  resources/assets/lib/interfaces/user-json-extended.ts
  resources/assets/lib/interfaces/user-json.ts
  resources/assets/lib/profile-page/links.tsx
Labels: type:performance

#7836 Skip trying to send notification to comment parent if user doesn't exist
  app/Jobs/Notifications/CommentNew.php
Labels: area:comments, area:notifications

#7840 Wrap switch case with variable declaration in a block
  resources/assets/lib/beatmap-discussions/review-post.tsx
  resources/assets/lib/quick-search/worker.ts
Labels: type:code-quality

#7834 Update Paypal SDK
  app/Http/Controllers/Payments/PaypalController.php
  app/Libraries/Payments/PaypalApiContext.php
  app/Libraries/Payments/PaypalCreatePayment.php
  app/Libraries/Payments/PaypalExecutePayment.php
  app/Libraries/Payments/PaypalPaymentProcessor.php
  app/Models/Store/Order.php
  app/Notifications/Store/ErrorMessage.php
  composer.json
  composer.lock
  resources/lang/en/paypal/errors.php
Labels: area:store

#7842 Fix some user relations using wrong foreign keys
  app/Models/Notification.php
  app/Models/UserGroupEvent.php
  app/Models/UserNotificationOption.php
Labels: type:code-quality

#7843 Fix Twitch stream links
  app/Models/Twitch/Stream.php
Labels: type:reliability

#7841 Prevent showing empty livestream listing on error
  app/Models/LivestreamCollection.php
Labels: type:reliability

#7837 Multiplayer realtime room password
  app/Http/Controllers/Multiplayer/RoomsController.php
  app/Models/Multiplayer/Room.php
  app/Transformers/Multiplayer/RoomTransformer.php
  database/migrations/2021_07_07_065618_add_password_to_multiplayer_rooms.php
  resources/lang/en/multiplayer.php
  tests/Controllers/Multiplayer/RoomsControllerTest.php
Labels: area:multiplayer

#7844 Use correct variable
  app/Libraries/Payments/PaypalExecutePayment.php
Labels: area:store

#7845 Fix render error of contest voting page
  resources/assets/coffee/react/contest-voting.coffee
Labels: area:contests

#7804 Unique namespace for React event
  resources/assets/coffee/_classes/store-supporter-tag.coffee
  resources/assets/coffee/react/_components/block-button.coffee
  resources/assets/coffee/react/_components/comments-manager.coffee
  resources/assets/coffee/react/_components/friend-button.coffee
  resources/assets/coffee/react/_components/notification-banner.coffee
  resources/assets/coffee/react/admin/contest/user-entry-list.coffee
  resources/assets/coffee/react/beatmap-discussions-history/main.coffee
  resources/assets/coffee/react/beatmap-discussions/beatmap-list.coffee
  resources/assets/coffee/react/beatmap-discussions/discussions.coffee
  resources/assets/coffee/react/beatmap-discussions/main.coffee
  resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
  resources/assets/coffee/react/beatmaps/paginator.coffee
  resources/assets/coffee/react/beatmaps/search-panel.coffee
  resources/assets/coffee/react/beatmapset-page/info.coffee
  resources/assets/coffee/react/beatmapset-page/main.coffee
  resources/assets/coffee/react/beatmapset-page/scoreboard.coffee
  resources/assets/coffee/react/beatmapset-page/stats.coffee
  resources/assets/coffee/react/contest-entry/uploader.coffee
  resources/assets/coffee/react/contest-entry/user-entry-list.coffee
  resources/assets/coffee/react/contest-voting/base-entry-list.coffee
  resources/assets/coffee/react/modding-profile/detail-bar.coffee
  resources/assets/coffee/react/modding-profile/main.coffee
  resources/assets/coffee/react/profile-page/achievement-badge.coffee
  resources/assets/coffee/react/profile-page/cover-selector.coffee
  resources/assets/coffee/react/profile-page/detail-bar.coffee
  resources/assets/coffee/react/profile-page/header.coffee
  resources/assets/coffee/react/profile-page/historical.coffee
  resources/assets/coffee/react/profile-page/main.coffee
  resources/assets/coffee/react/profile-page/rank-chart.coffee
  resources/assets/lib/admin-menu.tsx
  resources/assets/lib/beatmap-discussions/editor-insertion-menu.tsx
  resources/assets/lib/beatmap-discussions/editor-toolbar.tsx
  resources/assets/lib/beatmap-discussions/new-review.tsx
  resources/assets/lib/beatmaps/main.tsx
  resources/assets/lib/follow-toggle.tsx
  resources/assets/lib/follow-user-mapping-button.tsx
  resources/assets/lib/gallery-contest-vote-button.tsx
  resources/assets/lib/gallery-contest-vote-progress.tsx
  resources/assets/lib/gallery-contest.tsx
  resources/assets/lib/globals.d.ts
  resources/assets/lib/news-index/main.tsx
  resources/assets/lib/popup-menu.coffee
  resources/assets/lib/portal.tsx
  resources/assets/lib/user-card-brick.tsx
  resources/assets/lib/user-card-store.tsx
  resources/assets/lib/utils/seq.ts
Labels: type:code-quality, type:reliability

#7809 Only store completed scores in main scores table
  app/Http/Controllers/Solo/ScoreTokensController.php
  app/Http/Controllers/Solo/ScoresController.php
  app/Models/Solo/Score.php
  app/Models/Solo/ScoreToken.php
  app/Transformers/Solo/ScoreTokenTransformer.php
  database/migrations/2021_06_28_084610_create_solo_score_tokens.php
  routes/web.php
  tests/Controllers/Solo/ScoreTokensControllerTest.php
  tests/Controllers/Solo/ScoresControllerTest.php
  tests/api_routes.json
Labels: area:scoring

#7848 Filter out fail scores by the pass flag instead of rank
  app/Models/LegacyMatch/Score.php
  app/Models/Score/Best/Model.php
  app/Models/Score/Model.php
  app/Transformers/ScoreTransformer.php
  resources/assets/lib/interfaces/score-json.ts
  resources/views/docs/_structures/score.md
Labels: area:scoring

#7851 Fix multiplayer rooms password migration rollback
  database/migrations/2021_07_07_065618_add_password_to_multiplayer_rooms.php
Labels: type:database

#7854 Pre-bind function for throttle
  resources/assets/lib/beatmap-discussions/editor-insertion-menu.tsx
Labels: javascript, type:code-quality

#7824 Use database query for checking artist new track status
  app/Http/Controllers/ArtistsController.php
  app/Models/Artist.php
  app/Traits/Memoizes.php
Labels: type:code-quality

#7849 Convert beatmap list component to typescript and make it more reusable
  resources/assets/coffee/_classes/blackout.coffee
  resources/assets/coffee/react/beatmap-discussions/beatmap-list-item.coffee
  resources/assets/coffee/react/beatmap-discussions/beatmap-list.coffee
  resources/assets/coffee/react/beatmap-discussions/header.coffee
  resources/assets/lib/beatmap-discussions/beatmap-list-item.tsx
  resources/assets/lib/beatmap-discussions/beatmap-list.tsx
  resources/assets/lib/blackout.ts
  resources/assets/lib/import-shims.coffee
Labels: type:code-quality

#7838 Fix audio player playlist for non-album listing
  resources/assets/coffee/react/_components/tracklist.coffee
  resources/views/artists/show.blade.php
Labels: area:featured-artist, type:ux

#7858 Fix chart rendering
  resources/assets/coffee/react/beatmapset-page/info.coffee
  resources/assets/coffee/react/beatmapset-page/stats.coffee
  resources/assets/coffee/react/profile-page/historical.coffee
  resources/assets/coffee/react/profile-page/rank-chart.coffee
  resources/assets/lib/react-turbolinks.ts
Labels: area:charts, javascript, type:reliability

#7860 Fix blackout default visible opacity
  resources/assets/lib/blackout.ts
Labels: type:design

#7857 Update php coding standard lint
  composer.json
  composer.lock
  phpcs.xml
Labels: area:tooling, php

#7872 Skip returning socket worker start function promise
  resources/assets/lib/socket-worker.ts
Labels: javascript, type:code-quality

#7873 Remove underscore identifier lint
  .eslintrc.js
Labels: area:tooling, javascript, type:code-quality

#7874 Use constructor instead of Object.create
  resources/assets/lib/models/chat/channel.ts
  resources/assets/lib/models/chat/message.ts
  resources/assets/lib/models/user.ts
Labels: javascript, type:code-quality

#7864 Review embed typing updates
  resources/assets/lib/beatmap-discussions/discussions-context.ts
  resources/assets/lib/beatmap-discussions/review-post-embed.tsx
Labels: area:beatmap-discussions, javascript, type:code-quality

#7877 Query correct page when cleaning up during react component mount
  resources/assets/coffee/react/beatmaps/search-panel.coffee
Labels: area:beatmap-listing, javascript, type:reliability

#7879 Remove score country rank display
  app/Http/Controllers/ScoresController.php
  resources/assets/less/bem/score-player.less
  resources/assets/lib/scores-show/player.tsx
Labels: area:scoring, type:performance

#7880 Increase user stats per-page limit to 100
  app/Http/Controllers/UsersController.php
Labels: area:user-profile, php, type:api

#7833 Add specific exception for usage inside OsuAuthorize
  app/Exceptions/AuthorizationCheckException.php
  app/Libraries/OsuAuthorize.php
Labels: type:code-quality

#7878 Add typings for incoming socket messages
  resources/assets/lib/notifications/worker.ts
  resources/assets/lib/socket-message-event.ts
  resources/assets/lib/socket-worker.ts
Labels: type:code-quality

#7882 Allow user registration by default
  config/osu.php
Labels: area:settings, php, type:code-quality

#7881 Configurable trusted proxy
  .env.example
  app/Http/Kernel.php
  composer.json
  composer.lock
  config/octane.php
  config/trustedproxy.php
Labels: php, type:reliability

#7887 Fix download score replay button
  resources/assets/lib/scores-show/buttons.tsx
Labels: area:scoring, javascript, type:ux

#7865 Don't return cursor if there's no more result
  app/Libraries/Elasticsearch/Search.php
Labels: area:search, php

#7888 Add language hint on wiki pages
  app/Models/Wiki/Page.php
  app/Transformers/WikiPageTransformer.php
  resources/views/layout/metadata.blade.php
  resources/views/wiki/_actions.blade.php
  resources/views/wiki/_locale_menu.blade.php
  resources/views/wiki/layout.blade.php
  resources/views/wiki/main.blade.php
  resources/views/wiki/show.blade.php
  resources/views/wiki/sitemap.blade.php
Labels: area:wiki, php

#7827 Always use normal font weight for extra icons
  resources/assets/less/bem/beatmaps-popup-item.less
  resources/assets/less/icons.less
Labels: type:design

#7897 Add group url as osu-web url
  resources/assets/lib/osu-url-helper.ts
Labels: javascript, type:ux

#7889 Fix (lazer) failed plays showing up in profile recent plays
  app/Models/Solo/Score.php
  tests/Models/Solo/ScoreTest.php
Labels: area:scoring

#7883 Fix shopify debug typing
  resources/assets/lib/shopify-debug.ts
Labels: javascript, type:code-quality

#7896 Fix current url handling
  resources/assets/coffee/_classes/beatmap-discussion-helper.coffee
  resources/assets/coffee/_classes/forum-topic-reply.coffee
  resources/assets/coffee/_classes/forum.coffee
  resources/assets/coffee/osu_common.coffee
  resources/assets/coffee/react/beatmap-discussions/main.coffee
  resources/assets/coffee/react/beatmapset-page/main.coffee
  resources/assets/coffee/turbolinks-overrides.coffee
  resources/assets/lib/beatmaps/beatmapset-search-controller.ts
  resources/assets/lib/chat.tsx
  resources/assets/lib/forum-post-input.ts
  resources/assets/lib/globals.d.ts
  resources/assets/lib/import-shims.coffee
  resources/assets/lib/laroute.ts
  resources/assets/lib/notifications/notification-controller.ts
  resources/assets/lib/quick-search-button.tsx
  resources/assets/lib/ranking-filter.tsx
  resources/assets/lib/react-turbolinks.ts
  resources/assets/lib/user-list.tsx
  resources/assets/lib/utils/beatmapset-discussion-helper.ts
  resources/assets/lib/utils/turbolinks.ts
Labels: javascript, type:reliability

#7901 Use rank D instead of F for failed plays
  app/Models/Solo/Score.php
  tests/Models/Solo/ScoreTest.php
Labels: area:scoring

#7850 Add default search cache key
  app/Libraries/Elasticsearch/SearchParams.php
  app/Libraries/Search/BeatmapsetSearchParams.php
  app/Libraries/Search/ForumSearchParams.php
  app/Libraries/Search/UserSearchParams.php
  app/Libraries/Search/WikiSearchParams.php
  app/Libraries/Search/WikiSuggestionsParams.php
Labels: area:search, type:code-quality

#7903 Fix octane watch sometimes not reloading
  config/octane.php
Labels: area:tooling, php

#7793 Show when a user's nomination gets reset
  app/Console/Commands/BeatmapsetNominationSyncCommand.php
  app/Console/Kernel.php
  app/Http/Controllers/BeatmapDiscussionPostsController.php
  app/Libraries/BeatmapsetDiscussionReview.php
  app/Models/BeatmapDiscussion.php
  app/Models/Beatmapset.php
  app/Models/BeatmapsetEvent.php
  app/Models/BeatmapsetNomination.php
  database/factories/BeatmapsetFactory.php
  database/factories/BeatmapsetNominationFactory.php
  database/migrations/2021_07_07_073634_create_beatmapset_nominations.php
  database/migrations/2021_07_19_084446_add_nomination_reset_received_to_beatmapset_events.php
  resources/assets/coffee/react/beatmap-discussions/events.coffee
  resources/assets/coffee/react/modding-profile/events.coffee
  resources/assets/less/bem/beatmapset-event.less
  resources/assets/lib/beatmap-discussions/event.tsx
  resources/assets/lib/beatmap-discussions/events.tsx
  resources/assets/lib/beatmapset-events.tsx
  resources/assets/lib/register-components.coffee
  resources/lang/en/beatmap_discussions.php
  resources/lang/en/beatmapset_events.php
  tests/BeatmapsetDisqualifyNotificationsTest.php
  tests/BeatmapsetEventNominationResetTest.php
  tests/Controllers/BeatmapDiscussionPostsControllerTest.php
  tests/Controllers/BeatmapDiscussionsControllerTest.php
  tests/Models/BeatmapsetTest.php
Labels: area:beatmap-discussions

#7905 Update remaining use of document.location
  resources/assets/coffee/react/modding-profile/main.coffee
  resources/assets/coffee/react/profile-page/main.coffee
  resources/assets/lib/utils/turbolinks.ts
Labels: javascript, type:code-quality

#7906 Fix profile page navigation scroll on Firefox
  resources/assets/coffee/react/modding-profile/main.coffee
  resources/assets/coffee/react/profile-page/main.coffee
Labels: area:user-profile, javascript, type:ux

#7904 Update Sentry to support Octane
  composer.json
  composer.lock
Labels: area:tooling, php

#7855 Implement New Difficulty Rating Colour Proposal
  resources/assets/coffee/osu_common.coffee
  resources/assets/less/bem/difficulty-badge.less
  resources/assets/less/bem/multiplayer-room.less
  resources/assets/less/variables.less
  resources/assets/lib/beatmap-icon.tsx
  resources/assets/lib/beatmapset-panel.tsx
  resources/assets/lib/difficulty-badge.tsx
  resources/assets/lib/globals.d.ts
  resources/assets/lib/scores-show/beatmap-info.tsx
  resources/assets/lib/user-multiplayer-index/room.tsx
  resources/assets/lib/utils/beatmap-helper.ts
Labels: area:beatmap-info, type:design

#7923 Fix session duration for non-guest user on octane
  app/Libraries/Session/Store.php
Labels: php, type:reliability

#7917 Remove `classWithModifiers` from osu-common
  resources/assets/coffee/_classes/line-chart.coffee
  resources/assets/coffee/osu_common.coffee
  resources/assets/coffee/react/_components/bbcode-editor.coffee
  resources/assets/coffee/react/_components/big-button.coffee
  resources/assets/coffee/react/_components/block-button.coffee
  resources/assets/coffee/react/_components/build.coffee
  resources/assets/coffee/react/_components/changelog-header-streams.coffee
  resources/assets/coffee/react/_components/comment-editor.coffee
  resources/assets/coffee/react/_components/comment-show-more.coffee
  resources/assets/coffee/react/_components/comment.coffee
  resources/assets/coffee/react/_components/comments.coffee
  resources/assets/coffee/react/_components/friend-button.coffee
  resources/assets/coffee/react/_components/value-display.coffee
  resources/assets/coffee/react/beatmap-discussions/user-card.coffee
  resources/assets/coffee/react/beatmapset-page/scoreboard-table-row.coffee
  resources/assets/coffee/react/beatmapset-page/scoreboard-table.coffee
  resources/assets/coffee/react/contest-voting/vote-summary.coffee
  resources/assets/coffee/react/profile-page/achievement-badge.coffee
  resources/assets/coffee/react/profile-page/cover-selection.coffee
  resources/assets/lib/beatmap-discussions/editor-discussion-component.tsx
  resources/assets/lib/beatmap-discussions/editor-toolbar-button.tsx
  resources/assets/lib/beatmap-discussions/editor.tsx
  resources/assets/lib/beatmap-discussions/icon-dropdown-menu.tsx
  resources/assets/lib/beatmap-discussions/new-review.tsx
  resources/assets/lib/beatmap-discussions/review-post-embed.tsx
  resources/assets/lib/deleted-comments-count.tsx
  resources/assets/lib/flag-country.tsx
  resources/assets/lib/header-v4.tsx
  resources/assets/lib/import-shims.coffee
  resources/assets/lib/mod.tsx
  resources/assets/lib/news-index/post-item.tsx
  resources/assets/lib/news-show/main.tsx
  resources/assets/lib/notification-widget/item.tsx
  resources/assets/lib/notification-widget/main.tsx
  resources/assets/lib/notifications/notification-delete-button.tsx
  resources/assets/lib/notifications/notification-read-button.tsx
  resources/assets/lib/play-detail-list.coffee
  resources/assets/lib/quick-search/beatmapset.tsx
  resources/assets/lib/quick-search/main.tsx
  resources/assets/lib/quick-search/user.tsx
  resources/assets/lib/sort.tsx
  resources/assets/lib/supporter-icon.tsx
  resources/assets/lib/user-card-brick.tsx
  resources/assets/lib/user-card.tsx
  resources/assets/lib/user-cards.tsx
  resources/assets/lib/user-list.tsx
  resources/assets/lib/user-profile-container.tsx
  resources/assets/lib/validating-input.tsx
Labels: type:code-quality

#7929 Adjust flag size and fix overlay and shadow for non-rectangular flags
  resources/assets/less/bem/flag-country.less
Labels: type:design

#7932 Fix new problem notification for qualified maps
  app/Models/BeatmapDiscussion.php
Labels: area:beatmap-discussions, php

#7933 Add notification tests for reopening problems on Beatmap discussions
  tests/Controllers/BeatmapDiscussionPostsControllerTest.php
Labels: area:beatmap-discussions

#7938 Generate nav links and locale meta once when rendering view
  resources/views/home/landing.blade.php
  resources/views/layout/_nav2.blade.php
  resources/views/layout/header_mobile/nav.blade.php
  resources/views/layout/metadata.blade.php
  resources/views/master.blade.php
Labels: php, type:performance

#7937 Adjust page and menu titles
  resources/lang/en/layout.php
  resources/lang/en/page_title.php
Labels: type:localisation

#7943 Fix qualified problem notification being sent on non-qualified maps
  app/Libraries/BeatmapsetDiscussionReview.php
Labels: area:beatmap-discussions, area:notifications, php

#7948 Fix session error on password reset
  app/Http/Controllers/PasswordResetController.php
  resources/lang/en/password_reset.php
Labels: php, type:reliability

#7953 Fix wording for mapping follow tooltips
  resources/lang/en/follows.php
Labels: type:localisation

#7945 Add muted mod
  app/Libraries/Multiplayer/Mod.php
Labels: area:scoring
