Repository ppy/osu-web, pull requests merged in 2022-01, with the labels that each got.

#8474 Fix display check for playmode tabs count label
  resources/assets/lib/playmode-tabs.tsx
Labels: area:beatmap-discussions, type:ux

#8475 Limit title length for beatmapset model factory
  database/factories/BeatmapsetFactory.php
Labels: type:testing

#8477 Check for poll title length
  app/Models/Forum/TopicPoll.php
Labels: area:forum, type:reliability

#8484 Fix error trying to observe guest user's nonexistent cover
  resources/assets/coffee/_classes/current-user-observer.coffee
Labels: type:reliability

#8403 More getters and less HTMLElement for sticky header
  resources/assets/lib/core/sticky-header.ts
Labels: type:code-quality

#8482 Remove unused export shims
  resources/assets/lib/import-shims.coffee
Labels: type:code-quality

#8481 Directly import fileupload callback
  resources/assets/coffee/_classes/account-edit-avatar.coffee
  resources/assets/coffee/_classes/forum-cover.coffee
  resources/assets/coffee/react/contest-entry/uploader.coffee
  resources/assets/lib/import-shims.coffee
Labels: type:code-quality

#8438 Combine score helper files
  resources/assets/coffee/react/beatmapset-page/scoreboard-table-row.coffee
  resources/assets/coffee/react/beatmapset-page/scoreboard-table.coffee
  resources/assets/coffee/react/beatmapset-page/scoreboard.coffee
  resources/assets/less/bem/beatmap-scoreboard-table.less
  resources/assets/lib/beatmapsets-show/score-top.tsx
  resources/assets/lib/interfaces/score-json.ts
  resources/assets/lib/scores-show/stats.tsx
  resources/assets/lib/utils/score-helper.ts
  resources/assets/lib/utils/score.ts
Labels: type:code-quality

#8483 Directly import fade functions
  resources/assets/coffee/_classes/changelog-chart.coffee
  resources/assets/coffee/_classes/fancy-chart.coffee
  resources/assets/coffee/_classes/forum-posts-seek.coffee
  resources/assets/coffee/_classes/menu.coffee
  resources/assets/coffee/_classes/nav2.coffee
  resources/assets/coffee/_classes/twitch-player.coffee
  resources/assets/lib/import-shims.coffee
Labels: type:code-quality

#8465 Clean up PlayDetailList component
  resources/assets/coffee/react/modding-profile/votes.coffee
  resources/assets/lib/components/profile-page-extra-section-title.tsx
  resources/assets/lib/play-detail-list.tsx
  resources/assets/lib/profile-page/account-standing.tsx
  resources/assets/lib/profile-page/beatmapsets.tsx
  resources/assets/lib/profile-page/extra-page-props.ts
  resources/assets/lib/profile-page/historical.tsx
  resources/assets/lib/profile-page/medals.tsx
  resources/assets/lib/profile-page/play-detail-list.tsx
  resources/assets/lib/profile-page/play-detail.tsx
  resources/assets/lib/profile-page/top-scores.tsx
Labels: area:user-profile

#8489 Add endpoint to reindex artist tracks
  app/Http/Controllers/InterOp/ArtistTracksController.php
  routes/web.php
Labels: area:featured-artist, type:reliability

#8487 Remove Promise polyfill
  package.json
  resources/assets/lib/import-shims.coffee
  yarn.lock
Labels: type:code-quality

#8485 Directly import currentUrl
  resources/assets/coffee/_classes/beatmap-discussion-helper.coffee
  resources/assets/coffee/_classes/forum-topic-reply.coffee
  resources/assets/coffee/_classes/forum.coffee
  resources/assets/coffee/osu_common.coffee
  resources/assets/coffee/turbolinks-overrides.coffee
  resources/assets/lib/import-shims.coffee
Labels: type:code-quality

#8479 Ignore elasticsearch cursor parameter error
  app/Exceptions/InvalidCursorException.php
  app/Http/Controllers/BeatmapsetsController.php
  app/Libraries/Elasticsearch/Search.php
  resources/lang/en/errors.php
Labels: area:beatmap-listing, type:reliability

#8486 Convert Blackout object to utility
  resources/assets/coffee/_classes/nav2.coffee
  resources/assets/lib/beatmap-discussions/beatmap-list.tsx
  resources/assets/lib/blackout.ts
  resources/assets/lib/import-shims.coffee
  resources/assets/lib/modal.coffee
  resources/assets/lib/select-options.coffee
  resources/assets/lib/utils/blackout.ts
Labels: type:code-quality

#8495 Fix incorrect nullable specification in migration
  database/migrations/2021_10_14_094706_add_build_id_to_solo_score_tokens.php
Labels: type:database

#8457 More reliable way to remove reactTurbolinks page load listener
  resources/assets/coffee/react/beatmapset-page/info.coffee
  resources/assets/coffee/react/beatmapset-page/stats.coffee
  resources/assets/coffee/react/modding-profile/main.coffee
  resources/assets/lib/chat/conversation-view.tsx
  resources/assets/lib/core/react-turbolinks.ts
  resources/assets/lib/profile-page/historical.tsx
  resources/assets/lib/profile-page/main.tsx
  resources/assets/lib/profile-page/rank-chart.tsx
Labels: type:code-quality, type:reliability

#8478 replaced dash for unranked & loved maps with heart
  resources/assets/lib/profile-page/play-detail.tsx
Labels: area:user-profile

#8510 Remove unused styling
  resources/assets/less/bem-index.less
  resources/assets/less/bem/user-profile-header.less
Labels: type:code-quality

#8518 Remove Cookies webpack plugin
  webpack.unmix.js
Labels: type:code-quality

#8519 Update username change history table to use utf8(mb4)
  database/migrations/2015_01_01_133337_base_tables.php
Labels: type:database, type:reliability

#8517 Use UTC time for charts
  resources/assets/lib/charts/line-chart.ts
  resources/assets/lib/profile-page/historical.tsx
Labels: type:ux, area:charts

#8520 Update default beatmaps bpm
  database/migrations/2022_01_17_104933_update_default_beatmaps_bpm.php
Labels: type:database

#8504 Directly import route function
  resources/assets/coffee/_classes/account-edit-avatar.coffee
  resources/assets/coffee/_classes/account-edit.coffee
  resources/assets/coffee/_classes/bbcode-preview.coffee
  resources/assets/coffee/_classes/beatmap-discussion-helper.coffee
  resources/assets/coffee/_classes/beatmap-pack.coffee
  resources/assets/coffee/_classes/post-preview.coffee
  resources/assets/coffee/_classes/store-supporter-tag.coffee
  resources/assets/coffee/react/_components/beatmapset-mapping.coffee
  resources/assets/coffee/react/_components/comment-editor.coffee
  resources/assets/coffee/react/_components/comment-show-more.coffee
  resources/assets/coffee/react/_components/comment.coffee
  resources/assets/coffee/react/_components/comments-manager.coffee
  resources/assets/coffee/react/admin/contest/user-art-entry.coffee
  resources/assets/coffee/react/admin/contest/user-entry-delete-button.coffee
  resources/assets/coffee/react/admin/contest/user-entry.coffee
  resources/assets/coffee/react/beatmap-discussions/discussion.coffee
  resources/assets/coffee/react/beatmap-discussions/header.coffee
  resources/assets/coffee/react/beatmap-discussions/main.coffee
  resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
  resources/assets/coffee/react/beatmap-discussions/new-reply.coffee
  resources/assets/coffee/react/beatmap-discussions/nominations.coffee
  resources/assets/coffee/react/beatmap-discussions/post.coffee
  resources/assets/coffee/react/beatmap-discussions/subscribe.coffee
  resources/assets/coffee/react/beatmap-discussions/system-post.coffee
  resources/assets/coffee/react/beatmap-discussions/user-card.coffee
  resources/assets/coffee/react/beatmaps/search-content.coffee
  resources/assets/coffee/react/beatmapset-page/header.coffee
  resources/assets/coffee/react/beatmapset-page/info.coffee
  resources/assets/coffee/react/beatmapset-page/main.coffee
  resources/assets/coffee/react/beatmapset-page/scoreboard-table-row.coffee
  resources/assets/coffee/react/beatmapset-page/scoreboard.coffee
  resources/assets/coffee/react/changelog-build/main.coffee
  resources/assets/coffee/react/changelog-index/main.coffee
  resources/assets/coffee/react/comments-index/main.coffee
  resources/assets/coffee/react/comments-show/main.coffee
  resources/assets/coffee/react/contest-entry/uploader.coffee
  resources/assets/coffee/react/contest-entry/user-entry.coffee
  resources/assets/coffee/react/contest-voting/art-entry.coffee
  resources/assets/coffee/react/contest-voting/entry.coffee
  resources/assets/coffee/react/contest-voting/voter.coffee
  resources/assets/coffee/react/modding-profile/discussions.coffee
  resources/assets/coffee/react/modding-profile/events.coffee
  resources/assets/coffee/react/modding-profile/posts.coffee
  resources/assets/coffee/react/modding-profile/votes.coffee
  resources/assets/coffee/react/mp-history/event.coffee
  resources/assets/coffee/react/mp-history/game-header.coffee
  resources/assets/coffee/react/mp-history/main.coffee
  resources/assets/coffee/react/mp-history/score.coffee
  resources/assets/coffee/store-username-change.coffee
  resources/assets/lib/import-shims.coffee
  resources/assets/lib/laroute.ts
  resources/assets/lib/store-checkout.coffee
  resources/assets/lib/store-paypal.coffee
Labels: type:code-quality

#8505 Directly import parse json
  resources/assets/coffee/_classes/changelog-chart.coffee
  resources/assets/coffee/_classes/fancy-chart.coffee
  resources/assets/coffee/_classes/landing-user-stats.coffee
  resources/assets/lib/import-shims.coffee
Labels: type:code-quality

#8506 Remove import shims and fix forum post delete button
  app/Libraries/OsuAuthorize.php
  resources/assets/coffee/_classes/bbcode-preview.coffee
  resources/assets/coffee/_classes/forum-topic-reply.coffee
  resources/assets/coffee/_classes/forum.coffee
  resources/assets/coffee/_classes/nav2.coffee
  resources/assets/coffee/_classes/post-preview.coffee
  resources/assets/coffee/spoilerbox.coffee
  resources/assets/less/bem-index.less
  resources/assets/less/bem/forum-post-actions.less
  resources/assets/less/bem/forum-post.less
  resources/assets/less/variables.less
  resources/assets/lib/entrypoints/app.ts
  resources/assets/lib/import-shims.coffee
  resources/views/forum/posts/_button_delete.blade.php
  resources/views/forum/topics/_post.blade.php
  resources/views/forum/topics/_posts.blade.php
  resources/views/forum/topics/delete.blade.php
  resources/views/forum/topics/replace_delete_button.blade.php
Labels: area:forum, type:ux, type:code-quality

#8500 Fix comment footer overlapping over "read more" button
  resources/assets/less/bem/comment.less
Labels: area:comments

#8499 Fix generating wiki image url
  app/Http/Controllers/WikiController.php
  app/Libraries/Markdown/Osu/DocumentProcessor.php
  app/helpers.php
Labels: area:wiki, type:reliability

#8525 Only show beatmapset page if it has beatmaps
  app/Http/Controllers/BeatmapsetsController.php
  tests/Controllers/BeatmapsetsControllerTest.php
Labels: area:beatmap-info, type:reliability

#8442 Add pinning scores
  .env.example
  app/Http/Controllers/ScorePinsController.php
  app/Http/Controllers/UsersController.php
  app/Libraries/OsuAuthorize.php
  app/Libraries/User/ScorePins.php
  app/Models/ScorePin.php
  app/Models/User.php
  app/Providers/AppServiceProvider.php
  app/Transformers/Score/CurrentUserAttributesTransformer.php
  app/Transformers/ScoreTransformer.php
  app/Transformers/UserCompactTransformer.php
  config/osu.php
  database/factories/ScorePinFactory.php
  database/migrations/2022_01_22_110033_create_score_pins.php
  resources/assets/less/bem/score-buttons.less
  resources/assets/lib/beatmapsets-show/score-top.tsx
  resources/assets/lib/components/score-pin.tsx
  resources/assets/lib/core/user/score-pins.ts
  resources/assets/lib/interfaces/profile-page/extras-json.ts
  resources/assets/lib/interfaces/score-json.ts
  resources/assets/lib/interfaces/user-json.ts
  resources/assets/lib/osu-core.ts
  resources/assets/lib/play-detail-menu.tsx
  resources/assets/lib/popup-menu-persistent.tsx
  resources/assets/lib/profile-page/controller.tsx
  resources/assets/lib/profile-page/extra-page-props.ts
  resources/assets/lib/profile-page/play-detail-list.tsx
  resources/assets/lib/profile-page/play-detail.tsx
  resources/assets/lib/scores-show/buttons.tsx
  resources/lang/en/authorization.php
  resources/lang/en/beatmapsets.php
  resources/lang/en/users.php
  routes/web.php
  tests/Controllers/ScorePinsControllerTest.php
Labels: area:user-profile

#8529 Fix event listener namespace value
  resources/assets/lib/popup-menu.coffee
Labels: type:reliability

#8522 Prevent sending messages to non-friends if only accepting messages from friends
  app/Libraries/OsuAuthorize.php
  app/Models/User.php
  resources/assets/lib/actions/friend-updated.ts
  resources/assets/lib/chat/chat-api.ts
  resources/assets/lib/chat/chat-state-store.ts
  resources/assets/lib/components/friend-button.tsx
  resources/assets/lib/models/chat/channel.ts
  resources/lang/en/authorization.php
  resources/lang/en/chat.php
  tests/Libraries/ChatTest.php
Labels: type:ux, area:chat

#8539 Fix unable to pin best score from non-best score model
  app/Models/Score/Best/Model.php
  app/Models/Score/Model.php
  app/Transformers/Score/CurrentUserAttributesTransformer.php
  app/Transformers/ScoreTransformer.php
  resources/assets/lib/core/user/score-pins.ts
  resources/assets/lib/osu-core.ts
  resources/assets/lib/utils/score-helper.ts
Labels: area:user-profile, type:reliability

#8468 Add support to rearrange pinned scores
  app/Http/Controllers/ScorePinsController.php
  app/Jobs/RenumberUserScorePins.php
  resources/assets/less/bem-index.less
  resources/assets/less/bem/page-extra-dragdrop.less
  resources/assets/less/bem/play-detail.less
  resources/assets/less/bem/sortable-handle.less
  resources/assets/lib/interfaces/score-json.ts
  resources/assets/lib/profile-page/controller.tsx
  resources/assets/lib/profile-page/extra-header.tsx
  resources/assets/lib/profile-page/play-detail-list.tsx
  resources/assets/lib/profile-page/play-detail.tsx
  routes/web.php
  tests/Controllers/ScorePinsControllerTest.php
Labels: area:user-profile

#8509 Support using docker on M1-based Macs
  .github/workflows/tests.yml
  Dockerfile.development
  SETUP.md
  bin/db_setup.sh
  docker-compose.yml
  docker/development/db_setup.sql
  docker/development/install_chrome.sh
Labels: area:tooling

#8490 Update laravel
  composer.lock
Labels: type:reliability

#8543 Remove url-polyfill
  package.json
  resources/assets/lib/entrypoints/app.ts
  yarn.lock
Labels: type:code-quality

#8545 Update browserslist package
  yarn.lock
Labels: type:code-quality

#8418 Add support for announcement channels in chat
  app/Events/BroadcastableEventBase.php
  app/Http/Controllers/Chat/ChannelsController.php
  app/Jobs/Notifications/ChannelAnnouncement.php
  app/Libraries/BroadcastsPendingForTests.php
  app/Libraries/Chat.php
  app/Libraries/OsuAuthorize.php
  app/Models/Chat/Channel.php
  app/Models/Notification.php
  app/Models/User.php
  app/Models/UserNotificationOption.php
  app/Providers/AppServiceProvider.php
  database/migrations/2022_01_26_210000_add_announce_type_to_channels.php
  resources/assets/lib/interfaces/chat/channel-json.ts
  resources/assets/lib/models/notification-details.ts
  resources/assets/lib/notification-maps/category.ts
  resources/assets/lib/notification-maps/icons.ts
  resources/assets/lib/notification-maps/url.ts
  resources/assets/lib/stores/channel-store.ts
  resources/lang/en/authorization.php
  resources/lang/en/notifications.php
  resources/views/vendor/scribe/index.blade.php
  tests/Controllers/Chat/ChannelsControllerTest.php
  tests/Libraries/ChatTest.php
  tests/Models/Chat/ChannelTest.php
  tests/Models/OAuth/GroupPermissionTest.php
  tests/TestCase.php
  tests/api_routes.json
Labels: area:chat

#8546 Fix account settings saved message
  resources/assets/less/bem/account-edit-entry.less
Labels: type:design

#8527 Add participated multiplayer games to user profile page
  app/Http/Controllers/Users/MultiplayerController.php
  app/Models/Multiplayer/Room.php
  resources/assets/lib/entrypoints/user-multiplayer-index.tsx
  resources/assets/lib/interfaces/room-json.ts
  resources/assets/lib/interfaces/user-multiplayer-history-json.ts
  resources/assets/lib/profile-page/header-links.ts
  resources/assets/lib/user-multiplayer-history-context.ts
  resources/assets/lib/user-multiplayer-index/header.tsx
  resources/assets/lib/user-multiplayer-index/main.tsx
  resources/assets/lib/user-multiplayer-index/multiplayer-history-store.ts
  resources/assets/lib/user-multiplayer-index/multiplayer-history.tsx
  resources/assets/lib/user-multiplayer-index/room.tsx
  resources/lang/en/layout.php
  resources/lang/en/users.php
  routes/web.php
  tests/Browser/SanityTest.php
Labels: area:user-profile

#8553 Import specific lodash util
  resources/assets/lib/profile-page/header-info.tsx
Labels: type:code-quality

#8555 Fix some mod names not being consistent with lazer / wiki
  resources/lang/en/beatmaps.php
Labels: type:localisation

#8439 Add support for rendering markdown in announcement messages
  app/Libraries/Markdown/Chat/Extension.php
  app/Models/Chat/Channel.php
  app/Transformers/Chat/MessageTransformer.php
  app/helpers.php
  resources/assets/less/bem/chat-message-group.less
  resources/assets/less/bem/chat-message-item.less
  resources/assets/lib/chat/conversation-view.tsx
  resources/assets/lib/interfaces/chat/message-json.ts
  resources/assets/lib/models/chat/message.ts
  tests/Libraries/Markdown/ChatMarkdownTest.php
  tests/Libraries/Markdown/chat_markdown_examples/code.html
  tests/Libraries/Markdown/chat_markdown_examples/code.md
  tests/Libraries/Markdown/chat_markdown_examples/code_inline.html
  tests/Libraries/Markdown/chat_markdown_examples/code_inline.md
  tests/Libraries/Markdown/chat_markdown_examples/font_style.html
  tests/Libraries/Markdown/chat_markdown_examples/font_style.md
  tests/Libraries/Markdown/chat_markdown_examples/header.html
  tests/Libraries/Markdown/chat_markdown_examples/header.md
  tests/Libraries/Markdown/chat_markdown_examples/html.html
  tests/Libraries/Markdown/chat_markdown_examples/html.md
  tests/Libraries/Markdown/chat_markdown_examples/link.html
  tests/Libraries/Markdown/chat_markdown_examples/link.md
  tests/Libraries/Markdown/chat_markdown_examples/list_ordered.html
  tests/Libraries/Markdown/chat_markdown_examples/list_ordered.md
  tests/Libraries/Markdown/chat_markdown_examples/list_unordered.html
  tests/Libraries/Markdown/chat_markdown_examples/list_unordered.md
  tests/Libraries/Markdown/chat_markdown_examples/table.html
  tests/Libraries/Markdown/chat_markdown_examples/table.md
Labels: area:chat

#8560 Remove unused layout css modifiers
  resources/assets/less/bem/osu-layout.less
Labels: type:code-quality

#8556 Remove unused css modifiers
  resources/assets/less/bem/page-mode-link.less
  resources/assets/less/bem/page-mode.less
Labels: type:code-quality

#8283 Allow mapper and moderators to pin comments on beatmapsets
  app/Http/Controllers/CommentsController.php
  app/Libraries/OsuAuthorize.php
  app/Models/Comment.php
  database/factories/CommentFactory.php
  resources/assets/lib/models/comment.ts
  resources/assets/lib/stores/commentable-meta-store.ts
  tests/Controllers/CommentsControllerTest.php
Labels: area:comments
