Repository ppy/osu-web, pull requests merged in 2022-12, with the labels that each got.

#9565 Always show guest mapper name on hover on beatmap page
  resources/assets/lib/beatmapsets-show/header.tsx
Labels: type:ux

#9568 Remove visible props from modal
  resources/assets/lib/beatmap-discussions/nominations.coffee
  resources/assets/lib/beatmap-discussions/nominator.tsx
  resources/assets/lib/beatmapsets-show/info.tsx
  resources/assets/lib/components/modal.tsx
  resources/assets/lib/components/quick-search-button.tsx
  resources/assets/lib/components/report-form.tsx
  resources/assets/lib/oauth/own-clients.tsx
Labels: type:code-quality

#9569 Clean up popup component
  resources/assets/lib/beatmap-discussions/editor-insertion-menu.tsx
  resources/assets/lib/beatmap-discussions/editor-toolbar.tsx
  resources/assets/lib/beatmapset-panel/beatmaps-popup.tsx
  resources/assets/lib/components/portal.ts
  resources/assets/lib/components/portal.tsx
Labels: type:code-quality

#9560 Convert IconExpand to typescript
  resources/assets/lib/beatmap-discussions/discussions.coffee
  resources/assets/lib/components/icon-expand.coffee
  resources/assets/lib/components/icon-expand.tsx
Labels: type:code-quality

#9558 Remove `MYSQL_ONETIME_PASSWORD` specification
  docker-compose.yml
Labels: area:tooling

#9559 Use `docker-compose`'s `healthcheck` instead of custom wait script
  bin/wait_for.sh
  docker-compose.yml
  docker/development/entrypoint.sh
Labels: area:tooling

#9523 Support joining component into string sentences
  resources/assets/lib/beatmap-discussions/new-discussion.tsx
  resources/assets/lib/beatmap-discussions/nominations.coffee
  resources/assets/lib/utils/lang.tsx
Labels: type:code-quality

#9581 Fix joining one component
  resources/assets/lib/utils/lang.tsx
Labels: type:ux

#9591 Store locale variables in view
  resources/views/layout/metadata.blade.php
Labels: type:code-quality

#9574 Prevent error when parsing invalid timestamp
  app/helpers.php
Labels: type:reliability

#9595 Use existing locale variable
  resources/views/layout/metadata.blade.php
Labels: type:code-quality

#9561 Separate report form from its button
  resources/assets/lib/beatmap-discussions/beatmap-owner-editor.tsx
  resources/assets/lib/components/forum-post-report.tsx
  resources/assets/lib/components/play-detail-menu.tsx
  resources/assets/lib/components/report-form.tsx
  resources/assets/lib/components/report-reportable.tsx
  resources/assets/lib/components/user-avatar.tsx
  resources/assets/lib/components/user-card.tsx
  resources/assets/lib/core/forum/forum-post-report.ts
  resources/assets/lib/osu-core.ts
  resources/assets/lib/profile-page/extra-menu.tsx
  resources/assets/lib/register-components.coffee
  resources/assets/lib/scores-show/buttons.tsx
Labels: area:user-profile, type:ux

#9606 Send ack on channel join
  app/Http/Controllers/Chat/ChannelsController.php
  app/Libraries/Chat.php
  app/Models/Chat/Channel.php
Labels: type:api, area:chat

#9605 Update GitHub Action cache version
  .github/workflows/lint.yml
  .github/workflows/tests.yml
Labels: type:code-quality

#9597 Show experimental pp
  .env.example
  app/Http/Controllers/RankingController.php
  app/Models/UserStatistics/Model.php
  app/Transformers/UserStatisticsTransformer.php
  config/osu.php
  database/migrations/2022_12_05_114748_add_rank_exp_to_user_statistics.php
  resources/assets/less/utilities.less
  resources/assets/lib/app-deps.ts
  resources/assets/lib/core-legacy/tooltip-default.coffee
  resources/assets/lib/interfaces/user-statistics-json.ts
  resources/assets/lib/profile-page/pp.tsx
  resources/views/layout/metadata.blade.php
  resources/views/rankings/performance.blade.php
Labels: area:scoring

#9603 Use different input type for bpm fields in tracks search
  resources/assets/lib/artist-tracks-index/search-form.tsx
Labels: type:ux, area:featured-artist

#9616 Add support for redirect-only product
  app/Http/Controllers/Store/ProductsController.php
  app/Models/Store/Order.php
  app/Models/Store/Product.php
  resources/views/store/_product.blade.php
Labels: area:store

#9613 Use iterable for array-like typing
  app/helpers.php
Labels: type:code-quality

#9607 Use custom cast for store OrderItem extra_data
  app/Events/Fulfillments/SupporterTagEvent.php
  app/Http/Controllers/Store/CartController.php
  app/Libraries/Fulfillments/ApplySupporterTag.php
  app/Libraries/Fulfillments/BannerFulfillment.php
  app/Libraries/Fulfillments/OrderItemFulfillment.php
  app/Libraries/Fulfillments/SupporterTagFulfillment.php
  app/Models/Store/ExtraDataBase.php
  app/Models/Store/ExtraDataSupporterTag.php
  app/Models/Store/ExtraDataTournamentBanner.php
  app/Models/Store/Order.php
  app/Models/Store/OrderItem.php
  app/Models/SupporterTag.php
  database/factories/OrderItemFactory.php
  tests/Libraries/Fulfillments/SupporterTagFulfillmentTest.php
Labels: area:store, type:code-quality

#9628 Add support for exp rank history
  app/Models/Count.php
  app/Models/RankHistory.php
  database/migrations/2022_12_12_052806_create_user_performance_rank_exp.php
Labels: area:scoring

#9630 Clean up handling of global rank (and exp)
  app/Models/UserStatistics/Model.php
  app/Transformers/UserStatisticsTransformer.php
Labels: area:scoring

#9631 Simplify generation for data attribute of rank history model
  app/Models/RankHistory.php
Labels: type:performance

#9629 Fix rank history display when there's no history
  resources/assets/lib/profile-page/rank-chart.tsx
Labels: type:ux

#9632 Empty rank highest for exp rank
  app/Models/User.php
Labels: area:scoring

#9633 Support exp rank for country rank
  app/Models/UserStatistics/Model.php
Labels: area:scoring

#9623 Prevent incorrect error on simultaneous first wiki image request
  app/Models/Wiki/Image.php
Labels: area:wiki

#9576 Put modal helper where they belong
  resources/assets/lib/chat/input-box.tsx
  resources/assets/lib/components/popup-menu.tsx
  resources/assets/lib/core/click-menu.ts
  resources/assets/lib/profile-page/cover-editor.tsx
  resources/assets/lib/utils/modal-helper.ts
Labels: type:code-quality

#9526 Remove support for retrieving messages from chat updates endpoint
  app/Http/Controllers/Chat/ChatController.php
  resources/views/docs/info.blade.php
  tests/Controllers/Chat/ChatControllerTest.php
Labels: area:chat

#9640 Convert tournament to class-based factory
  database/factories/TournamentFactory.php
  database/seeders/ModelSeeders/ProductSeeder.php
  tests/Browser/SanityTest.php
  tests/Libraries/Fulfillments/BannerFulfillmentTest.php
  tests/Libraries/OrderCheckoutTest.php
  tests/Models/TournamentTest.php
Labels: type:testing

#9642 Simplify proxy trusting logic
  app/Http/Kernel.php
  app/Providers/AppServiceProvider.php
  composer.json
  composer.lock
  config/trustedproxy.php
Labels: type:code-quality

#9543 Convert beatmapset discussion component to typescript
  .github/workflows/lint.yml
  resources/assets/lib/app-deps.ts
  resources/assets/lib/beatmap-discussions/discussion-vote-buttons.tsx
  resources/assets/lib/beatmap-discussions/discussion.coffee
  resources/assets/lib/beatmap-discussions/discussion.tsx
  resources/assets/lib/beatmap-discussions/editor-discussion-component.tsx
  resources/assets/lib/beatmap-discussions/new-discussion.tsx
  resources/assets/lib/beatmap-discussions/new-reply.tsx
  resources/assets/lib/beatmap-discussions/post.tsx
  resources/assets/lib/components/user-card-tooltip.tsx
  resources/assets/lib/components/user-list-popup.tsx
  resources/assets/lib/interfaces/beatmapset-discussion-json.ts
  resources/assets/lib/utils/beatmapset-discussion-helper.ts
Labels: type:code-quality

#9644 Return empty messages in chat updates for compatibility
  app/Http/Controllers/Chat/ChatController.php
Labels: area:chat

#9647 Ensure correct cast type for order item extra data
  app/Models/Store/OrderItem.php
Labels: area:store

#9649 Fix store line item closing tag
  resources/views/store/objects/order.blade.php
Labels: type:code-quality

#9651 Update docker to use latest LTS Ubuntu
  Dockerfile.deployment
  Dockerfile.development
Labels: type:code-quality

#9652 Update docs on docker compose
  DEPLOYMENT.md
  SETUP.md
  bin/docker_dev.sh
  docker/development/prepare.sh
Labels: type:documentation

#9612 Use memory for local cache
  .env.dusk.local.example
  .env.example
  .github/workflows/tests.yml
  app/Libraries/ChatFilters.php
  app/Libraries/Groups.php
  app/Libraries/LayoutCache.php
  app/Libraries/LocalCacheManager.php
  app/Listeners/OctaneResetLocalCache.php
  app/Models/Group.php
  app/Providers/AppServiceProvider.php
  app/Traits/LocallyCached.php
  app/Traits/Memoizes.php
  config/cache.php
  database/factories/UserFactory.php
  phpunit.xml
  tests/Browser/SanityTest.php
Labels: type:code-quality

#9646 Add support for including messages in supporter tag gifts
  app/Libraries/Fulfillments/SupporterTagFulfillment.php
  app/Mail/SupporterGift.php
  app/Models/Store/ExtraDataSupporterTag.php
  app/Models/Store/Order.php
  app/Models/Store/OrderItem.php
  resources/assets/less/bem/order-line-items.less
  resources/assets/less/bem/store-order-item.less
  resources/assets/less/bem/store-supporter-tag.less
  resources/assets/lib/core-legacy/store-supporter-tag.coffee
  resources/lang/en/mail.php
  resources/lang/en/store.php
  resources/views/emails/store/supporter_gift.blade.php
  resources/views/store/cart/_item.blade.php
  resources/views/store/objects/order.blade.php
  resources/views/store/products/supporter-tag.blade.php
  tests/Libraries/Fulfillments/SupporterTagFulfillmentTest.php
  tests/Models/Store/ExtraDataSupporterTagTest.php
Labels: area:store

#9659 Limit cron job task to single worker
  app/Console/Kernel.php
Labels: area:admin

#9660 Adjust country list in ranking page
  app/Http/Controllers/RankingController.php
  resources/assets/lib/components/ranking-filter.tsx
Labels: area:rankings

#9577 Support nesting modal dialog
  resources/assets/less/bem/beatmap-owner-editor.less
  resources/assets/less/variables.less
  resources/assets/lib/beatmap-discussions/beatmap-owner-editor.tsx
  resources/assets/lib/components/modal.tsx
Labels: type:ux

#9664 Update docker compose to use octane
  .github/workflows/tests.yml
  Dockerfile.development
  SETUP.md
  bin/run_dusk.sh
  docker-compose.yml
  docker/development/entrypoint.sh
  docker/development/nginx-default.conf
  docker/development/php-fpm.conf
  docker/development/prepare.sh
  public/index.php
Labels: area:tooling

#9668 Remove declaration of nonexistent helper object
  resources/assets/lib/globals.d.ts
Labels: type:code-quality

#9634 Reduce queries for notification bundle
  app/Libraries/NotificationsBundle.php
  resources/assets/lib/interfaces/notification-json.ts
  resources/assets/lib/models/notification-stack.ts
Labels: type:performance, area:notifications

#9672 Disable elasticsearch geoip downloader for docker compose
  .github/workflows/tests.yml
  docker-compose.yml
Labels: area:tooling

#9674 Always skip verification for preference update
  app/Http/Middleware/VerifyUser.php
Labels: area:user-profile

#9676 Only show published news posts for navigation
  app/Models/NewsPost.php
Labels: area:news

#9677 Update commonmark conversion function call
  app/Libraries/Markdown/OsuMarkdown.php
  app/helpers.php
Labels: type:code-quality

#9685 Add option to hide pinned solo scores
  .env.example
  app/Models/ScorePin.php
  config/osu.php
Labels: area:user-profile

#9696 Fix OAuth user check
  app/Http/Middleware/AuthApi.php
Labels: type:api
