Repository ppy/osu-web, pull requests merged in 2022-11, with the labels that each got.

#9446 Increase username reuse limit
  app/Models/User.php
Labels: area:user-profile, type:reliability

#9448 Accept uuid parameter for new PM
  app/Http/Controllers/Chat/ChatController.php
  resources/views/docs/_structures/chat_message.md
Labels: area:chat

#9430 Show contest vote percentage based on count of users who voted
  app/Models/Contest.php
  app/Transformers/ContestTransformer.php
  resources/assets/lib/contest-voting/art-entry-list.coffee
  resources/assets/lib/contest-voting/art-entry.coffee
  resources/assets/lib/contest-voting/entry-list.coffee
  resources/assets/lib/contest-voting/entry.coffee
Labels: area:contests

#9349 Update User phpdoc
  app/Models/DeletedUser.php
  app/Models/Traits/Reportable.php
  app/Models/User.php
  app/Models/UserNotFound.php
Labels: type:documentation

#9445 Update Achievement php doc block
  app/Models/Achievement.php
  app/Models/Beatmap.php
Labels: type:documentation

#9455 Fix locale for nonexistent user message
  app/Models/UserNotFound.php
Labels: area:user-profile

#9458 Use user preference for home beatmap listing
  resources/views/home/_user_beatmapset.blade.php
Labels: area:dashboard

#9468 Add note about user verification on token auth
  app/Http/Middleware/AuthApi.php
Labels: type:code-quality

#9469 Remove osu.promisify
  resources/assets/coffee/osu_common.coffee
  resources/assets/lib/core-legacy/store-checkout.coffee
  resources/assets/lib/globals.d.ts
  resources/assets/lib/store.ts
Labels: type:code-quality

#9474 Reset review editor cursor position after posting
  resources/assets/lib/beatmap-discussions/editor.tsx
Labels: area:beatmap-discussions, type:reliability

#9475 Convert osu.uuid to typescript
  resources/assets/coffee/osu_common.coffee
  resources/assets/lib/beatmap-discussions/review-post.tsx
  resources/assets/lib/globals.d.ts
  resources/assets/lib/models/chat/create-announcement.ts
  resources/assets/lib/models/chat/message.ts
  resources/assets/lib/utils/seq.ts
Labels: type:code-quality

#9476 Convert urlPresence to typescript
  resources/assets/coffee/osu_common.coffee
  resources/assets/lib/components/header-v4.tsx
  resources/assets/lib/components/track-preview.tsx
  resources/assets/lib/components/tracklist-track.tsx
  resources/assets/lib/components/user-avatar.tsx
  resources/assets/lib/contest-voting/art-entry.coffee
  resources/assets/lib/core-legacy/current-user-observer.coffee
  resources/assets/lib/core-legacy/forum-cover.coffee
  resources/assets/lib/follows-mapping/main.tsx
  resources/assets/lib/globals.d.ts
  resources/assets/lib/news-show/main.tsx
  resources/assets/lib/notification-widget/item.tsx
  resources/assets/lib/profile-page/badges.tsx
  resources/assets/lib/profile-page/cover-selection.tsx
  resources/assets/lib/profile-page/cover.tsx
  resources/assets/lib/quick-search/user.tsx
  resources/assets/lib/utils/css.ts
  resources/assets/lib/utils/html.ts
  tests/karma/utils/css.spec.ts
Labels: type:code-quality

#9478 Add missing asterisks in multiline comments
  app/Http/Controllers/BeatmapDiscussionPostsController.php
  app/Http/Controllers/BeatmapDiscussionsController.php
  app/Http/Controllers/BeatmapsetDiscussionVotesController.php
Labels: type:code-quality

#9479 Move group names to class declaration
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/Multiplayer/Rooms/Playlist/ScoresController.php
Labels: type:code-quality, type:documentation

#9477 Remove osu.focus()
  resources/assets/coffee/osu_common.coffee
  resources/assets/lib/beatmap-discussions/nominations.coffee
Labels: type:code-quality

#9480 Remove osu.isIos
  resources/assets/coffee/bootstrap-modal.coffee
  resources/assets/coffee/osu_common.coffee
Labels: type:code-quality

#9481 Query beatmapset description post once
  app/Models/Beatmapset.php
Labels: type:code-quality

#9483 Remove nulls before whereIn query in comment bundle
  app/Libraries/CommentBundle.php
  app/helpers.php
Labels: type:code-quality, area:comments

#9484 Remove ajaxError from osu_common
  resources/assets/coffee/osu_common.coffee
  resources/assets/coffee/ujs-common.coffee
  resources/assets/lib/admin/contest/user-entry-delete-button.coffee
  resources/assets/lib/beatmap-discussions/discussion.coffee
  resources/assets/lib/beatmap-discussions/nominations.coffee
  resources/assets/lib/beatmap-discussions/subscribe.coffee
  resources/assets/lib/components/comment.coffee
  resources/assets/lib/components/comments-manager.coffee
  resources/assets/lib/contest-entry/user-entry.coffee
  resources/assets/lib/contest-voting/voter.coffee
  resources/assets/lib/core-legacy/bbcode-preview.coffee
  resources/assets/lib/core-legacy/beatmap-pack.coffee
  resources/assets/lib/core-legacy/form-error.coffee
  resources/assets/lib/core-legacy/forum-topic-title.coffee
  resources/assets/lib/core-legacy/forum.coffee
  resources/assets/lib/core-legacy/store-checkout.coffee
  resources/assets/lib/utils/ajax.ts
Labels: type:code-quality

#9467 Refactor session verification
  app/Http/Controllers/Controller.php
  app/Http/Kernel.php
  app/Http/Middleware/SetSessionVerification.php
  app/Http/Middleware/UpdateUserLastvisit.php
  app/Http/Middleware/VerifyUser.php
  app/Http/Middleware/VerifyUserAlways.php
  app/Libraries/UserVerification.php
  app/Libraries/UserVerificationState.php
Labels: type:reliability

#9492 Fix non-json xhr error handling
  resources/assets/lib/utils/ajax.ts
Labels: type:reliability

#9491 Faster comment pagination
  app/Libraries/CommentBundle.php
Labels: type:performance, area:comments

#9495 Remove unused function
  resources/assets/coffee/osu_common.coffee
Labels: type:code-quality

#9494 Check beatmapset existence for score listing
  app/Models/Score/Model.php
  app/Models/ScorePin.php
Labels: area:user-profile, type:reliability

#9497 Convert osu.navigate to typescript
  resources/assets/coffee/main.coffee
  resources/assets/coffee/osu_common.coffee
  resources/assets/lib/artist-tracks-index/main.tsx
  resources/assets/lib/components/multiplayer-select-options.tsx
  resources/assets/lib/components/ranking-filter.tsx
  resources/assets/lib/components/wiki-search.tsx
  resources/assets/lib/core-legacy/forum-topic-reply.coffee
  resources/assets/lib/globals.d.ts
  resources/assets/lib/quick-search/main.tsx
  resources/assets/lib/utils/turbolinks.ts
Labels: type:code-quality

#9496 Convert osu.groupColour to typescript
  resources/assets/coffee/osu_common.coffee
  resources/assets/lib/beatmap-discussions/discussion.coffee
  resources/assets/lib/beatmap-discussions/user-card.tsx
  resources/assets/lib/beatmap-discussions/user-filter.coffee
  resources/assets/lib/components/user-card-brick.tsx
  resources/assets/lib/components/user-group-badge.tsx
  resources/assets/lib/css.d.ts
  resources/assets/lib/globals.d.ts
  resources/assets/lib/modding-profile/votes.coffee
  resources/assets/lib/utils/css.ts
  tests/karma/osu_common.spec.ts
  tests/karma/utils/css.spec.ts
Labels: type:code-quality

#9500 Convert presence and present to typescript
  resources/assets/coffee/osu_common.coffee
  resources/assets/lib/artist-tracks-index/search-form.tsx
  resources/assets/lib/artist-tracks-index/sort-bar.tsx
  resources/assets/lib/beatmap-discussions/editor-helpers.ts
  resources/assets/lib/beatmap-discussions/new-discussion.tsx
  resources/assets/lib/beatmap-discussions/new-reply.tsx
  resources/assets/lib/beatmap-discussions/nominations.coffee
  resources/assets/lib/beatmap-discussions/review-document.ts
  resources/assets/lib/beatmapset-search-filters.ts
  resources/assets/lib/beatmapsets-show/info.tsx
  resources/assets/lib/chat/input-box.tsx
  resources/assets/lib/components/big-button.tsx
  resources/assets/lib/components/circular-progress.tsx
  resources/assets/lib/components/header-v4.tsx
  resources/assets/lib/components/tracklist-track.tsx
  resources/assets/lib/components/user-card-tooltip.tsx
  resources/assets/lib/components/user-card.tsx
  resources/assets/lib/core-legacy/bbcode-preview.coffee
  resources/assets/lib/core-legacy/forum-topic-title.coffee
  resources/assets/lib/core-legacy/forum.coffee
  resources/assets/lib/core-legacy/tooltip-default.coffee
  resources/assets/lib/core/osu-audio/main.ts
  resources/assets/lib/globals.d.ts
  resources/assets/lib/models/chat/create-announcement.ts
  resources/assets/lib/models/notification.ts
  resources/assets/lib/profile-page/badges.tsx
  resources/assets/lib/profile-page/main.tsx
  resources/assets/lib/profile-page/user-page.tsx
  resources/assets/lib/utils/ajax.ts
  resources/assets/lib/utils/css.ts
  resources/assets/lib/utils/string.ts
  tests/karma/osu_common.spec.ts
  tests/karma/utils/string.spec.ts
Labels: type:code-quality

#9504 Add lint for spaces between curly braces
  .eslintrc.js
  resources/assets/lib/beatmap-discussions/autolink-plugin.ts
  resources/assets/lib/beatmap-discussions/disable-tokenizers-plugin.ts
  resources/assets/lib/beatmap-discussions/editor-beatmap-selector.tsx
  resources/assets/lib/beatmap-discussions/editor-insertion-menu.tsx
  resources/assets/lib/beatmap-discussions/editor-issue-type-selector.tsx
  resources/assets/lib/beatmap-discussions/editor-toolbar.tsx
  resources/assets/lib/beatmap-discussions/nominator.tsx
  resources/assets/lib/beatmap-discussions/review-post.tsx
  resources/assets/lib/beatmap-discussions/timestamp-plugin.ts
  resources/assets/lib/beatmapsets-show/beatmapset-menu.tsx
  resources/assets/lib/chat/chat-api.ts
  resources/assets/lib/chat/conversation-panel.tsx
  resources/assets/lib/chat/conversation-view.tsx
  resources/assets/lib/chat/message-divider.tsx
  resources/assets/lib/cli/generate-localizations.js
  resources/assets/lib/components/bbcode-editor.tsx
  resources/assets/lib/components/beatmapset-panel.tsx
  resources/assets/lib/components/landing-news.tsx
  resources/assets/lib/components/news-header.tsx
  resources/assets/lib/components/report-form.tsx
  resources/assets/lib/components/user-card-tooltip.tsx
  resources/assets/lib/components/user-group-badge.tsx
  resources/assets/lib/core/react-turbolinks.ts
  resources/assets/lib/friends-index/main.tsx
  resources/assets/lib/quick-search/worker.ts
Labels: type:code-quality

#8022 Implement new notification header design
  resources/assets/less/bem/nav-button.less
  resources/assets/less/bem/nav2.less
  resources/assets/less/bem/notification-icon.less
  resources/assets/lib/components/main-notification-icon.tsx
  resources/views/layout/_nav2.blade.php
  resources/views/layout/nav2/_locales.blade.php
Labels: type:design

#9503 Mark recent_messages as deprecated
  app/Http/Controllers/Chat/ChannelsController.php
  app/Transformers/Chat/ChannelTransformer.php
  resources/views/docs/_structures/chat_channel.md
  resources/views/docs/info.blade.php
Labels: area:chat

#9498 Show nominators on beatmap info page
  app/Http/Controllers/BeatmapsetsController.php
  app/Models/Beatmapset.php
  app/Models/BeatmapsetNomination.php
  app/Transformers/BeatmapsetCompactTransformer.php
  app/Transformers/BeatmapsetNominationTransformer.php
  resources/assets/less/bem/beatmapset-info.less
  resources/assets/lib/beatmapsets-show/info.tsx
  resources/assets/lib/interfaces/beatmapset-extended-json.ts
  resources/assets/lib/interfaces/beatmapset-json.ts
  resources/assets/lib/interfaces/beatmapset-nomination-json.ts
  resources/lang/en/beatmapsets.php
Labels: area:beatmap-info

#9502 Convert reloadPage and popup to typescript
  resources/assets/coffee/osu_common.coffee
  resources/assets/coffee/ujs-common.coffee
  resources/assets/lib/app-deps.ts
  resources/assets/lib/beatmaps/beatmapset-search-controller.ts
  resources/assets/lib/components/score-pin.tsx
  resources/assets/lib/contest-entry/uploader.coffee
  resources/assets/lib/core-legacy/forum-topic-title.coffee
  resources/assets/lib/core/user/user-login.ts
  resources/assets/lib/core/user/user-verification.ts
  resources/assets/lib/globals.d.ts
  resources/assets/lib/store.ts
  resources/assets/lib/utils/ajax.ts
  resources/assets/lib/utils/popup.ts
  resources/assets/lib/utils/turbolinks.ts
  resources/views/forum/topics/replace_button.blade.php
  resources/views/layout/ujs-reload.blade.php
Labels: type:code-quality

#9510 Return recent silences with chat ack
  app/Http/Controllers/Chat/ChatController.php
  app/Models/UserAccountHistory.php
Labels: area:chat

#9518 Fix notification popup not correctly hid
  resources/views/layout/_nav2.blade.php
Labels: type:ux

#9515 Limit chat ack silences to last hour
  app/Models/UserAccountHistory.php
Labels: area:chat

#9514 Remove unused helpers
  app/helpers.php
Labels: type:code-quality

#9444 Add basic support for nominated beatmaps profile display
  app/Http/Controllers/UsersController.php
  app/Models/User.php
  app/Transformers/UserCompactTransformer.php
  database/migrations/2022_11_12_103015_index_user_id_on_beatmapset_nominations.php
  resources/assets/lib/interfaces/user-json.ts
  resources/assets/lib/profile-page/beatmapsets.tsx
  resources/assets/lib/profile-page/controller.tsx
  resources/assets/lib/profile-page/extra-page-props.ts
  resources/lang/en/users.php
Labels: area:user-profile

#9513 Preload channel data
  app/Http/Controllers/Chat/ChatController.php
  app/Libraries/UserChannelList.php
Labels: type:performance, area:chat

#9521 Check type before parsing local storage userPreferences
  .github/workflows/lint.yml
  resources/assets/lib/core/user/user-preferences.ts
Labels: type:code-quality

#9524 Clean up Report Form component
  resources/assets/lib/components/report-form.tsx
  resources/assets/lib/components/report-reportable.tsx
Labels: type:code-quality

#9528 Fix variable and function return typings in Command classes
  app/Console/Commands/ChatChannelSetLastMessageId.php
  app/Console/Commands/MigrateFreshAllCommand.php
  app/Console/Commands/MigrateFreshOrRunCommand.php
Labels: type:code-quality

#9530 Typescript Modal component
  resources/assets/lib/beatmap-discussions/nominations.coffee
  resources/assets/lib/beatmap-discussions/nominator.tsx
  resources/assets/lib/beatmapsets-show/info.tsx
  resources/assets/lib/coffee-modules.d.ts
  resources/assets/lib/components/modal.coffee
  resources/assets/lib/components/modal.tsx
  resources/assets/lib/components/quick-search-button.tsx
  resources/assets/lib/components/report-form.tsx
  resources/assets/lib/modal-helper.ts
  resources/assets/lib/oauth/own-clients.tsx
Labels: type:code-quality

#9538 Fix missing translations
  resources/assets/lib/utils/lang.ts
Labels: type:localisation

#9537 Hot fix solo scores leaderboard when extra scores need to be fetched
  app/Libraries/Elasticsearch/Search.php
  app/Libraries/Score/FetchDedupedScores.php
Labels: area:beatmap-info

#9540 Fix tournament banner size on other user profile tabs
  resources/assets/lib/modding-profile/main.coffee
  resources/assets/lib/user-multiplayer-index/main.tsx
Labels: area:user-profile

#9542 Add missing export for type definition
  resources/assets/lib/utils/lang.ts
Labels: type:code-quality

#9546 Add max banner height
  resources/assets/less/bem/profile-tournament-banner.less
Labels: type:design

#9545 Enable ESLint strict-boolean-expressions
  .eslintrc.js
  resources/assets/lib/beatmap-discussions/discussion-type.ts
  resources/assets/lib/beatmap-discussions/editor-helpers.ts
  resources/assets/lib/beatmap-discussions/editor-toolbar.tsx
  resources/assets/lib/beatmap-discussions/icon-dropdown-menu.tsx
  resources/assets/lib/beatmap-discussions/new-discussion.tsx
  resources/assets/lib/beatmap-discussions/nominator.tsx
  resources/assets/lib/beatmap-discussions/review-document.ts
  resources/assets/lib/store.ts
Labels: type:code-quality

#9548 Remove unused job
  app/Jobs/EsIndexDocument.php
Labels: type:code-quality

#9547 Add typing for contest vote button state
  .github/workflows/lint.yml
  resources/assets/lib/components/gallery-contest-vote-button.tsx
Labels: type:code-quality

#9550 Simplify discussion transformer return
  app/Transformers/BeatmapDiscussionTransformer.php
Labels: type:code-quality

#9555 Add command to create initial databases
  .github/workflows/tests.yml
  SETUP.md
  app/Console/Commands/DbCreate.php
  app/Console/Commands/DbSetup.php
  app/Console/Commands/MigrateFreshOrRunCommand.php
  app/Console/Kernel.php
  build.sh
  docker-compose.yml
  docker/development/db_setup.sql
  docker/development/entrypoint.sh
Labels: area:tooling

#9554 Add redis port mapping in `docker-compose` configuration
  docker-compose.yml
Labels: area:tooling

#9564 Configurable max friends settings
  .env.example
  config/osu.php
Labels: type:code-quality
