Repository ppy/osu-web, pull requests merged in 2022-09, with the labels that each got.

#9235 Add auto skip to multiplayer rooms
  app/Models/Multiplayer/Room.php
  app/Transformers/Multiplayer/RoomTransformer.php
  database/migrations/2022_08_31_102024_add_auto_skip_to_multiplayer_rooms.php
Labels: area:multiplayer

#9241 Update env name for score indexer service
  .github/workflows/tests.yml
Labels: type:testing

#9236 Remove api-only controller namespace
  app/Http/Controllers/API/BeatmapsetsController.php
  app/Http/Controllers/API/Controller.php
  app/Http/Controllers/BeatmapsetsController.php
  routes/web.php
  tests/api_routes.json
Labels: type:code-quality

#9234 Add perfect combo check for solo scores
  resources/assets/lib/interfaces/solo-score-json.ts
  resources/assets/lib/utils/score-helper.ts
Labels: area:scoring

#9250 Queue beatmapset for bss process when ranked
  app/Models/Beatmapset.php
  app/Models/BssProcessQueue.php
  tests/Models/BeatmapsetTest.php
Labels: area:beatmap-processing

#9256 Add contest vote requirement
  app/Http/Controllers/ContestsController.php
  app/Models/Contest.php
  resources/lang/en/contest.php
  resources/views/contests/voting.blade.php
  tests/Models/ContestTest.php
Labels: area:contests

#9254 Reindex solo scores as part of user reindex
  app/Http/Controllers/LegacyInterOpController.php
Labels: area:scoring

#9259 Only restrict entry display during voting period
  app/Http/Controllers/ContestsController.php
Labels: area:contests

#9264 Add migration changing all `score_id`s to `BIGINT`
  database/migrations/2022_09_09_011035_upgrade_legacy_scoreids_to_bigint.php
Labels: type:database

#9260 Use non-redirect beatmap url
  resources/assets/lib/beatmapsets-show/main.tsx
  resources/assets/lib/profile-page/beatmap-playcount.tsx
  resources/assets/lib/profile-page/play-detail.tsx
  resources/assets/lib/utils/beatmapset-page-hash.ts
  resources/assets/lib/utils/url.ts
Labels: type:ux

#9261 Remove unused broken `UserReport#score` relation
  app/Models/UserReport.php
Labels: type:code-quality

#9266 Add migration for `osu_beatmap_performance_blacklist`
  database/migrations/2022_09_09_080211_create_osu_beatmap_performance_blacklist.php
Labels: type:database

#9262 Uniform `getClass` between UserStatistics and Score
  app/Http/Controllers/BeatmapsController.php
  app/Http/Controllers/LegacyInterOpController.php
  app/Http/Controllers/ScoresController.php
  app/Jobs/RemoveBeatmapsetBestScores.php
  app/Libraries/Search/BeatmapsetSearch.php
  app/Libraries/User/ScorePins.php
  app/Libraries/UserBestScoresCheck.php
  app/Models/Score/Model.php
  app/Models/Solo/Score.php
  app/Models/Spotlight.php
  app/Models/Traits/UserScoreable.php
  app/Models/UserStatistics/Model.php
  database/seeders/ModelSeeders/SpotlightSeeder.php
  tests/Controllers/BeatmapsControllerTest.php
  tests/Controllers/Solo/ScoresControllerTest.php
  tests/Models/Score/Best/ModelTest.php
  tests/Models/Score/ModelTest.php
Labels: type:code-quality

#9268 Stop previous test run on new push to same branch/PR
  .github/workflows/lint.yml
  .github/workflows/tests.yml
Labels: type:testing

#9269 Remove `get_model_basename` helper
  app/Transformers/KudosuHistoryTransformer.php
  app/helpers.php
Labels: type:code-quality

#9273 Remove link nesting
  resources/assets/less/bem/beatmap-discussions-header-top.less
  resources/assets/lib/beatmap-discussions/header.coffee
Labels: type:design

#9274 Add scope to remove order in a query
  app/Models/Model.php
  app/Models/Score/Best/Model.php
Labels: type:code-quality

#9267 Use mod names from data JSON
  .gitignore
  resources/assets/build/.keep
  resources/assets/lib/cli/mod-names-generator.js
  resources/assets/lib/components/mod.tsx
  resources/assets/lib/globals.d.ts
  resources/assets/lib/utils/score-helper.ts
  resources/lang/en/beatmaps.php
  tsconfig.json
  webpack.config.js
  webpack.unmix.js
Labels: type:ux

#9282 Order returned beatmaps by id
  app/Http/Controllers/BeatmapsController.php
Labels: type:testing

#9281 Fix docker deployment build
  .dockerignore
  resources/assets/build/.keep
  resources/assets/lib/cli/mod-names-generator.js
Labels: area:tooling

#9278 Redirect old tumblr news post urls
  app/Http/Controllers/NewsController.php
  database/migrations/2022_09_13_080115_index_news_posts_tumblr_id.php
  resources/assets/lib/utils/url.ts
  routes/web.php
Labels: area:news

#9277 Don't report error if token isn't configured
  app/Models/LivestreamCollection.php
  config/osu.php
Labels: type:code-quality

#9224 Convert more beatmapset discussion helpers to typescript
  resources/assets/coffee/_classes/beatmap-discussion-helper.coffee
  resources/assets/lib/beatmap-discussions/chart.tsx
  resources/assets/lib/beatmap-discussions/discussion.coffee
  resources/assets/lib/beatmap-discussions/editor-discussion-component.tsx
  resources/assets/lib/beatmap-discussions/editor-helpers.ts
  resources/assets/lib/beatmap-discussions/editor.tsx
  resources/assets/lib/beatmap-discussions/main.coffee
  resources/assets/lib/beatmap-discussions/new-discussion.tsx
  resources/assets/lib/beatmap-discussions/review-document.ts
  resources/assets/lib/beatmap-discussions/review-post-embed.tsx
  resources/assets/lib/globals.d.ts
  resources/assets/lib/utils/beatmapset-discussion-helper.ts
  tests/karma/utils/beatmapset-discussion-helper.spec.ts
Labels: type:code-quality

#9291 Better beatmap scoreboard performance on mobile Safari
  resources/assets/less/utilities.less
  resources/assets/lib/beatmapsets-show/scoreboard/table-row.tsx
Labels: type:performance, area:beatmap-info

#9298 Faster and less blurry flags
  resources/assets/less/bem/flag-country.less
  resources/assets/less/utilities.less
  resources/assets/lib/beatmapsets-show/scoreboard/table-row.tsx
Labels: type:performance

#9147 Elasticsearch 8 support
  .github/workflows/tests.yml
  app/Console/Commands/EsCreateSearchBlacklist.php
  app/Jobs/EsIndexDocumentBulk.php
  app/Libraries/Elasticsearch/SearchResponse.php
  app/Libraries/Search/BeatmapsetSearch.php
  app/Models/Traits/Es/BaseDbIndexable.php
  app/Models/Traits/Es/BaseIndexable.php
  app/Models/Wiki/Page.php
  config/schemas/artist_tracks.json
  config/schemas/beatmapsets.json
  config/schemas/posts.json
  config/schemas/users.json
  config/schemas/wiki_page.json
  docker-compose.yml
Labels: area:search

#9295 Add migration for `osu_difficulty_attribs` table
  database/migrations/2022_09_21_052117_create_osu_difficulty_attribs.php
Labels: type:database

#9306 Remove solo scores on beatmap state change
  app/Jobs/RemoveBeatmapsetSoloScores.php
  app/Models/Beatmapset.php
  tests/Jobs/RemoveBeatmapsetSoloScoresTest.php
  tests/TestCase.php
Labels: area:scoring

#9308 Skip rebuilding redundant transformer includes
  app/Http/Controllers/UsersController.php
  app/Transformers/UserCompactTransformer.php
Labels: area:user-profile

#9310 Missing No Mod tooltip
  resources/assets/lib/cli/mod-names-generator.js
  resources/assets/lib/utils/score-helper.ts
Labels: area:beatmap-info

#9309 Skip refetching same user from database
  app/Http/Controllers/UsersController.php
  app/Transformers/ScoreTransformer.php
Labels: area:user-profile, type:performance

#9315 Fix empty elasticsearch response
  app/Libraries/Elasticsearch/SearchResponse.php
Labels: type:code-quality

#9265 Add score indexer to docker-compose
  docker-compose.yml
  docker/development/entrypoint.sh
Labels: area:tooling

#9287 Sideload beatmapsets in bundle instead of embedding in discussions
  app/Libraries/BeatmapsetDiscussionsBundle.php
  app/Libraries/ModdingHistoryEventsBundle.php
  resources/assets/lib/beatmap-discussions-history/main.coffee
  resources/assets/lib/beatmap-discussions/beatmapsets-context.ts
  resources/assets/lib/entrypoints/beatmap-discussions-history.coffee
  resources/assets/lib/entrypoints/modding-profile.coffee
  resources/assets/lib/interfaces/beatmapset-discussion-json.ts
  resources/assets/lib/modding-profile/discussions.coffee
  resources/assets/lib/modding-profile/main.coffee
Labels: area:user-profile, area:beatmap-discussions

#9318 Skip laravel casting for beatmap and beatmapset transformers
  app/Models/Beatmap.php
  app/Models/Beatmapset.php
  app/Transformers/BeatmapCompactTransformer.php
  app/Transformers/BeatmapTransformer.php
  app/Transformers/BeatmapsetCompactTransformer.php
  app/Transformers/BeatmapsetTransformer.php
  app/helpers.php
Labels: type:performance
