Repository ppy/osu-web, pull requests merged in 2022-02, with the labels that each got.

#8572 Show different text for empty lists of different game types
  resources/assets/lib/user-multiplayer-index/multiplayer-history.tsx
  resources/lang/en/multiplayer.php
Labels: area:user-profile

#8573 Disable autolink extension in wiki
  app/Libraries/Markdown/OsuMarkdown.php
Labels: area:wiki

#8571 Force wrap room name
  resources/assets/less/bem/multiplayer-room.less
Labels: area:user-profile

#8575 Use dedicated plugin for TypeScript type check
  package.json
  webpack.unmix.js
  yarn.lock
Labels: area:tooling

#8550 Simplify user settings object
  app/Models/UserProfileCustomization.php
Labels: type:code-quality

#8523 Listen to browser pause event
  resources/assets/lib/core/osu-audio/main.ts
Labels: type:ux, type:reliability

#8480 Add string cursor for beatmapset listing
  app/Http/Controllers/BeatmapsetsController.php
  app/Libraries/Search/BeatmapsetSearchRequestParams.php
  app/helpers.php
  resources/assets/lib/beatmaps/beatmapset-search.ts
  resources/assets/lib/beatmaps/result-set.ts
Labels: type:api

#8501 Add string cursor for beatmapset discussion
  app/Http/Controllers/BeatmapDiscussionPostsController.php
  app/Http/Controllers/BeatmapDiscussionsController.php
  app/Http/Controllers/BeatmapsetDiscussionVotesController.php
  app/Libraries/BeatmapsetDiscussionPostsBundle.php
  app/Libraries/BeatmapsetDiscussionVotesBundle.php
  app/Libraries/BeatmapsetDiscussionsBundle.php
  app/Models/BeatmapDiscussion.php
  app/Models/BeatmapDiscussionPost.php
  app/Models/BeatmapDiscussionVote.php
  resources/views/docs/_structures/cursor.md
  resources/views/docs/_structures/cursor_string.md
Labels: area:beatmap-discussions, type:code-quality

#8521 Simplify popup menu button css
  resources/assets/less/bem/popup-menu.less
  resources/assets/lib/popup-menu.coffee
Labels: type:code-quality

#8558 Remove extra gap between beatmap page sections
  resources/assets/coffee/react/beatmapset-page/main.coffee
Labels: type:design

#8578 Fix 24h osu!catch scores from lazer missing count50 values
  app/Models/Solo/Score.php
Labels: area:scoring

#8559 Simplify beatmap discussion page structure
  resources/assets/coffee/react/beatmap-discussions/main.coffee
  resources/assets/less/bem/beatmap-discussion-new-float.less
  resources/assets/less/bem/osu-layout.less
Labels: type:code-quality

#8561 Add support for country flags in markdown
  app/Libraries/Markdown/Attributes/AttributesAllowedListener.php
  app/Libraries/Markdown/CustomContainerInline/Element.php
  app/Libraries/Markdown/CustomContainerInline/Extension.php
  app/Libraries/Markdown/CustomContainerInline/Parser.php
  app/Libraries/Markdown/CustomContainerInline/Renderer.php
  app/Libraries/Markdown/Indexing/Extension.php
  app/Libraries/Markdown/Osu/Extension.php
  app/Libraries/Markdown/OsuMarkdown.php
  resources/assets/less/bem/flag-country.less
  tests/Libraries/Markdown/ProcessorTest.php
  tests/Libraries/Markdown/html_markdown_examples/attribute.html
  tests/Libraries/Markdown/html_markdown_examples/attribute_flag.html
  tests/Libraries/Markdown/html_markdown_examples/attribute_flag.md
  tests/Libraries/Markdown/html_markdown_examples/custom_container_inline.html
  tests/Libraries/Markdown/html_markdown_examples/custom_container_inline.md
  tests/Libraries/Markdown/html_markdown_examples/custom_container_inline_invalid.html
  tests/Libraries/Markdown/html_markdown_examples/custom_container_inline_invalid.md
  tests/Libraries/Markdown/indexable_markdown_examples/attribute_flag.md
  tests/Libraries/Markdown/indexable_markdown_examples/attribute_flag.txt
  tests/Libraries/Markdown/indexable_markdown_examples/custom_container_inline.md
  tests/Libraries/Markdown/indexable_markdown_examples/custom_container_inline.txt
  tests/Libraries/Markdown/indexable_markdown_examples/custom_container_inline_invalid.md
  tests/Libraries/Markdown/indexable_markdown_examples/custom_container_inline_invalid.txt
Labels: area:wiki

#8491 Add string cursor for forum topics
  app/Http/Controllers/Forum/TopicsController.php
  resources/assets/coffee/main.coffee
  resources/assets/lib/core-legacy/forum.coffee
  resources/assets/lib/entrypoints/app.ts
  resources/views/forum/topics/show.blade.php
Labels: type:api

#8589 Add support for new lazer mods
  app/Libraries/Multiplayer/Mod.php
Labels: area:scoring

#8593 Fix saving user settings when the options column is null
  app/Models/UserProfileCustomization.php
Labels: type:reliability

#8591 Additional class-based factories for discussion-related tests
  database/factories/BeatmapDiscussionPostFactory.php
  database/factories/BeatmapsetFactory.php
  database/factories/UserFactory.php
  database/factories/UserStatistics/FruitsFactory.php
  database/factories/UserStatistics/ManiaFactory.php
  database/factories/UserStatistics/ModelFactory.php
  database/factories/UserStatistics/OsuFactory.php
  database/factories/UserStatistics/TaikoFactory.php
  tests/BeatmapsetDisqualifyNotificationsTest.php
  tests/BeatmapsetEventNominationResetTest.php
  tests/BroadcastNotificationTest.php
  tests/Browser/BeatmapDiscussionPostsTest.php
  tests/Commands/NotificationsSendMailTest.php
  tests/Controllers/BeatmapDiscussionPostsControllerTest.php
  tests/Controllers/BeatmapDiscussionsControllerTest.php
  tests/Controllers/Chat/Channels/MessagesControllerTest.php
  tests/Controllers/Chat/ChatControllerTest.php
  tests/Controllers/CommentsControllerTest.php
  tests/Transformers/BeatmapDiscussionPostTransformerTest.php
  tests/Transformers/BeatmapDiscussionTransformerTest.php
  tests/Transformers/BeatmapsetEventTransformerTest.php
Labels: type:testing, type:code-quality

#8594 Temporarily disable inline container for wiki markdown
  app/Libraries/Markdown/OsuMarkdown.php
Labels: type:reliability

#8602 Add test for user settings update
  tests/Models/UserProfileCustomizationTest.php
Labels: type:testing

#8590 Clean up user list page styling
  resources/assets/less/bem/user-card-brick.less
  resources/assets/less/bem/user-list.less
  resources/assets/lib/friends-index/main.tsx
  resources/assets/lib/groups-show/main.tsx
  resources/views/friends/index.blade.php
  resources/views/groups/show.blade.php
Labels: type:design

#8588 Move constant variable outside of class definition
  resources/assets/coffee/react/modding-profile/stats.coffee
Labels: type:code-quality

#8557 New page extra style
  resources/assets/coffee/react/modding-profile/main.coffee
  resources/assets/coffee/react/modding-profile/posts.coffee
  resources/assets/less/bem/bbcode-editor.less
  resources/assets/less/bem/beatmap-discussion.less
  resources/assets/less/bem/beatmap-playcount.less
  resources/assets/less/bem/beatmapset-panel.less
  resources/assets/less/bem/medals-group.less
  resources/assets/less/bem/modding-profile-vote-card.less
  resources/assets/less/bem/osu-page.less
  resources/assets/less/bem/page-extra-tabs.less
  resources/assets/less/bem/page-extra.less
  resources/assets/less/bem/page-mode-link.less
  resources/assets/less/bem/page-mode.less
  resources/assets/less/bem/play-detail.less
  resources/assets/less/bem/user-profile-pages.less
  resources/assets/lib/components/profile-page-extra-tab.tsx
  resources/assets/lib/profile-page/main.tsx
  resources/assets/lib/profile-page/medals.tsx
  resources/assets/lib/user-multiplayer-index/main.tsx
Labels: type:design

#8612 Skip calling Beatmapset factory with discussion default
  tests/Browser/SanityTest.php
  tests/Controllers/BeatmapDiscussionsControllerTest.php
  tests/Libraries/BeatmapsetDiscussionReviewTest.php
  tests/Models/BeatmapDiscussionPostTest.php
  tests/Models/BeatmapDiscussionTest.php
  tests/Models/BeatmapsetTest.php
Labels: type:testing, type:code-quality

#8611 Move beatmapset events listing to components directory
  resources/assets/coffee/react/beatmap-discussions/events.coffee
  resources/assets/coffee/react/modding-profile/events.coffee
  resources/assets/lib/components/beatmapset-event.tsx
  resources/assets/lib/components/beatmapset-events.tsx
  resources/assets/lib/register-components.coffee
Labels: type:code-quality

#8604 More discussion-related test cleanups
  tests/Controllers/BeatmapDiscussionsControllerTest.php
  tests/TestCase.php
Labels: type:testing

#8585 Remove content section check on default layout
  resources/views/master.blade.php
Labels: type:code-quality

#8603 Typescript Scoreboard Tab component
  resources/assets/coffee/react/beatmapset-page/scoreboard-tab.coffee
  resources/assets/coffee/react/beatmapset-page/scoreboard.coffee
  resources/assets/lib/beatmapsets-show/scoreboard-tab.tsx
Labels: type:code-quality, area:beatmap-info

#8605 Typescript Scoreboard Table Row component
  resources/assets/coffee/react/beatmapset-page/scoreboard-table-row.coffee
  resources/assets/coffee/react/beatmapset-page/scoreboard-table.coffee
  resources/assets/lib/beatmapsets-show/scoreboard-table-row.tsx
  resources/assets/lib/components/friend-button.tsx
  resources/assets/lib/core/user/user-model.ts
  resources/assets/lib/interfaces/score-json.ts
  resources/assets/lib/osu-core.ts
Labels: type:code-quality, area:beatmap-info, type:reliability

#8606 Typescript Scoreboard Table component
  resources/assets/coffee/react/beatmapset-page/scoreboard-table.coffee
  resources/assets/coffee/react/beatmapset-page/scoreboard.coffee
  resources/assets/lib/beatmapsets-show/scoreboard-tab.tsx
  resources/assets/lib/beatmapsets-show/scoreboard-table.tsx
  resources/assets/lib/beatmapsets-show/scoreboard-type.ts
Labels: type:code-quality, area:beatmap-info

#8584 Send notification when unresolved discussion is replied to
  app/Http/Controllers/BeatmapDiscussionPostsController.php
  app/Jobs/Notifications/BeatmapsetDiscussionPostNotification.php
Labels: area:beatmap-discussions, area:notifications

#8615 Remove unused old beatmap score helper
  resources/assets/coffee/_classes/hits.coffee
  resources/assets/lib/entrypoints/app.ts
Labels: type:code-quality

#8574 Improve user search ordering
  app/Libraries/Search/UserSearchRequestParams.php
Labels: area:search

#8629 Filter score pins by user
  app/Libraries/User/ScorePins.php
Labels: area:user-profile, type:performance

#8616 Add model keys to elasticsearch index fields
  app/Models/Traits/Es/BeatmapsetSearch.php
  app/Models/Traits/Es/UserSearch.php
  config/schemas/artist_tracks.json
  config/schemas/beatmapsets.json
  config/schemas/users.json
  config/schemas/wiki_page.json
Labels: area:search, type:code-quality

#8609 Improve scoreboard error handling
  resources/assets/coffee/react/beatmapset-page/main.coffee
  resources/assets/lib/beatmapsets-show/scoreboard.tsx
  resources/lang/en/beatmapsets.php
  resources/lang/en/common.php
Labels: type:ux, area:beatmap-info

#8627 Add confirmation for reporting problem on qualified maps
  resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
  resources/lang/en/beatmaps.php
Labels: area:beatmap-discussions, type:ux

#7814 Include poll data in forum topic JSON
  app/Libraries/OsuAuthorize.php
  app/Models/Forum/PollOption.php
  app/Models/Forum/Topic.php
  app/Models/Forum/TopicPoll.php
  app/Transformers/Forum/PollOptionTransformer.php
  app/Transformers/Forum/PollTransformer.php
  app/Transformers/Forum/TopicTransformer.php
  composer.json
  database/factories/Forum/PollOptionFactory.php
  database/factories/ForumFactory.php
  resources/views/docs/_structures/forum_topic.md
  tests/Transformers/PollOptionTransformerTest.php
  tests/Transformers/TopicTransformerTest.php
Labels: area:forum, type:api

#8630 Specify polymorphic target for relation query
  app/Models/ScorePin.php
Labels: type:performance

#8633 Add count change expectation test helper
  tests/Models/Multiplayer/RoomTest.php
  tests/TestCase.php
Labels: type:testing

#8636 Normalise score id before adding it to pinned array
  resources/assets/lib/profile-page/controller.tsx
Labels: area:user-profile, type:reliability

#8635 Restructure rooms listing
  app/Http/Controllers/Multiplayer/RoomsController.php
  app/Models/Multiplayer/Room.php
  app/Transformers/Multiplayer/RoomTransformer.php
  app/helpers.php
Labels: type:api, area:multiplayer

#8645 Don't load empty url with Img2x
  resources/assets/lib/components/img2x.tsx
Labels: type:code-quality

#8644 Beatmapsets wip pending filtering
  app/Libraries/Search/BeatmapsetSearch.php
  app/Libraries/Search/BeatmapsetSearchRequestParams.php
  resources/assets/coffee/_classes/beatmapset-filter.coffee
  resources/assets/lib/beatmaps/search-sort.coffee
  resources/lang/en/beatmaps.php
Labels: area:beatmap-listing, area:search

#8642 More restructure room listing json
  app/Http/Controllers/Multiplayer/RoomsController.php
  app/Http/Controllers/Users/MultiplayerController.php
  app/Models/Multiplayer/PlaylistItem.php
  app/Models/Multiplayer/Room.php
  app/Transformers/Multiplayer/RoomTransformer.php
  app/helpers.php
  resources/assets/lib/interfaces/beatmap-json.ts
  resources/assets/lib/interfaces/playlist-item-json.ts
  resources/assets/lib/interfaces/room-json.ts
  resources/assets/lib/interfaces/user-multiplayer-history-json.ts
  resources/assets/lib/user-multiplayer-index/multiplayer-history-store.ts
  resources/assets/lib/user-multiplayer-index/room.tsx
Labels: type:api, area:multiplayer

#8617 Remove sorting by _id field
  app/Console/Commands/EsIndexWiki.php
  app/Libraries/Elasticsearch/HasSearch.php
  app/Libraries/Search/ArtistTrackSearchParams.php
  app/Libraries/Search/BeatmapsetSearchRequestParams.php
  app/Libraries/Wiki/WikiSitemap.php
  tests/Libraries/Search/BeatmapsetSearchRequestParamsTest.php
Labels: type:performance, area:search, type:code-quality

#8658 Fix popup hover area
  resources/assets/less/layout.less
Labels: type:ux

#8657 Fix removal of popup message element after fading out
  resources/assets/coffee/shared.coffee
Labels: type:reliability

#8610 Typescript landing user stats chart component
  resources/assets/coffee/_classes/landing-graph.coffee
  resources/assets/coffee/_classes/landing-user-stats.coffee
  resources/assets/lib/charts/landing-user-stats.ts
  resources/assets/lib/entrypoints/app.ts
Labels: type:code-quality

#8632 Skip loading unused user data for forum topic json response
  app/Http/Controllers/Forum/TopicsController.php
Labels: area:forum, type:api, type:performance

#8655 Always show explicit beatmap filter option
  resources/assets/lib/beatmaps/search-panel.coffee
Labels: area:beatmap-listing, type:ux

#8634 Use existing topic first post data
  app/Libraries/OsuAuthorize.php
  app/Models/Forum/Topic.php
  tests/Browser/SanityTest.php
  tests/Controllers/ForumTopicsControllerTest.php
Labels: area:forum

#8640 Fix test to account for unexpected network errors
  tests/Browser/SanityTest.php
Labels: type:testing, type:reliability

#8625 Add endpoint to retrieve all scores of a user on a beatmap
  app/Http/Controllers/BeatmapsController.php
  routes/web.php
  tests/api_routes.json
Labels: type:api, area:beatmap-info

#8664 Change password reset emails to not urge the user to reply
  resources/lang/en/mail.php
  resources/views/emails/password_reset.blade.php
Labels: type:localisation
