Repository ppy/osu-web, pull requests merged in 2022-05, with the labels that each got.

#8848 Fix interop signature check
  app/Http/Middleware/LegacyInterOpAuth.php
Labels: area:admin

#8851 Link to post for beatmap discussion notifications
  resources/assets/coffee/_classes/beatmap-discussion-helper.coffee
  resources/assets/lib/notification-maps/url.ts
Labels: area:notifications

#8816 Prevent scroll jump when keyword input box is in focus
  resources/assets/lib/beatmaps/search-panel.coffee
Labels: area:beatmap-listing, type:ux

#8863 Remove osu.ajaxError from typescript and fix missing mobx action
  resources/assets/lib/artist-tracks-index/main.tsx
  resources/assets/lib/beatmap-discussions/editor.tsx
  resources/assets/lib/beatmap-discussions/love-beatmap-modal.tsx
  resources/assets/lib/beatmap-discussions/nominator.tsx
  resources/assets/lib/beatmaps/main.tsx
  resources/assets/lib/beatmapsets-show/metadata-editor.tsx
  resources/assets/lib/components/report-reportable.tsx
  resources/assets/lib/globals.d.ts
  resources/assets/lib/models/oauth/client.ts
  resources/assets/lib/models/oauth/own-client.ts
  resources/assets/lib/notifications/notification-resolver.ts
  resources/assets/lib/oauth/authorized-client.tsx
  resources/assets/lib/oauth/client-details.tsx
  resources/assets/lib/oauth/own-client.tsx
  resources/assets/lib/stores/channel-store.ts
  resources/assets/lib/utils/ajax.ts
Labels: type:code-quality, javascript

#8827 Unify user list popup
  resources/assets/less/bem/qtip.less
  resources/assets/less/bem/user-list-popup.less
  resources/assets/lib/beatmap-discussions/discussion.coffee
  resources/assets/lib/beatmapsets-show/header.coffee
  resources/assets/lib/components/user-link.tsx
  resources/assets/lib/components/user-list-popup.tsx
Labels: type:code-quality, javascript

#8878 Update source for perfect combo score highlight
  resources/assets/lib/beatmapsets-show/score-top.tsx
  resources/assets/lib/beatmapsets-show/scoreboard-table-row.tsx
  resources/assets/lib/scores-show/stats.tsx
  resources/assets/lib/utils/score-helper.ts
Labels: area:scoring

#8817 Remove unused gutter variable for profile page
  resources/assets/less/bem/header-v4.less
  resources/assets/less/bem/page-extra.less
  resources/assets/less/bem/profile-links.less
  resources/assets/less/variables.less
Labels: area:user-profile, type:code-quality

#8858 Beatmap owner editor lookup fixes
  app/Http/Controllers/UsersController.php
  resources/assets/lib/beatmap-discussions/beatmap-owner-editor.tsx
  resources/assets/lib/beatmap-discussions/beatmaps-owner-editor.tsx
  resources/assets/lib/models/user.ts
Labels: area:beatmap-discussions

#8887 Fix routing for download quota check
  routes/web.php
  tests/Controllers/HomeControllerTest.php
  tests/api_routes.json
Labels: type:api

#8829 Typescript beatmap header component
  resources/assets/lib/beatmapsets-show/header.coffee
  resources/assets/lib/beatmapsets-show/header.tsx
  resources/assets/lib/beatmapsets-show/main.coffee
Labels: type:code-quality, area:beatmap-info, javascript

#8892 Remove wait for preference setting update
  resources/assets/lib/beatmapsets-show/nsfw-warning.tsx
Labels: area:beatmap-info

#8890 Simplify int parsing
  resources/assets/lib/beatmapsets-show/metadata-editor.tsx
Labels: type:code-quality

#8768 Add support for adding spotlight label to beatmaps
  app/Libraries/Search/BeatmapsetSearch.php
  app/Libraries/Search/BeatmapsetSearchParams.php
  app/Libraries/Search/BeatmapsetSearchRequestParams.php
  app/Models/Beatmapset.php
  app/Transformers/BeatmapsetCompactTransformer.php
  config/schemas/beatmapsets.json
  database/migrations/2022_04_30_152502_add_spotlight_to_beatmapsets.php
  resources/assets/less/bem/beatmapset-badge.less
  resources/assets/less/bem/beatmapset-panel.less
  resources/assets/lib/beatmap-discussions/header.coffee
  resources/assets/lib/beatmapsets-show/header.tsx
  resources/assets/lib/components/beatmapset-panel.tsx
  resources/assets/lib/interfaces/beatmapset-json.ts
  resources/lang/en/beatmaps.php
  resources/lang/en/beatmapsets.php
Labels: area:beatmap-listing

#8908 Fix wrong beatmap popup position on resize
  resources/assets/lib/beatmapset-panel/beatmaps-popup.tsx
Labels: type:ux

#8903 Fix news nav icon visibility
  resources/assets/less/bem/page-nav-fancy.less
Labels: type:design, area:news

#8910 Don't animate beatmap popup repositioning
  resources/assets/less/bem/beatmaps-popup.less
Labels: type:design, area:beatmap-listing

#8895 Move formatDuration to utils
  resources/assets/lib/components/beatmap-basic-stats.tsx
  resources/assets/lib/utils/html.ts
Labels: type:code-quality

#8914 Fix positioning of user avatar in new comment box
  resources/assets/less/bem/comment-editor.less
Labels: type:design, area:comments

#8906 Pass XSolla sandbox option when fetching token
  DEPLOYMENT.md
  app/Http/Controllers/Payments/XsollaController.php
  resources/assets/lib/store-xsolla.coffee
  webpack.unmix.js
Labels: area:store

#8904 Fix gap on profile page nav header on Chrome
  resources/assets/less/bem/page-extra-tabs.less
Labels: type:design, area:user-profile

#8897 Typescript isClickable and isInputElement
  resources/assets/coffee/osu_common.coffee
  resources/assets/coffee/shared.coffee
  resources/assets/lib/core-legacy/forum.coffee
  resources/assets/lib/globals.d.ts
  resources/assets/lib/notification-widget/item.tsx
  resources/assets/lib/utils/html.ts
  tests/karma/utils/html.spec.ts
Labels: type:code-quality

#8905 Set channel name on browser title
  resources/assets/lib/chat/chat-state-store.ts
  resources/assets/lib/utils/html.ts
Labels: type:ux, area:chat

#8891 Use mobx for MetadataEditor component
  resources/assets/lib/beatmapsets-show/metadata-editor.tsx
Labels: area:beatmap-info

#8907 Move shopify options to store page layout
  DEPLOYMENT.md
  Dockerfile.deployment
  config/store.php
  resources/assets/lib/shopify-client.ts
  resources/assets/lib/shopify-debug.ts
  resources/assets/lib/store.ts
  resources/views/store/layout.blade.php
  webpack.unmix.js
Labels: area:store

#8930 Fix missing news posts
  app/Libraries/OsuWiki.php
  app/Models/NewsPost.php
Labels: area:news

#8923 Fix quick search debounce not running in mobx action
  resources/assets/lib/quick-search/worker.ts
Labels: type:code-quality

#8931 Reuse html purifier instance and always create cache directory
  app/Libraries/BBCodeFromDB.php
  app/Libraries/CleanHTML.php
  app/Providers/AppServiceProvider.php
Labels: area:forum, type:performance

#8921 Fix friending blocked user
  app/Http/Controllers/FriendsController.php
  tests/Controllers/FriendsControllerTest.php
Labels: area:user-profile, type:reliability

#8922 Include mutual friend state on blocking/unblocking user
  app/Http/Controllers/BlocksController.php
Labels: area:user-profile, type:reliability

#8933 Include table columns when creating score data object
  app/Models/Solo/ScoreData.php
Labels: type:reliability

#8940 Add unique constraint to group identifier
  app/Libraries/Groups.php
  database/migrations/2022_05_23_052743_add_unique_index_to_groups_identifier.php
Labels: type:reliability

#8935 Add ScorePerformance model
  app/Models/Solo/Score.php
  app/Models/Solo/ScorePerformance.php
Labels: type:database

#8955 Add missing notifiable type filter
  app/Models/User.php
Labels: type:performance

#8936 Split out user rank cache function
  app/Libraries/Score/UserRankCache.php
  app/Models/Score/Best/Model.php
Labels: type:code-quality, area:scoring

#8967 Add featured artist category to multiplayer rooms
  app/Models/Multiplayer/Room.php
  database/migrations/2022_05_27_094956_add_featured_artist_to_multiplayer_rooms_category.php
Labels: area:multiplayer

#8957 Adjust spotlight badge colour
  resources/assets/less/bem/beatmapset-badge.less
Labels: type:design, area:beatmap-info

#8943 Clean up polymorphic class name handling
  app/Jobs/UpdateUserForumTopicFollows.php
  app/Libraries/MorphMap.php
  app/Libraries/User/ScorePins.php
  app/Models/Model.php
  app/Providers/AppServiceProvider.php
Labels: type:code-quality

#8947 Combine score transformers
  app/Http/Controllers/BeatmapsController.php
  app/Http/Controllers/ScoresController.php
  app/Http/Controllers/Solo/ScoresController.php
  app/Http/Controllers/UsersController.php
  app/Libraries/ReplayFile.php
  app/Models/LegacyMatch/Score.php
  app/Models/Score/Best/Model.php
  app/Models/Score/Model.php
  app/Models/Solo/Score.php
  app/Models/Traits/Scoreable.php
  app/Transformers/LegacyMatch/GameTransformer.php
  app/Transformers/ScoreTransformer.php
  app/Transformers/Solo/ScoreTransformer.php
  database/factories/Score/Best/ModelFactory.php
Labels: type:code-quality

#8946 Combine score ruleset function
  app/Libraries/ReplayFile.php
  app/Models/LegacyMatch/Score.php
  app/Models/Score/Best/Model.php
  app/Models/Score/Model.php
  app/Models/Solo/Score.php
  app/Models/Traits/Scoreable.php
  app/Transformers/ScoreTransformer.php
  database/factories/Score/Best/ModelFactory.php
Labels: type:code-quality

#8941 Create build on release event instead of tag
  app/Libraries/GithubImporter.php
  app/Models/Build.php
  database/migrations/2022_05_23_072546_rename_builds_build_on_release.php
Labels: area:changelog

#8966 Reorganize node packages
  Dockerfile.deployment
  build.sh
  package.json
  yarn.lock
Labels: area:tooling

#8963 Use separate header tag for outdated translations on wiki
  app/Models/Wiki/Page.php
  resources/views/wiki/_notice.blade.php
Labels: area:wiki
