Repository ppy/osu-web, pull requests merged in 2022-07, with the labels that each got.

#9074 Sync mods data
  database/mods.json
Labels: area:scoring

#9083 Allow api request to obtain scores in new json format
  app/Transformers/ScoreTransformer.php
  resources/views/docs/_structures/score.md
Labels: type:api

#9070 Combine elasticsearch config
  app/Libraries/Elasticsearch/Es.php
  config/elasticsearch.php
  config/elasticsearch_scores.php
Labels: type:code-quality

#9073 Add basic test for UserSearch
  app/Libraries/Elasticsearch/Search.php
  tests/Libraries/Search/UserSearchTest.php
Labels: area:search

#9047 Don't requery when showing profile for logged in user
  app/Libraries/User/FindForProfilePage.php
Labels: area:user-profile, type:performance

#9066 👽️ Support s3-nginx-proxy's cache purging mechanism
  .env.example
  app/Models/Traits/UserAvatar.php
  config/osu.php
Labels: area:user-profile

#9076 Fix some mods being disallowed for playlist
  app/Libraries/Mods.php
  app/Models/Multiplayer/PlaylistItem.php
  tests/Controllers/Multiplayer/RoomsControllerTest.php
Labels: area:multiplayer

#9086 Remove unused EsDeleteDocument job
  app/Jobs/EsDeleteDocument.php
Labels: type:code-quality

#9067 Cleanup global typescript declarations
  resources/assets/lib/beatmap-discussions/chart.tsx
  resources/assets/lib/beatmap-discussions/discussions-context.ts
  resources/assets/lib/beatmap-discussions/editor-discussion-component.tsx
  resources/assets/lib/beatmap-discussions/editor.tsx
  resources/assets/lib/beatmap-discussions/new-review.tsx
  resources/assets/lib/beatmap-discussions/review-document.ts
  resources/assets/lib/beatmap-discussions/review-post-embed.tsx
  resources/assets/lib/components/beatmapset-event.tsx
  resources/assets/lib/globals.d.ts
  resources/assets/lib/interfaces/beatmapset-discussion-json.ts
  resources/assets/lib/interfaces/beatmapset-discussion-post-json.ts
  resources/assets/lib/interfaces/beatmapset-event-json.ts
  resources/assets/lib/interfaces/changelog-build.ts
  resources/assets/lib/utils/beatmapset-discussion-helper.ts
  resources/assets/lib/utils/url.ts
Labels: type:code-quality

#9080 Reset transaction states after the transaction ends
  app/Libraries/TransactionStateManager.php
  tests/Libraries/Transactions/AfterCommitTest.php
Labels: type:reliability

#9093 Use class factory for BeatmapPack
  database/factories/BeatmapPackFactory.php
  tests/Browser/SanityTest.php
  tests/Models/BeatmapPackTest.php
Labels: type:code-quality

#9081 Transaction manager clean ups
  app/Libraries/TransactionStateManager.php
Labels: type:code-quality

#8953 Allow pinning solo scores
  app/Http/Controllers/ScorePinsController.php
  app/Libraries/OsuAuthorize.php
  app/Libraries/User/ScorePins.php
  app/Models/ScorePin.php
  app/Transformers/Score/CurrentUserAttributesTransformer.php
  database/factories/ScorePinFactory.php
  database/migrations/2022_07_07_070707_add_solo_score_to_score_pins_score_type.php
Labels: area:user-profile

#9097 Add `allow_performance` column to `osu_builds`
  database/migrations/2022_07_08_085310_add_allow_performance_to_osu_builds.php
Labels: type:database

#9100 Fix migration rollbacks
  .github/workflows/tests.yml
  database/migrations/2019_08_21_104727_add_index_to_beatmapset_events.php
  database/migrations/2020_05_15_083037_sync_structure.php
  database/migrations/2020_07_22_045416_add_timestamp_index_to_user_account_history.php
  database/migrations/2020_10_13_064901_add_provider_reference_to_orders.php
  database/migrations/2021_08_30_153214_add_track_id_to_beatmapsets.php
Labels: type:code-quality

#9102 Clean up public directory
  public/browserconfig.xml
  public/images/favicon/android-chrome-192x192.png
  public/images/favicon/android-chrome-512x512.png
  public/images/favicon/apple-touch-icon.png
  public/images/favicon/favicon-16x16.png
  public/images/favicon/favicon-32x32.png
  public/images/favicon/safari-pinned-tab.svg
  public/mstile-150x150.png
  public/site.webmanifest
  resources/views/layout/metadata.blade.php
Labels: type:code-quality

#9103 Remove outdated (and unused) config files
  osu!web.sublime-project
  public/.hhconfig
Labels: type:code-quality

#9088 Deprecate chat presence endpoint
  app/Http/Controllers/Chat/ChatController.php
  app/Models/Chat/Channel.php
  resources/views/docs/info.blade.php
  tests/Controllers/Chat/ChannelsControllerTest.php
  tests/Controllers/Chat/ChatControllerTest.php
  tests/Libraries/UserChannelListTest.php
Labels: area:chat

#9107 Update mods data
  database/mods.json
Labels: area:scoring

#9006 Improve chat channel unread marker handling
  resources/assets/lib/chat/chat-state-store.ts
  resources/assets/lib/chat/conversation-view.tsx
  resources/assets/lib/interfaces/chat/channel-json.ts
  resources/assets/lib/models/chat/channel.ts
  resources/assets/lib/stores/channel-store.ts
Labels: area:chat

#9099 Updated Channel test factory
  app/Models/Chat/Channel.php
  database/factories/Chat/ChannelFactory.php
  tests/Controllers/Chat/Channels/MessagesControllerTest.php
  tests/Models/Chat/ChannelTest.php
Labels: type:testing, area:chat

#9121 Fix oauth client grant token clean up message
  app/Console/Commands/OAuthDeleteExpiredTokens.php
Labels: type:code-quality

#9110 Add endpoint to fetch solo scores from elasticsearch
  .env.example
  app/Http/Controllers/BeatmapsController.php
  app/Libraries/Elasticsearch/Search.php
  app/Libraries/Score/BeatmapScores.php
  app/Libraries/Score/UserRank.php
  app/Libraries/Search/ScoreSearch.php
  app/Libraries/Search/ScoreSearchParams.php
  config/elasticsearch.php
  routes/web.php
  tests/api_routes.json
Labels: area:scoring

#9124 Clean up user profile seeder
  app/Models/BeatmapLeader/Fruits.php
  app/Models/BeatmapLeader/Mania.php
  app/Models/BeatmapLeader/Model.php
  app/Models/BeatmapLeader/Osu.php
  app/Models/BeatmapLeader/Taiko.php
  database/seeders/ModelSeeders/UserProfileSeeder.php
Labels: type:code-quality

#9126 Use the new es search error assertion
  app/Models/Traits/UserScoreable.php
Labels: type:code-quality

#9130 Fix setHash triggering on wrong page after navigation.
  resources/assets/lib/beatmapsets-show/main.tsx
Labels: area:beatmap-info

#9136 Fix clockwork timeline timing
  app/helpers.php
Labels: area:tooling

#9133 Set max length on channel message input box
  app/Models/Chat/Channel.php
  resources/assets/less/bem/btn-osu-big.less
  resources/assets/less/bem/chat-input.less
  resources/assets/lib/chat/create-announcement.tsx
  resources/assets/lib/chat/input-box.tsx
  resources/assets/lib/models/chat/message.ts
Labels: area:chat

#9134 Truncate long channel names in channel list
  resources/assets/less/bem/chat-conversation-list-item.less
  resources/assets/lib/chat/conversation-list-item.tsx
Labels: area:chat

#9123 Fix scoreboard hover performance on Safari
  resources/assets/less/bem/beatmap-scoreboard-table.less
Labels: type:performance

#9128 Fix solo scores nomod filter support
  app/Libraries/Search/ScoreSearch.php
Labels: area:scoring

#9137 Check for beatmap hash when creating score token
  app/Http/Controllers/Solo/ScoreTokensController.php
  tests/Controllers/Solo/ScoreTokensControllerTest.php
Labels: area:scoring

#9129 Fix mods filter when no ruleset is set
  app/Libraries/Mods.php
  app/Libraries/Search/ScoreSearch.php
Labels: area:scoring

#9132 Fix implied mods score search and update tests
  app/Libraries/Mods.php
  tests/Controllers/BeatmapsControllerTest.php
Labels: area:scoring

#9143 Fix user score rank sort option
  app/Libraries/Search/ScoreSearchParams.php
Labels: area:scoring

#9144 Fix incorrect limit parameter for user best score search
  app/Libraries/Score/BeatmapScores.php
Labels: area:scoring

#9142 Add missing `finish()` call on progress bars
  app/Console/Commands/BeatmapLeadersRefresh.php
  app/Console/Commands/ForumTopicCoversCleanup.php
Labels: type:code-quality

#8651 Filter out blocked user's comments on beatmap pages.
  resources/assets/lib/components/comment.coffee
  resources/lang/en/users.php
Labels: area:comments

#9072 Convert beatmapset discussions NewReply component to typescript
  .eslintrc.js
  resources/assets/coffee/_classes/beatmap-discussion-helper.coffee
  resources/assets/lib/beatmap-discussions/new-discussion.coffee
  resources/assets/lib/beatmap-discussions/new-reply.coffee
  resources/assets/lib/beatmap-discussions/new-reply.tsx
  resources/assets/lib/beatmap-discussions/post.coffee
  resources/assets/lib/interfaces/beatmapset-discussion-post-responses.ts
  resources/assets/lib/interfaces/beatmapset-json.ts
  resources/assets/lib/quick-search/worker.ts
  resources/assets/lib/stores/root-data-store.ts
  resources/assets/lib/stores/ui-state-store.ts
  resources/assets/lib/utils/beatmapset-discussion-helper.ts
  resources/assets/lib/utils/input-handler.ts
  tests/karma/utils/beatmapset-discussion-helper.spec.ts
Labels: area:beatmap-discussions, type:code-quality

#9152 Skip deleted beatmaps for ownership check on nomination
  resources/assets/lib/beatmap-discussions/nominator.tsx
Labels: area:beatmap-discussions

#9155 Fix own best solo score lookup
  app/Libraries/Score/BeatmapScores.php
Labels: area:scoring

#9153 Fix click event on menu button not propagated
  resources/assets/lib/core/click-menu.ts
Labels: type:ux

#9154 Adjust z-index of navigation menu
  resources/assets/less/bem/mobile-menu.less
  resources/assets/less/bem/navbar-mobile.less
  resources/assets/less/layout.less
  resources/assets/less/variables.less
  resources/assets/lib/core-legacy/nav2.coffee
Labels: type:ux

#9145 Truncate report text content sent to webhook
  app/Models/UserReport.php
  resources/assets/lib/components/report-form.coffee
Labels: type:reliability
