Repository ppy/osu-web, pull requests merged in 2022-04, with the labels that each got.

#8732 Clean up ScoreJson
  resources/assets/lib/beatmapsets-show/score-top.tsx
  resources/assets/lib/beatmapsets-show/scoreboard-table-row.tsx
  resources/assets/lib/beatmapsets-show/scoreboard-table.tsx
  resources/assets/lib/beatmapsets-show/scoreboard.tsx
  resources/assets/lib/core/user/score-pins.ts
  resources/assets/lib/interfaces/profile-page/extras-json.ts
  resources/assets/lib/interfaces/score-json.ts
  resources/assets/lib/profile-page/controller.tsx
  resources/assets/lib/profile-page/play-detail-list.tsx
  resources/assets/lib/profile-page/play-detail.tsx
  resources/assets/lib/scores-show/buttons.tsx
  resources/assets/lib/scores-show/info.tsx
  resources/assets/lib/scores-show/main.tsx
  resources/assets/lib/scores-show/player.tsx
  resources/assets/lib/scores-show/stats.tsx
  resources/assets/lib/utils/score-helper.ts
Labels: type:code-quality, javascript

#8742 Update location bar when switching chat channels
  resources/assets/less/bem-index.less
  resources/assets/less/bem/chat-conversation-panel.less
  resources/assets/less/bem/chat.less
  resources/assets/less/bem/footer.less
  resources/assets/less/bem/osu-layout.less
  resources/assets/less/utilities.less
  resources/assets/lib/chat/chat-state-store.ts
  resources/assets/lib/chat/conversation-list-item.tsx
  resources/assets/lib/chat/conversation-list.tsx
  resources/assets/lib/chat/conversation-panel.tsx
  resources/assets/lib/chat/conversation-view.tsx
  resources/assets/lib/chat/input-box.tsx
  resources/assets/lib/chat/main-view.tsx
  resources/assets/lib/entrypoints/chat.tsx
  resources/assets/lib/stores/channel-store.ts
  resources/assets/lib/turbolinks.d.ts
  resources/lang/en/chat.php
  resources/views/chat/index.blade.php
Labels: area:chat

#8767 Typescript osu_common setHash
  resources/assets/coffee/osu_common.coffee
  resources/assets/lib/beatmapsets-show/main.coffee
  resources/assets/lib/modding-profile/main.coffee
  resources/assets/lib/utils/beatmapset-page-hash.ts
Labels: type:code-quality, area:beatmap-info

#8766 Use live rank for rank history last entry
  app/Models/RankHistory.php
  resources/assets/lib/profile-page/rank-chart.tsx
Labels: area:user-profile

#8773 Remove beatmap page event listener on unmount
  resources/assets/lib/beatmapsets-show/main.coffee
Labels: area:beatmap-info, type:reliability

#8772 Remove use of nonexistent state
  resources/assets/lib/beatmapsets-show/main.coffee
Labels: type:code-quality, area:beatmap-info

#8771 Use plain html for rating and fail chart
  resources/assets/less/bem/stacked-bar-chart.less
  resources/assets/lib/beatmapsets-show/info.coffee
  resources/assets/lib/beatmapsets-show/stats.coffee
  resources/assets/lib/charts/stacked-bar-chart.coffee
Labels: area:beatmap-info

#8761 Clean up BeatmapsetJson typing
  app/Transformers/BeatmapsetTransformer.php
  resources/assets/lib/beatmapsets-show/metadata-editor.tsx
  resources/assets/lib/components/beatmapset-panel.tsx
  resources/assets/lib/interfaces/beatmapset-extended-json.ts
  resources/assets/lib/interfaces/beatmapset-json.ts
  resources/assets/lib/utils/beatmapset-helper.ts
Labels: type:code-quality, javascript

#8703 Split best_of into two separate contest extra options
  app/Models/Contest.php
  app/Transformers/ContestTransformer.php
  resources/assets/less/bem/contest-voting-list.less
  resources/assets/lib/contest-voting/entry-list.coffee
  resources/assets/lib/contest-voting/entry.coffee
Labels: area:contests

#8780 Remove unused component
  resources/assets/lib/artist-tracks-index/track.tsx
Labels: type:code-quality, javascript

#8775 Typescript formatNumber
  resources/assets/coffee/_classes/store-supporter-tag-price.coffee
  resources/assets/coffee/osu_common.coffee
  resources/assets/lib/beatmaps/search-filter.coffee
  resources/assets/lib/beatmapsets-show/header.coffee
  resources/assets/lib/beatmapsets-show/info.coffee
  resources/assets/lib/beatmapsets-show/score-top.tsx
  resources/assets/lib/beatmapsets-show/scoreboard-table-row.tsx
  resources/assets/lib/beatmapsets-show/stats.coffee
  resources/assets/lib/charts/changelog-chart.coffee
  resources/assets/lib/charts/landing-user-stats.ts
  resources/assets/lib/components/beatmap-basic-stats.coffee
  resources/assets/lib/components/beatmapset-panel.tsx
  resources/assets/lib/components/comments.coffee
  resources/assets/lib/components/difficulty-badge.tsx
  resources/assets/lib/components/follow-user-mapping-button.tsx
  resources/assets/lib/components/friend-button.tsx
  resources/assets/lib/components/notification-icon.tsx
  resources/assets/lib/components/profile-page-extra-section-title.tsx
  resources/assets/lib/components/profile-page-kudosu.tsx
  resources/assets/lib/components/tracklist-track.tsx
  resources/assets/lib/contest-voting/art-entry.coffee
  resources/assets/lib/contest-voting/entry.coffee
  resources/assets/lib/core-legacy/forum.coffee
  resources/assets/lib/globals.d.ts
  resources/assets/lib/modding-profile/stats.coffee
  resources/assets/lib/mp-history/game.coffee
  resources/assets/lib/mp-history/score.coffee
  resources/assets/lib/profile-page/beatmap-playcount.tsx
  resources/assets/lib/profile-page/historical.tsx
  resources/assets/lib/profile-page/play-detail.tsx
  resources/assets/lib/profile-page/play-time.tsx
  resources/assets/lib/profile-page/pp.tsx
  resources/assets/lib/profile-page/rank-chart.tsx
  resources/assets/lib/profile-page/rank-count.tsx
  resources/assets/lib/profile-page/rank.tsx
  resources/assets/lib/profile-page/stats.tsx
  resources/assets/lib/quick-search/main.tsx
  resources/assets/lib/scores-show/beatmap-info.tsx
  resources/assets/lib/scores-show/player.tsx
  resources/assets/lib/scores-show/stats.tsx
  resources/assets/lib/scores/pp-value.tsx
  resources/assets/lib/utils/html.ts
  tests/karma/osu_common.spec.ts
  tests/karma/utils/html.spec.ts
Labels: type:code-quality, javascript

#8778 Allow modifier for beatmap list item
  resources/assets/less/bem/beatmap-icon.less
  resources/assets/less/bem/beatmap-list-item.less
  resources/assets/lib/beatmap-discussions/beatmap-list-item.tsx
  resources/assets/lib/beatmap-discussions/beatmap-list.tsx
Labels: type:code-quality, area:beatmap-info, javascript

#8783 Fix typing for beatmapset extended json
  resources/assets/lib/interfaces/beatmapset-extended-json.ts
Labels: type:code-quality, javascript

#8777 More precise typing of beatmap json interface
  resources/assets/lib/beatmap-discussions/beatmaps-owner-editor.tsx
  resources/assets/lib/beatmap-discussions/love-beatmap-modal.tsx
  resources/assets/lib/globals.d.ts
  resources/assets/lib/interfaces/beatmap-extended-json.ts
  resources/assets/lib/interfaces/beatmap-json.ts
  resources/assets/lib/interfaces/beatmapset-extended-json.ts
Labels: type:code-quality, javascript

#8782 Simplify Mod component
  resources/assets/lib/components/mod.tsx
Labels: type:code-quality, javascript

#8788 Fix array access in case the user is observable
  resources/assets/lib/components/user-card-brick.tsx
Labels: javascript, type:reliability

#8789 Simplify user brick margin
  resources/assets/less/bem/user-card-brick.less
  resources/assets/less/bem/user-cards.less
Labels: type:code-quality

#8792 Fix Typos on Downloads Page
  resources/lang/en/home.php
Labels: type:localisation

#8790 Add channel type group headers to channel list
  resources/assets/less/bem/chat-conversation-list-separator.less
  resources/assets/less/bem/chat-conversation-list.less
  resources/assets/lib/chat/conversation-list.tsx
  resources/lang/en/chat.php
Labels: area:chat

#8796 Remove unused helper
  resources/assets/lib/utils/user-helper.ts
Labels: type:code-quality

#8797 Remove setState from user profile container
  resources/assets/lib/components/user-profile-container.tsx
Labels: area:user-profile, type:code-quality

#8774 Typescript beatmap page hype section
  resources/assets/lib/beatmapsets-show/hype.coffee
  resources/assets/lib/beatmapsets-show/hype.tsx
  resources/assets/lib/beatmapsets-show/main.coffee
Labels: type:code-quality, area:beatmap-info, javascript

#8795 Typescript Beatmap Basic Stats component
  resources/assets/lib/beatmap-discussions/header.coffee
  resources/assets/lib/beatmapsets-show/stats.coffee
  resources/assets/lib/components/beatmap-basic-stats.coffee
  resources/assets/lib/components/beatmap-basic-stats.tsx
Labels: type:code-quality

#8803 Include php-ds extension in Dockerfile
  Dockerfile.deployment
  Dockerfile.development
Labels: area:tooling

#8793 More efficient cover url generator
  app/Models/Beatmapset.php
Labels: type:performance, php

#8814 Accept int for mods parameter
  app/Http/Controllers/BeatmapsController.php
  tests/Controllers/BeatmapsControllerTest.php
Labels: area:beatmap-info, type:reliability

#8798 Typescript Beatmap Stats component
  resources/assets/lib/beatmapsets-show/header.coffee
  resources/assets/lib/beatmapsets-show/stats.coffee
  resources/assets/lib/beatmapsets-show/stats.tsx
Labels: type:code-quality, javascript

#8815 Use correct unescape function
  resources/assets/lib/utils/url.ts
Labels: area:beatmap-discussions

#8784 New ruleset switcher style
  resources/assets/less/bem/beatmap-discussions-header-bottom.less
  resources/assets/less/bem/beatmap-discussions-header-top.less
  resources/assets/less/bem/game-mode-link.less
  resources/assets/less/bem/game-mode.less
  resources/assets/less/bem/header-v4.less
  resources/assets/less/bem/osu-page.less
  resources/assets/less/bem/profile-page-button.less
  resources/assets/less/variables.less
  resources/assets/lib/beatmap-discussions/header.coffee
  resources/assets/lib/beatmapsets-show/header-links.ts
  resources/assets/lib/beatmapsets-show/header.coffee
  resources/assets/lib/beatmapsets-show/main.coffee
  resources/assets/lib/components/header-v4.tsx
  resources/assets/lib/components/playmode-tabs.tsx
  resources/assets/lib/profile-page/game-mode-switcher.tsx
  resources/assets/lib/profile-page/header.tsx
  resources/lang/en/layout.php
  resources/views/layout/_page_header_v4.blade.php
  resources/views/rankings/_mode_selector.blade.php
  resources/views/rankings/index.blade.php
  resources/views/store/header.blade.php
  resources/views/wiki/main.blade.php
  resources/views/wiki/show.blade.php
  resources/views/wiki/sitemap.blade.php
Labels: type:design

#8813 Prevent error on support the game page
  app/Http/Controllers/HomeController.php
  resources/views/home/support-the-game.blade.php
Labels: type:reliability

#8791 Unify beatmap cover component
  resources/assets/less/bem/beatmap-discussions-header-top.less
  resources/assets/less/bem/beatmap-playcount.less
  resources/assets/less/bem/beatmapset-cover.less
  resources/assets/less/bem/beatmapset-header.less
  resources/assets/less/bem/beatmapset-list-view.less
  resources/assets/less/bem/beatmapset-panel.less
  resources/assets/less/bem/beatmapset-search-card.less
  resources/assets/less/bem/beatmapsets-search.less
  resources/assets/less/bem/mp-history-game.less
  resources/assets/less/bem/multiplayer-room.less
  resources/assets/less/bem/score-info.less
  resources/assets/less/bem/user-home-beatmapset.less
  resources/assets/less/functions.less
  resources/assets/lib/beatmap-discussions-history/main.coffee
  resources/assets/lib/beatmap-discussions/header.coffee
  resources/assets/lib/beatmaps/search-content.coffee
  resources/assets/lib/beatmaps/search-panel.coffee
  resources/assets/lib/beatmapsets-show/header.coffee
  resources/assets/lib/components/beatmapset-cover.tsx
  resources/assets/lib/components/beatmapset-event.tsx
  resources/assets/lib/components/beatmapset-list-view.tsx
  resources/assets/lib/components/beatmapset-panel.tsx
  resources/assets/lib/components/img2x.tsx
  resources/assets/lib/modding-profile/discussions.coffee
  resources/assets/lib/modding-profile/posts.coffee
  resources/assets/lib/mp-history/game-header.coffee
  resources/assets/lib/profile-page/beatmap-playcount.tsx
  resources/assets/lib/quick-search/beatmapset.tsx
  resources/assets/lib/scores-show/info.tsx
  resources/assets/lib/user-multiplayer-index/room.tsx
  resources/assets/lib/utils/html.ts
  resources/lang/en/beatmapsets.php
  resources/views/beatmap_discussion_posts/_item.blade.php
  resources/views/beatmap_discussions/_item.blade.php
  resources/views/home/_user_beatmapset.blade.php
  resources/views/home/user.blade.php
  resources/views/objects/_beatmapset_cover.blade.php
Labels: type:ux, javascript

#8818 Remove padding to avoid taller text from increasing item height
  resources/assets/less/bem/beatmap-playcount.less
Labels: type:design, area:user-profile

#8821 Fix viewing user modding history as guest
  resources/views/objects/_beatmapset_cover.blade.php
Labels: area:user-profile

#8823 Skip user preferences check if not needed
  resources/views/objects/_beatmapset_cover.blade.php
Labels: type:performance

#8826 Fix typo
  resources/lang/en/accounts.php
Labels: type:localisation

#8734 Display guest difficulties on the user profile
  app/Http/Controllers/UsersController.php
  app/Models/User.php
  app/Transformers/UserCompactTransformer.php
  resources/assets/lib/interfaces/profile-page/extras-json.ts
  resources/assets/lib/interfaces/user-json.ts
  resources/assets/lib/profile-page/beatmapsets.tsx
  resources/assets/lib/profile-page/controller.tsx
  resources/assets/lib/profile-page/extra-page-props.ts
  resources/lang/en/users.php
Labels: area:user-profile

#8819 Change button component type to non-pure
  resources/assets/lib/components/big-button.tsx
Labels: type:code-quality

#8831 Allow moderator to change beatmap difficulty owner
  app/Libraries/OsuAuthorize.php
  tests/Controllers/BeatmapsControllerTest.php
Labels: area:beatmap-discussions

#8834 Only allow admin to edit beatmap offset
  app/Http/Controllers/BeatmapsetsController.php
  app/Libraries/OsuAuthorize.php
  app/Transformers/BeatmapsetCompactTransformer.php
  resources/assets/lib/beatmapsets-show/metadata-editor.tsx
  resources/assets/lib/interfaces/beatmapset-json.ts
  tests/Controllers/BeatmapsetsControllerTest.php
Labels: area:beatmap-info

#8836 Move guest participation beatmap listing on profile page
  resources/assets/lib/profile-page/beatmapsets.tsx
Labels: type:design, area:user-profile

#8835 Always show cover for beatmap info page
  resources/assets/lib/beatmapsets-show/header.coffee
  resources/assets/lib/components/beatmapset-cover.tsx
Labels: type:ux, area:beatmap-info

#8763 Add additional icons in recent events
  resources/assets/less/bem/profile-extra-entries.less
  resources/assets/lib/profile-page/parse-event.tsx
  resources/assets/lib/profile-page/recent-activity.tsx
Labels: area:user-profile

#8801 Typescript beatmap Info component
  resources/assets/lib/beatmapsets-show/info.coffee
  resources/assets/lib/beatmapsets-show/info.tsx
  resources/assets/lib/beatmapsets-show/main.coffee
  resources/assets/lib/interfaces/beatmapset-extended-json.ts
  resources/assets/lib/interfaces/beatmapset-json.ts
Labels: type:code-quality, area:beatmap-info, javascript

#8849 Fix profile page state
  resources/assets/lib/profile-page/controller.tsx
Labels: area:user-profile, type:reliability

#8852 Fix discussion link sometimes not scrolling to the discussion
  resources/assets/lib/beatmap-discussions/main.coffee
  resources/assets/lib/beatmap-discussions/new-discussion.coffee
Labels: area:beatmap-discussions, type:ux

#8850 Sanitise search parameters
  app/Libraries/Search/BeatmapsetSearchRequestParams.php
Labels: area:beatmap-listing

#8853 Change default discussion page to general all
  resources/assets/coffee/_classes/beatmap-discussion-helper.coffee
Labels: area:beatmap-discussions

#8855 Fix forum topic auto pagination
  app/Http/Controllers/Forum/TopicsController.php
Labels: area:forum

#8854 Remove unused function in beatmap model
  app/Models/Beatmap.php
Labels: type:code-quality
