Repository ppy/osu-web, pull requests merged in 2023-09, with the labels that each got.

#10511 Fix old and legacy link markdown parsing errors
  resources/js/remark-plugins/legacy-link/micromark.ts
  resources/js/remark-plugins/old-link/micromark.ts
Labels: area:beatmap-discussions, area:comments, area:chat

#9709 Pass elasticsearch sort cursor value as is
  app/Libraries/Elasticsearch/Search.php
  app/Libraries/Score/FetchDedupedScores.php
Labels: type:code-quality

#10500 Highlight new top rank (1-50) in event
  resources/js/profile-page/parse-event.tsx
  resources/lang/en/events.php
Labels: type:cosmetic

#10509 Add test for sql unique exception check
  tests/HelpersTest.php
Labels: type:testing

#10508 Update to webpack 5
  package.json
  webpack.unmix.js
  yarn.lock
Labels: area:tooling

#10518 Fix slow query when looking up messages beyond backlog limit
  app/Http/Controllers/Chat/Channels/MessagesController.php
  app/Models/Chat/Channel.php
  app/Models/Chat/Message.php
  app/Transformers/Chat/ChannelTransformer.php
Labels: type:api, area:chat

#10520 Include featured artist playlist in multiplayer rank page dropdown
  app/Http/Controllers/Multiplayer/RoomsController.php
  app/Models/Multiplayer/Room.php
Labels: area:multiplayer

#10522 Always wrap chat announcement description
  resources/css/bem/chat-conversation.less
Labels: area:chat, type:cosmetic

#10519 Add more information about test groups in documentation
  SETUP.md
  tests/Controllers/AccountControllerTest.php
  tests/Controllers/BeatmapsControllerSoloScoresTest.php
  tests/Controllers/BeatmapsControllerTest.php
  tests/Jobs/RemoveBeatmapsetSoloScoresTest.php
  tests/Libraries/Search/UserSearchTest.php
  tests/Libraries/User/CountryChangeTest.php
  tests/Models/Solo/ScoreEsIndexTest.php
Labels: type:documentation

#10523 Make ruleset id column on playlist items not nullable
  database/migrations/2023_09_06_070904_set_not_null_ruleset_id_on_playlist_items.php
Labels: type:code-quality, area:multiplayer

#10512 Add 2x image url to user badge
  app/Transformers/UserBadgeTransformer.php
  resources/js/interfaces/user-badge-json.ts
  resources/views/docs/_structures/user.md
  resources/views/docs/_structures/user_compact.md
Labels: type:api

#10528 Use existing reindexScores function
  tests/Controllers/BeatmapsControllerSoloScoresTest.php
Labels: type:testing, type:code-quality

#10501 Fix beatmap discussion jump to anchor position
  resources/css/bem/beatmap-discussion-post.less
  resources/css/bem/beatmap-discussion.less
  resources/css/bem/beatmap-discussions.less
  resources/css/layout.less
  resources/js/beatmap-discussions/discussion.tsx
  resources/js/beatmap-discussions/discussions.tsx
  resources/js/beatmap-discussions/main.coffee
Labels: area:beatmap-discussions, type:behavioural

#10529 Reorganise beatmaps controller static functions
  app/Http/Controllers/BeatmapsController.php
Labels: type:code-quality

#10531 Add default scope for solo score
  app/Models/Solo/Score.php
Labels: type:code-quality

#10527 Remove unnecessary beatmap discussion wrapper
  resources/css/bem/beatmap-discussions.less
  resources/js/beatmap-discussions/discussions.tsx
  resources/views/beatmap_discussion_posts/_item.blade.php
  resources/views/beatmap_discussions/_item.blade.php
Labels: area:beatmap-discussions, type:code-quality

#10530 Make entire quick search user card a link
  resources/css/bem/user-search-card.less
  resources/js/quick-search/user.tsx
Labels: area:search

#10534 Add beatmapset difficulty name search filter
  app/Libraries/Search/BeatmapsetQueryParser.php
  app/Libraries/Search/BeatmapsetSearch.php
  app/Libraries/Search/BeatmapsetSearchParams.php
  app/Libraries/Search/BeatmapsetSearchRequestParams.php
Labels: area:beatmap-listing, area:search

#10540 Remove mobx-react-devtools
  package.json
  yarn.lock
Labels: area:tooling

#10543 Remove react-autosize-textarea
  package.json
  resources/js/beatmap-discussions/new-discussion.tsx
  resources/js/beatmap-discussions/new-reply.tsx
  resources/js/beatmap-discussions/post.tsx
  resources/js/chat/input-box.tsx
  resources/js/components/comment-editor.tsx
  resources/js/components/textarea-autosize.tsx
  resources/js/oauth/client-details.tsx
  resources/js/oauth/new-client.tsx
  yarn.lock
Labels: type:code-quality, area:tooling

#10547 Move autosize types dependency
  package.json
Labels: area:tooling

#10535 Update to Typescript 5
  .github/workflows/lint.yml
  package.json
  resources/js/actions/chat-message-send-action.ts
  resources/js/actions/chat-new-conversation-added.ts
  resources/js/actions/chat-update-silences.ts
  resources/js/actions/friend-updated.ts
  resources/js/actions/socket-message-send-action.ts
  resources/js/actions/socket-state-changed-action.ts
  resources/js/chat/conversation-view.tsx
  resources/js/chat/ping-service.ts
  resources/js/models/chat/channel.ts
  yarn.lock
Labels: type:code-quality, area:tooling

#10542 Match object docs with TypeScript interface
  app/Http/Controllers/BeatmapDiscussionPostsController.php
  app/Http/Controllers/BeatmapDiscussionsController.php
  app/Http/Controllers/BeatmapsController.php
  app/Http/Controllers/BeatmapsetDiscussionVotesController.php
  app/Http/Controllers/Chat/ChannelsController.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/UsersController.php
  resources/views/docs/_structures/beatmap.md
  resources/views/docs/_structures/beatmap_compact.md
  resources/views/docs/_structures/beatmap_extended.md
  resources/views/docs/_structures/beatmap_playcount.md
  resources/views/docs/_structures/beatmapset.md
  resources/views/docs/_structures/beatmapset_compact.md
  resources/views/docs/_structures/beatmapset_discussion.md
  resources/views/docs/_structures/beatmapset_extended.md
  resources/views/docs/_structures/chat_message.md
  resources/views/docs/_structures/comment_bundle.md
  resources/views/docs/_structures/rankings.md
  resources/views/docs/_structures/user.md
  resources/views/docs/_structures/user_compact.md
  resources/views/docs/_structures/user_extended.md
  resources/views/docs/_structures/user_statistics.md
  resources/views/docs/_websocket_events.md
  resources/views/docs/info.md.blade.php
Labels: type:documentation

#10545 Add user table column to lock changing email
  app/Http/Controllers/AccountController.php
  app/Libraries/OsuAuthorize.php
  app/Models/User.php
  database/migrations/2023_09_11_100621_add_lock_email_changes_to_users.php
  resources/lang/en/accounts.php
  resources/lang/en/authorization.php
  resources/views/accounts/_edit_email.blade.php
  tests/Controllers/AccountControllerTest.php
Labels: area:settings

#10546 Fix button area changing height when disabled
  resources/css/bem/btn-osu-big.less
Labels: type:cosmetic

#10549 Fix sending multi-line message plain text chat error
  resources/js/remark-plugins/disable-constructs.ts
Labels: area:chat

#10553 Add arm64 to build platforms
  .github/workflows/pack.yml
Labels: area:tooling

#10554 Speed up assets building on non-native platform
  Dockerfile.deployment
Labels: area:tooling

#10468 Move WIP/pending beatmaps to graveyard when approving their beatmapset
  app/Models/Beatmapset.php
  tests/Models/BeatmapsetTest.php
Labels: area:beatmap-processing

#10557 Use webpack Asset Modules
  package.json
  webpack.unmix.js
  yarn.lock
Labels: area:tooling

#10552 Add beatmapset search param for beatmapset events
  app/Models/BeatmapsetEvent.php
Labels: type:api, area:beatmap-discussions

#10555 Update to node 18
  .github/workflows/lint.yml
  .github/workflows/tests.yml
  Dockerfile.deployment
  Dockerfile.development
Labels: area:tooling

#10559 Use existing manifest plugin instead of a custom one
  package.json
  webpack.unmix.js
  yarn.lock
Labels: area:tooling

#10558 Add missing @-prefix username support for history and own user check
  app/Libraries/User/FindForProfilePage.php
  app/Models/User.php
Labels: area:user-profile

#9488 Add group history endpoint
  app/Http/Controllers/GroupHistoryController.php
  app/Libraries/OsuAuthorize.php
  app/Models/UserGroupEvent.php
  app/Transformers/UserGroupEventTransformer.php
  database/factories/GroupFactory.php
  database/factories/UserGroupEventFactory.php
  resources/js/interfaces/user-group-event-json.ts
  routes/web.php
  tests/Browser/SanityTest.php
  tests/Controllers/GroupHistoryControllerTest.php
  tests/Transformers/UserGroupEventTransformerTest.php
Labels: type:api

#10576 Remove unused base62 encode function
  app/helpers.php
Labels: type:code-quality

#10570 Add opengraph header to user profile
  app/Http/Controllers/UsersController.php
  app/Models/User.php
  app/Transformers/UserStatisticsTransformer.php
  app/helpers.php
  resources/lang/en/users.php
  resources/views/users/show.blade.php
Labels: area:user-profile

#10577 Remove unused server-side build icon function
  app/helpers.php
Labels: type:code-quality

#10580 Fix artist tracks search form class
  resources/js/artist-tracks-index/main.tsx
Labels: type:cosmetic

#10581 Add missing cast for Contest show_votes
  app/Models/Contest.php
Labels: area:contests, type:reliability

#10586 Fix type of Count name
  app/Models/Count.php
Labels: type:code-quality

#10571 Combine lookup username array generation logic
  app/Libraries/User/UsernamesForDbLookup.php
  app/Models/User.php
Labels: area:user-profile, type:code-quality

#10253 Add tiered level badge colouring
  public/images/backgrounds/level-hexagon.svg
  resources/css/bem/user-level.less
  resources/css/variables.less
  resources/js/components/user-level.tsx
Labels: area:user-profile

#10583 Remove box-shadow on header-v4
  resources/css/bem/header-v4.less
Labels: type:cosmetic

#10211 Dim forum topic entry if its older than 1 month
  app/Models/Forum/Topic.php
  config/osu.php
  resources/css/bem/forum-item-stripe.less
  resources/css/bem/forum-item.less
  resources/css/bem/forum-topic-entry.less
  resources/css/colors.less
  resources/css/layout.less
  resources/css/variables.less
  resources/views/forum/forums/_topic.blade.php
Labels: area:forum

#10594 Hide unknown mod settings
  resources/js/components/mod.tsx
Labels: area:scoring, type:cosmetic

#10568 Simplify Webpack config
  karma.conf.js
  package.json
  webpack.config.js
  webpack.unmix.js
  yarn.lock
Labels: type:code-quality

#10596 Fix beatmap badges area wrapping onto another line
  resources/css/bem/beatmapset-panel.less
Labels: area:beatmap-listing, type:cosmetic

#10598 Reduce user last visit recording frequency to 5 minutes
  app/Http/Middleware/UpdateUserLastvisit.php
Labels: area:user-profile, type:performance

#9465 Add account setting to link GitHub account
  .env.example
  app/Http/Controllers/Account/GithubUsersController.php
  app/Http/Controllers/AccountController.php
  app/Http/Controllers/ChangelogController.php
  app/Models/GithubUser.php
  app/Models/User.php
  app/Transformers/GithubUserTransformer.php
  composer.json
  composer.lock
  config/osu.php
  database/migrations/2023_09_25_230000_update_github_users.php
  resources/css/bem-index.less
  resources/css/bem/account-edit-entry.less
  resources/css/bem/btn-osu-big.less
  resources/css/bem/github-user.less
  resources/js/entrypoints/account-edit.tsx
  resources/js/github-user/index.tsx
  resources/js/interfaces/github-user-json.ts
  resources/js/legacy-api-key/details.tsx
  resources/js/legacy-irc-key/details.tsx
  resources/js/oauth/authorized-client.tsx
  resources/js/oauth/own-client.tsx
  resources/lang/en/accounts.php
  resources/views/accounts/_edit_github_user.blade.php
  resources/views/accounts/edit.blade.php
  resources/views/docs/_structures/github_user.md
  routes/web.php
  tests/Browser/SanityTest.php
Labels: area:settings, area:changelog

#10584 Remove support for legacy sessions
  app/Http/Kernel.php
  app/Http/Middleware/AutologinFromLegacyCookie.php
  app/Http/Middleware/EncryptCookies.php
  app/Libraries/User/ForceReactivation.php
  app/Libraries/UserVerificationState.php
  app/Models/LegacySession.php
  app/helpers.php
Labels: type:behavioural, type:code-quality

#10593 Add support for setting actor from usergroup interop endpoints
  app/Http/Controllers/InterOp/UserGroupsController.php
  tests/Controllers/InterOp/UserGroupsControllerTest.php
Labels: area:admin

#10602 Use beatmap max combo column value if available
  app/Models/Beatmap.php
Labels: type:api, area:beatmap-info

#10601 Bypass date object for common last visit checks
  app/Models/User.php
  app/Models/UserRelation.php
  config/osu.php
  tests/Controllers/SessionsControllerTest.php
Labels: area:user-profile, type:performance

#10595 Remove old `server.php`
  server.php
Labels: type:code-quality

#10604 Fix parsing non-string redirect uri parameter
  app/Http/Controllers/Passport/AuthorizationController.php
Labels: type:api, type:reliability
