Repository ppy/osu-web, pull requests merged in 2023-10, with the labels that each got.

#10603 Update github pack action
  .github/workflows/pack.yml
Labels: type:code-quality, area:tooling

#10600 Stringify beatmapsets json for caching
  app/Http/Controllers/BeatmapsetsController.php
  resources/views/beatmapsets/index.blade.php
Labels: area:beatmap-discussions, type:performance

#10609 Remove redundant beatmap discussions page title
  resources/views/beatmap_discussions/index.blade.php
Labels: area:beatmap-discussions, type:cosmetic

#10610 Use username for discussion listing link from modding profile
  resources/js/modding-profile/discussions.tsx
Labels: area:beatmap-discussions, type:cosmetic

#10620 Fix error viewing realtime room on web
  app/Http/Controllers/Multiplayer/RoomsController.php
Labels: area:multiplayer

#10621 Fix page scrolling when typing into new discussions text box
  resources/js/beatmap-discussions/main.coffee
  resources/js/beatmap-discussions/new-discussion.tsx
  resources/js/beatmap-discussions/new-review.tsx
Labels: area:beatmap-discussions

#10624 Fix multiplayer scores around query returning unmigrated entries
  app/Models/Multiplayer/PlaylistItemUserHighScore.php
Labels: area:multiplayer

#10614 Fix markdown wiki link locale and case
  resources/js/chat/message-item.tsx
  resources/js/remark-plugins/wiki-link.ts
  resources/js/types/remark-wiki-link.d.ts
  resources/js/utils/url.ts
Labels: type:behavioural, area:chat

#10605 Refactor rank history model
  app/Models/Count.php
  app/Models/RankHistory.php
  app/Transformers/RankHistoryTransformer.php
Labels: area:rankings, type:reliability

#10608 Add option to hide review posts
  app/Models/BeatmapDiscussion.php
  resources/lang/en/beatmap_discussions.php
  resources/views/beatmap_discussions/index.blade.php
Labels: area:beatmap-discussions

#10615 Skip time object for cache helpers
  app/helpers.php
Labels: type:code-quality

#10627 Refactor password reset backend
  app/Events/BroadcastableEventBase.php
  app/Exceptions/User/PasswordResetFailException.php
  app/Http/Controllers/PasswordResetController.php
  app/Libraries/BroadcastsPendingForTests.php
  app/Libraries/User/PasswordResetData.php
  app/Providers/AppServiceProvider.php
  composer.json
  composer.lock
  resources/lang/en/password_reset.php
  resources/views/password_reset/_initial.blade.php
  resources/views/password_reset/_reset.blade.php
  resources/views/password_reset/index.blade.php
  resources/views/password_reset/reset.blade.php
  routes/web.php
  tests/Controllers/PasswordResetControllerTest.php
  tests/Models/Chat/ChannelTest.php
  tests/TestCase.php
Labels: area:user-profile

#10629 Show more useful error message on resending password reset key
  app/Http/Controllers/PasswordResetController.php
  tests/Controllers/PasswordResetControllerTest.php
Labels: area:user-profile, type:behavioural

#10633 Fix generated filename in beatmap seeder
  database/seeders/ModelSeeders/BeatmapSeeder.php
Labels: area:tooling

#10630 Replace multiplayer ruleset const with enum
  app/Libraries/Multiplayer/Ruleset.php
  app/Libraries/Ruleset.php
  app/Models/Multiplayer/PlaylistItem.php
  tests/Libraries/ModsTest.php
Labels: type:code-quality

#10635 Fill in score id on multiplayer high score tables
  app/Models/Multiplayer/PlaylistItemUserHighScore.php
  app/Models/Multiplayer/UserScoreAggregate.php
Labels: area:multiplayer

#10647 Preload contest entry users when included in json
  app/Models/Contest.php
Labels: type:performance, area:contests

#10645 Apidoc type consistency
  app/Http/Controllers/BeatmapDiscussionsController.php
  app/Http/Controllers/BeatmapsController.php
  app/Http/Controllers/ChangelogController.php
  app/Http/Controllers/Forum/TopicsController.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/NewsController.php
  app/Http/Controllers/RankingController.php
  app/Http/Controllers/UsersController.php
  resources/views/docs/_structures/beatmap.md
  resources/views/docs/_structures/beatmap_pack.md
  resources/views/docs/_structures/beatmap_playcount.md
  resources/views/docs/_structures/beatmap_user_score.md
  resources/views/docs/_structures/beatmapset.md
  resources/views/docs/_structures/beatmapset_discussion.md
  resources/views/docs/_structures/beatmapset_discussion_post.md
  resources/views/docs/_structures/beatmapset_discussion_vote.md
  resources/views/docs/_structures/beatmapset_extended.md
  resources/views/docs/_structures/build.md
  resources/views/docs/_structures/changelog_entry.md
  resources/views/docs/_structures/chat_channel.md
  resources/views/docs/_structures/chat_message.md
  resources/views/docs/_structures/comment.md
  resources/views/docs/_structures/comment_bundle.md
  resources/views/docs/_structures/commentable_meta.md
  resources/views/docs/_structures/current_user_attributes.md
  resources/views/docs/_structures/event.md
  resources/views/docs/_structures/forum_post.md
  resources/views/docs/_structures/forum_topic.md
  resources/views/docs/_structures/github_user.md
  resources/views/docs/_structures/group.md
  resources/views/docs/_structures/kudosu_history.md
  resources/views/docs/_structures/multiplayer_score.md
  resources/views/docs/_structures/multiplayer_scores.md
  resources/views/docs/_structures/multiplayer_scores_around.md
  resources/views/docs/_structures/multiplayer_scores_cursor.md
  resources/views/docs/_structures/multiplayer_scores_sort.md
  resources/views/docs/_structures/news_post.md
  resources/views/docs/_structures/nomination.md
  resources/views/docs/_structures/notification.md
  resources/views/docs/_structures/rankings.md
  resources/views/docs/_structures/ruleset.md
  resources/views/docs/_structures/spotlight.md
  resources/views/docs/_structures/update_stream.md
  resources/views/docs/_structures/user.md
  resources/views/docs/_structures/user_extended.md
  resources/views/docs/_structures/user_group.md
  resources/views/docs/_structures/user_silence.md
  resources/views/docs/_structures/user_statistics.md
  resources/views/docs/_websocket_events.md
  resources/views/docs/auth.blade.php
  resources/views/docs/info.md.blade.php
Labels: type:documentation

#10649 Remove unused beatmapset search path parameter
  routes/web.php
  tests/api_routes.json
Labels: type:code-quality

#10650 Support annotations to handle cursor_string parameter for apidocs
  app/Docs/Strategies/UsesCursor.php
  app/Http/Controllers/BeatmapDiscussionsController.php
  app/Http/Controllers/BeatmapPacksController.php
  app/Http/Controllers/BeatmapsetsController.php
  app/Http/Controllers/EventsController.php
  app/Http/Controllers/Forum/TopicsController.php
  app/Http/Controllers/Multiplayer/Rooms/Playlist/ScoresController.php
  app/Http/Controllers/NewsController.php
  config/scribe.php
Labels: type:documentation

#10644 Clean up `StorageWithUrl`
  app/Libraries/StorageWithUrl.php
  app/Models/Beatmapset.php
  app/Models/Traits/UserAvatar.php
  app/Traits/Uploadable.php
Labels: type:code-quality

#10657 Remove custom laravel validator and related translations/functions
  app/Http/Controllers/Controller.php
  app/Providers/AppServiceProvider.php
  resources/lang/en/validation.php
Labels: type:code-quality

#10646 Fix permission for local storage upload
  app/Traits/Uploadable.php
Labels: type:reliability

#10670 Return 0 for missing spotlights grade_counts
  app/Transformers/UserStatisticsTransformer.php
Labels: type:api, area:rankings

#10677 Support showing multiple tournament banners
  app/Models/ProfileBanner.php
  app/Transformers/UserCompactTransformer.php
  resources/js/components/profile-tournament-banner.tsx
  resources/js/interfaces/user-json.ts
  resources/js/modding-profile/main.tsx
  resources/js/profile-page/detail.tsx
  resources/js/user-multiplayer-index/main.tsx
Labels: area:user-profile

#10634 Move some of score link function to score token
  app/Exceptions/GameCompletedException.php
  app/Http/Controllers/Multiplayer/Rooms/Playlist/ScoresController.php
  app/Models/Contest.php
  app/Models/Multiplayer/PlaylistItem.php
  app/Models/Multiplayer/PlaylistItemUserHighScore.php
  app/Models/Multiplayer/Room.php
  app/Models/Multiplayer/ScoreLink.php
  app/Models/Multiplayer/UserScoreAggregate.php
  app/Models/Solo/Score.php
  app/Models/Solo/ScoreToken.php
  app/Models/Traits/SoloScoreInterface.php
  app/Transformers/Multiplayer/UserScoreAggregateTransformer.php
  app/Transformers/Score/CurrentUserAttributesTransformer.php
  app/Transformers/ScoreTransformer.php
  app/Transformers/Solo/ScoreTokenTransformer.php
  database/factories/Multiplayer/ScoreLinkFactory.php
  database/migrations/2023_10_12_065846_simplify_score_links.php
  database/migrations/2023_10_12_071549_add_playlist_item_id_to_score_tokens.php
  tests/Controllers/Chat/ChannelsControllerTest.php
  tests/Controllers/Multiplayer/Rooms/Playlist/ScoresControllerTest.php
  tests/Controllers/Multiplayer/RoomsControllerTest.php
  tests/Models/ContestTest.php
  tests/Models/Multiplayer/RoomTest.php
  tests/Models/Multiplayer/UserScoreAggregateTest.php
Labels: type:api, area:multiplayer

#10676 Drop id column from user profile customisations table
  database/migrations/2023_10_24_122345_drop_id_from_user_profile_customizations.php
Labels: type:reliability

#10681 Remove unused analytics service
  .env.example
  config/services.php
  resources/views/layout/metadata.blade.php
Labels: type:code-quality

#10631 Improve UI performance of long chat channel lists
  resources/css/bem/chat-conversation-list.less
  resources/css/utilities.less
  resources/js/chat/conversation-list.tsx
Labels: type:performance, area:chat

#10683 Prevent html purifier mkdir error in simple case
  app/Libraries/CleanHTML.php
Labels: type:code-quality

#10682 Move namespace of ScoreToken classes
  app/Http/Controllers/Multiplayer/Rooms/Playlist/ScoresController.php
  app/Http/Controllers/ScoreTokensController.php
  app/Http/Controllers/Solo/ScoresController.php
  app/Models/Multiplayer/PlaylistItem.php
  app/Models/Multiplayer/Room.php
  app/Models/ScoreToken.php
  app/Models/Solo/Score.php
  app/Transformers/ScoreTokenTransformer.php
  database/factories/ScoreTokenFactory.php
  routes/web.php
  tests/Controllers/Multiplayer/Rooms/Playlist/ScoresControllerTest.php
  tests/Controllers/ScoreTokensControllerTest.php
  tests/Controllers/Solo/ScoresControllerTest.php
  tests/api_routes.json
Labels: type:code-quality

#10685 Fix stuttering while scrolling on mobile Safari
  package.json
  yarn.lock
Labels: type:behavioural

#10694 Fix page scrolling when typing into new review text box
  resources/js/beatmap-discussions/main.coffee
Labels: area:beatmap-discussions
