Repository ppy/osu-web, pull requests merged in 2023-02, with the labels that each got.

#9810 Fairer duration for supporter tags
  app/Libraries/Fulfillments/ApplySupporterTag.php
  app/Models/User.php
  database/factories/UserFactory.php
  database/migrations/2023_01_30_080509_use_datetime_for_supporter_expiry.php
  tests/Libraries/Fulfillments/SupporterTagFulfillmentTest.php
Labels: area:user-profile, type:database

#9814 Remove unused interface fields
  resources/js/interfaces/user-multiplayer-history-json.ts
Labels: type:code-quality

#9813 Disallow taking over inactive top player usernames
  app/Libraries/UsernameValidation.php
  database/factories/RankHighestFactory.php
  tests/Libraries/UsernameValidationTest.php
Labels: area:admin, area:user-profile

#9817 Support all kinds of newline for split string parameter
  app/helpers.php
  tests/HelpersTest.php
Labels: type:api, type:reliability

#9834 Fix typing for beatmapset discussion system post
  resources/js/beatmap-discussions/discussion.tsx
  resources/js/beatmap-discussions/system-post.tsx
  resources/js/interfaces/beatmapset-discussion-post-json.ts
Labels: area:beatmap-discussions

#9820 Adjust wordings for first support event entry
  resources/lang/en/events.php
Labels: type:design

#9830 Adjust me! page edit button label
  resources/js/profile-page/user-page.tsx
Labels: type:design, area:user-profile

#9794 Convert SelectOptions to TypeScript
  app/Http/Controllers/RankingController.php
  app/Http/Controllers/SeasonsController.php
  app/Transformers/SelectOptionTransformer.php
  resources/js/beatmap-discussions/user-filter.coffee
  resources/js/coffee-modules.d.ts
  resources/js/components/ranking-filter.tsx
  resources/js/components/ranking-select-options.tsx
  resources/js/components/report-form.tsx
  resources/js/components/select-options.coffee
  resources/js/components/select-options.tsx
  resources/js/components/spotlight-select-options.coffee
  resources/js/interfaces/select-option-json.ts
  resources/js/seasons-show/main.tsx
  resources/views/multiplayer/rooms/show.blade.php
Labels: type:code-quality

#9841 Add accuracy challenge mod support
  database/mods.json
Labels: area:multiplayer

#9828 Show link to wiki page in user restriction message
  .env.example
  config/osu.php
  resources/lang/en/users.php
  resources/views/master.blade.php
Labels: area:admin, area:user-profile

#9832 Format timestamp in osu! time format
  resources/js/beatmap-discussions/timestamp-plugin.ts
  resources/js/utils/beatmapset-discussion-helper.ts
Labels: area:beatmap-discussions

#9811 Convert Beatmap discussion url helpers to typescript
  resources/js/_classes/beatmap-discussion-helper.coffee
  resources/js/beatmap-discussions-history/main.coffee
  resources/js/beatmap-discussions/chart.tsx
  resources/js/beatmap-discussions/current-discussions.ts
  resources/js/beatmap-discussions/discussion.tsx
  resources/js/beatmap-discussions/editor-discussion-component.tsx
  resources/js/beatmap-discussions/header.coffee
  resources/js/beatmap-discussions/main.coffee
  resources/js/beatmap-discussions/mode-switcher.tsx
  resources/js/beatmap-discussions/new-discussion.tsx
  resources/js/beatmap-discussions/nominations.coffee
  resources/js/beatmap-discussions/post.tsx
  resources/js/beatmap-discussions/review-post-embed.tsx
  resources/js/beatmap-discussions/user-filter.coffee
  resources/js/components/beatmapset-event.tsx
  resources/js/entrypoints/app.ts
  resources/js/globals.d.ts
  resources/js/modding-profile/discussions.coffee
  resources/js/modding-profile/posts.coffee
  resources/js/notification-maps/url.ts
  resources/js/utils/beatmapset-discussion-helper.ts
Labels: type:code-quality

#9796 Add component for simple progress and discrete bar
  resources/css/bem-index.less
  resources/css/bem/bar.less
  resources/css/bem/beatmap-discussion-nomination.less
  resources/css/bem/beatmapset-hype.less
  resources/css/bem/discrete-bar.less
  resources/js/beatmap-discussions/nominations.coffee
  resources/js/beatmapsets-show/hype.tsx
  resources/js/beatmapsets-show/info.tsx
  resources/js/beatmapsets-show/stats.tsx
  resources/js/components/bar.tsx
  resources/js/components/discrete-bar.tsx
  resources/js/profile-page/detail-bar.tsx
Labels: type:code-quality

#9837 Simplify setting beatmapset discussion icon colour
  resources/css/bem-index.less
  resources/css/bem/beatmap-discussion-message-type.less
  resources/css/layout.less
  resources/js/beatmap-discussions/discussion.tsx
  resources/js/beatmap-discussions/editor-issue-type-selector.tsx
  resources/js/beatmap-discussions/review-post-embed.tsx
  resources/views/beatmap_discussions/_item.blade.php
Labels: type:code-quality

#9815 Fix extra margin on room listing
  resources/css/bem/room-list.less
  resources/css/bem/show-more-link.less
  resources/js/components/room-list.tsx
Labels: type:design

#9823 Reduce padding of user score in mobile version profile page
  resources/css/bem/play-detail.less
Labels: type:design, area:user-profile

#9836 Don't link user to specific ruleset for multiplayer score listing
  resources/views/multiplayer/rooms/_rankings_table.blade.php
  resources/views/multiplayer/rooms/show.blade.php
Labels: type:ux, area:multiplayer

#9848 Disallow restricted user from editing beatmap description
  app/Libraries/OsuAuthorize.php
Labels: area:beatmap-info

#9819 Fix beatmap search panel alignment
  resources/css/bem/beatmapsets-search-filter.less
  resources/css/bem/beatmapsets-search.less
  resources/js/beatmaps/search-filter.tsx
  resources/js/beatmaps/search-panel.tsx
Labels: type:design

#9831 Adjust font size of difficulty rating badge
  resources/css/bem/difficulty-badge.less
Labels: type:design

#9840 Fix hover area of forum post search card
  resources/css/bem-index.less
  resources/css/bem/search-entry.less
  resources/css/bem/search-forum-post.less
  resources/css/bem/search-result-entry.less
  resources/css/bem/search-result.less
  resources/views/home/_search_result_beatmapset.blade.php
  resources/views/home/_search_result_forum_post.blade.php
  resources/views/home/_search_result_wiki_page.blade.php
  resources/views/objects/search/_forum_post.blade.php
Labels: type:ux

#9829 Add bbcode tag for inline code
  app/Libraries/BBCodeForDB.php
  app/Libraries/BBCodeFromDB.php
  resources/css/bbcode.less
  tests/Libraries/bbcode_examples/basic_inline_code.base.txt
  tests/Libraries/bbcode_examples/basic_inline_code.db.txt
  tests/Libraries/bbcode_examples/basic_inline_code.html
Labels: area:forum

#9842 Hide delete beatmap button for moderators
  app/Libraries/OsuAuthorize.php
Labels: area:admin

#9824 Recursively delete discussion post
  app/Models/BeatmapDiscussion.php
Labels: area:beatmap-discussions

#9818 Add coloured marker for Beatmap discussion type on mobile view
  resources/css/bem/beatmap-discussion-timestamp.less
  resources/css/bem/beatmap-discussion-vote.less
  resources/css/bem/beatmap-discussion.less
  resources/css/bem/beatmapset-discussions-chart.less
  resources/css/bem/counter-box.less
  resources/js/beatmap-discussions/discussion-type.ts
  resources/js/beatmap-discussions/discussion.tsx
Labels: area:beatmap-discussions

#9844 More reliable notification banner positioning
  resources/css/bem/header-v4.less
  resources/css/bem/notification-banner-v2.less
  resources/css/bem/osu-page.less
  resources/js/components/header-v4.tsx
  resources/js/components/notification-banner.tsx
  resources/js/profile-page/header.tsx
  resources/views/layout/_page_header_v4.blade.php
  resources/views/master.blade.php
Labels: type:reliability

#9839 Update react markdown
  .github/workflows/lint.yml
  package.json
  resources/js/beatmap-discussions/autolink-plugin.ts
  resources/js/beatmap-discussions/disable-tokenizers-plugin.ts
  resources/js/beatmap-discussions/editor-helpers.ts
  resources/js/beatmap-discussions/editor.tsx
  resources/js/beatmap-discussions/plugins/add.ts
  resources/js/beatmap-discussions/plugins/autolink.ts
  resources/js/beatmap-discussions/plugins/disable-constructs.ts
  resources/js/beatmap-discussions/renderers.tsx
  resources/js/beatmap-discussions/review-document.ts
  resources/js/beatmap-discussions/review-post.tsx
  resources/js/beatmap-discussions/timestamp-plugin.ts
  tsconfig.json
  yarn.lock
Labels: area:beatmap-discussions

#9853 Fix border-radius on resolved marker on mobile
  resources/css/bem/beatmap-discussion.less
Labels: type:design

#9858 Add user hit counts to statistics json
  app/Transformers/UserStatisticsTransformer.php
  resources/js/interfaces/user-statistics-json.ts
  resources/views/docs/_structures/user_statistics.md
Labels: type:api

#9860 Mark read on notification middle click
  resources/js/notification-widget/item.tsx
Labels: type:ux, area:notifications

#9866 Update to php 8.1
  .github/workflows/lint.yml
  .github/workflows/tests.yml
  Dockerfile.deployment
  Dockerfile.development
  composer.json
  composer.lock
Labels: type:reliability

#9857 Unify beatmapset badge component
  resources/css/bem/beatmapset-badge.less
  resources/js/beatmap-discussions/header.coffee
  resources/js/beatmapsets-show/header.tsx
  resources/js/components/beatmapset-badge.tsx
  resources/js/components/beatmapset-panel.tsx
Labels: type:code-quality

#9859 Change message box type on blocked user to info
  resources/js/components/user-profile-container.tsx
Labels: area:user-profile

#9861 Add 2x image url to profile banner
  app/Transformers/ProfileBannerTransformer.php
  resources/js/components/img2x.tsx
  resources/js/components/profile-tournament-banner.tsx
  resources/js/interfaces/profile-banner.ts
Labels: type:api

#9868 Update date casting and fix missing composite key settings
  app/Models/Beatmap.php
  app/Models/BeatmapDifficulty.php
  app/Models/BeatmapDiscussion.php
  app/Models/BeatmapDiscussionPost.php
  app/Models/BeatmapModeStats.php
  app/Models/BeatmapPack.php
  app/Models/Beatmapset.php
  app/Models/BeatmapsetWatch.php
  app/Models/Build.php
  app/Models/BuildPropagationHistory.php
  app/Models/Changelog.php
  app/Models/Chat/Channel.php
  app/Models/Chat/Message.php
  app/Models/Chat/UserChannel.php
  app/Models/Comment.php
  app/Models/Contest.php
  app/Models/Event.php
  app/Models/FavouriteBeatmapset.php
  app/Models/Forum/FeatureVote.php
  app/Models/Forum/Forum.php
  app/Models/Forum/ForumTrack.php
  app/Models/Forum/TopicTrack.php
  app/Models/IpBan.php
  app/Models/KudosuHistory.php
  app/Models/LegacyMatch/Event.php
  app/Models/LegacyMatch/Game.php
  app/Models/LegacyMatch/LegacyMatch.php
  app/Models/LegacyMatch/Score.php
  app/Models/LegacySession.php
  app/Models/Log.php
  app/Models/Multiplayer/Room.php
  app/Models/Multiplayer/Score.php
  app/Models/NewsPost.php
  app/Models/RankHighest.php
  app/Models/Score/Model.php
  app/Models/Spotlight.php
  app/Models/Store/Order.php
  app/Models/Store/Payment.php
  app/Models/Store/Product.php
  app/Models/Tournament.php
  app/Models/User.php
  app/Models/UserAccountHistory.php
  app/Models/UserAchievement.php
  app/Models/UserBadge.php
  app/Models/UserClient.php
  app/Models/UserContestEntry.php
  app/Models/UserDonation.php
  app/Models/UserReport.php
  app/Models/UsernameChangeHistory.php
  composer.json
  tests/Models/ModelCompositePrimaryKeysTest.php
Labels: type:reliability

#9863 Allow translating "or later" part of os version
  app/Http/Controllers/HomeController.php
  resources/lang/en/home.php
Labels: type:localisation

#9835 Fix body params documentation for mark read notification endpoint
  app/Http/Controllers/NotificationsController.php
Labels: type:documentation

#9705 Only fetch scores with valid beatmap
  app/Libraries/Score/FetchDedupedScores.php
Labels: area:scoring

#9873 Fix calling explode() on null deprecation
  app/Http/Controllers/ChangelogController.php
  app/Http/Controllers/Passport/AuthorizationController.php
  app/Libraries/Search/BeatmapsetSearchRequestParams.php
Labels: type:code-quality

#9877 Use native lazy loading to lazy load images
  app/Libraries/CleanHTML.php
  app/helpers.php
  package.json
  resources/js/core/osu-layzr.ts
  resources/js/layzr.d.ts
  resources/js/osu-core.ts
  tests/Libraries/bbcode_examples/basic_img.html
  webpack.unmix.js
  yarn.lock
Labels: area:user-profile

#9885 Fix variable usage in strings
  app/Libraries/Elasticsearch/Es.php
  app/helpers.php
  tests/Controllers/InterOp/UsersControllerTest.php
  tests/Controllers/Multiplayer/RoomsControllerTest.php
Labels: type:code-quality

#9878 Fix page change event triggered before page load
  resources/js/components/header-v4.tsx
  resources/js/core-legacy/forum.coffee
Labels: type:reliability

#9888 Update php version requirement
  README.md
  composer.json
  composer.lock
Labels: type:code-quality

#9882 Separate ipv4 and ipv6 lookup
  .gitignore
  app/Libraries/Ip.php
  app/Libraries/Ip2Asn.php
  app/Libraries/Ip2AsnUpdater.php
  database/ip2asn/.keep
  docker/development/prepare.sh
Labels: type:reliability

#9896 Ignore deleted post when checking nearby beatmap discussions
  resources/js/utils/beatmapset-discussion-helper.ts
Labels: area:beatmap-discussions, type:ux

#9886 Fix reordering solo scores
  app/Http/Controllers/ScorePinsController.php
  resources/js/interfaces/score-json.ts
  resources/js/profile-page/controller.tsx
  tests/Controllers/ScorePinsControllerTest.php
Labels: area:user-profile

#9901 Replace anonymous function transformer with primitive
  app/Transformers/BuildTransformer.php
  app/Transformers/ContestEntryTransformer.php
  app/Transformers/NewsPostTransformer.php
  app/Transformers/UserStatisticsTransformer.php
Labels: type:code-quality

#9900 Add beatmap id to legacy match game json
  app/Models/LegacyMatch/Game.php
  app/Transformers/LegacyMatch/GameTransformer.php
Labels: type:api

#9904 Typescript Countdown Timer
  resources/js/components/countdown-timer.coffee
  resources/js/components/countdown-timer.tsx
  resources/js/register-components.coffee
Labels: type:code-quality

#9909 Typescript Spotlight Select Option
  resources/js/components/spotlight-select-options.coffee
  resources/js/components/spotlight-select-options.tsx
  resources/js/register-components.coffee
  resources/views/rankings/charts.blade.php
Labels: type:code-quality

#9822 Include pack tags in beatmapset search/show response
  app/Http/Controllers/BeatmapsetsController.php
  app/Libraries/Search/BeatmapsetSearch.php
  app/Models/Beatmapset.php
  app/Transformers/BeatmapsetCompactTransformer.php
  resources/views/docs/_structures/beatmapset_compact.md
Labels: type:api

#9903 Allow sorting forum topics by creation date
  app/Models/Forum/Topic.php
  database/migrations/2023_02_22_103305_add_create_time_index_to_forum_topics.php
  resources/lang/en/sort.php
  resources/views/forum/forums/_topics_sort.blade.php
Labels: area:forum

#9915 Remove unused style
  resources/js/changelog-index/main.coffee
  resources/js/components/comment-show-more.coffee
Labels: type:code-quality

#9914 Remove unused field
  resources/js/notifications/legacy-pm.tsx
Labels: type:code-quality

#9899 Adjust user popup margin
  resources/css/bem/qtip.less
  resources/css/bem/user-list-popup.less
Labels: type:design
