Repository ppy/osu-web, pull requests merged in 2024-02, with the labels that each got.

#10936 Remove alias for for scores table
  database/migrations/2024_01_31_181425_unview_scores.php
Labels: type:performance

#10941 Use correct rank/accuracy for beatmap leaderboard
  resources/js/beatmapsets-show/scoreboard/table-row.tsx
  resources/js/beatmapsets-show/scoreboard/top-card.tsx
Labels: area:scoring

#10943 Adjust score pinning behaviour
  app/Http/Controllers/ScorePinsController.php
  app/Libraries/OsuAuthorize.php
  resources/js/core/user/score-pins.ts
  resources/lang/en/authorization.php
Labels: area:scoring

#10933 Fix legacy score json
  app/Models/LegacyMatch/Score.php
  app/Models/Solo/Score.php
  app/Models/Traits/Scoreable.php
  app/Transformers/ScoreTransformer.php
  tests/Controllers/BeatmapsControllerSoloScoresTest.php
  tests/Models/Solo/ScoreTest.php
Labels: type:api

#10946 Better initial score preserve value
  app/Models/Solo/Score.php
Labels: area:scoring

#10950 Fix undefined variable
  app/Transformers/ScoreTransformer.php
Labels: type:reliability

#10953 Fix rank calculator for catch
  app/Models/Traits/Scoreable.php
Labels: area:scoring

#10952 Fix converted score type
  app/Models/Solo/Score.php
  app/Transformers/ScoreTransformer.php
Labels: type:api

#10959 Match score page visiblity between lazer and legacy
  app/Http/Controllers/ScoresController.php
  app/Models/Solo/Score.php
Labels: area:scoring

#10969 Fix recent votes section of modding profile
  resources/js/modding-profile/main.tsx
  resources/js/modding-profile/votes.tsx
Labels: area:user-profile, area:beatmap-discussions

#10970 Limit recent scores to 24h again
  app/Models/Solo/Score.php
Labels: area:user-profile, type:behavioural

#10979 Use 2x variant for default avatar image
  .env.example
  config/osu.php
  resources/js/models/user.ts
Labels: area:user-profile, type:cosmetic

#10982 Match initial user locale with current session's
  app/Http/Controllers/UsersController.php
  tests/Controllers/UsersControllerTest.php
Labels: area:user-profile

#10978 An attempt to get legacy perfect for mania closer to what it should be
  app/Models/Solo/Score.php
Labels: area:scoring

#10958 Fix error on invalid ruleset
  app/Http/Controllers/BeatmapsController.php
  tests/Controllers/BeatmapsControllerSoloScoresTest.php
Labels: area:scoring

#10872 Display a warning on discussions page if a qualified map has unresolved discussions that are blocking it from ranked
  resources/css/bem/beatmap-discussion-nomination.less
  resources/js/beatmap-discussions/nominations.tsx
  resources/lang/en/beatmaps.php
Labels: area:beatmap-discussions

#10985 Fix disqualify button not focusing on new discussion text box
  resources/js/beatmap-discussions/nominations.tsx
Labels: area:beatmap-discussions

#10994 Fix missing checks for multiplayer start play
  app/Http/Controllers/Multiplayer/Rooms/Playlist/ScoresController.php
  resources/lang/en/score_tokens.php
  tests/Controllers/Multiplayer/Rooms/Playlist/ScoresControllerTest.php
Labels: type:api

#10995 Fix error on passing unexpected parameter type
  app/Libraries/Search/WikiSuggestionsRequestParams.php
Labels: type:reliability

#10997 Fix search highlight cutoff position
  app/Libraries/Elasticsearch/Hit.php
  app/helpers.php
  resources/views/home/_search_result_forum_post.blade.php
Labels: area:search

#11000 Persistent redis for docker dev
  docker-compose.yml
Labels: area:tooling

#10999 Use docker builtin init
  docker-compose.yml
Labels: area:tooling

#11001 Fix default deployment docker command
  .dockerignore
  Dockerfile.deployment
  docker/deployment/entrypoint.sh
Labels: area:tooling

#11002 Update docs relating to score
  app/Http/Controllers/BeatmapPacksController.php
  app/Http/Controllers/BeatmapsController.php
  app/Http/Controllers/UsersController.php
  resources/views/docs/info.md.blade.php
Labels: type:documentation

#10988 Hide global rank display if a score is non-ranked or non-preserved
  resources/js/scores-show/player.tsx
  resources/lang/en/scores.php
Labels: area:scoring, type:cosmetic

#11012 Fix beatmap discussion filter resetting when switching difficulties or page tabs
  resources/js/beatmap-discussions/beatmap-list.tsx
  resources/js/beatmap-discussions/discussions-state.ts
Labels: area:beatmap-discussions

#11017 Use total length for beatmap search
  app/Libraries/Search/BeatmapsetSearch.php
  app/Libraries/Search/BeatmapsetSearchParams.php
  app/Libraries/Search/BeatmapsetSearchRequestParams.php
Labels: area:beatmap-listing

#11028 Fix legacy score rank calculation
  app/Models/Traits/Scoreable.php
Labels: area:scoring

#11020 Improve supporter icon alignment
  resources/css/bem/supporter-icon.less
  resources/js/components/supporter-icon.tsx
  resources/js/components/user-card.tsx
  resources/js/quick-search/user.tsx
Labels: type:cosmetic

#11024 Do full recalculation when adding new multiplayer score
  app/Models/Multiplayer/PlaylistItemUserHighScore.php
  app/Models/Multiplayer/UserScoreAggregate.php
Labels: area:multiplayer, area:scoring

#11009 Remove unused locales from `LocaleMeta`
  app/Libraries/LocaleMeta.php
Labels: type:localisation

#11036 Update to nodejs 20
  Dockerfile.deployment
  Dockerfile.development
Labels: area:tooling

#11023 Filter out stats without pp when recalculating country stats
  app/Models/CountryStatistics.php
Labels: area:rankings

#11038 Simplify pagination limit parameter validation
  resources/js/utils/offset-paginator.ts
Labels: type:code-quality

#11045 Remove trailing space of reference link tooltip
  resources/js/core/wiki/reference-link-tooltip.ts
Labels: area:wiki, type:cosmetic

#11046 Always push (only) notification for medal unlock
  app/Jobs/Notifications/UserAchievementUnlock.php
  app/Models/UserNotificationOption.php
  resources/lang/en/accounts.php
  resources/lang/en/notifications.php
Labels: area:notifications

#11047 Specify defaults for medal unlock notification options
  app/Jobs/Notifications/UserAchievementUnlock.php
Labels: area:notifications

#11044 Remove pp handling from multiplayer
  app/Models/Multiplayer/PlaylistItemUserHighScore.php
  app/Models/Multiplayer/UserScoreAggregate.php
  app/Transformers/Multiplayer/UserScoreAggregateTransformer.php
Labels: type:code-quality

#11052 Skip fetching rank for certain score types
  app/Models/Solo/Score.php
  resources/js/scores-show/player.tsx
Labels: area:scoring

#11051 Don't escape supporter gift message mail
  resources/views/emails/store/supporter_gift.blade.php
Labels: area:store, type:cosmetic

#11035 Add documentation for new score json
  app/Http/Controllers/Multiplayer/Rooms/Playlist/ScoresController.php
  resources/views/docs/_structures/multiplayer_score.md
  resources/views/docs/_structures/multiplayer_scores.md
  resources/views/docs/_structures/score.md
Labels: type:documentation

#11049 Update ranked flag to remove scores from index
  app/Jobs/RemoveBeatmapsetSoloScores.php
  app/Models/Solo/Score.php
  tests/Jobs/RemoveBeatmapsetSoloScoresTest.php
Labels: area:scoring
