Repository ppy/osu-web, pull requests merged in 2024-01, with the labels that each got.

#10836 React typing fixes
  resources/js/components/beatmapset-event.tsx
  resources/js/components/modal.tsx
  resources/js/components/portal.ts
  resources/js/utils/lang.tsx
Labels: type:code-quality

#10856 Revert back to php 8.2
  .github/workflows/tests.yml
  Dockerfile.deployment
  Dockerfile.development
  composer.json
  composer.lock
Labels: area:tooling

#10859 Update docker images
  .gitignore
  docker-compose.yml
Labels: area:tooling

#10864 Update github action js lint warning count
  .github/workflows/lint.yml
Labels: type:testing

#10854 More useful return type for user score legacy preference
  app/Libraries/Search/ScoreSearchParams.php
Labels: area:scoring

#10865 Support displaying F rank and make it default for fail scores
  app/Models/Solo/Score.php
  public/images/badges/score-ranks-v2019/GradeSmall-F.svg
  resources/css/bem/score-rank.less
  resources/js/interfaces/rank.ts
  resources/js/scores-show/dial.tsx
  resources/js/scores-show/tower.tsx
  tests/Models/Solo/ScoreTest.php
Labels: area:scoring

#10867 Convert ScoreRank to enum
  app/Enums/ScoreRank.php
  app/Libraries/ScoreRank.php
  app/Models/Solo/ScoreData.php
Labels: type:code-quality

#10871 Log successful login
  app/Models/LoginAttempt.php
  tests/Controllers/SessionsControllerTest.php
Labels: area:admin

#10870 Fix field initialization order
  resources/js/core/timeago.ts
  resources/js/notifications/notification-controller.ts
Labels: type:code-quality

#10874 Fix browser test on docker dev
  .env.dusk.local.example
  docker-compose.yml
  docker/development/entrypoint.sh
  docker/development/nginx-default.conf
Labels: area:tooling

#10857 Fix new discussion pinned position
  resources/js/beatmap-discussions/new-discussion.tsx
  resources/js/beatmap-discussions/new-review.tsx
Labels: area:beatmap-discussions

#10875 Mark user active on password reset
  app/Http/Controllers/PasswordResetController.php
  tests/Controllers/PasswordResetControllerTest.php
Labels: area:settings

#10876 Add message on forced password reset
  app/Http/Controllers/SessionsController.php
  app/Libraries/User/ForceReactivation.php
  resources/js/core/user/user-login.ts
  resources/lang/en/password_reset.php
  resources/views/password_reset/index.blade.php
Labels: area:settings

#10883 Use older indexer version
  docker-compose.yml
Labels: area:tooling

#10881 Deprecate active_tournament_banner property in User API response
  app/Transformers/UserCompactTransformer.php
  resources/css/entrypoints/docs.less
  resources/views/docs/_structures/user.md
  resources/views/docs/info.md.blade.php
Labels: type:documentation

#10886 Configurable score processing queue
  .env.example
  app/Models/Solo/Score.php
  config/osu.php
  tests/Controllers/Solo/ScoresControllerTest.php
Labels: area:scoring

#10896 Use correct isLegacy parameter for score user rank
  app/Models/Solo/Score.php
  app/Transformers/ScoreTransformer.php
Labels: area:scoring

#10887 Update score table structure
  app/Http/Controllers/BeatmapsController.php
  app/Http/Controllers/Multiplayer/Rooms/Playlist/ScoresController.php
  app/Http/Controllers/Solo/ScoresController.php
  app/Jobs/RemoveBeatmapsetSoloScores.php
  app/Libraries/Search/ScoreSearch.php
  app/Models/Multiplayer/PlaylistItemUserHighScore.php
  app/Models/Multiplayer/ScoreLink.php
  app/Models/Multiplayer/UserScoreAggregate.php
  app/Models/Score/Best/Model.php
  app/Models/Score/Model.php
  app/Models/Solo/Score.php
  app/Models/Solo/ScoreData.php
  app/Models/Solo/ScorePerformance.php
  app/Transformers/ScoreTransformer.php
  database/factories/Solo/ScoreFactory.php
  database/migrations/2024_01_12_115738_update_scores_table_final.php
  docker-compose.yml
  resources/js/interfaces/solo-score-json.ts
  resources/js/utils/score-helper.ts
  tests/Controllers/BeatmapsControllerSoloScoresTest.php
  tests/Controllers/Multiplayer/Rooms/Playlist/ScoresControllerTest.php
  tests/Controllers/PasswordResetControllerTest.php
  tests/Controllers/ScoresControllerTest.php
  tests/Jobs/RemoveBeatmapsetSoloScoresTest.php
  tests/Models/ContestTest.php
  tests/Models/Multiplayer/ScoreLinkTest.php
  tests/Models/Multiplayer/UserScoreAggregateTest.php
  tests/Models/Solo/ScoreEsIndexTest.php
  tests/Models/Solo/ScoreTest.php
Labels: area:scoring

#10800 Add verification for password oauth token
  app/Http/Controllers/UsersController.php
  app/Http/Kernel.php
  app/Http/Middleware/AuthApi.php
  app/Http/Middleware/UpdateUserLastvisit.php
  app/Http/Middleware/VerifyUser.php
  app/Libraries/OAuth/EncodeToken.php
  app/Libraries/OAuth/RefreshTokenGrant.php
  app/Libraries/SessionVerification/Controller.php
  app/Libraries/SessionVerification/Helper.php
  app/Models/OAuth/Token.php
  app/Models/Traits/FasterAttributes.php
  app/Providers/PassportServiceProvider.php
  app/Transformers/UserCompactTransformer.php
  app/helpers.php
  config/app.php
  database/factories/OAuth/TokenFactory.php
  database/migrations/2023_12_18_104437_add_verified_column_to_oauth_access_tokens.php
  resources/views/docs/_structures/user.md
  routes/web.php
  tests/Controllers/OAuth/TokensControllerTest.php
  tests/Libraries/SessionVerification/ControllerTest.php
  tests/TestCase.php
  tests/api_routes.json
Labels: area:user-profile

#10903 Add ranked field in score params
  app/Models/Solo/Score.php
Labels: area:scoring

#10899 Show correct legacy attributes on non-lazer mode
  resources/js/beatmapsets-show/scoreboard/table-row.tsx
  resources/js/beatmapsets-show/scoreboard/top-card.tsx
  resources/js/interfaces/user-preferences-json.ts
  resources/js/mp-history/game-header.coffee
  resources/js/profile-page/play-detail.tsx
  resources/js/scores-show/info.tsx
  resources/js/scores-show/player.tsx
  resources/js/utils/legacy-score-helper.ts
  resources/js/utils/score-helper.ts
Labels: area:scoring

#10884 Add option to disable score submission
  .env.example
  app/Http/Controllers/ScoreTokensController.php
  config/osu.php
Labels: area:scoring

#10888 Add client hash check
  app/Exceptions/ClientCheckParseTokenException.php
  app/Http/Controllers/Multiplayer/Rooms/Playlist/ScoresController.php
  app/Http/Controllers/ScoreTokensController.php
  app/Http/Controllers/Solo/ScoresController.php
  app/Libraries/ClientCheck.php
  app/Models/Build.php
  config/osu.php
  database/factories/BuildFactory.php
  phpunit.xml
  tests/Controllers/Multiplayer/Rooms/Playlist/ScoresControllerTest.php
  tests/Controllers/ScoreTokensControllerTest.php
  tests/Controllers/Solo/ScoresControllerTest.php
  tests/Libraries/ClientCheckTest.php
  tests/TestCase.php
Labels: area:settings, area:scoring

#10889 Add menu to switch score display mode
  public/images/layout/osu-lazer-logo-triangles.svg
  public/images/layout/osu-lazer-logo-white.svg
  resources/css/bem/nav2.less
  resources/css/bem/navbar-mobile.less
  resources/css/bem/osu-layout.less
  resources/css/bem/simple-menu.less
  resources/lang/en/layout.php
  resources/views/layout/_popup_user.blade.php
  resources/views/layout/_score_mode_toggle.blade.php
  resources/views/layout/header_mobile/user.blade.php
  resources/views/master.blade.php
Labels: area:settings, area:scoring

#10909 Adjust octane watch list
  config/octane.php
Labels: area:tooling

#10914 Ignore third party cookie error from youtube
  tests/Browser/SanityTest.php
Labels: type:testing

#10913 Limit recent scores to 48h
  app/Http/Controllers/UsersController.php
  app/Models/Solo/Score.php
  app/Models/User.php
  app/Transformers/UserCompactTransformer.php
Labels: area:user-profile

#10915 Remove lazer score conversion to legacy score
  app/Http/Controllers/Solo/ScoresController.php
  app/Models/Solo/Score.php
  tests/Controllers/Solo/ScoresControllerTest.php
  tests/Models/Solo/ScoreTest.php
Labels: area:scoring

#10907 Fix nomination button disabled state with unresolved issues and discussion post editing
  resources/js/beatmap-discussions/discussion.tsx
  resources/js/beatmap-discussions/discussions-state.ts
  resources/js/beatmap-discussions/post.tsx
Labels: area:beatmap-discussions

#10929 Fix accuracy value in score page
  resources/js/scores-show/stats.tsx
Labels: area:scoring

#10926 Add configurable client token lifetime
  app/Libraries/ClientCheck.php
  config/osu.php
Labels: type:api

#10928 Fix score perfect combo attribute
  app/Models/Score/Model.php
  app/Models/Solo/Score.php
  app/Transformers/ScoreTransformer.php
  resources/js/interfaces/solo-score-json.ts
  resources/js/utils/score-helper.ts
Labels: area:scoring
