Repository ppy/osu-web, pull requests merged in 2024-09, with the labels that each got.

#11463 Make total participation number on popup more prominent
  resources/css/bem/daily-challenge-popup.less
  resources/js/profile-page/daily-challenge.tsx
Labels: area:user-profile, type:cosmetic

#11464 Better session cookie settings
  config/session.php
Labels: type:code-quality

#11468 Add scope to filter passing multiplayer high scores
  app/Models/DailyChallengeUserStats.php
  app/Models/Multiplayer/PlaylistItem.php
  app/Models/Multiplayer/PlaylistItemUserHighScore.php
Labels: type:code-quality

#11465 Always show own score on multiplayer room leaderboard
  app/Http/Controllers/Multiplayer/RoomsController.php
  resources/views/multiplayer/rooms/_rankings_table.blade.php
Labels: area:rankings

#11467 Adjust daily challenge stats visibility
  resources/js/profile-page/daily-challenge.tsx
  resources/js/profile-page/detail.tsx
Labels: area:user-profile

#11473 Fix container size of beatmap title and artist
  resources/css/bem/beatmapset-header.less
Labels: type:cosmetic

#11476 Update forum auto notification option to include replies
  app/Http/Controllers/Forum/TopicsController.php
  resources/js/core-legacy/forum-topic-reply.coffee
  resources/lang/en/accounts.php
Labels: area:forum

#11469 Add daily ranking page
  app/Http/Controllers/Multiplayer/RoomsController.php
  app/Http/Controllers/Ranking/DailyChallengeController.php
  app/Http/Controllers/RankingController.php
  app/Models/Multiplayer/Room.php
  app/Singletons/RouteSection.php
  app/helpers.php
  resources/css/bem/rankings-beatmapsets.less
  resources/js/components/basic-select-options.tsx
  resources/js/core/spoilerbox.ts
  resources/js/utils/fail.ts
  resources/lang/en/rankings.php
  resources/views/rankings/_beatmapsets.blade.php
  resources/views/rankings/daily_challenge.blade.php
  resources/views/rankings/index.blade.php
  routes/web.php
  tests/Browser/SanityTest.php
Labels: area:rankings

#11482 Fix spotlight dropdown height
  app/Http/Controllers/RankingController.php
  resources/css/bem/select-options.less
  resources/js/components/basic-select-options.tsx
  resources/js/components/spotlight-select-options.tsx
  resources/js/register-components.tsx
  resources/views/multiplayer/rooms/show.blade.php
  resources/views/rankings/charts.blade.php
  resources/views/rankings/daily_challenge.blade.php
Labels: area:rankings, type:cosmetic

#11484 Show daily ranking list in most recent order
  app/Http/Controllers/Ranking/DailyChallengeController.php
Labels: area:rankings

#11486 Fix ruleset selector not shown on mobile
  resources/views/rankings/index.blade.php
Labels: area:rankings

#11471 Beatmap ranking timer changes
  .env.example
  app/Models/Beatmapset.php
  app/Models/BeatmapsetNomination.php
  config/osu.php
  database/factories/BeatmapFactory.php
  database/factories/BeatmapsetEventFactory.php
  database/factories/BeatmapsetFactory.php
  resources/js/beatmap-discussions/discussions-state.ts
  resources/js/beatmap-discussions/nominations.tsx
  resources/js/beatmap-discussions/nominator.tsx
  resources/lang/en/beatmapsets.php
  tests/Libraries/Fulfillments/SupporterTagFulfillmentTest.php
  tests/Models/BeatmapsetRequalifyTest.php
  tests/Models/BeatmapsetTest.php
  tests/TestCase.php
Labels: area:beatmap-discussions

#11480 Combine input classes and split off interleaved bem
  resources/css/bem-index.less
  resources/css/bem/artist-track-search-form.less
  resources/css/bem/chat-form-users.less
  resources/css/bem/chat-form.less
  resources/css/bem/contest-judge-entry.less
  resources/css/bem/input-container.less
  resources/css/bem/input-text.less
  resources/js/artist-tracks-index/search-form.tsx
  resources/js/chat/create-announcement.tsx
  resources/js/contest-judge/entry.tsx
Labels: type:code-quality

#11491 Fix BeatmapsetRequalifyTest failing due to timing variance.
  tests/Models/BeatmapsetRequalifyTest.php
Labels: type:testing

#11503 Add support for rejecting payments
  app/Console/Commands/StoreGetPaypalOrder.php
  app/Console/Kernel.php
  app/Exceptions/Store/PaymentRejectedException.php
  app/Http/Controllers/Payments/PaypalController.php
  app/Libraries/Payments/PaypalExecutePayment.php
  app/Models/Store/PaypalBanned.php
  database/migrations/2024_09_24_000001_create_store_paypal_banned.php
Labels: area:store

#11461 Change parameter for country flag view
  resources/views/accounts/_edit_country.blade.php
  resources/views/accounts/_edit_sessions.blade.php
  resources/views/forum/topics/_post_info.blade.php
  resources/views/home/_landing_locales.blade.php
  resources/views/layout/header_mobile/_locales.blade.php
  resources/views/layout/nav2/_locales.blade.php
  resources/views/multiplayer/rooms/_rankings_table.blade.php
  resources/views/objects/_flag_country.blade.php
  resources/views/rankings/_spotlight_rankings_table.blade.php
  resources/views/rankings/country.blade.php
  resources/views/rankings/kudosu.blade.php
  resources/views/rankings/performance.blade.php
  resources/views/rankings/score.blade.php
  resources/views/wiki/_locale_menu.blade.php
Labels: type:code-quality

#11492 Use fa-var variables
  resources/css/bem/form-select.less
  resources/css/bem/header-nav-v4.less
  resources/css/bem/osu-switch-v2.less
  resources/css/bem/sticky-header-breadcrumbs.less
  resources/css/bem/supporter-heart.less
Labels: type:code-quality

#11493 Use subgrid for store cart
  resources/css/bem/cart-items.less
  resources/css/bem/store-order-item.less
Labels: type:cosmetic

#11504 Fix null being passed to str replace
  app/Libraries/Markdown/Osu/DocumentProcessor.php
Labels: type:code-quality

#11508 Remove unused route
  routes/web.php
Labels: type:code-quality

#11507 Use preloaded country data for user json
  app/Transformers/UserCompactTransformer.php
Labels: type:performance

#11505 Remove redundant user card endpoint
  app/Http/Controllers/UsersController.php
  app/Models/UserNotFound.php
  resources/js/components/user-card-tooltip.tsx
  resources/js/models/user.ts
  resources/js/store/store-supporter-tag.tsx
  routes/web.php
Labels: type:code-quality

#11512 More reliable app key init
  docker/development/prepare.sh
Labels: area:tooling

#11509 Allow more users for chat announcement
  app/Libraries/Chat.php
Labels: area:chat

#11511 Add helper command for getting Shopify-related checkout details
  app/Console/Commands/StoreGetShopifyCheckout.php
  app/Console/Kernel.php
  composer.json
  composer.lock
Labels: area:store

#11510 Don't send user ids for announcement channels
  app/Http/Controllers/Chat/ChannelsController.php
  app/Models/Chat/Channel.php
  app/Transformers/Chat/ChannelTransformer.php
  tests/Models/Chat/ChannelTest.php
Labels: area:chat

#11506 Open up user lookup api
  app/Http/Controllers/Users/LookupController.php
  resources/js/components/user-card-tooltip.tsx
  resources/js/utils/user.ts
  routes/web.php
  tests/api_routes.json
Labels: type:api

#11517 Check for null username parameter in password reset
  app/Libraries/User/PasswordResetData.php
Labels: type:reliability

#11497 Document Apidoc User profile_hue
  resources/views/docs/_structures/user_extended.md
Labels: type:documentation
