Repository ppy/osu-web, pull requests merged in 2024-05, with the labels that each got.

#11187 Update default legacy only config value on frontend
  resources/js/interfaces/user-preferences-json.ts
Labels: area:scoring

#11195 Skip beatmapset_id for converting to legacy score
  app/Models/Score/Model.php
  app/Models/Solo/Score.php
Labels: type:code-quality, area:scoring

#11191 Fix initial listing of comment index
  resources/js/comments-index/index.tsx
  resources/js/comments-show/index.tsx
  resources/js/components/comments-controller.ts
Labels: area:comments

#11197 Use cloudflare captcha (turnstile)
  .env.example
  app/Http/Controllers/SessionsController.php
  app/Http/Controllers/UsersController.php
  app/helpers.php
  composer.json
  composer.lock
  config/captcha.php
  config/osu.php
  config/turnstile.php
  resources/views/objects/_captcha_script.blade.php
Labels: type:reliability

#11200 Fix captcha display language
  resources/js/core/captcha.ts
  resources/views/objects/_captcha_script.blade.php
Labels: type:localisation

#11185 Fix beatmap discussion open issue count display
  resources/js/beatmap-discussions/discussions-state.ts
Labels: area:beatmap-discussions

#11196 Filter by best legacy scores when searching beatmap in legacy mode
  app/Libraries/Search/BeatmapsetSearch.php
Labels: area:beatmap-listing

#11202 Fix comments display order
  resources/js/components/comments-controller.ts
Labels: area:comments

#11203 Adjust turnstile lifetime
  app/Http/Controllers/SessionsController.php
  app/Http/Controllers/UsersController.php
  package.json
  resources/js/core/captcha.ts
  resources/views/objects/_captcha_script.blade.php
  yarn.lock
Labels: type:reliability

#11186 Include rank in country ranking page json
  app/Http/Controllers/RankingController.php
  app/Models/UserStatistics/Model.php
Labels: type:api, area:rankings

#11207 Add basic accuracy validation
  app/Models/Solo/Score.php
  tests/Models/Multiplayer/UserScoreAggregateTest.php
Labels: area:scoring

#11214 Update logo
  public/images/layout/osu-lazer-logo-white.svg
  resources/css/bem/nav2.less
Labels: type:cosmetic

#11198 Change deleted comment behaviour
  resources/js/components/comment.tsx
  resources/js/components/comments-controller.ts
  resources/js/components/comments.tsx
  resources/js/components/deleted-comments-count.tsx
  resources/js/models/comment.ts
Labels: area:comments

#11215 Fix ellipsis overflow mixin
  resources/css/bem/beatmap-owner-editor.less
  resources/css/bem/play-detail.less
  resources/css/functions.less
  resources/css/utilities.less
Labels: type:code-quality

#11209 Convert AccountEdit and AccountEditAvatar to typescript
  resources/js/core-legacy/account-edit-avatar.coffee
  resources/js/core-legacy/account-edit.coffee
  resources/js/core/account-edit-avatar.ts
  resources/js/core/account-edit-state.ts
  resources/js/core/account-edit.ts
  resources/js/main.coffee
  resources/js/osu-core.ts
  resources/views/accounts/_edit_entry_simple.blade.php
  resources/views/accounts/_edit_notifications.blade.php
  resources/views/accounts/_edit_options.blade.php
  resources/views/accounts/_edit_playstyles.blade.php
  resources/views/accounts/_edit_privacy.blade.php
Labels: area:settings, type:code-quality

#11206 Add links to contest entry title
  resources/css/bem/contest-voting-list.less
  resources/js/contest-voting/entry.coffee
Labels: type:behavioural, area:contests

#11216 Use mobx for follow user button
  resources/js/components/follow-toggle.tsx
  resources/js/components/follow-user-mapping-button.tsx
  resources/js/core/user/user-model.ts
Labels: type:code-quality

#11224 Check against specific sql unique constraint exception
  app/helpers.php
  tests/HelpersTest.php
Labels: type:code-quality

#11204 Implement creating rooms for queued beatmaps for "daily challenge" system
  app/Console/Commands/DailyChallengeCreateNext.php
  app/Console/Kernel.php
  app/Models/Multiplayer/DailyChallengeQueueItem.php
  app/Models/Multiplayer/Room.php
  database/factories/Multiplayer/DailyChallengeQueueItemFactory.php
  database/migrations/2024_05_09_082011_create_daily_challenge_queue.php
  tests/Commands/DailyChallengeCreateNextTest.php
Labels: area:multiplayer

#11228 Fix error on setting playstyle to null
  app/Models/User.php
Labels: type:reliability

#11221 Include variant statistics in user index API
  app/Http/Controllers/UsersController.php
  app/Models/User.php
Labels: area:user-profile, type:api

#11227 Fix forum topic cover handling
  app/Http/Controllers/Forum/TopicsController.php
  app/Transformers/Forum/TopicCoverTransformer.php
Labels: area:forum

#10597 Show rank changes on performance ranking
  app/Http/Controllers/RankingController.php
  app/Models/Count.php
  app/Models/RankHistory.php
  app/Models/UserStatistics/Model.php
  app/Transformers/UserStatisticsTransformer.php
  resources/css/bem/ranking-page-table.less
  resources/lang/en/rankings.php
  resources/views/docs/_structures/rankings.md
  resources/views/docs/_structures/user.md
  resources/views/docs/_structures/user_statistics.md
  resources/views/rankings/performance.blade.php
  routes/web.php
  tests/Controllers/RankingControllerTest.php
Labels: area:rankings

#11237 Use schedule worker for docker dev
  docker/development/entrypoint.sh
Labels: area:tooling

#11235 Automatically schedule daily challenge room creation
  app/Console/Kernel.php
Labels: area:multiplayer

#11238 Remove header animation initial page load
  resources/css/bem/avatar.less
  resources/css/bem/login-box.less
  resources/css/bem/nav2-header.less
  resources/css/bem/nav2.less
  resources/css/layout.less
  resources/css/variables.less
  resources/js/core/animate-nav.ts
  resources/js/core/sticky-header.ts
  resources/js/osu-core.ts
Labels: type:cosmetic

#11243 Fix beatmapset ruleset id array
  app/Models/Beatmapset.php
Labels: type:reliability
