Repository ppy/osu-web, pull requests merged in 2024-11, with the labels that each got.

#11610 Sort user notifications with existing notifications table index
  app/Libraries/NotificationsBundle.php
  composer.json
  composer.lock
Labels: type:performance, area:notifications

#11614 Remove unused variable
  app/Models/Forum/TopicWatch.php
Labels: type:code-quality

#11604 Add 2x support for news cover image
  app/Models/NewsPost.php
  app/Transformers/NewsPostTransformer.php
  app/helpers.php
  resources/css/bem/news-post-preview.less
  resources/css/bem/page-nav-fancy.less
  resources/js/interfaces/news-post-json.ts
  resources/js/news-index/post-item.tsx
  resources/js/news-show/main.tsx
  resources/views/docs/_structures/news_post.md
  resources/views/home/_user_news_post_preview.blade.php
Labels: type:cosmetic

#11632 Limit chat message reporting context
  app/Models/Chat/Message.php
Labels: area:admin

#11635 Include user colour icon as part of the link
  app/helpers.php
  resources/css/bem/forum-user-icon.less
Labels: area:forum

#11639 Fix sub module resolution
  webpack.config.js
  yarn.lock
Labels: area:tooling

#11641 Update beatmap difficulty server port number
  SETUP.md
  docker-compose.yml
Labels: area:tooling

#11640 Skip dev only webpack plugins on production
  package.json
  webpack.config.js
  yarn.lock
Labels: area:tooling

#11616 Async script loading
  resources/js/core/react-turbolinks.ts
  resources/js/core/turbolinks-reload.ts
  resources/js/store-xsolla.coffee
Labels: area:tooling

#11638 Simplify docker dev entrypoint script
  Dockerfile.development
  docker/development/entrypoint.sh
  docker/development/run.sh
Labels: area:tooling

#11634 Adjust forum topic links
  app/Http/Controllers/Forum/TopicsController.php
  resources/lang/en/forum.php
  resources/views/forum/forums/_topic.blade.php
Labels: area:forum

#11644 Fix legacy match score rank value
  app/Models/LegacyMatch/Score.php
  app/Models/Traits/Scoreable.php
Labels: area:multiplayer

#11633 Restructure forum colour stripe
  resources/css/bem/forum-item-stripe.less
  resources/views/forum/forums/_forum.blade.php
  resources/views/forum/forums/_topic.blade.php
Labels: area:forum, type:code-quality

#11645 Update laravel framework
  composer.lock
Labels: type:code-quality

#11646 Use new laravel helper method
  app/Http/Controllers/Chat/Channels/MessagesController.php
  app/Http/Controllers/ContestEntriesController.php
  app/Http/Controllers/Forum/TopicsController.php
  app/Http/Controllers/MatchesController.php
  app/Http/Controllers/Multiplayer/Rooms/Playlist/ScoresController.php
  app/Http/Controllers/Multiplayer/RoomsController.php
  app/Http/Controllers/RankingController.php
  app/Http/Controllers/UsersController.php
  app/Libraries/BBCodeFromDB.php
  app/Libraries/CommentBundleParams.php
  app/Libraries/Score/BeatmapScores.php
  app/Models/Beatmap.php
  app/Models/Model.php
  app/Models/Multiplayer/Room.php
  app/Models/NewsPost.php
  app/Models/Score/Best/Model.php
  app/helpers.php
Labels: type:code-quality

#11649 Fix json decode error when sentry records request
  composer.lock
Labels: type:reliability

#11652 Cache ip2asn db on GitHub Action
  .github/workflows/tests.yml
Labels: area:tooling

#11625 Move active tournament banner data to table
  .env.example
  app/Models/ProfileBanner.php
  app/Models/TournamentBanner.php
  app/Models/User.php
  app/Transformers/UserCompactTransformer.php
  config/osu.php
  database/migrations/2024_11_06_074123_create_tournament_banners.php
Labels: area:user-profile

#11651 Try fixing user country on login
  app/Http/Controllers/SessionsController.php
Labels: area:user-profile

#11657 Fix difficulty lookup cache address in docker compose
  docker-compose.yml
Labels: type:testing

#11659 Disable turbo on oauth form buttons
  resources/views/vendor/passport/authorize.blade.php
Labels: type:api

#11662 Fix parsing page parameter of ranking page
  app/Http/Controllers/RankingController.php
Labels: area:rankings, type:reliability

#11655 Allow silenced user to play in playlist
  app/Models/Multiplayer/Room.php
  app/Singletons/OsuAuthorize.php
Labels: area:multiplayer

#11664 Fix ranking page parameter type
  app/Http/Controllers/RankingController.php
Labels: area:rankings

#11667 Add endpoint for closing playlists within grace period of creation
  .env.example
  app/Http/Controllers/Multiplayer/RoomsController.php
  app/Models/Multiplayer/Room.php
  app/Singletons/OsuAuthorize.php
  config/osu.php
  resources/lang/en/authorization.php
  routes/web.php
  tests/Controllers/Multiplayer/RoomsControllerTest.php
  tests/api_routes.json
Labels: area:multiplayer

#11668 Add tables for beatmap versioning support
  database/migrations/2024_11_19_130731_create_beatmap_versioning_tables.php
Labels: area:beatmap-processing

#11669 Fix cache key for ip2asn
  .github/workflows/tests.yml
Labels: type:testing

#11673 Make test user session/token helpers chainable
  tests/TestCase.php
Labels: type:testing, type:code-quality

#11672 Create helper to check http(s) string
  app/Models/NewsPost.php
  app/Models/User.php
  app/helpers.php
Labels: type:code-quality

#11675 Return populated room object when joined
  app/Http/Controllers/Multiplayer/RoomsController.php
Labels: area:multiplayer

#11674 Fix acting as null user not reset existing user in test
  tests/TestCase.php
Labels: type:testing, area:tooling

#11670 Don't override InputContainer error colour when focused
  resources/css/bem/input-container.less
Labels: type:cosmetic

#11681 Add `status` to `multiplayer_rooms`
  app/Models/Multiplayer/Room.php
  app/Transformers/Multiplayer/RoomTransformer.php
  database/migrations/2024_11_22_092704_add_status_to_multiplayer_rooms.php
Labels: area:multiplayer

#11687 Do an explicit turbo visit for redirecting turbo request
  app/helpers.php
Labels: type:reliability

#11689 Fix timing of calling boot on initial page load
  resources/js/core/react-turbolinks.ts
Labels: type:reliability

#11688 Fix turbo redirect
  app/helpers.php
  package.json
  resources/js/setup-turbo.ts
  yarn.lock
Labels: type:reliability

#11693 Clean up user stats json generator
  app/helpers.php
Labels: type:code-quality

#11698 Adjust daily challenge tier thresholds to match expectations
  resources/js/profile-page/daily-challenge.tsx
Labels: area:user-profile

#11695 Remove unused variable
  resources/css/bem/input-container.less
Labels: type:code-quality
