Repository ppy/osu-web, pull requests merged in 2024-10, with the labels that each got.

#11523 Allow prefilling reset password username
  resources/views/password_reset/index.blade.php
Labels: type:behavioural

#11499 Cleanup discussion related search query and params helper
  app/Models/BeatmapDiscussion.php
  app/Models/BeatmapDiscussionPost.php
  app/Models/BeatmapDiscussionVote.php
  app/Models/BeatmapsetEvent.php
  app/Models/Model.php
  app/helpers.php
Labels: area:beatmap-discussions, type:code-quality

#11526 Reduce session verification key lifetime
  app/Libraries/SessionVerification/State.php
Labels: type:behavioural

#11525 Adjust session verification reissue limit
  app/Http/Controllers/AccountController.php
  tests/api_routes.json
Labels: type:behavioural

#11522 Improve chat announcement permission message
  app/Singletons/OsuAuthorize.php
  resources/lang/en/authorization.php
Labels: type:cosmetic

#11527 Adjust user current location length limit
  app/Models/User.php
  database/factories/UserFactory.php
Labels: type:reliability

#11514 Fix params handler not returning expected array
  app/helpers.php
Labels: type:reliability

#11518 Put back announcement channel user listing
  app/Http/Controllers/Chat/Channels/UsersController.php
  app/Models/Chat/UserChannel.php
  app/Singletons/OsuAuthorize.php
  app/Transformers/Chat/ChannelTransformer.php
  resources/css/bem/chat-conversation.less
  resources/js/chat/chat-api.ts
  resources/js/chat/conversation-view.tsx
  resources/js/interfaces/chat/channel-json.ts
  resources/js/models/chat/channel.ts
  routes/web.php
Labels: area:chat

#11528 Prevent forum poll option image from overflowing
  resources/css/bem/forum-poll-option.less
Labels: area:forum, type:cosmetic

#9617 Add news announcement carousel to dashboard
  .env.example
  app/Http/Controllers/HomeController.php
  app/Libraries/MenuContent.php
  app/Transformers/MenuImageTransformer.php
  config/osu.php
  resources/css/bem-index.less
  resources/css/bem/menu-image.less
  resources/css/bem/menu-images.less
  resources/js/components/menu-image.tsx
  resources/js/components/menu-images.tsx
  resources/js/interfaces/menu-image-json.ts
  resources/js/register-components.tsx
  resources/views/home/user.blade.php
Labels: area:dashboard

#11529 Form styling cleanup
  resources/css/bem/artist-track-search-form.less
  resources/css/bem/input-container.less
  resources/css/bem/input-text.less
  resources/js/artist-tracks-index/search-form.tsx
  resources/js/chat/create-announcement.tsx
Labels: type:cosmetic

#11531 Add new score replay count data
  app/Http/Controllers/ScoresController.php
  app/Models/ScoreReplayStats.php
  database/migrations/2024_10_04_082317_create_score_replay_stats.php
  tests/Controllers/ScoresControllerTest.php
Labels: area:user-profile

#11534 Update dropdown on store page
  resources/css/bem/input-container.less
  resources/css/bem/input-text.less
  resources/css/bem/store-text.less
  resources/lang/en/store.php
  resources/views/store/products/show.blade.php
Labels: type:cosmetic

#11537 Adjust dashboard banner position
  resources/css/bem/menu-image.less
  resources/css/bem/menu-images.less
  resources/js/components/menu-image.tsx
  resources/js/components/menu-images.tsx
  resources/views/home/user.blade.php
Labels: area:dashboard, type:cosmetic

#11542 Remove extra padding on comment editor footer
  resources/css/bem/comment-editor.less
Labels: type:cosmetic

#11545 Show video icon on beatmap page
  resources/js/beatmapsets-show/header.tsx
Labels: area:beatmap-info, type:cosmetic

#11544 Remove usage of old score es index
  .env.example
  app/Console/Commands/UserBestScoresCheckCommand.php
  app/Http/Controllers/LegacyInterOpController.php
  app/Jobs/RemoveBeatmapsetBestScores.php
  app/Libraries/UserBestScoresCheck.php
  config/elasticsearch.php
  docker-compose.yml
  routes/web.php
Labels: type:code-quality

#11535 Add separator before each forum main categories
  resources/views/forum/topics/_moderate_move.blade.php
  resources/views/objects/search/_forum_options.blade.php
Labels: type:cosmetic

#11536 Fix incorrect cutoffs on grade dial when displaying lazer scores and stable scores in lazer mode
  resources/css/colors.less
  resources/js/scores-show/dial.tsx
  resources/js/scores-show/info.tsx
  resources/js/utils/score-helper.ts
Labels: area:scoring, type:cosmetic

#11538 Remove some react container from page layout
  resources/views/beatmapsets/discussion.blade.php
  resources/views/beatmapsets/show.blade.php
  resources/views/changelog/build.blade.php
  resources/views/changelog/index.blade.php
  resources/views/chat/index.blade.php
  resources/views/follows/comment.blade.php
  resources/views/follows/mapping.blade.php
  resources/views/news/index.blade.php
  resources/views/news/show.blade.php
  resources/views/notifications/index.blade.php
  resources/views/scores/show.blade.php
  resources/views/users/beatmapset_activities.blade.php
  resources/views/users/multiplayer/index.blade.php
  resources/views/users/show.blade.php
Labels: type:code-quality

#11539 Simplify session verification css
  resources/css/bem/user-verification-popup.less
  resources/views/layout/_user_verification_popup.blade.php
Labels: type:code-quality

#11546 Remove osu-layout row block element
  resources/css/bem/landing-sitemap.less
  resources/css/bem/osu-layout.less
  resources/css/bem/page-extra.less
  resources/js/beatmaps/search-content.tsx
  resources/js/profile-page/beatmapsets.tsx
  resources/views/beatmapset_events/index.blade.php
  resources/views/home/landing.blade.php
Labels: type:code-quality

#11555 Do case insensitive lookup of medal name
  app/Singletons/Medals.php
Labels: area:user-profile

#11554 Remove unused modifier
  resources/js/chat/create-announcement.tsx
Labels: type:code-quality

#11548 Remove unnecessary class
  app/Libraries/Fulfillments/ApplySupporterTag.php
  app/Libraries/Fulfillments/OrderItemFulfillment.php
Labels: type:code-quality

#11549 add beatmap favourite count search parameter
  app/Libraries/Search/BeatmapsetQueryParser.php
  app/Libraries/Search/BeatmapsetSearch.php
  app/Libraries/Search/BeatmapsetSearchParams.php
  app/Libraries/Search/BeatmapsetSearchRequestParams.php
Labels: area:beatmap-listing, area:search

#11557 Fix error on null reportable
  app/Notifications/UserReportNotification.php
Labels: type:reliability

#11558 Fix error on oauth client with no attached user
  app/Models/OAuth/Token.php
Labels: type:reliability

#11556 Use origin check for guests
  app/Http/Middleware/VerifyCsrfToken.php
  app/helpers.php
  resources/views/layout/metadata.blade.php
Labels: type:reliability

#11540 Add manual refresh to Beatmap Discussions page
  app/Http/Controllers/BeatmapDiscussionsController.php
  app/Http/Controllers/BeatmapsetsController.php
  app/Models/Beatmapset.php
  resources/css/bem-index.less
  resources/css/bem/floating-toolbar-button.less
  resources/css/bem/floating-toolbar.less
  resources/css/variables.less
  resources/js/beatmap-discussions/discussions-state-worker.ts
  resources/js/beatmap-discussions/discussions-state.ts
  resources/js/beatmap-discussions/main.tsx
  resources/js/beatmap-discussions/refresh.tsx
  resources/js/components/back-to-top.tsx
  resources/lang/en/beatmap_discussions.php
  routes/web.php
Labels: area:beatmap-discussions

#11565 Fix legacy score lookup on new table
  app/Http/Controllers/ScoresController.php
Labels: area:scoring

#11567 Use global config variable
  tests/Models/BeatmapsetRequalifyTest.php
Labels: type:testing, type:code-quality

#11560 Fix show more button alignment on profile page
  resources/css/bem/show-more-link.less
  resources/js/profile-page/beatmapsets.tsx
Labels: type:cosmetic

#11547 Update forum search form style
  resources/css/bem/btn-osu-big.less
  resources/css/bem/search-forum-options.less
  resources/views/objects/search/_forum_options.blade.php
Labels: type:cosmetic

#11570 Fix wiki search bar click area
  resources/css/bem/wiki-search.less
Labels: area:wiki

#11569 Fix wording in Daily Challenge Ranking page
  resources/lang/en/rankings.php
  resources/lang/uk/rankings.php
Labels: type:localisation

#11575 Fix exception class name
  app/Models/Forum/TopicWatch.php
Labels: type:reliability

#11580 Fix user listing preload scope
  app/Http/Controllers/FriendsController.php
  app/Http/Controllers/GroupsController.php
  app/Models/User.php
  app/Transformers/UserCompactTransformer.php
Labels: type:performance

#11574 Fix percentile related key names
  app/Models/DailyChallengeUserStats.php
  app/Models/Multiplayer/PlaylistItem.php
  resources/lang/en/rankings.php
  resources/views/rankings/daily_challenge.blade.php
Labels: type:code-quality

#11576 Pass timestamp to elasticsearch for beatmap search
  app/Libraries/Search/BeatmapsetQueryParser.php
  tests/Libraries/Search/BeatmapsetQueryParserTest.php
Labels: type:reliability

#11582 Return user relation json for friends listing endpoint
  app/Http/Controllers/FriendsController.php
  app/Models/User.php
  app/Transformers/UserCompactTransformer.php
  app/Transformers/UserRelationTransformer.php
Labels: type:api

#11587 Use native uuid generator function
  resources/js/models/chat/create-announcement.ts
  resources/js/models/chat/message.ts
  resources/js/turbolinks-overrides.coffee
  resources/js/turbolinks.d.ts
  resources/js/utils/seq.ts
Labels: type:code-quality

#11588 Fix show more button alignment on comments
  resources/css/bem/show-more-link.less
Labels: type:cosmetic

#11589 Check ruleset conversion validity when issuing submission tokens
  app/Http/Controllers/BeatmapsController.php
  app/Http/Controllers/ScoreTokensController.php
  app/Models/Beatmap.php
  app/Models/Multiplayer/PlaylistItem.php
  app/Models/Multiplayer/Room.php
  tests/Controllers/Multiplayer/Rooms/Playlist/ScoresControllerTest.php
  tests/Controllers/ScoreTokensControllerTest.php
  tests/Models/Multiplayer/PlaylistItemTest.php
  tests/Models/Multiplayer/RoomTest.php
Labels: area:multiplayer, area:scoring

#11593 Move user registration step in `SETUP.md` to be after database seeding
  SETUP.md
Labels: type:documentation

#11595 Fix dashboard moving around on initial load
  resources/css/bem/menu-images.less
  resources/views/home/user.blade.php
Labels: type:cosmetic

#11602 Reduce number of queries to count notifications
  app/Libraries/NotificationsBundle.php
Labels: type:performance

#11601 Randomise dashboard banner order
  resources/js/components/menu-images.tsx
  resources/js/register-components.tsx
Labels: type:behavioural

#11581 Add api endpoint for adding/removing friends
  app/Http/Controllers/FriendsController.php
  resources/js/components/friend-button.tsx
  resources/js/core/user/user-model.ts
  routes/web.php
  tests/api_routes.json
Labels: type:api

#11606 Don't create user notification entry if mail and push are both disabled
  app/Jobs/Notifications/BroadcastNotificationBase.php
Labels: type:performance, area:notifications

#11584 Add user block management api
  app/Http/Controllers/BlocksController.php
  resources/js/components/block-button.tsx
  resources/js/core/user/user-model.ts
  routes/web.php
  tests/api_routes.json
Labels: type:api

#11607 Limit maximum number of mappers that can be followed
  .env.example
  app/Http/Controllers/FollowsController.php
  config/osu.php
  resources/lang/en/follows.php
Labels: area:beatmap-discussions

#11608 Support score on interop bulk indexing endpoint
  app/Http/Controllers/InterOp/Indexing/BulkController.php
Labels: area:scoring

#11609 Speed up first place score query
  app/Http/Controllers/UsersController.php
  app/Models/LegacyScoreFirst/Fruits.php
  app/Models/LegacyScoreFirst/Mania.php
  app/Models/LegacyScoreFirst/Model.php
  app/Models/LegacyScoreFirst/Osu.php
  app/Models/LegacyScoreFirst/Taiko.php
  app/Models/User.php
  app/Transformers/UserCompactTransformer.php
Labels: area:user-profile, type:performance
