Repository ppy/osu-web, pull requests merged in 2025-07, with the labels that each got.

#11934 Support specifying short name for team url
  app/Http/Controllers/TeamsController.php
  app/helpers.php
Labels: area:team

#12282 Update mod icon appearance to match client
  public/images/badges/mods/autopilot.svg
  public/images/badges/mods/autoplay.svg
  public/images/badges/mods/blanks/mod-icon-extender.svg
  public/images/badges/mods/blanks/mod-icon.svg
  public/images/badges/mods/cinema.svg
  public/images/badges/mods/double-time.svg
  public/images/badges/mods/easy.svg
  public/images/badges/mods/flashlight.svg
  public/images/badges/mods/half-time.svg
  public/images/badges/mods/hard-rock.svg
  public/images/badges/mods/hidden.svg
  public/images/badges/mods/nightcore.svg
  public/images/badges/mods/no-fail.svg
  public/images/badges/mods/perfect.svg
  public/images/badges/mods/random.svg
  public/images/badges/mods/relax.svg
  public/images/badges/mods/spun-out.svg
  public/images/badges/mods/sudden-death.svg
  public/images/badges/mods/target-practice.svg
  public/images/badges/mods/touch-device.svg
  resources/css/bem/mod.less
  resources/css/variables.less
  resources/js/cli/mod-names-generator.js
  resources/js/components/mod.tsx
Labels: area:beatmap-listing, area:scoring, type:cosmetic

#12283 Allow filtering beatmap leaderboards using lazer mods when lazer mode is active
  resources/js/beatmapsets-show/scoreboard/main.tsx
  resources/js/cli/mod-names-generator.js
Labels: area:beatmap-info

#12294 Fix pippi in supporter page being occasionally cropped
  resources/css/bem/supporter-status.less
Labels: area:user-profile

#12292 Adjust team member display
  resources/lang/en/teams.php
  resources/views/teams/show.blade.php
Labels: area:team

#12296 Show total duration of supporter tags on supporter page
  app/Http/Controllers/HomeController.php
  app/Models/SupporterTag.php
  resources/lang/en/community.php
  resources/views/home/support-the-game.blade.php
Labels: area:user-profile

#12293 Add new report type
  resources/js/components/report-form.tsx
  resources/lang/en/users.php
Labels: area:beatmap-info

#12298 Restore voted state on contest entry when navigating through history
  resources/js/contest-voting/base-entry-list.coffee
  resources/js/entrypoints/contest-voting.coffee
Labels: area:contests

#12297 Add admin menu to more pages
  resources/lang/en/beatmapsets.php
  resources/lang/en/common.php
  resources/lang/en/contest.php
  resources/lang/en/home.php
  resources/views/beatmapsets/show.blade.php
  resources/views/contests/base.blade.php
  resources/views/home/user.blade.php
  resources/views/layout/footer.blade.php
Labels: area:admin

#12311 Fix incorrect early number formatting
  app/Http/Controllers/HomeController.php
Labels: type:reliability

#12300 Apply phpbb acl check to editing Topic title and posts
  app/Singletons/OsuAuthorize.php
  database/factories/Forum/ForumFactory.php
  database/factories/Forum/TopicFactory.php
  resources/lang/en/authorization.php
  tests/Controllers/Forum/PostsControllerTest.php
  tests/Controllers/Forum/TopicsControllerTest.php
Labels: area:forum

#12312 Separate active and ended room listing
  app/Http/Controllers/Users/MultiplayerController.php
  app/Models/Multiplayer/Room.php
  resources/css/bem/page-extra.less
  resources/js/components/room-list.tsx
  resources/js/entrypoints/user-multiplayer-index.tsx
  resources/js/seasons-show/main.tsx
  resources/js/user-multiplayer-index/main.tsx
  resources/lang/en/multiplayer.php
  resources/lang/en/users.php
Labels: area:user-profile

#12313 Clean up verify modal popup
  resources/js/core/user/user-verification.ts
  resources/views/layout/_user_verification_popup.blade.php
  resources/views/layout/header.blade.php
  resources/views/master.blade.php
Labels: type:code-quality
