Repository ppy/osu-web, pull requests merged in 2025-04, with the labels that each got.

#12059 Add per ruleset tag support
  app/Http/Controllers/BeatmapTagsController.php
  app/Models/Tag.php
  database/factories/TagFactory.php
  database/migrations/2025_03_28_000001_add_ruleset_id_to_tags.php
  resources/lang/en/beatmap_tags.php
  tests/Controllers/BeatmapTagsControllerTest.php
Labels: area:tags

#12066 Fix error when checking blocked user ids for notification
  app/Jobs/Notifications/BroadcastNotificationBase.php
Labels: area:notifications

#12050 Convert game header component to typescript
  resources/js/mp-history/game-header.coffee
  resources/js/mp-history/game-header.tsx
  resources/js/mp-history/game.coffee
Labels: type:code-quality, area:multiplayer

#12067 Return user tag ruleset ID when listing all tags
  app/Transformers/TagTransformer.php
Labels: area:tags

#12054 Allow changing team leader
  app/Http/Controllers/Teams/MembersController.php
  resources/css/bem/team-members-manage.less
  resources/lang/en/teams.php
  resources/views/teams/members/index.blade.php
  routes/web.php
  tests/Controllers/Teams/MembersControllerTest.php
Labels: area:team

#12071 Filter chat messages from block users from being displayed
  resources/js/chat/conversation-view.tsx
Labels: area:chat

#12048 Add deadline to contest judging period
  app/Http/Controllers/ContestsController.php
  app/Models/Contest.php
  app/Transformers/ContestTransformer.php
  resources/css/bem/contest-judge-entry.less
  resources/css/bem/contest-judge.less
  resources/css/bem/sort.less
  resources/js/contest-judge/entry.tsx
  resources/js/contest-judge/main.tsx
  resources/js/interfaces/contest-json.ts
  resources/js/stores/contest-judge-store.ts
Labels: area:contests

#12068 Convert game score component to typescript
  resources/js/mp-history/game.coffee
  resources/js/mp-history/score.coffee
  resources/js/mp-history/score.tsx
Labels: type:code-quality, area:multiplayer

#12077 Use newer syntax for default mode function
  app/helpers.php
Labels: type:code-quality

#12080 Prevent invalid image output size
  app/Libraries/ImageProcessor.php
Labels: type:code-quality

#12041 Update to Laravel 11
  app/Http/Middleware/LegacyInterOpAuth.php
  app/Http/Middleware/ThrottleRequests.php
  app/Libraries/Fulfillments/ApplySupporterTag.php
  app/Libraries/User/ForceReactivation.php
  app/Models/Beatmapset.php
  app/Providers/AuthServiceProvider.php
  app/Providers/MigrationServiceProvider.php
  bootstrap/app.php
  composer.json
  composer.lock
  database/migrations/2022_12_05_114748_add_rank_exp_to_user_statistics.php
  database/migrations/2023_08_17_133006_sync_structure.php
  tests/TestCase.php
Labels: type:code-quality

#12083 Fix overlapping scrollable Beatmap info sections
  resources/css/bem/beatmapset-info.less
  resources/js/beatmapsets-show/info.tsx
Labels: area:beatmap-info

#12081 Convert game component to typescript
  resources/js/interfaces/beatmap-json.ts
  resources/js/interfaces/beatmapset-json.ts
  resources/js/interfaces/legacy-match-game-json.ts
  resources/js/interfaces/score-json.ts
  resources/js/mp-history/content.coffee
  resources/js/mp-history/game-header.tsx
  resources/js/mp-history/game.coffee
  resources/js/mp-history/game.tsx
  resources/js/mp-history/score.tsx
Labels: type:code-quality, area:multiplayer

#12073 Show all available statistics on score pages
  resources/css/bem/score-stats.less
  resources/js/beatmapsets-show/scoreboard/table-row.tsx
  resources/js/beatmapsets-show/scoreboard/table.tsx
  resources/js/beatmapsets-show/scoreboard/top-card.tsx
  resources/js/interfaces/solo-score-json.ts
  resources/js/scores-show/stats.tsx
  resources/js/utils/score-helper.ts
Labels: area:scoring, type:cosmetic

#12091 Fix username availability time display
  app/Libraries/UsernameValidation.php
Labels: area:store

#12058 Update to php 8.4
  .github/workflows/lint.yml
  .github/workflows/tests.yml
  Dockerfile.deployment
  Dockerfile.development
  README.md
  composer.json
  composer.lock
  config/sentry.php
Labels: type:code-quality

#12092 Fix php deprecations
  app/Models/Traits/Es/BaseDbIndexable.php
  app/Models/Traits/Es/BaseIndexable.php
  app/helpers.php
Labels: type:code-quality

#12065 Clean up ranking page table styling
  resources/css/bem-index.less
  resources/css/bem/avatar.less
  resources/css/bem/ranking-page-table-main.less
  resources/css/bem/ranking-page-table.less
  resources/views/multiplayer/rooms/_rankings_table.blade.php
  resources/views/rankings/_main_column.blade.php
  resources/views/rankings/_spotlight_rankings_table.blade.php
  resources/views/rankings/country.blade.php
  resources/views/rankings/kudosu.blade.php
  resources/views/rankings/performance.blade.php
  resources/views/rankings/score.blade.php
  resources/views/rankings/team.blade.php
  resources/views/seasons/_rankings_table.blade.php
Labels: area:rankings

#12070 Update team leaderboard page
  app/Http/Controllers/TeamsController.php
  resources/css/bem-index.less
  resources/css/bem/team-members-leaderboard-item.less
  resources/css/bem/team-members-leaderboard.less
  resources/views/rankings/_main_column.blade.php
  resources/views/teams/_members_leaderboard.blade.php
  resources/views/teams/leaderboard.blade.php
Labels: area:team

#12086 Convert multiplayer room history content component to typescript
  resources/js/mp-history/content.coffee
  resources/js/mp-history/content.tsx
  resources/js/mp-history/game.tsx
  resources/js/mp-history/main.coffee
Labels: type:code-quality, area:multiplayer

#12097 Better test dataset entry name
  tests/Browser/SanityTest.php
Labels: type:testing

#12100 Fix Beatmap description header hidden by imagemap
  resources/css/bem/beatmapset-info.less
Labels: area:beatmap-info

#12082 Fix username column overflow on beatmap leaderboard
  resources/css/bem/beatmap-scoreboard-table.less
  resources/css/bem/flag-team.less
  resources/css/utilities.less
  resources/js/beatmapsets-show/scoreboard/table-row.tsx
Labels: area:beatmap-info

#12108 Hide user avatar on non-team leaderboards
  resources/css/bem/ranking-page-table.less
  resources/views/rankings/_main_column.blade.php
  resources/views/teams/_members_leaderboard.blade.php
Labels: area:rankings

#12089 Allow fetching up to 200 best scores
  app/Http/Controllers/UsersController.php
  app/Models/Traits/UserScoreable.php
Labels: area:user-profile

#12109 Fix nullable typing
  app/Exceptions/ChangeUsernameException.php
  app/Exceptions/ValidationException.php
  app/Jobs/RegenerateBeatmapsetCover.php
  app/Libraries/Elasticsearch/SearchResponse.php
  app/Libraries/Search/BasicSearch.php
  app/Libraries/SessionVerification/Helper.php
  app/Libraries/TransactionState.php
  app/Models/Store/Order.php
  app/Singletons/OsuAuthorize.php
  app/Transformers/UserStatisticsTransformer.php
  tests/Libraries/OrderCheckoutTest.php
Labels: type:code-quality

#12113 Fix dusk failing logout test
  tests/Browser/LoginTest.php
Labels: type:testing

#12096 Prevent type error when non-array json is specified
  app/Http/Controllers/BeatmapDiscussionsController.php
Labels: type:code-quality

#12101 Remove temporary apiVersion check in /rooms endpoint
  app/Http/Controllers/Multiplayer/RoomsController.php
Labels: type:code-quality

#12094 Add passed flag to playlist item attempts json
  app/Models/Multiplayer/PlaylistItemUserHighScore.php
  app/Models/Multiplayer/UserScoreAggregate.php
Labels: area:multiplayer

#12114 More php null related fixes
  app/Libraries/BeatmapsetDiscussion/Review.php
  app/Models/Beatmapset.php
  app/Models/Multiplayer/Room.php
  app/Transformers/BeatmapsetEventTransformer.php
  phpcs.xml
  tests/Models/BeatmapsetTest.php
Labels: type:code-quality

#12098 Convert main mp history components to typescript
  resources/js/entrypoints/mp-history.coffee
  resources/js/entrypoints/mp-history.tsx
  resources/js/mp-history/main.coffee
  resources/js/mp-history/main.tsx
Labels: type:code-quality, area:multiplayer

#12119 Show User Tags with Beatmap converts
  app/Http/Controllers/BeatmapsetsController.php
Labels: area:beatmap-info

#12118 Adjust user profile specific report types
  app/Models/UserReport.php
  database/migrations/2025_04_17_073210_add_inappropriate_chat_to_report_types.php
  resources/js/components/report-form.tsx
  resources/lang/en/users.php
Labels: area:user-profile

#12116 Support reporting team
  app/Models/Team.php
  app/Models/UserReport.php
  database/migrations/2025_04_21_111148_add_team_to_report_types.php
  resources/js/components/report-form.tsx
  resources/js/components/team-extra-menu.tsx
  resources/js/interfaces/reportable.ts
  resources/js/register-components.tsx
  resources/lang/en/model_validation.php
  resources/lang/en/report.php
  resources/views/teams/show.blade.php
  tests/Models/UserReportTest.php
Labels: area:team

#12120 Add database table for storing lazer multiplayer room events
  database/migrations/2025_04_17_113658_create_multiplayer_room_events_table.php
Labels: area:multiplayer

#12087 Include artist track in global search
  app/Http/Controllers/ArtistTracksController.php
  app/Http/Controllers/HomeController.php
  app/Libraries/Search/ArtistTrackSearch.php
  app/Libraries/Search/ArtistTrackSearchParamsFromRequest.php
  app/Libraries/Search/ArtistTrackSearchRequestParams.php
  app/Libraries/Search/MultiSearch.php
  app/Libraries/Search/QuickSearch.php
  app/Transformers/ArtistTrackTransformer.php
  resources/css/bem/artist-track.less
  resources/css/bem/quick-search-items.less
  resources/css/bem/search-result.less
  resources/js/quick-search/main.tsx
  resources/js/quick-search/worker.ts
  resources/js/register-components.tsx
  resources/lang/en/home.php
  resources/lang/en/quick_search.php
  resources/views/home/_search_result_artist_track.blade.php
Labels: area:search

#12129 Fix typo
  resources/lang/en/model_validation.php
Labels: type:localisation

#12124 Remove redundant team id in notification detail
  app/Jobs/Notifications/TeamApplicationBase.php
Labels: type:code-quality, area:team

#12125 Simplify linking notification to chat channel
  resources/js/notification-maps/url.ts
Labels: type:code-quality, area:chat

#12136 Move new message notification logic to its own function
  app/Models/Chat/Channel.php
  app/Models/Chat/Message.php
Labels: type:code-quality, area:chat

#12140 Show detailed team formation date on hover
  resources/views/teams/show.blade.php
Labels: area:team

#12141 Fix ranked score attribute on variant statistics
  app/Models/UserStatistics/VariantModel.php
Labels: area:rankings

#12139 Reset variant parameter when switching ruleset
  resources/views/rankings/index.blade.php
Labels: area:rankings

#12133 Send notification on new team join requests
  app/Http/Controllers/Teams/ApplicationsController.php
  app/Jobs/Notifications/BroadcastNotificationBase.php
  app/Jobs/Notifications/TeamApplicationStore.php
  app/Models/Notification.php
  app/Models/TeamApplication.php
  database/migrations/2025_04_22_121439_add_notification_id_to_team_applications.php
  resources/js/notification-maps/category.ts
  resources/js/notification-maps/icons.ts
  resources/js/notification-maps/message.ts
  resources/js/notification-maps/url.ts
  resources/lang/en/notifications.php
  tests/Controllers/Teams/ApplicationsControllerTest.php
Labels: area:team

#12142 Fix type of beatmapset id column on downloads table
  database/migrations/2025_04_24_054138_fix_downloads_beatmapset_id_type.php
Labels: type:reliability

#12144 Add alternative url for iptoasn database source
  app/Libraries/Ip2AsnUpdater.php
Labels: type:reliability

#12130 Speed up beatmapset es indexing
  .env.example
  app/Models/Beatmap.php
  app/Models/BeatmapTag.php
  app/Models/Traits/Es/BeatmapsetSearch.php
  config/osu.php
Labels: area:beatmap-listing, type:performance

#12145 Combine channel notification job classes
  app/Jobs/Notifications/ChannelAnnouncement.php
  app/Jobs/Notifications/ChannelMessage.php
  app/Jobs/Notifications/ChannelMessageBase.php
Labels: type:code-quality
