Repository ppy/osu-web, pull requests merged in 2025-08, with the labels that each got.

#12320 Clean up verification exception class
  app/Exceptions/UserVerificationException.php
  app/Libraries/SessionVerification/Controller.php
Labels: area:user-profile

#12324 Update class name for verification mail state
  app/Libraries/SessionVerification/Controller.php
  app/Libraries/SessionVerification/Helper.php
  app/Libraries/SessionVerification/MailState.php
  tests/Browser/SanityTest.php
  tests/Libraries/SessionVerification/ControllerTest.php
Labels: area:user-profile

#12333 Remove remember login option
  app/Http/Controllers/Controller.php
  app/Http/Controllers/SessionsController.php
Labels: area:user-profile, type:code-quality

#12338 Add retry logic to the commonly failing dusk test
  tests/Browser/LoginTest.php
Labels: type:testing

#12334 Clean up login action parameter handling
  app/Http/Controllers/SessionsController.php
Labels: area:user-profile, type:code-quality

#12342 Use svg fontawesome for mod icons
  resources/css/bem/mod.less
Labels: area:beatmap-listing

#12325 Calculate multiplayer room difficulty range based only on non-expired items when the room is open
  app/Models/Multiplayer/Room.php
  tests/Models/Multiplayer/RoomTest.php
Labels: area:multiplayer

#12347 Use correct translation function
  app/Models/Event.php
  app/Models/Store/OrderItem.php
  resources/views/comments/show.blade.php
  resources/views/contests/voting.blade.php
  tests/Browser/BeatmapDiscussionPostsTest.php
Labels: type:localisation

#12346 Wrap another randomly failing test with retries
  tests/Browser/AccountTest.php
  tests/Browser/LoginTest.php
  tests/DuskTestCase.php
Labels: type:testing

#12344 Simplify dusk retry logic
  tests/Browser/LoginTest.php
Labels: type:code-quality

#12349 Account classic scores when syncing beatmap leaders
  app/Models/BeatmapLeader.php
Labels: area:user-profile

#12365 Include user team data in multiplayer score responses
  app/Transformers/ScoreTransformer.php
Labels: area:multiplayer

#12362 Add pinned flag & description field to multiplayer rooms
  app/Models/Multiplayer/Room.php
  app/Transformers/Multiplayer/RoomTransformer.php
  database/migrations/2025_08_21_103748_add_pinned_description_to_multiplayer_rooms.php
Labels: area:multiplayer
